import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "accountant marketing Cardiff",
    "Cardiff accountant SEO",
    "accountancy practice marketing Cardiff",
    "South Wales accountant lead generation",
    "small business accountant Cardiff marketing",
  ],
  secondaryKeywords: [
    "cyfrifydd Caerdydd marchnata",
    "Cardiff Bay BBC fintech accountant",
    "Pontcanna Canton SME accountant SEO",
    "Whitchurch Llanishen private client accountant",
    "Welsh Revenue Authority LTT accountant Cardiff",
    "Cardiff IR35 BBC contractor accountant",
    "Welsh language accountant Caerdydd",
    "MTD ITSA Cardiff landlord campaigns",
  ],
  heroSubhead:
    "Cardiff hosts the largest accountancy market in Wales, anchored by the Senedd, the Welsh Revenue Authority (WRA), BBC Cymru Wales' Central Square HQ, S4C, ITV Cymru Wales, the Capital Quarter and Tramshed Tech fintech cluster, and three universities supporting 65,000+ students. Welsh devolved taxes — Land Transaction Tax (LTT) replacing SDLT, Landfill Disposals Tax (LDT) replacing Landfill Tax, and Welsh Rates of Income Tax setting 10p of each income tax band — create a Welsh-specific compliance layer most rest-of-UK templated practices ignore. Welsh-language client expectation is real and structurally under-served — 'cyfrifydd Caerdydd', 'cyfrifydd busnes bach' carry meaningful search volume and almost no competitive bidding. Named locals include Gerald Thomas Accountants, Bevan Buckland LLP, UHY Hacker Young Cardiff, Watts Gregory, Roberts Crisp Webb (now Azets Cardiff), Broomfield & Alexander (now BDO Wales), MHA Broomfield Alexander; consolidators Azets and BDO compete aggressively. Kerblabs builds Cardiff-specific accountancy funnels with Welsh devolved-tax expertise, bilingual English/Welsh positioning and the Welsh Government grants accountancy work the rest-of-UK templated competitors don't deliver.",
  marketContext: [
    "Cardiff's accountancy market is shaped by three Wales-specific forces. First, devolved taxation: the Welsh Revenue Authority (Awdurdod Cyllid Cymru), based in Treforest, administers Land Transaction Tax (LTT) replacing SDLT on Welsh property since April 2018, and Landfill Disposals Tax replacing Landfill Tax since the same date. Welsh Rates of Income Tax (WRIT) operate 10p of each band set by the Welsh Government — currently aligned with rest-of-UK rates but politically separable and a permanent compliance layer affecting every Welsh-resident PAYE and Self-Assessment client. The Welsh Government also operates a distinct grants and Business Wales support landscape (Development Bank of Wales, Business Wales, Welsh Government Innovation Vouchers) with accountancy-relevant compliance and reporting requirements. Second, the Welsh-language dimension: Cardiff is the most-Welsh-speaking major UK city by absolute numbers (around 11.6% of residents), and 'cyfrifydd Caerdydd', 'cyfrifydd busnes bach' search queries carry meaningful volume that rest-of-UK consolidators don't bid on. Welsh Government, public-sector and culture-sector clients (S4C, Welsh National Opera, Wales Millennium Centre suppliers) often actively prefer Welsh-medium-capable accountants for procurement reasons. Third, the broadcast-and-fintech-and-public-sector cluster: BBC Cymru Wales' Central Square HQ, S4C, ITV Cymru Wales drive a substantial freelance and PSC contractor demand layer; Capital Quarter and Tramshed Tech fintech cluster generate startup accountancy demand; Cardiff University, Cardiff Met and University of South Wales drive academic research-spinout accountancy work.",
    "Pricing and named local competitors: Cardiff SME accountancy fees for an owner-managed Ltd company with bookkeeping, VAT, payroll, year-end and corporation tax run £150-£400/month — broadly aligned with Birmingham/Manchester levels and 25-30% below London. Self-Assessment runs £150-£400 retail, property portfolio Self-Assessments with multiple BTLs and LTT planning run £400-£900, BBC/S4C freelancer Self-Assessments run £250-£600 (often more complex than they appear because of multi-employer broadcast-cycle income), and small-Ltd year-end accounts plus CT600 run £600-£1,800. The Whitchurch/Llanishen/Cyncoed/Penarth premium belt commands 25-35% fee premiums. Named local independents include Gerald Thomas Accountants (long-established Cardiff practice), Bevan Buckland LLP (Swansea-headquartered with strong Cardiff presence), UHY Hacker Young Cardiff, Watts Gregory, MHA Broomfield Alexander (post-Broomfield & Alexander rollup), Kilsby Williams (Newport but very active in Cardiff), Wilkins & Co, Wilcox & Hughes, plus a long tail of two-to-five-partner firms across CF11, CF14 and CF24. Big 4 (Deloitte Wales, KPMG, PwC, EY) anchor city-centre work; mid-tier Azets (post-Roberts Crisp Webb), BDO Wales (post-Broomfield & Alexander), RSM Cardiff and Grant Thornton compete for £1M+ owner-managed clients. TaxAssist runs 4+ South Wales franchises across Cardiff, Penarth, Caerphilly and Bridgend.",
    "Cardiff Google Ads CPCs in accountancy keywords run £6-£14 for 'accountant near me Cardiff', £8-£16 for 'small business accountant Cardiff', £10-£20 for 'accountant for ltd company Cardiff', and £12-£24 for 'IR35 accountant Cardiff' driven by BBC and S4C contractor demand. CPCs are 35-45% below London and broadly aligned with Birmingham. The non-obvious lever is Welsh-language and Welsh-devolved-tax positioning: 'cyfrifydd Caerdydd', 'cyfrifydd busnes bach', 'LTT property accountant Cardiff', 'Welsh Revenue Authority adviser', 'Welsh Government grants accountant' produce CPCs in the £3-£8 range with high commercial intent and almost no competition because rest-of-UK firms don't bid. The MTD ITSA April 2026 cliff is concentrated across the CF14 (Whitchurch/Llanishen/Cyncoed) landlord belt, the substantial BBC/S4C/Capital Quarter freelance-PSC contractor cohort, and the Welsh-government-grants adjacent SME base. Kerblabs Cardiff accountancy clients running borough-stratified ads + bilingual Welsh positioning + LTT/WRIT expertise + MTD ITSA + named-partner GBP velocity typically reach 5-12 net new monthly client signups inside 6 months.",
  ],
  stats: [
    { value: "WRA", label: "Welsh Revenue Authority administers LTT, LDT — distinct from HMRC", source: "Welsh Revenue Authority" },
    { value: "£6-£14", label: "Google Ads CPC for 'accountant near me Cardiff'", source: "Kerblabs client accounts" },
    { value: "11.6%", label: "of Cardiff residents speak Welsh — most absolute speakers of any major UK city", source: "Census 2021" },
    { value: "£150-£400/mo", label: "typical Cardiff SME Ltd company fee range" },
    { value: "65,000+", label: "Cardiff students supporting student-let landlord and HMO accountancy work", source: "HESA 2023/24" },
    { value: "April 2026", label: "MTD ITSA cliff hitting CF14 landlord belt and BBC/S4C freelance-PSC cohort" },
  ],
  painPoints: [
    {
      title: "Azets and BDO Wales consolidation absorbing the £500k-£3M owner-managed business tier",
      body: "Azets has rolled up Roberts Crisp Webb in Cardiff; BDO Wales absorbed Broomfield & Alexander; both compete aggressively for £500k-£3M owner-managed business work alongside RSM Cardiff, Grant Thornton, Forvis Mazars and the Big 4 Wales offices. Independent two-to-five-partner Cardiff practices lose mid-market clients because they don't run LinkedIn outbound, don't have Welsh-devolved-tax-led service pages, and don't show up in 'business advisor Cardiff' or 'fractional CFO Capital Quarter' search.",
    },
    {
      title: "Welsh devolved-tax expertise undermarketed despite material divergence",
      body: "Land Transaction Tax replacing SDLT, Landfill Disposals Tax, Welsh Rates of Income Tax (10p of each band), Welsh Government grants compliance — all material to every Welsh-resident SME and landlord client, yet most independent Cardiff practice websites read identically to a Bristol or Birmingham firm's. Online disruptors (Crunch, Mazuma) don't address Welsh specificity. Welsh Government, public-sector and culture-sector clients explicitly prefer Welsh-medium-capable accountants for procurement reasons — yet Welsh-language content and Welsh-tax positioning are nearly absent across Cardiff independent practice websites.",
    },
    {
      title: "BBC/S4C/Capital Quarter freelance-PSC IR35 work flowing to Crunch and SJD",
      body: "Cardiff has the second-largest broadcast and creative freelance cluster in the UK after London — BBC Cymru Wales Central Square HQ, S4C, ITV Cymru Wales, Bad Wolf studios, Boom Cymru, plus the Capital Quarter fintech cluster. IR35 status reviews, deemed-employment payroll, Ltd-to-PAYE transitions and PSC closure work flow to Crunch, SJD and InTouch by default because they own paid search at the £99-£149/month price point. Reposition with named-partner relationships and Welsh-language capability and we run targeted BBC/S4C/Capital Quarter outbound rather than competing on the brutal 'IR35 accountant Cardiff' headline term.",
    },
    {
      title: "CF14 landlord belt and BBC/S4C freelancer cohort unprepared for MTD ITSA April 2026",
      body: "Whitchurch, Llanishen, Cyncoed, Penarth and Radyr (CF14, CF23, CF64) carry heavy multi-property landlord ownership across LTT-affected portfolios. The BBC/S4C freelance cohort (often holding both PSC dividend income and Self-Assessment property income) crosses MTD ITSA thresholds in significant numbers. Most clients don't yet know quarterly digital reporting is mandatory from April 2026 (above £50k) or April 2027 (above £30k). Practices running automated MTD ITSA assessment campaigns now will pick up 30-90 net new clients in 18 months.",
    },
  ],
  faqs: [
    {
      q: "Do you actually market in Welsh — and is bilingual capability worth the investment?",
      a: "Yes — and for Cardiff specifically it is one of the highest-leverage structural advantages an independent practice can build. Cardiff is the most-Welsh-speaking major UK city by absolute numbers (around 11.6% of residents per the 2021 Census, but more than that in absolute headcount terms because the city is large). Welsh-medium SMEs, Welsh Government suppliers, S4C-adjacent freelancers, Welsh National Opera and Wales Millennium Centre vendors, education-sector clients and culture-sector clients all explicitly value or require Welsh-medium accountancy capability. Search queries 'cyfrifydd Caerdydd', 'cyfrifydd busnes bach', 'cynghorydd ariannol' carry meaningful commercial intent and almost no competitive bidding. We build hreflang-correct bilingual landing pages, Welsh-language Google Business Profile attributes, Welsh-language Google reviews, and where appropriate Welsh-language social and content. AI receptionist supports a true bilingual greeting and lets the caller choose Welsh or English. Even where the practice serves primarily English-speaking clients, adding Welsh signals to schema and GBP is a low-cost authority lift that rest-of-UK consolidators completely ignore.",
    },
    {
      q: "How do you handle Welsh devolved tax (LTT, LDT, Welsh Rates of Income Tax, Welsh Government grants)?",
      a: "Welsh devolved-tax expertise is structurally under-marketed across Cardiff independent practices, despite being material to every Welsh-resident client. Land Transaction Tax (LTT) replacing SDLT operates with different bands and rates (0% up to £225k for residential, then progressive bands), Landfill Disposals Tax replaces Landfill Tax for waste-to-Welsh-landfill operators, Welsh Rates of Income Tax (WRIT) sets 10p of each tax band — currently aligned with rest-of-UK but politically separable. Welsh Government grants (Development Bank of Wales loans and equity, Business Wales grants, Welsh Government Innovation Vouchers, Capital Investment Fund, Cymru Innovation) carry distinct accounting treatment and compliance requirements. We build Welsh-tax-explicit landing pages: 'LTT property accountant Cardiff', 'Welsh Revenue Authority adviser', 'Welsh Government grants accountant', 'Development Bank of Wales finance accountant', 'Business Wales support accountant'. Google Ads target these terms specifically — currently low CPC and high commercial intent. Compliance-wise everything sits within ICAEW or ACCA advertising rules with the additional layer that Welsh-language and Welsh-public-sector marketing must respect Welsh Language Standards where applicable.",
    },
    {
      q: "How do we compete with Azets, BDO Wales and the Big 4 on £500k-£3M owner-managed business?",
      a: "Not on scale. Mid-tier and Big 4 win through breadth of service, audit registration, geographical footprint and senior recruitment pipeline. Independent two-to-five-partner Cardiff practices win on three structural advantages: (1) named-partner relationships where the founding partner actually does the work — Welsh owner-managers cite this as the reason they leave Azets or BDO after a partner-track rotation; (2) Welsh-language and Welsh-public-sector capability, which Big 4 and rest-of-UK consolidators structurally cannot manufacture and which is genuinely valued by Welsh Government suppliers, S4C-adjacent businesses and culture-sector clients; and (3) sector specialisation in something the consolidators treat as generic — broadcast and creative freelancers (BBC Cymru Wales, S4C, Bad Wolf, Boom Cymru), fintech (Capital Quarter, Tramshed Tech), academic spin-outs from Cardiff University and Cardiff Met, and the large public-sector and third-sector base that Cardiff anchors. Kerblabs builds LinkedIn outbound, Welsh-language and sector landing pages, and review velocity. Cardiff practices running this typically grow £400/month+ client base 25-50% inside 12 months while sister Azets/BDO offices stagnate.",
    },
    {
      q: "What does the BBC/S4C/Capital Quarter PSC and IR35 contractor strategy look like for Cardiff specifically?",
      a: "Cardiff's broadcast-and-fintech freelance cluster is the second-largest UK concentration outside London. The strategy runs across three channels. First, content positioning specifically against Crunch, SJD and InTouch: landing pages on 'BBC contractor accountant Cardiff', 'S4C freelancer accountant', 'Bad Wolf production accountant', 'Capital Quarter fintech contractor accountant', with transparent fixed-fee pricing, named-partner relationships and Welsh-medium capability where relevant. Second, LinkedIn outbound targeted at specific contractor categories — broadcast production roles, post-production at dock10/Bad Wolf, Welsh-medium production at S4C and Boom Cymru, fintech consultancy at Capital Quarter, change managers and interim CTOs. Content focuses on inside/outside IR35 determinations, deemed-employment payroll setup, multi-employer broadcast-cycle income smoothing, dividend planning, pension contributions and HMRC enquiry support. Third, partnerships with local recruiters and broadcast-industry bodies (BECTU Wales, PACT Cymru, Welsh language broadcaster networks). Cardiff independent accountancy clients running this typically build a 30-100 PSC client book within 18 months at fees 2-3x Crunch's price point.",
    },
  ],
  approach:
    "For Cardiff independent accountancy practices, our 90-day playbook is: (1) split your market into 5 distinct funnels — Cardiff Bay/Capital Quarter B2B and fintech FD outsourcing, Whitchurch/Llanishen/Penarth premium private client and landlord, BBC/S4C/Bad Wolf broadcast-and-creative PSC contractor, Pontcanna/Canton/Roath SME, and Welsh-language/Welsh-public-sector practice — each with separate landing pages, ad creative and Welsh devolved-tax positioning; (2) deploy AI receptionist with bilingual English/Welsh greeting and Welsh place-name pronunciation; (3) launch the MTD ITSA April 2026 acquisition funnel targeting the CF14 landlord belt and BBC/S4C freelancer cohort; (4) drive Google review velocity to 6-10 monthly reviews mentioning named Cardiff neighbourhoods (some in Welsh) to surface against Azets, BDO Wales and Big 4 brand presence; and (5) build LinkedIn-led outbound with explicit Welsh-medium and Welsh-devolved-tax positioning to defend the £500k-£3M client tier and capture Welsh Government, S4C and public-sector procurement work the rest-of-UK consolidators structurally can't access.",
};
