import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "accountant marketing Edinburgh",
    "Edinburgh accountant SEO",
    "accountancy practice marketing Edinburgh",
    "Lothian accountant lead generation",
    "small business accountant Edinburgh marketing",
  ],
  secondaryKeywords: [
    "Edinburgh ICAS chartered accountant marketing",
    "New Town financial services accountant",
    "Stockbridge SME accountant SEO",
    "Bruntsfield Morningside private client accountant",
    "Leith creative SME accountant Google Ads",
    "Edinburgh festival hospitality accountant",
    "Scottish trust partnership accountant Edinburgh",
    "MTD ITSA Lothian landlord campaigns",
  ],
  heroSubhead:
    "Edinburgh hosts the UK's second-largest financial centre and the headquarters of ICAS at CA House on Hampden Gardens — making it the most concentrated chartered accountancy market in Scotland. £800B+ in assets under management anchors RBS/NatWest, Standard Life Aberdeen, Baillie Gifford, Aegon and Scottish Widows; the legal cluster (Brodies, Burness Paull, Shepherd and Wedderburn, CMS, Dentons, Pinsent Masons) drives professional-services SME demand; Festival-season hospitality generates hundreds of seasonal-trader Self-Assessments; and the New Town/Stockbridge/Bruntsfield/Morningside premium belt carries Scotland's highest-fee private client work at £800-£3,000/month. Named locals include Chiene + Tait, Whitelaw Wells, Anderson Strathern (legal-adjacent), Geoghegans, Springfords, Fife and Edinburgh Audit; consolidators AAB UK and Azets (post-Campbell Dallas) compete aggressively. ICAS-regulated marketing, Scottish-tax expertise, and Festival-season-aware funnels separate winning Edinburgh practices from rest-of-UK templated competitors. Kerblabs builds those funnels.",
  marketContext: [
    "Edinburgh's accountancy market is uniquely shaped by ICAS proximity. CA House at 21 Haymarket Yards (formerly Hampden Gardens) is the headquarters and regulatory home of Scotland's chartered accountancy profession, with 23,000+ members worldwide and the densest UK concentration of ICAS-qualified partners outside London. Edinburgh practices are predominantly ICAS-regulated, dual-qualified ICAS+ACCA or ICAS+ICAEW partners are common, and the regulatory framework (ICAS Code of Ethics, CA Practice Manual, ICAS AML Supervision) sits alongside the broader Scottish-specific tax and corporate landscape that distinguishes the market. Scottish Income Tax bands diverge materially from rest-of-UK (top rate 48% vs 45% UK), Land and Buildings Transaction Tax replaces SDLT with the 8% Additional Dwelling Supplement on second properties, Scottish trust and partnership law has subtle differences, Companies House Scotland is in Edinburgh itself, and Revenue Scotland administers devolved taxes. The Scottish Government's annual budget routinely diverges from Westminster on tax thresholds, increasing the value of named-Scottish-tax expertise to clients across the Lothians.",
    "Pricing and named local competitors: Edinburgh SME accountancy fees for an owner-managed Ltd company with bookkeeping, VAT, payroll, year-end and corporation tax run £200-£500/month — at the high end of Scottish pricing because of the financial-services concentration and the affluent New Town/Stockbridge/Morningside professional client base. Self-Assessment runs £200-£500 retail, property portfolio Self-Assessments with multiple BTLs and Scottish ADS implications run £450-£1,200, HNW returns with trust structures run £800-£3,000, and small-Ltd year-end accounts plus CT600 run £800-£2,500. The New Town/Bruntsfield/Morningside premium belt commands fee premiums of 30-50% above central Edinburgh and supports HNW relationships at £800-£3,000/month. Named local independents include Chiene + Tait (a strong Edinburgh and London firm with long ICAS heritage), Whitelaw Wells, Geoghegans, Springfords, Anderson Strathern (legal-adjacent corporate and trust work), Fife & Edinburgh Audit, Henderson Loggie (active in Edinburgh as well as Tayside-Glasgow), Johnston Carmichael (Edinburgh office). Consolidators AAB UK (post-French Duncan), Azets (post-Campbell Dallas), Saffery Champness, BDO, RSM, EY, KPMG and PwC all anchor the New Town financial-services district. TaxAssist runs 4+ Edinburgh-region franchises but the city centre is dominated by ICAS-led named-partner firms rather than franchise high-street.",
    "Edinburgh Google Ads CPCs in accountancy keywords run £8-£16 for 'accountant near me Edinburgh', £10-£20 for 'small business accountant Edinburgh', £12-£24 for 'accountant for ltd company Edinburgh', £15-£28 for 'IR35 accountant Edinburgh' (driven up by the financial-services contractor demand), and £18-£34 for 'private client accountant Edinburgh' specifically because of the HNW base. The strategic implication is that Edinburgh paid acquisition is unusually profitable on premium long-tail terms — 'Scottish trust accountant', 'estate planning accountant Edinburgh', 'EIS investor accountant Stockbridge', 'private client tax adviser Bruntsfield' click at £4-£12 with high commercial intent and almost no competition, while the brutal headline 'accountant Edinburgh' term is dominated by the Big 4 and mid-tier. The MTD ITSA April 2026 cliff is concentrated in the Bruntsfield/Morningside/Murrayfield landlord belt, in the substantial Festival-season seasonal-trader cohort across the Old Town and Leith, and in the New Town professional client base with mixed self-employment income. Kerblabs Edinburgh accountancy clients running premium long-tail ads + Scottish-tax positioning + ICAS-compliant content + named-partner GBP velocity typically reach 5-12 net new monthly client signups inside 6 months at fees 25-50% above Glasgow comparables.",
  ],
  stats: [
    { value: "ICAS HQ", label: "CA House at 21 Haymarket Yards — chartered accountancy regulatory home", source: "ICAS" },
    { value: "£800B+", label: "assets under management in Edinburgh financial sector", source: "TheCityUK / Scottish Financial Enterprise" },
    { value: "£8-£16", label: "Google Ads CPC for 'accountant near me Edinburgh'", source: "Kerblabs client accounts" },
    { value: "£200-£500/mo", label: "typical Edinburgh SME Ltd company fee range — highest in Scotland" },
    { value: "48%", label: "Scottish Income Tax top rate vs 45% rest-of-UK", source: "Scottish Government 2024-25 budget" },
    { value: "April 2026", label: "MTD ITSA cliff hitting Bruntsfield/Morningside landlords and Festival-season traders" },
  ],
  painPoints: [
    {
      title: "AAB UK and Azets aggressive Scottish mid-market consolidation",
      body: "AAB UK has absorbed French Duncan and other Scottish firms; Azets rolled up Campbell Dallas across Scotland. Both compete aggressively in Edinburgh for £500k-£3M owner-managed business work alongside Henderson Loggie, Johnston Carmichael, Saffery Champness, BDO and RSM Edinburgh. Independent two-to-five-partner Edinburgh practices lose mid-market clients because they don't run LinkedIn outbound, don't have Scottish-tax-led service pages, and don't show up in 'business advisor Edinburgh' or 'fractional CFO New Town' search.",
    },
    {
      title: "Premium private client market commoditised by generic 'accountant Edinburgh' messaging",
      body: "Bruntsfield, Morningside, Stockbridge and the New Town carry the highest concentration of HNW private client work in Scotland — Scottish trust structures, family business succession, EIS/SEIS investor portfolios, partnership distributions, multi-property landlord work. Yet most independent practice websites read identically to a Glasgow or Manchester firm's. The premium belt rewards genuinely positioned Scottish-trust, Scottish-tax and HNW expertise — not generic 'we do accounts and tax' messaging.",
    },
    {
      title: "Festival-season seasonal-trader cohort unmarketed",
      body: "Edinburgh's August Festival Fringe, Royal Edinburgh Military Tattoo, Hogmanay and broader festival calendar generates several thousand seasonal-trader Self-Assessments annually — performers, tour operators, F&B pop-ups, Airbnb hosts, festival production crew. Most are sole-trader or single-PSC structures with seasonally peaked income that crosses MTD ITSA thresholds when April 2026 hits. Almost no Edinburgh practice markets explicitly to this cohort, despite it being one of the city's most distinctive demand layers.",
    },
    {
      title: "Bruntsfield/Morningside landlord cohort unprepared for MTD ITSA April 2026",
      body: "Bruntsfield, Morningside, Murrayfield, Cramond and Barnton carry exceptionally heavy multi-property landlord ownership across Scottish ADS-affected portfolios. Many households accumulated 5-30 BTLs across 1990-2015. MTD ITSA hits self-employed and landlords above £50,000 income from April 2026 with Scottish Income Tax bands applied rather than rest-of-UK rates. Most clients don't yet know the timeline. Practices running automated MTD ITSA assessment campaigns now will pick up 30-90 net new landlord clients in 18 months.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs handle the gap between £3,000/month HNW New Town private client work and £200/month Leith creative SME work?",
      a: "We don't run one Edinburgh-wide funnel. We segment by postcode cluster and client type with separate landing pages, ad creative and fee anchoring per segment. The New Town/Stockbridge/Bruntsfield/Morningside premium funnel emphasises ICAS chartered status, named partner credentials with longevity, Scottish trust structures, family business succession planning, EIS/SEIS investor work, multi-property MTD ITSA expertise, and Google reviews from named affluent streets. The Leith/Old Town/Marchmont funnel leads with creative-agency and tech-startup positioning, R&D tax credits, EIS for the area's tech and creative SMEs, transparent fixed-fee pricing for Ltd company accountancy, and reviews from the regenerated waterfront and Old Town wards. The Festival-season seasonal-trader funnel runs as a separate overlay with sole-trader/PSC seasonal-income positioning, MTD ITSA preparation, and Airbnb host tax compliance content. The financial-services-contractor IR35 funnel targets the New Town, Charlotte Square and Lothian Road professional cluster. This stratification typically lifts new-client conversion 35-55% versus a flat city campaign.",
    },
    {
      q: "Are your campaigns ICAS-compliant — important given Edinburgh practices are typically ICAS-regulated?",
      a: "Yes. Edinburgh independent accountancy practices are predominantly ICAS-regulated rather than ICAEW, with CA House at 21 Haymarket Yards as the regulator's headquarters. Every piece of creative, landing page and ad copy is reviewed against ICAS advertising and solicitation rules under the ICAS Code of Ethics, the CA Practice Manual and ICAS Public Practice Regulations, with specific attention to Scottish jurisdictional context, use of the 'CA' designation, and cross-border representation rules where the firm serves clients across UK jurisdictions. For dual-qualified firms (ICAS + ACCA, or ICAS partners with rest-of-UK practice rights via ICAEW reciprocity) we layer both regimes. ICAS AML Supervision compliance is reviewed for marketing data flows ensuring no breach of MLR 2017 record-keeping requirements. We never use 'audit' marketing language unless the firm holds Scottish RSB Audit Registration with ICAS, never use 'specialist' without defensible basis, and never make outcome-guarantee claims on tax savings or HMRC enquiries (which in Scotland may involve both HMRC for income tax/CT and Revenue Scotland for LBTT/SLfT/ADS).",
    },
    {
      q: "How do you handle Scottish-specific tax (Scottish Income Tax, LBTT, ADS, Scottish trusts) and the divergence from rest-of-UK?",
      a: "Scottish-tax expertise is the single most under-marketed structural advantage Edinburgh independent practices hold against rest-of-UK consolidators and online disruptors. Scottish Income Tax has six bands (Starter, Basic, Intermediate, Higher, Advanced, Top) versus three in rest-of-UK, with the top rate at 48% versus 45% UK, and the higher rate threshold below the UK figure. LBTT replaces SDLT on Scottish property with the 8% Additional Dwelling Supplement on second properties calculated differently from the rest-of-UK SDLT 3% surcharge. Scottish trust law differs subtly on succession, taxable presence and reporting. We build it into the customer journey: landing pages with side-by-side worked examples of Scottish-resident vs UK-resident tax outcomes; property and BTL pages covering LBTT and ADS planning explicitly; HNW pages with Scottish trust structures; IR35 contractor pages addressing Scottish-resident PSC dividend planning. Google Ads target Scottish-tax long-tail like 'Scottish trust accountant Edinburgh', 'LBTT property accountant New Town', 'ADS landlord adviser Bruntsfield' — terms with low CPC and high commercial intent that rest-of-UK firms don't bid on.",
    },
    {
      q: "What does the Festival-season seasonal-trader and Airbnb host MTD ITSA strategy look like?",
      a: "Edinburgh's Festival calendar generates one of the UK's most distinctive seasonal-trader cohorts: Fringe performers, Tattoo production crew, festival F&B pop-ups, tour operators, and a substantial Airbnb host population (concentrated through the Old Town, New Town and Leith) whose income is seasonally peaked but annually substantial. Many cross the MTD ITSA threshold (£50k from April 2026, £30k from April 2027) without realising it because the income is bunched in 4-8 weeks and feels like 'extra' rather than self-employment. We build a Festival-season-specific MTD ITSA system: (1) seasonal-trader-specific landing pages addressing Fringe/Tattoo/Festival income, Airbnb host tax compliance, and FHL (Furnished Holiday Letting) status changes (FHL relief abolition from April 2025 is itself a major Edinburgh-relevant issue); (2) targeted Google Ads on 'Airbnb host accountant Edinburgh', 'Festival performer tax Edinburgh', 'seasonal trader accountant Edinburgh'; (3) automated email/SMS sequences educating each cohort on April 2026 timeline; (4) free MTD readiness review with seasonal-income smoothing and Scottish-tax planning as call-to-action. Edinburgh practices running this typically book 40-120 net new seasonal-trader and host clients in 18 months at average annual fees of £400-£1,500.",
    },
  ],
  approach:
    "For Edinburgh independent accountancy practices, our 90-day playbook is: (1) split your market into 5 distinct funnels — New Town/Bruntsfield/Morningside HNW private client and trust work, Stockbridge/Leith creative-and-professional SME, Old Town/Leith Festival-season seasonal-trader and Airbnb host, financial-services IR35 contractor (RBS/NatWest, Baillie Gifford, Standard Life, Aegon contractors), and outer-Lothian TaxAssist-pressured high-street — each with separate landing pages, ad creative and Scottish-tax positioning; (2) deploy AI receptionist plus missed-call text-back with ICAS-compliant tax-deflection scripting and Festival-season capacity overlays; (3) launch the MTD ITSA April 2026 acquisition funnel with Scottish-landlord, seasonal-trader and Airbnb host variants; (4) drive Google review velocity to 6-10 monthly reviews mentioning named Edinburgh neighbourhoods to surface against AAB UK, Azets and Big 4 brand presence; and (5) build LinkedIn-led outbound with explicit Scottish-tax and ICAS-chartered positioning to defend the £500k-£3M client tier against AAB UK, Azets, Henderson Loggie and Johnston Carmichael absorption.",
};
