import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "accountant marketing Derby",
    "Derby accountant SEO",
    "accountancy practice marketing Derby",
    "Derbyshire accountant lead generation",
    "small business accountant Derby marketing",
  ],
  secondaryKeywords: [
    "Rolls-Royce supply chain accountant Derby",
    "Toyota Burnaston supply chain accountant",
    "Alstom Litchurch Lane manufacturer accountant",
    "Smith Cooper Mazars RSM Derby competitor",
    "Allestree Mickleover private client accountant",
    "Derby IR35 engineering contractor accountant",
    "Derby aerospace R&D tax credits accountant",
    "MTD ITSA Derby Derbyshire landlord",
  ],
  heroSubhead:
    "Derby is the UK's most concentrated advanced-engineering accountancy market — Rolls-Royce Civil Aerospace HQ at Sinfin/Raynesway with 14,000+ employees, Toyota Burnaston (5M+ cars produced since 1992), Alstom (formerly Bombardier) at Litchurch Lane (UK's only volume train-manufacturing facility, 3,000+ workforce), Pattonair, JCB Power Systems, plus the wider East Midlands aerospace and rail tier-1 supply chain. Smith Cooper has multi-office Midlands presence (Derby, Nottingham, Birmingham); PKF Smith Cooper similarly; Mazars Derby (now Forvis Mazars), RSM Derby and Crowe Derby compete; named locals include UHY Hacker Young Derby, Brown McLeod, Clarke Bell, plus dozens of two-to-five-partner firms across DE1-DE24. The Allestree, Mickleover, Littleover, Quarndon and Stivichall premium belt carries premium private client work; Derby has unusually concentrated R&D-claim opportunity across aerospace, rail, automotive and power systems. Kerblabs builds Derby-specific accountancy funnels with Rolls-Royce/Toyota/Alstom supply-chain and aerospace-R&D positioning the rest-of-UK competitors don't deliver.",
  marketContext: [
    "Derby's accountancy market is shaped by three forces no other UK city replicates at this scale. First, the Rolls-Royce/Toyota/Alstom blue-chip cluster: Rolls-Royce Civil Aerospace HQ at Sinfin/Raynesway employs 14,000+; Toyota Burnaston (8 miles south-west) has produced 5M+ cars since 1992; Alstom Litchurch Lane is the UK's only volume train-manufacturing facility with 3,000+ workforce; Pattonair (aerospace component supply), JCB Power Systems and a deep tier-1/tier-2 supply chain across DE1-DE7 and DE21-DE24. The aerospace R&D claim opportunity is exceptional — civil aerospace SMEs need substantial R&D-tax-credit work, patent box claims for IP-generating manufacturers, capital allowances on specialist aerospace machinery, and grant-and-claim interaction (ATI Programme, Innovate UK, Faraday Battery Challenge for Toyota's electrification supply chain). The merged R&D scheme effective April 2024 changed mechanics. Aerospace and rail SMEs need specific FRS 102 revenue recognition for long-tenor contracts, milestone billing, and the unusual capital-recovery patterns of aerospace tooling. Second, the East Midlands logistics and M1 corridor: East Midlands Airport (10 miles south, UK's largest dedicated cargo hub), the M1 corridor logistics SME base, and the Pride Park business cluster anchor distinctive logistics and B2B-services accountancy demand. Third, the Allestree/Mickleover/Littleover/Quarndon/Duffield premium belt: Derby has one of the highest concentrations of high-earning STEM professionals per capita in the UK, anchoring premium private client demand at £400-£1,500/month fees including family business succession, EIS/SEIS investor portfolios for the deep aerospace and rail SME ecosystem, and multi-property landlord work.",
    "Pricing and named local competitors: Derby SME accountancy fees for an owner-managed Ltd company with bookkeeping, VAT, payroll, year-end and corporation tax run £150-£380/month — broadly aligned with Nottingham and below Manchester/Leeds. Aerospace and rail SMEs with active R&D claim work command 30-60% premiums at £400-£1,500/month for ongoing claim and capital-allowance optimisation. Self-Assessment runs £150-£380 retail, property portfolio Self-Assessments run £400-£900, and small-Ltd year-end accounts plus CT600 run £600-£1,800. The Allestree (DE22), Mickleover (DE3), Littleover (DE23), Quarndon and Duffield premium belt commands fee premiums of 25-40%. Named local independents include Smith Cooper (East Midlands-headquartered with Derby, Nottingham, Birmingham offices, mid-market specialist), PKF Smith Cooper (separate firm to Smith Cooper, also East Midlands-headquartered), UHY Hacker Young Derby, Clarke Bell, Brown McLeod, Page Kirk (Nottingham with Derby reach), Bowers Partnership (Nottingham-Derby), plus a long tail of two-to-five-partner firms. Big 4 PwC, Deloitte, EY and KPMG operate Derby and Nottingham offices anchored to Rolls-Royce, Toyota and Alstom audit and major clients. Consolidators Azets (post-rollups), BDO Nottingham/Derby reach, RSM Derby, Grant Thornton, Forvis Mazars Derby and Crowe compete for £1M+ owner-managed clients. TaxAssist runs 4-6 East Midlands franchises in striking distance.",
    "Derby Google Ads CPCs in accountancy keywords run £4-£11 for 'accountant near me Derby', £6-£13 for 'small business accountant Derby', £8-£16 for 'accountant for ltd company Derby', and £12-£24 for 'IR35 accountant Derby' driven by Rolls-Royce/Toyota/Alstom contractor demand. CPCs are 30-40% below London and broadly aligned with Nottingham. Borough/postcode-stratified paid acquisition works profitably across Allestree, Mickleover, Littleover and Quarndon at £55-£110 cost-per-signup. The non-obvious lever is aerospace and supply-chain positioning: 'Rolls-Royce supplier accountant Derby', 'Toyota Burnaston supply chain accountant', 'Alstom Litchurch Lane accountant', 'aerospace R&D tax credits Derby', 'rail manufacturer accountant Derby' produce CPCs in the £3-£8 range with high commercial intent and almost no competition. The MTD ITSA April 2026 cliff is concentrated across the Allestree/Mickleover/Quarndon/Duffield/Belper landlord belt and the Pride Park BTL apartment cohort.",
  ],
  stats: [
    { value: "Rolls-Royce 14,000+", label: "Civil Aerospace HQ at Sinfin/Raynesway anchoring aerospace SME supply chain", source: "Rolls-Royce" },
    { value: "Toyota / Alstom", label: "Burnaston car plant (5M+ cars) and UK's only volume train-manufacturing at Litchurch Lane" },
    { value: "£4-£11", label: "Google Ads CPC for 'accountant near me Derby'", source: "Kerblabs client accounts" },
    { value: "£150-£380/mo", label: "typical Derby SME Ltd company fee range" },
    { value: "Smith Cooper / PKF Smith Cooper", label: "the dominant East Midlands independent mid-tier firms" },
    { value: "April 2026", label: "MTD ITSA cliff hitting Allestree/Mickleover/Quarndon landlord belt" },
  ],
  painPoints: [
    {
      title: "Smith Cooper, PKF Smith Cooper and consolidators absorbing the £500k-£3M tier",
      body: "Smith Cooper and PKF Smith Cooper have built deep East Midlands mid-market presence with Derby, Nottingham and Birmingham offices over decades. Mazars Derby (now Forvis Mazars), RSM Derby and BDO Nottingham/Derby reach absorb mid-market clients aggressively. Independent two-to-five-partner Derby practices lose £500k-£3M owner-managed clients because they don't run LinkedIn outbound, don't have aerospace/rail/automotive supply-chain specialist service pages, and don't show up in 'business advisor Derby' or 'fractional CFO aerospace' search.",
    },
    {
      title: "Aerospace and rail R&D and supply-chain work undermarketed despite genuine technical depth",
      body: "Rolls-Royce Civil Aerospace, Toyota Burnaston, Alstom Litchurch Lane (UK's only volume train-manufacturing facility), Pattonair and the wider East Midlands aerospace and rail tier-1 supply chain anchor a substantial R&D-claim and supply-chain accountancy market. Most independent Derby practices have genuine R&D claim experience but don't surface it in marketing — leaving aerospace, rail and automotive R&D and supply-chain work flowing to Smith Cooper, PKF Smith Cooper, Big 4 and specialist boutiques by default.",
    },
    {
      title: "Engineering professional STEM-graduate cohort research-driven and hard to win generically",
      body: "Derby has one of the UK's highest concentrations of STEM graduates and engineering professionals working at Rolls-Royce, Toyota, Alstom, JCB, MTC adjacency. This audience researches accountants thoroughly — visiting websites multiple times, reading every Google review, scrutinising ICAEW/ACCA registration, comparing line-item quotes carefully — and rejects generic 'we do tax' messaging. Independent Derby practices need detailed technical content rather than glossy hero shots.",
    },
    {
      title: "Allestree/Mickleover/Quarndon landlord cohort unprepared for MTD ITSA April 2026",
      body: "The Allestree (DE22), Mickleover (DE3), Littleover (DE23), Quarndon, Duffield (DE56) and Belper premium belt carries heavy multi-property landlord ownership accumulated over 20+ years by Rolls-Royce/Toyota/Alstom professional households. Many hold 5-15 BTLs. MTD ITSA hits self-employed and landlords above £50,000 income from April 2026. Most clients don't yet know quarterly digital reporting is mandatory.",
    },
  ],
  faqs: [
    {
      q: "How do you handle the Rolls-Royce/Toyota/Alstom aerospace and rail supply chain R&D opportunity specifically?",
      a: "Derby's aerospace, rail and automotive supply chain is the most distinctive accountancy opportunity in the East Midlands and the most under-marketed structural advantage Derby independents hold. Rolls-Royce Civil Aerospace HQ anchors hundreds of tier-1/tier-2 aerospace SMEs across DE3, DE21, DE22 and DE24; Toyota Burnaston anchors automotive supply chain across the wider Derbyshire/Staffordshire footprint; Alstom Litchurch Lane (UK's only volume train-manufacturing facility) anchors rail supply chain. The merged R&D scheme effective April 2024 changed mechanics for SMEs. We build R&D-specialist landing pages with worked examples of typical aerospace, rail and automotive SME claim sizes (often £80k-£500k+ benefit), patent box benefit modelling for IP-generating manufacturers, capital allowances and full-expensing optimisation for aerospace tooling and rail manufacturing plant, and grant-and-claim interaction (ATI Programme, Innovate UK, Faraday Battery Challenge, Driving the Electric Revolution). Aerospace-and-rail-supplier-specific accountancy content covers tooling cost recovery, milestone billing, capital-recovery patterns for long-tenor aerospace contracts, FRS 102 revenue recognition. Google Ads target 'Rolls-Royce supplier accountant Derby', 'Toyota Burnaston supply chain accountant', 'Alstom rail manufacturer accountant', 'aerospace R&D tax credits Derby' — currently low CPC and high commercial intent.",
    },
    {
      q: "How do we compete with Smith Cooper, PKF Smith Cooper and the East Midlands mid-tier on Derby owner-managed business?",
      a: "Smith Cooper and PKF Smith Cooper hold long-tenure regional relationships and multi-office East Midlands footprints with deep manufacturing expertise. Independent two-to-five-partner Derby practices win on three structural advantages: (1) named-partner relationships where the founding partner actually does the work — Derby engineering-professional owner-managers cite this as the reason they leave Smith Cooper or PKF Smith Cooper after a partner-track rotation hands them to a manager; (2) sub-sector specialisation in something the larger firms treat as generic — aerospace civil supply chain (specific Rolls-Royce technical depth), rail manufacturing (Alstom Litchurch Lane and the rail tier-2 base), Toyota and electric vehicle transition supply chain, JCB Power Systems and adjacent power-systems SMEs, East Midlands Airport and Pride Park logistics and aviation services; and (3) explicit research-led, technically-detailed positioning — Derby engineering professionals reject glossy hero-image marketing and reward detailed technical content with named expert profiles, ICAEW/ACCA registration prominence, and case-study depth. Kerblabs builds LinkedIn outbound, sub-sector landing pages and trigger-event marketing. Derby practices running this typically grow £400/month+ client base 25-50% inside 12 months while Smith Cooper retains incumbent relationships.",
    },
    {
      q: "Can the AI receptionist actually distinguish a Rolls-Royce supplier SME enquiry from a Toyota Burnaston supplier from an Alstom rail SME?",
      a: "Yes — that's the core qualifying flow for Derby specifically. The AI's first three questions cover: are you a Ltd company director, sole trader/freelancer, employee/contractor (and if contractor, current engagement), or landlord; what sector (aerospace civil supply chain, rail/train manufacturing, automotive supply chain, power systems, logistics/aviation services, professional services, retail/F&B, property landlord); what's your relationship to the major Derby employers (current employee, ex-employee consulting, supply chain SME serving them). Aerospace civil supply enquiries route to the R&D-and-tooling-specialist partner with sector intake (Rolls-Royce tier classification, contract-tenor pattern); rail enquiries route to the rail-manufacturing-specialist partner (Alstom relationship, long-tenor contract structures); automotive enquiries route to the EV-transition-aware specialist (Toyota's electrification supply chain). The AI never gives tax advice — it deflects regulated questions. Calls dropped into your CRM with structured intake summaries.",
    },
    {
      q: "What does the MTD ITSA strategy look like specifically for the Allestree/Mickleover/Quarndon premium landlord belt?",
      a: "The Derby premium belt — Allestree (DE22), Mickleover (DE3), Littleover (DE23), Quarndon, Duffield (DE56) and Belper — has unusually heavy multi-property landlord ownership accumulated over 20+ years by Rolls-Royce, Toyota, Alstom and JCB professional households. Many households hold 5-15 BTLs accumulated through 2000-2015 BTL boom plus the post-2015 affordability crisis acquisition wave. MTD ITSA hits self-employed and landlords above £50,000 income from April 2026, dropping to £30,000 from April 2027. Engineering professionals are research-driven — they will read full MTD ITSA briefings before booking, scrutinise quarterly-reporting cost implications, and want clear technical content rather than marketing language. We build a Derby-specific MTD ITSA system: (1) DE-postcode landing pages with detailed technical content on quarterly reporting requirements, software requirements (Xero, QuickBooks, FreeAgent, Sage), and pricing transparency; (2) Google Ads on 'MTD landlord accountant Allestree', 'Mickleover BTL MTD ITSA', 'Quarndon landlord accountant'; (3) detailed technical email sequences engineering professionals actually read; (4) free MTD readiness review with portfolio assessment and software-migration planning. Derby practices running this typically book 25-70 net new landlord clients in the 18 months running into April 2026.",
    },
  ],
  approach:
    "For Derby independent accountancy practices, our 90-day playbook is: (1) split your market into 5 distinct funnels — Rolls-Royce aerospace civil supply chain SME and R&D, Toyota Burnaston automotive and EV-transition supply chain, Alstom Litchurch Lane rail manufacturing, Allestree/Mickleover/Quarndon premium private client and landlord, and East Midlands Airport/Pride Park logistics and aviation services — each with separate landing pages, ad creative and detailed technical content (engineering professionals reject glossy marketing); (2) deploy AI receptionist with sector-specific qualifying flow; (3) launch the MTD ITSA April 2026 acquisition funnel targeting the DE22/DE3/DE23/DE56 landlord belt with detailed technical content; (4) drive Google review velocity to 5-10 monthly reviews mentioning named Derby suburbs, ICAEW/ACCA registration, and aerospace/rail/automotive specialism; and (5) build LinkedIn-led sub-sector and FD-light outbound to defend the £500k-£3M client tier against Smith Cooper, PKF Smith Cooper and consolidator absorption.",
};
