import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "accountant marketing Aberdeen",
    "Aberdeen accountant SEO",
    "accountancy practice marketing Aberdeen",
    "North East Scotland accountant lead generation",
    "oil gas service company accountant Aberdeen",
  ],
  secondaryKeywords: [
    "Aberdeen oil gas project rate card accountant",
    "FPSO contractor accountant Aberdeen",
    "Westhill Cults Bieldside SME accountant",
    "Anderson Anderson Brown competitor Aberdeen",
    "Aberdeen energy transition ScotWind accountant",
    "Aberdeen IR35 contractor accountant",
    "Aberdeenshire MTD ITSA landlord",
    "Aberdeen Norwegian Dutch expat accountant",
  ],
  heroSubhead:
    "Aberdeen runs the most distinctive UK accountancy market — built around oil and gas service-company complexity, FPSO and rig-day-rate contractor invoicing, project-rate-card revenue recognition and one of the highest concentrations of internationally-mobile expat clients outside London. Anderson Anderson & Brown (AAB UK) is headquartered in Aberdeen and is one of the most aggressive consolidators in UK mid-tier accountancy; Johnston Carmichael, Hall Morrice, Meston Reid and Ritson Smith anchor named-local mid-market presence; Stronachs and Burness Paull adjacency drives professional-services support work. The Cults/Bieldside/Milltimber and Westhill premium belt carries Scotland's third-most-affluent client base after Edinburgh New Town and Glasgow's East Renfrewshire. Energy transition (ScotWind, Acorn CCS, hydrogen, Energy Transition Zone) is reshaping the workforce composition through the late 2020s. Kerblabs builds Aberdeen-specific accountancy funnels with oil-and-gas, energy-transition, expat and rotation-aware positioning the rest-of-UK consolidators don't deliver.",
  marketContext: [
    "Aberdeen's accountancy market is shaped by three forces no other UK city replicates. First, oil and gas service-company complexity: project-rate cards, FPSO and platform day rates, JOA (Joint Operating Agreement) cost recovery, AFE (Authorisation for Expenditure) accounting, decommissioning provisions under FRS 102 Section 21, and the unusual revenue-recognition timing of oil-and-gas service work where contracts span multiple years and milestones. AAB UK is headquartered at Prime Four Business Park in Kingswells and built much of its reputation on oil and gas service-company expertise; Johnston Carmichael (HQ in Aberdeen) similarly anchors energy-sector accountancy across the UK; Hall Morrice, Meston Reid, Ritson Smith and Brown McNeil cover named-local mid-market work. Second, the expat client cohort: Norwegian, Dutch, American and Houston-based oil professionals on 2-4 year postings form a meaningful slice of the private client base, requiring dual-jurisdiction tax expertise, US FATCA and FBAR reporting, Norwegian Skatteetaten interaction, double-tax treaty optimisation and Statutory Residence Test analysis. Third, the rotation rhythm: 2-on/3-off and 4-on/4-off offshore patterns drive client availability and booking behaviour unlike any other UK city, with crew-change Fridays at Dyce heliport creating sharp peaks.",
    "Pricing and named local competitors: Aberdeen SME accountancy fees for an owner-managed Ltd company with bookkeeping, VAT, payroll, year-end and corporation tax run £180-£480/month — at the high end of Scottish pricing because of the oil-and-gas service-company complexity premium and the affluent Cults/Westhill client base. Service-company specialist work (offshore engineering, subsea, well services, ROV operations) commands higher fees again at £400-£1,500/month for Ltd companies with 5-50 employees. Self-Assessment for offshore-rotation contractors and PSC operators runs £250-£800 retail (typically more complex than mainstream Self-Assessment because of offshore allowances, Seafarers' Earnings Deduction qualification, and dual-jurisdiction implications). Property portfolio work runs £400-£1,200, and small-Ltd year-end accounts plus CT600 run £700-£2,200. Named locals beyond AAB UK and Johnston Carmichael include Hall Morrice (long-established Aberdeen mid-market firm), Meston Reid, Ritson Smith, Brown McNeil, EQ Accountants, Wilson Wright (also London) and Henderson Loggie's Aberdeen presence; Big 4 (Deloitte, EY, KPMG, PwC) all maintain Aberdeen offices anchored to oil-and-gas audit work. TaxAssist runs 2-3 Aberdeenshire franchises but the city centre is dominated by ICAS-led named-partner firms.",
    "Aberdeen Google Ads CPCs in accountancy keywords run £8-£18 for 'accountant near me Aberdeen', £10-£22 for 'small business accountant Aberdeen', £14-£28 for 'oil and gas accountant Aberdeen' specifically, and £12-£26 for 'IR35 contractor accountant Aberdeen' driven by the very heavy offshore PSC contractor base. CPCs are surprisingly high for a city Aberdeen's size because the customer-base economics support premium spend — oil-and-gas customer purchasing power keeps premium-treatment CPCs closer to Edinburgh than to Aberdeen's population base would suggest. Borough/postcode-stratified paid acquisition works profitably across AB13 (Cults/Bieldside), AB15 (West End/Milltimber), AB32 (Westhill), AB12 (Portlethen) and AB30 (Inverurie) at £80-£160 cost-per-signup. The non-obvious lever is energy-transition positioning: ScotWind contractor accountancy, Acorn CCS supply-chain accountancy, hydrogen-pilot startup accountancy, and Energy Transition Zone tenant accountancy are all under-bid and high-intent. The MTD ITSA April 2026 cliff is concentrated across the Cults/Westhill/Milltimber/Bieldside landlord belt and the substantial offshore-PSC contractor cohort with property income above the £50k threshold.",
  ],
  stats: [
    { value: "AAB UK HQ", label: "Anderson Anderson & Brown headquartered Prime Four Business Park, Kingswells", source: "AAB UK" },
    { value: "£8-£18", label: "Google Ads CPC for 'accountant near me Aberdeen' (high for population)", source: "Kerblabs client accounts" },
    { value: "£180-£480/mo", label: "typical Aberdeen SME Ltd company fee range" },
    { value: "ScotWind 20GW+", label: "offshore wind leasing pipeline driving energy-transition accountancy demand", source: "Crown Estate Scotland" },
    { value: "2-on/3-off", label: "offshore rotation rhythm reshaping client availability and booking patterns" },
    { value: "Norwegian/Dutch/US", label: "expat cohort requiring dual-jurisdiction tax and FATCA/FBAR expertise" },
  ],
  painPoints: [
    {
      title: "AAB UK's home-turf consolidation absorbing the £500k-£3M owner-managed business tier",
      body: "Anderson Anderson & Brown is headquartered in Aberdeen and has been one of the UK's most aggressive accountancy consolidators (rolling up French Duncan, Sagars and others across Scotland and rest-of-UK). On home turf, AAB UK's Aberdeen office competes hardest of all for £500k-£3M owner-managed business work alongside Johnston Carmichael, Big 4, Hall Morrice and Henderson Loggie. Independent two-to-five-partner Aberdeen practices lose mid-market oil-and-gas service-company clients because they don't run LinkedIn outbound, don't have FRS 102 Section 21 oil-and-gas-specific service pages, and don't show up in 'oil gas accountant Aberdeen' search.",
    },
    {
      title: "Oil-and-gas service-company complexity undermarketed despite real expertise",
      body: "Project-rate cards, JOA cost recovery, AFE accounting, decommissioning provisions, FPSO day-rate revenue recognition, percentage-of-completion vs milestone billing, IR35 contractor PSC structures common in subsea engineering — these are technical specialisms most independent Aberdeen practices have but don't surface in marketing. Generic 'we do accounts and tax' messaging concedes the high-fee oil-and-gas service-company tier to AAB UK and Johnston Carmichael by default. The single biggest under-marketed advantage Aberdeen independents hold is genuine oil-and-gas service-company expertise.",
    },
    {
      title: "Energy-transition positioning absent across local practices",
      body: "ScotWind floating offshore wind, Acorn CCS at St Fergus, hydrogen pilots and the Aberdeen Energy Transition Zone are reshaping client demand through 2025-2030. New entrants and pivoting incumbents need accountants familiar with renewables tax incentives, R&D tax credits in energy-transition contexts, contract accounting for ScotWind supply chain, and EIS/SEIS for the cluster of energy-transition startups. Almost no Aberdeen independent practice positions explicitly for this work, leaving the field open to AAB UK and Johnston Carmichael.",
    },
    {
      title: "Expat cohort dual-jurisdiction work flowing to specialists by default",
      body: "Aberdeen has unusually heavy Norwegian, Dutch, American and Houston expat density requiring dual-jurisdiction tax expertise, US FATCA and FBAR reporting, Norwegian Skatteetaten interaction, double-tax treaty optimisation, Statutory Residence Test analysis and Seafarers' Earnings Deduction qualification work. Most independent Aberdeen practices don't market this expertise even when they have it, conceding the work to Big 4 mobility teams or specialist boutiques.",
    },
  ],
  faqs: [
    {
      q: "How do we compete with AAB UK on home turf for £500k-£3M oil-and-gas service-company work?",
      a: "AAB UK is Aberdeen-headquartered, oil-and-gas-deep, and aggressive in consolidation — but it's still only one firm and it's running consolidation playbook that creates structural opportunities for independents. Independent two-to-five-partner Aberdeen practices win on three advantages AAB UK structurally cannot offset: (1) named-partner relationships where the founding partner actually does the technical work — owner-managers running £2-5M oil-and-gas service companies cite this enormously and routinely leave AAB UK after a partner-track rotation hands them to a manager; (2) sub-sector specialisation that AAB UK treats as generic — subsea engineering, ROV operations, well services, decommissioning specialist contractors, marine geophysical survey, drilling fluids; and (3) energy-transition positioning that recognises the workforce migration into ScotWind, Acorn CCS and hydrogen rather than being seen as legacy oil-and-gas only. Kerblabs builds LinkedIn outbound to specific oil-and-gas service-company segments, sub-sector landing pages with FRS 102 Section 21 expertise messaging, energy-transition positioning, and review velocity from named oil-and-gas clients. Aberdeen practices running this typically grow £500/month+ client base 25-45% inside 12 months while AAB UK competes on Big 4 ground for audit-required clients.",
    },
    {
      q: "Can the AI receptionist handle the offshore-rotation rhythm and crew-change peak windows?",
      a: "Yes — and getting this right is one of the highest-leverage configurations in Aberdeen specifically. Offshore workers on 2-on/3-off, 4-on/4-off or 14/14 rotations book accountancy meetings, file Self-Assessments and chase HMRC questions in compressed onshore windows, often calling in the unusual 4am-7am peak when crews land back from Dyce, or in late Friday afternoons before crew change. The AI is configured to recognise rotation-pattern keywords ('I'm offshore', 'I rotate', 'I'm only home for two weeks'), prioritise booking the meeting inside the onshore window, and flag the lead as offshore-rotation client for the partner's attention. SE Deduction qualification questions, offshore-allowance treatment, and overseas-day-count tracking for SRT (Statutory Residence Test) are all common offshore-contractor enquiries — the AI deflects regulated tax advice, but captures structured intake data so the partner walks into the meeting briefed. Crew-change-Friday call volumes can run 3-5x the daily baseline; AI capacity scales without additional cost. ICAS Code of Ethics compliance reviewed.",
    },
    {
      q: "What does the energy-transition ScotWind/Acorn CCS/hydrogen accountancy strategy look like?",
      a: "Aberdeen's energy transition is not a collapse — it's a workforce and supply-chain rebuild reusing roughly the same engineering and finance skill profile that built oil and gas. ScotWind's 20GW+ leasing pipeline, the Acorn CCS cluster at St Fergus, hydrogen pilots, and the Aberdeen Energy Transition Zone south of the harbour together create new SME formation through 2025-2030 for accountants positioned to capture it. We build a five-stage energy-transition system: (1) sub-sector landing pages for ScotWind supply chain (turbine installation contractors, cable laying, foundation engineering), Acorn CCS supply chain, hydrogen production startups, and ETZ tenants; (2) Google Ads on 'ScotWind contractor accountant', 'CCS startup accountant Aberdeen', 'hydrogen startup accountant', 'energy transition R&D tax credits Aberdeen' — all currently with low CPCs and almost no competition; (3) LinkedIn outbound to specific energy-transition founders and finance leads; (4) R&D tax credit, EIS/SEIS and capital allowance content tailored to energy-transition tax incentives; (5) partnerships with ETZ tenant accelerators and ScotWind supply-chain bodies. Aberdeen practices running this typically build a 30-80 client energy-transition book within 18 months at £400-£1,500/month fees.",
    },
    {
      q: "How do you handle the Norwegian, Dutch and American expat dual-jurisdiction tax work?",
      a: "Aberdeen's expat cohort is one of the densest UK concentrations of internationally-mobile high-earners outside London — Norwegian, Dutch, American (often Houston-based oil professionals) and increasingly Indian and Filipino energy-sector professionals on 2-4 year postings. Dual-jurisdiction work needs explicit positioning: Statutory Residence Test analysis, double-tax treaty optimisation (UK-Norway, UK-Netherlands, UK-US), US FATCA and FBAR compliance for American expats (an absolute requirement that most expats don't fully understand), Norwegian Skatteetaten interaction, Seafarers' Earnings Deduction qualification, and remittance-basis vs arising-basis planning for non-domiciled clients. We build expat-specific landing pages with multilingual review snippets where the practice has Norwegian or Dutch-speaking partners, Google Ads on 'US expat accountant Aberdeen', 'Norwegian expat accountant Aberdeen', 'oil and gas expat tax adviser Aberdeen', and partnerships with the relocation agencies and oil-major mobility teams that route this work. ICAS Code of Ethics compliance reviewed; expat work also requires careful AML enhanced due-diligence which we configure into the lead intake.",
    },
  ],
  approach:
    "For Aberdeen independent accountancy practices, our 90-day playbook is: (1) split your market into 5 distinct funnels — oil-and-gas service-company SME and £500k-£3M owner-managed, offshore-PSC IR35 contractor with rotation-aware booking, energy-transition (ScotWind/Acorn CCS/hydrogen/ETZ) startup and supply-chain, expat dual-jurisdiction private client (Norwegian/Dutch/US/Houston), and Cults/Westhill/Milltimber premium private client and landlord — each with separate landing pages, ad creative and sub-sector positioning; (2) deploy AI receptionist with rotation-pattern recognition, crew-change-Friday capacity scaling, and ICAS-compliant tax-deflection scripting; (3) launch the MTD ITSA April 2026 acquisition funnel targeting the AB13/AB15/AB32 landlord belt and the offshore-PSC contractor cohort with property income; (4) drive Google review velocity to 5-10 monthly reviews mentioning named Aberdeen neighbourhoods and naming oil-and-gas/energy-transition sub-sectors to surface against AAB UK and Johnston Carmichael brand presence; and (5) build LinkedIn-led outbound to defend the £500k-£3M client tier against AAB UK home-turf consolidation.",
};
