import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "bathroom fitter marketing Glasgow",
    "bathroom designer marketing Glasgow",
    "tenement bathroom installer Glasgow",
    "wet room installer Glasgow",
    "Glasgow bathroom showroom SEO",
  ],
  secondaryKeywords: [
    "Glasgow Bathroom Centre alternative",
    "Ripples Glasgow alternative bathroom designer",
    "West End tenement bathroom refit Glasgow",
    "Hyndland Hillhead Partick bathroom installer",
    "Bearsden Newton Mearns bespoke bathroom",
    "soil stack relocation tenement Glasgow",
    "Pollokshields bathroom installer",
    "Shawlands Strathbungo bathroom designer",
  ],
  heroSubhead:
    "Glasgow is the UK's most tenement-defined bathroom market. The West End (Hyndland, Partick, Hillhead, Dowanhill) and Southside (Shawlands, Strathbungo, Pollokshields) are dominated by pre-1914 sandstone tenement flats with shared soil-stack runs, no concrete slab, awkward joist directions and cast-iron drainage that retail-chain installers won't touch — making tenement-retrofit specialism the single biggest defensible advantage for any Glasgow independent. West End premium refits routinely clear £12,000–£25,000; Bearsden, Newton Mearns and Giffnock bespoke crosses £30,000. Ripples Glasgow and Glasgow Bathroom Centre anchor the premium tier; Wickes Darnley and B&Q Pollok push installed-bathroom finance against the £6–12k middle. Kerblabs gives Glasgow independent bathroom studios the AI receptionist, G-postcode-stratified Houzz funnel, deposit-conversion automation, tenement-retrofit authority and review velocity to win against the chains.",
  marketContext: [
    "Glasgow's bathroom market is structurally defined by the city's pre-1914 sandstone tenement housing stock, which dominates the West End (G11 Partick, G12 Hillhead/Hyndland/Dowanhill, G3 Finnieston/Yorkhill) and the inner Southside (G41 Shawlands/Strathbungo/Pollokshields, G42 Battlefield/Govanhill, G43 Pollokshaws). Tenement bathrooms have a specific set of constraints that retail-chain installers structurally cannot handle: there is no concrete slab to chase services into (joists run directly under floorboards), the soil stack is shared with the flats above and below and runs through the kitchen or hall in awkward boxed-in routes, the original cast-iron drainage often needs partial replacement at first-floor level requiring access to the close stairwell, lath-and-plaster ceilings need careful preservation during downlighter install, and Tenement Management Schemes (under the Tenements (Scotland) Act 2004) require neighbour consultation for any works affecting common property. Bathroom firms who don't understand this lose jobs at survey stage; firms who do command a 30–50% premium because the pool of capable competitors is materially smaller than the marketed independent base suggests.",
    "Project values stratify sharply. West End premium tenement refits in G11 and G12 routinely clear £12,000–£25,000 once Crosswater or Hansgrohe brassware, walk-in shower with concealed thermostatic, vanity unit replacement and full retile is factored in, with Hyndland and Dowanhill bespoke specifications crossing £30,000. The East Renfrewshire and East Dunbartonshire premium suburban belt (Bearsden, Milngavie, Newton Mearns, Giffnock, Whitecraigs, Clarkston) operates as a different market entirely: detached and semi-detached villa stock, bespoke specifications with Lefroy Brooks or Drummonds brassware, freestanding cast-iron baths, £25,000–£60,000 whole-house bathroom programmes, and a referral-led economy where Houzz reviews and Google review velocity matter more than paid spend. Move into the Southside (G41 Shawlands/Strathbungo/Pollokshields, G42 Battlefield/Govanhill, G43 Pollokshaws) and the market is £8,000–£15,000 tenement refits with the same retrofit constraints as the West End. The East End regeneration corridor (Dennistoun G31, Bridgeton G40, Clyde Gateway) sits at £6,000–£12,000 standard-spec refits. The Pollokshields G41 South Asian heritage community sustains a specific bridal-cosmetic-bathroom-spec demand pattern around prayer-washing wudu configurations that mainstream installers don't model — wedding-driven master bathroom refits clustering around Asian wedding seasons December–March and June–September.",
    "The non-obvious 2026 wins for Glasgow independents are threefold. First, the tenement-retrofit specialism: Ripples Glasgow and Glasgow Bathroom Centre compete strongly on bespoke specification but neither holds a structural advantage on the soil-stack relocation, joist-reinforcement and Tenement Management Scheme neighbour-consultation work that wins West End and Southside jobs. Second, the Pollokshields prayer-washing wudu bathroom configuration specialism — a bridal-and-family-bathroom market driven by wedding-season cycles that Wickes Darnley, Wren and B&Q DIY-route structurally cannot service. Third, the Disabled Facilities Grant pipeline across Glasgow City Council, East Renfrewshire, East Dunbartonshire, Renfrewshire and South Lanarkshire — the council-funded accessibility pipeline up to £30,000 per applicant where Glasgow's strong tenement-retrofit installer base has a natural advantage on level-access wet-room conversions in awkward soil-stack constraints. The 2019 Bathstore collapse closed the Glasgow Braehead and Glasgow Fort showrooms and left hundreds of G-postcode homeowners with paid deposits and unfinished bathrooms — that trust hangover is now a structural advantage for any independent who can prove staged-payment safety, named subcontractor credentials and a demonstrable five-year-plus trading history with named WaterSafe approved plumber, Gas Safe register and NICEIC Part P registration.",
  ],
  stats: [
    { value: "£12,000–£25,000", label: "typical West End (G11 Partick / G12 Hillhead / Hyndland / Dowanhill) tenement refit value" },
    { value: "£25,000–£60,000", label: "typical Bearsden / Newton Mearns / Giffnock / Whitecraigs whole-house bathroom programme value" },
    { value: "£8,000–£15,000", label: "typical Southside (G41 Shawlands / Strathbungo / Pollokshields) tenement refit value" },
    { value: "£6,000–£12,000", label: "typical East End regeneration corridor (Dennistoun G31 / Bridgeton G40) standard-spec refit value" },
    { value: "Up to £30,000", label: "DFG accessibility grant per applicant via Glasgow City Council and surrounding HSCPs" },
    { value: "100+ years", label: "typical age of West End and Southside tenement plumbing infrastructure requiring soil-stack and joist specialism" },
  ],
  painPoints: [
    {
      title: "Ripples Glasgow and Glasgow Bathroom Centre outspending you on premium G11 / G12 / G77 search",
      body: "Ripples Glasgow (regional anchor of the ~25-showroom national group) and Glasgow Bathroom Centre run unified bidding on 'bespoke bathroom designer Hyndland', 'wet room installer Bearsden' and 'walk-in shower Newton Mearns' with marketing budgets and showroom-funded media spend. Independents in Partick, Shawlands, Strathbungo and Dennistoun cannot match cost-per-click but win the long tail (specific suite × specific G-postcode), response speed at 10pm, and tenement-retrofit operational authority — which Ripples and the chains structurally cannot replicate at scale because their installers don't carry day-in-day-out experience of West End soil-stack relocations and Tenement Management Scheme neighbour-consultation work.",
    },
    {
      title: "Tenement-retrofit specialism completely under-marketed by most Glasgow independents",
      body: "Glasgow's pre-1914 sandstone tenement stock has structural constraints — no concrete slab, awkward joist directions, shared soil-stack runs through kitchens and halls, lath-and-plaster ceilings, Tenement Management Scheme neighbour-consultation requirements — that retail-chain installers won't handle and that mainstream bathroom marketing completely ignores. Yet most Glasgow independents have generic websites with stock photos that say nothing about soil-stack relocation experience, joist-reinforcement protocols, or Code 5 lead specification for tenement first-floor flat installations. We rebuild around named West End and Southside tenement case studies on actual G11, G12 and G41 streets — with before/after photography, technical detail on soil-stack runs and joist reinforcement, and explicit Tenement Management Scheme handling for shared common-property work.",
    },
    {
      title: "10pm Houzz, Instagram and West End enquiries dying overnight",
      body: "Glasgow homeowners researching £10k–£25k bathrooms DM Instagram, save Pins to Houzz and submit website enquiries between 8pm and 11pm — particularly West End young-professional households after Finnieston and Merchant City evening commute windows. Single-designer studios and 2–8-staff fitting firms cannot manually triage 12–30 evening enquiries a week, so 60–80% are dead by morning to a faster Ripples Glasgow or Glasgow Bathroom Centre reply. AI receptionist plus Houzz Pro and Instagram DM auto-routing closes that gap inside 90 seconds and routinely adds £20,000–£50,000 in monthly recovered design-appointment value.",
    },
    {
      title: "Pollokshields prayer-washing wudu configuration specialism uncaptured by Wickes / Wren / B&Q DIY-route",
      body: "The Pollokshields G41 South Asian heritage community sustains a specific bathroom configuration demand pattern around prayer-washing wudu provision — a half-height pour-over fixture with dedicated drainage, often integrated into the master bathroom adjacent to a walk-in shower, and clustered around bridal and Asian wedding-season cycles December–March and June–September. Wickes Darnley, Wren, B&Q DIY-route and most generalist Glasgow independents have no positioning around this configuration, no Urdu/Punjabi multilingual response capability, and no GBP attribute optimisation for the community-specific search behaviour. We build a dedicated Pollokshields-specialism funnel with multilingual landing pages, WhatsApp Business intake, and named case studies that compound community referral velocity in a way mainstream paid spend cannot replicate.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us compete with Ripples Glasgow and Glasgow Bathroom Centre on tenement-retrofit work?",
      a: "Out-spending Ripples Glasgow and Glasgow Bathroom Centre on Google Ads is the wrong battle. The right battle is tenement-retrofit operational authority, hyperlocal long-tail and 90-second response speed. We build out 18–28 G-postcode × suite-type landing pages (tenement bathroom Hyndland, walk-in shower Partick, soil-stack relocation Hillhead, wet-room Dowanhill, bespoke bathroom Bearsden, Pollokshields family bathroom, accessibility wet-room Dennistoun), each with named-designer credentials, KBSA / BIID badges, named WaterSafe-approved plumber, Gas Safe register number, NICEIC Part P fitter, and Houzz / Instagram portfolio embeds with named G11, G12, G41 and G77 projects with documented soil-stack and joist-reinforcement work. We then run a tight branded plus long-tail Google Ads campaign with G-postcode-stratified bidding, and route every enquiry through AI receptionist with 90-second response across phone, Houzz Pro, Instagram DM and contact form. Glasgow independent bathroom studios running this approach have consistently outperformed regional-chain spend by 2.5–3.5x ROAS with average project value 25–40% higher.",
    },
    {
      q: "How do you handle tenement-retrofit constraints — soil-stack relocations, joist directions, Tenement Management Schemes — in our marketing?",
      a: "We build tenement-retrofit literacy into the entire customer journey. Quote enquiry forms include tenement-flat-floor (ground/first/second/third), shared soil-stack location and Tenement Management Scheme common-property qualifying questions; AI receptionist asks the property's tenement constraints as the second question after job type; the website includes a tenement-bathroom content hub (different content for West End sandstone vs Southside red sandstone vs East End blonde sandstone tenement variants) which doubles as long-tail SEO pulling thousands of monthly informational searches. Landing pages educate prospects on the Tenements (Scotland) Act 2004 neighbour-consultation framework, like-for-like Code 5 lead specification, and Glasgow Building Control / LABC notification handling for full bathroom rewires. This filters survey time onto viable jobs and earns the firm citations from local conservation forums, heritage trades directories and West End and Southside Facebook community groups — strong Glasgow SEO signals that Ripples and the chains structurally cannot replicate.",
    },
    {
      q: "How do you handle Disabled Facilities Grant work across Glasgow City Council, East Renfrewshire and East Dunbartonshire?",
      a: "DFG (and the Scottish equivalent Stage 3 funding routed via Health and Social Care Partnerships) is one of the most undervalued lead sources for Glasgow bathroom firms. Glasgow City Council HSCP, East Renfrewshire HSCP, East Dunbartonshire HSCP, Renfrewshire HSCP and South Lanarkshire HSCP together process hundreds of accessibility bathroom adaptations per year — each up to £30,000 council-funded — with most HSCP approved-contractor lists actively short of WaterSafe-registered firms who understand OT-specified level-access wet-rooms in tenement constraints. We build a dedicated DFG funnel: a 'DFG / Scottish Stage 3 approved bathroom contractor Greater Glasgow' landing page with separate Glasgow City / East Renfrewshire / East Dunbartonshire / Renfrewshire / South Lanarkshire sub-pages, AI receptionist routing for OT and HSCP referrals (separate intake fields, council PO number capture, named-applicant safeguarding language), GBP attribute optimisation for 'Wheelchair-accessible entrance' and 'Mobility-accessible', and a homeowner content hub explaining the Stage 3 application pathway. Most Glasgow independents who run this funnel capture 8–15 council-paid installs per year worth £80,000–£200,000 of stable additional revenue with zero deposit risk.",
    },
    {
      q: "How do you handle the Pollokshields South Asian community demand for prayer-washing wudu bathroom configurations?",
      a: "Pollokshields G41 and adjacent Southside neighbourhoods host a significant South Asian heritage community with bridal-cycle and family-led demand patterns clustering around Asian wedding seasons December–March and June–September. The configuration ask is specific: a half-height pour-over wudu fixture with dedicated drainage adjacent to or integrated with the master walk-in shower, often combined with a freestanding bath master-suite specification at £15,000–£30,000 timed to a daughter's or son's wedding 9–12 months out. Bookings are made via WhatsApp Business and family referral rather than Google Ads; deposits arrive by bank transfer; pricing is package-based; multilingual capability (Urdu, Punjabi on request) materially boosts conversion. We configure WhatsApp Business automation, multilingual landing pages with culturally-specific copy (not just translated text), wedding-season campaign cycles tuned to Pollokshields specifically, and named G41 case studies with permission-cleared before/after photography. For Wickes Darnley, Wren and B&Q DIY-route, this is a structurally inaccessible market — for an independent who configures the funnel correctly, it's some of the highest-margin most-stable bridal-bathroom revenue available in Scotland.",
    },
  ],
  approach:
    "For Glasgow bathroom fitters and designers, our 90-day playbook is: (1) stratify your service area into 4 G-postcode tiers (G77/G46/G61/G62 Newton Mearns/Giffnock/Bearsden/Milngavie bespoke villa £25–60k, G11/G12/G3 West End tenement premium £12–25k, G41/G42/G43 Southside tenement standard £8–15k, G31/G40 East End regeneration £6–12k, plus dedicated Pollokshields G41 South Asian wedding-bathroom funnel £15–30k) and rebuild Google Ads, landing pages and Houzz Pro listings accordingly; (2) deploy AI receptionist with bathroom-specific qualifying flow including tenement-flat-floor and Tenement Management Scheme common-property capture, plus 90-second auto-response across phone, Houzz Pro, Instagram DM, WhatsApp Business and contact form; (3) build a dedicated DFG / Scottish Stage 3 accessibility funnel targeting Glasgow City / East Renfrewshire / East Dunbartonshire / Renfrewshire / South Lanarkshire HSCPs for council-paid £30k installs; (4) launch a deposit-conversion automation sequence with explicit 'why we're not Bathstore Braehead / Glasgow Fort' staged-payment reassurance, KBSA / BIID / WaterSafe / Gas Safe / NICEIC credentials and 'why us not Wickes Darnley / Wren / B&Q DIY-route' breakdown calibrated for Glasgow's research-driven independent-led market preference; and (5) drive Google review velocity to 6–10 new reviews per month through automated post-completion SMS to dominate G-postcode-level local pack against Ripples Glasgow and Glasgow Bathroom Centre.",
};
