import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "bathroom fitter marketing Belfast",
    "bathroom designer marketing Belfast",
    "Belfast Bathroom Centre alternative SEO",
    "wet room installer Belfast Google Ads",
    "Bathroom Inspirations NI alternative marketing",
  ],
  secondaryKeywords: [
    "Stranmillis Malone Road bathroom designer marketing",
    "Holywood Cultra premium bathroom refit SEO",
    "Ballyhackamore bathroom fitter Google Ads",
    "Lisburn Road bathroom showroom marketing",
    "DFG accessibility bathroom Belfast",
    "cross-border ROI bathroom installer NI",
    "BT9 BT4 BT18 bathroom fitter SEO",
    "Windsor Framework bathroom supply lead time NI",
  ],
  heroSubhead:
    "Belfast is the only UK bathroom market where cross-border ROI demand from Drogheda, Dundalk and Newry consistently lifts premium project value 15–25% above local NI baseline, where Windsor Framework supply-chain lead times genuinely change the spec conversation, and where BT9 Stranmillis / Malone, BT4 Ballyhackamore and BT18 Holywood / Cultra households routinely sign £12,000–£28,000 wet-room and ensuite jobs. Belfast Bathroom Centre and Bathroom Inspirations NI anchor the local showroom tier, while Wickes Belfast and Victoria Plum / Soak.com pull mid-market homeowners into the DIY-route. Add HSCNI's separate regulatory landscape and DFG via NIHE rather than English councils, and most Belfast bathroom firms are missing 30–50% of the cross-border premium opportunity. Kerblabs gives Belfast bathroom fitters and designers the AI receptionist, cross-border ROI funnel, deposit-conversion automation and DFG specialism to win across BT1 to BT18.",
  marketContext: [
    "Belfast's bathroom market is structurally distinct from any GB-mainland equivalent because three forces converge that exist nowhere else in the UK. The cross-border ROI premium is the most under-played: Drogheda, Dundalk, Newry, Carrickmacross and even Dublin-commuter households actively source bathroom designers in Belfast because Hansgrohe, Crosswater, Burlington and Drummonds product specification through NI showrooms typically lands 15–25% cheaper than Dublin equivalents once VAT and currency arbitrage settle, and the Windsor Framework has actually simplified cross-border professional-services trade since 2023. ROI customers tend to specify higher (more bespoke joinery, more underfloor heating, larger walk-in shower formers) because the perceived saving is reinvested into spec — meaning Belfast independents who target the cross-border funnel land £20,000–£35,000 projects that NI-only marketing wouldn't surface. The HSCNI separate regulatory layer matters because DFG accessibility work in Belfast routes through NIHE (Northern Ireland Housing Executive) rather than English-style council Home Improvement Agencies, with up to £30,000 per applicant council-funded but a different OT-referral pathway that almost no national agency understands.",
    "Job values stratify sharply by postcode. BT9 Stranmillis, Malone Road and Lisburn Road carry the premium tier where £15,000–£28,000 wet-rooms with bespoke joinery vanities, integrated underfloor heating and Hansgrohe / Crosswater brassware close routinely, anchored by professional households from Citi Titanic Quarter, Allstate, Liberty IT, Rapid7 and Kainos whose Belfast tech-cluster wages are the highest in NI. BT18 Holywood and Cultra carry the absolute top tier — disposable incomes higher than anywhere else in NI, £20,000–£35,000 projects routinely closing on referral rather than search. BT4 Ballyhackamore sits in the £10,000–£18,000 mid-premium young-family band where the foodie-strip independent retail culture extends into bathroom spec — clients here research extensively on Houzz and Instagram before booking. BT12, BT13 and BT5 (Falls, Shankill, East Belfast) operate at the £6,000–£12,000 standard refit level where Wickes-supply and value-led DIY routes pull the bulk of demand, but where a named WaterSafe-and-Gas-Safe credential layer plus NIHE DFG approval still wins meaningful guaranteed-revenue work. Belfast Bathroom Centre dominates the local showroom-anchored mid-premium tier; Bathroom Inspirations NI competes for the BT9 / BT18 premium specification work.",
    "The non-obvious 2026 win for Belfast bathroom independents is cross-border ROI funnel design plus Windsor Framework supply-chain literacy plus NIHE DFG specialism. CPCs for 'bathroom fitter Belfast' run £2.50–£6 (notably below Manchester at £4–£10 and Dublin at £5–£12), 'wet room installer Belfast' £3–£7, 'bathroom designer Belfast' £3.50–£8 with Belfast Bathroom Centre and Bathroom Inspirations NI dominating the branded local pack. Cross-border 'bathroom designer Drogheda Belfast', 'Belfast bathroom installer Dundalk' carry almost no advertiser competition and convert at exceptional rates. The 2019 Bathstore collapse — which had a Boucher Crescent retail-park presence — left a measurable trust hangover in NI that's compounded by the Better Bathrooms collapse the same year. Belfast bathroom independents running cross-border ROI ad copy in EUR and GBP, Windsor Framework-aware lead-time language explaining 14–18 week supply chains for German rigid versus 4–8 weeks for trade-direct, named WaterSafe / Gas Safe / NICEIC subcontractor credentials, NIHE DFG funnel and Houzz / Instagram 9pm-to-11pm capture typically lift quote-to-deposit conversion from 22–28% to 42–48% inside 6 months and grow average project value 25–35%.",
  ],
  stats: [
    { value: "£15,000–£28,000", label: "typical BT9 Stranmillis / Malone / Lisburn Road premium bathroom project value" },
    { value: "£20,000–£35,000", label: "typical BT18 Holywood / Cultra absolute-premium bathroom project value" },
    { value: "£2.50–£6", label: "Google Ads CPC range for 'bathroom fitter Belfast' 2024–2025", source: "Kerblabs client accounts" },
    { value: "Up to £30,000", label: "DFG per applicant via NIHE (Northern Ireland Housing Executive)" },
    { value: "15–25%", label: "cross-border ROI premium project-value lift versus NI-only baseline" },
    { value: "BT9 / BT4 / BT18", label: "highest-disposable-income postcodes for Belfast bathroom premium spec" },
  ],
  painPoints: [
    {
      title: "Cross-border ROI premium opportunity completely unmarketed by 95%+ of Belfast bathroom firms",
      body: "Drogheda, Dundalk, Newry, Carrickmacross and Dublin-commuter households actively cross the border for bathroom design because spec parity through Belfast showrooms typically lands 15–25% cheaper than Dublin once VAT and currency settle — but almost no Belfast bathroom firm runs cross-border ad copy in EUR and GBP, Windsor Framework-aware messaging, ASAI-compliant landing pages for ROI-served impressions, or county-targeted Meta campaigns into Louth, Meath and the Pale commuter belt. We build a dedicated cross-border funnel with EUR pricing transparency, Windsor Framework supply-chain explanation, ASAI-vs-ASA compliance routing, and AI receptionist that captures Eircode alongside BT-postcode. Belfast bathroom independents running this typically add £8,000–£20,000 monthly cross-border project value at notably higher average ticket.",
    },
    {
      title: "Windsor Framework supply-chain lead times bleeding deposits during 14–18 week wait windows",
      body: "Bathroom suite supply into NI under Windsor Framework runs 14–18 weeks for German rigid (Villeroy & Boch, Duravit, Geberit) versus 4–8 weeks for trade-direct UK supply, and homeowners not briefed properly on the lead-time difference panic during the wait window. Combined with the 2019 Bathstore Boucher Crescent collapse trust hangover, 30–50% of premium quotes ghost during the deposit-to-install gap. We rebuild around honest Windsor Framework lead-time framing in the quote, weekly automated progress updates from CAD sign-off through factory order confirmation through cross-border-customs clearance, and Bathstore-collapse-aware staged-payment wording with named WaterSafe / Gas Safe / NICEIC subcontractor public liability schedules.",
    },
    {
      title: "NIHE DFG accessibility work via NI Direct completely under-marketed despite NIHE struggling to source contractors",
      body: "DFG in Belfast routes through NIHE rather than English-style council HIAs, provides up to £30,000 per applicant of council-funded accessibility work, and NIHE genuinely struggles to source approved bathroom contractors with WaterSafe-and-NICEIC subcontractor coverage. Most Belfast bathroom firms have nothing on their website about DFG, NI Direct application pathways, OT liaison through HSCNI, or named subcontractor credentials. We build a dedicated NIHE DFG funnel with separate landing pages, AI routing for OT-referred enquiries with HSCNI-aware language, GBP attribute optimisation for 'Wheelchair-accessible entrance', and a content hub explaining the NI Direct DFG application process so homeowner-led searches ('walk-in shower DFG Belfast', 'disabled bathroom installer NI') convert directly.",
    },
    {
      title: "Belfast Bathroom Centre and Bathroom Inspirations NI dominating the branded local pack while independents leave the long tail uncaptured",
      body: "'Bathroom fitter Belfast', 'bathroom showroom Belfast' and 'bathroom designer Belfast' branded queries are essentially locked up by the established showroom names. The winning battle for independents is the long-tail postcode-and-style queries — 'wet room Stranmillis', 'walk-in shower Holywood', 'bathroom designer Ballyhackamore', 'bespoke bathroom Cultra' — where CPCs sit at £2–£4 and the Belfast Bathroom Centre / Bathroom Inspirations NI brand-bid stack doesn't reach. We build out 20–30 hyperlocal landing pages with named WaterSafe / Gas Safe / NICEIC subcontractor credentials, KBSA / BIID badges where held, and Bathstore-collapse-aware staged-payment language, then run tight long-tail Google Ads with postcode-stratified bidding (BT9 / BT4 / BT18 premium versus BT12 / BT13 / BT5 standard refit).",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs handle the cross-border ROI customer flow into our Belfast bathroom showroom — and is it genuinely worth pursuing?",
      a: "Cross-border ROI is the single most under-played opportunity in Belfast bathroom marketing in 2026 and almost no independent firm currently captures it properly. Drogheda, Dundalk, Newry, Carrickmacross and Dublin-commuter households cross into NI for bathroom design because Hansgrohe / Crosswater / Burlington / Drummonds product specification through Belfast showrooms typically lands 15–25% cheaper than Dublin equivalents once VAT, currency and supply-chain economics settle. We build a dedicated cross-border funnel with EUR-pricing landing pages served to ROI IPs, GBP-pricing landing pages served to NI IPs, ASAI-compliant ad copy for ROI-served impressions versus ASA for UK-served, and Meta lead campaigns county-targeted into Louth, Meath, Cavan, Monaghan and parts of north Dublin commuter belt. AI receptionist captures Eircode alongside BT-postcode and routes ROI customers to a slightly compressed survey-to-deposit flow because the cross-border travel cost (Newry-to-Belfast 40 minutes, Drogheda-to-Belfast 90 minutes) means the customer is already higher-intent. Belfast bathroom firms running this consistently add £8,000–£25,000 monthly cross-border project value at average ticket 30–40% above the NI-only baseline, because cross-border customers reinvest the perceived saving into higher specification. Windsor Framework has actually simplified cross-border bathroom-services trade since 2023 — the friction that existed pre-2021 has largely cleared.",
    },
    {
      q: "How do you handle Windsor Framework supply-chain lead times in our quote process, given the 2019 Bathstore Boucher Crescent collapse trust hangover?",
      a: "Windsor Framework supply lead times into NI are genuinely longer than GB-mainland equivalents — 14–18 weeks for German rigid (Villeroy & Boch, Duravit, Geberit, Hansgrohe), 6–10 weeks for UK trade-direct, 4–8 weeks for Wickes-supply or B&Q-installed routes — and the 2019 Bathstore Boucher Crescent collapse plus Better Bathrooms the same year left a measurable trust hangover that gets reactivated whenever a customer hits a long wait window. We rebuild the quote document around honest Windsor Framework lead-time framing (specific factory location, customs-clearance window, port-of-entry through Belfast or Larne), weekly automated progress updates from Virtual Worlds CAD sign-off through factory order confirmation through cross-border customs clearance through plumber-pre-visit through tile-delivery through install kickoff, and Bathstore-collapse-aware staged-payment wording with explicit named WaterSafe / Gas Safe / NICEIC subcontractor public liability schedules. The deposit-to-install nurture sequence runs four parallel touchpoints: same-day post-design-appointment SMS plus 48-hour email with branded sample list, week-one-to-three KBSA / BIID accreditation reassurance with Houzz reviews from completed similar specs, decision-stage installation-slot-holding SMS with deposit-deadline framing, and post-deposit weekly factory-progress updates. Belfast bathroom firms running this typically lift quote-to-deposit conversion from 22–28% to 42–48% inside 6 months.",
    },
    {
      q: "How do you build the NIHE DFG funnel for Belfast accessibility work — and why does it differ from English council DFG?",
      a: "NIHE DFG is structurally different from English council DFG and almost no GB-based bathroom marketing agency understands the difference. In NI, DFG provides up to £30,000 per applicant of council-funded accessibility bathroom work — level-access wet-rooms, walk-in showers, grab-rail and seat installations, raised WCs, Changing Places Toilet specification — but routes through NIHE (Northern Ireland Housing Executive) and NI Direct rather than English Home Improvement Agencies, with OT specification through HSCNI rather than NHS England trusts. The application pathway, payment terms and named-applicant safeguarding language are NI-specific. We build a dedicated NIHE DFG funnel with three separate landing pages — NIHE DFG approved bathroom contractor Belfast, walk-in shower DFG NI, Changing Places Toilet specification under Building Regs (NI) 2012 — AI receptionist running a separate intake flow for OT-referred enquiries with HSCNI-aware language and council PO number capture, GBP attribute optimisation for 'Wheelchair-accessible entrance' and 'Mobility-accessible' because NIHE genuinely searches the local pack when filling contractor lists, and a content hub explaining the NI Direct DFG application process. Belfast bathroom independents running this typically capture 6–12 NIHE DFG installs per year worth £70,000–£180,000 of guaranteed council revenue with zero deposit risk.",
    },
    {
      q: "How do we differentiate from Belfast Bathroom Centre, Bathroom Inspirations NI, Wickes Belfast and Victoria Plum without competing on price?",
      a: "Trying to outbid Belfast Bathroom Centre and Bathroom Inspirations NI on branded local-pack terms is the wrong battle — they have 15–25 years of authority and dominate the Belfast showroom-anchored search surface. The right battle is hyperlocal long-tail and credential-led specification: 'wet room Stranmillis', 'bespoke bathroom Cultra', 'walk-in shower BT9', 'bathroom designer Ballyhackamore', 'cross-border bathroom Drogheda Belfast'. We build the 'why us not Belfast Bathroom Centre / Wickes / Victoria Plum / Bathstore-style retailer' positioning around five differentiators that volume retailers and showroom chains structurally cannot match: named designer continuity (the same designer briefs, draws Virtual Worlds CAD, supervises install — versus showroom-chain salesperson-to-installer handover); supplier flexibility across Roper Rhodes, Crosswater, Hansgrohe, Burlington, Drummonds and trade-direct ranges versus locked-supplier showroom inventory; named local installation crew with KBSA membership, WaterSafe-approved plumber, Gas Safe register number, NICEIC Part P explicitly surfaced; honest Windsor Framework lead-time framing with Bathstore-collapse-aware staged-payment wording; and project management — site-protection, dust-management, party-wall coordination on BT9 Edwardian villas — that DIY routes simply don't include. Belfast bathroom firms running this lift average project value 28–40% within 6 months by escaping the £6–10k Wickes-finance bracket and winning the £15–28k BT9 / BT4 / BT18 specification work.",
    },
  ],
  approach:
    "For Belfast bathroom fitters and designers, our 90-day playbook is: (1) deploy AI receptionist with NI-aware qualifying flow including Eircode capture for cross-border ROI customers, NIHE DFG routing, and Windsor Framework lead-time setting expectation at first contact; (2) build out 20–30 hyperlocal landing pages — Stranmillis / Malone, Holywood / Cultra, Ballyhackamore, Lisburn Road, cross-border ROI Drogheda-Dundalk-Newry — with named WaterSafe / Gas Safe / NICEIC subcontractor credentials, KBSA / BIID badges and Bathstore-collapse-aware staged-payment wording; (3) launch dedicated NIHE DFG funnel with NI Direct application pathway content, OT-referral routing through HSCNI awareness, and Changing Places Toilet capability for commercial specification; (4) run cross-border Meta and Google Ads campaigns into Louth, Meath, Cavan, Monaghan and north Dublin with EUR pricing transparency and ASAI-compliant ad copy; and (5) drive Google review velocity to 6–10 new reviews per month with cross-border-aware and rotation-aware post-completion SMS so Belfast Bathroom Centre and Bathroom Inspirations NI lose the long-tail local pack to credential-led independents.",
};
