import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "bathroom fitter marketing Manchester",
    "bathroom designer marketing Manchester",
    "wet room installer Manchester",
    "luxury bathroom Manchester Google Ads",
    "Didsbury Altrincham bathroom showroom SEO",
  ],
  secondaryKeywords: [
    "Spinningfields penthouse bathroom installer",
    "Ripples Manchester alternative bathroom designer",
    "Bathroom Eleven Manchester alternative",
    "Didsbury walk-in shower fitter",
    "Altrincham Hale freestanding bath installer",
    "Salford Quays bathroom refit",
    "DFG accessibility bathroom Greater Manchester",
    "Chorlton Victorian terrace bathroom refit",
  ],
  heroSubhead:
    "Manchester is one of the fastest-growing UK bathroom markets — Spinningfields and NOMA penthouse refits clearing £15–30k, Didsbury and Chorlton M20/M21 Victorian terrace conversions averaging £10–20k, and Altrincham/Hale Cheshire-edge bespoke crossing £25k routinely. Ripples Manchester and Bathroom Eleven anchor the £15–35k premium tier; Wickes Trafford Park and B&Q Stockport push installed-bathroom finance against the £4–10k middle. Greater Manchester councils administer one of the largest DFG pipelines outside London — Bolton, Wigan, Rochdale and Tameside Home Improvement Agencies process hundreds of accessibility bathroom adaptations a year up to £30,000 per applicant. Kerblabs gives independent Manchester bathroom studios the AI receptionist, M-postcode-stratified Houzz / Instagram funnel, deposit-conversion automation and DFG accessibility funnel to win against the chains.",
  marketContext: [
    "Greater Manchester's bathroom market sits at a structural inflection point. The post-2018 build-to-rent and penthouse boom across Spinningfields, NOMA, Ancoats, Castlefield and Salford Quays generated several thousand high-end residential units whose original developer-spec bathrooms (typically £3–5k cost-fit, retail-equivalent £8–12k) are now 5–8 years old and entering refit cycle — driving a £15,000–£30,000 walk-in shower and freestanding-bath master-suite refit demand band that simply didn't exist in Manchester pre-2018. Ripples Manchester (the regional anchor of the ~25-showroom Ripples national group) and Bathroom Eleven Manchester compete for this band alongside specialists like the Manchester Tile Company, Bathroom Showrooms Manchester and the Cheshire-edge premium independents around Hale, Bowdon, Knutsford and Wilmslow. The MediaCityUK demographic — BBC, ITV, dock10 production staff, fintech and gaming engineers — is unusually willing to specify £20k+ master-suite bathrooms because the surrounding apartment values support the spend.",
    "Move into the M14–M21 belt running through Rusholme, Fallowfield, Withington, Didsbury, West Didsbury and Chorlton, and the market shifts to £8,000–£18,000 Victorian terrace bathroom refits — typically converting an old upstairs bathroom plus a separate WC into a single larger family bathroom, often with rear-extension knock-throughs, en-suite additions or loft-conversion bathrooms. This is the most contested band in Manchester because the Wickes Trafford Park and Stockport showrooms, Wren's Manchester satellites, B&Q, Magnet and a deep tail of independent fitters all compete for the same young-professional homeowner doing a £350–£500k Victorian terrace refurbishment. Houzz Pro lead fees in M20 and M21 routinely run £25–£45 per qualified enquiry. The Cheshire-edge belt — Altrincham, Hale, Bowdon, Wilmslow, Knutsford, Hale Barns — operates as a different market entirely: bespoke specifications, designer brassware (Lefroy Brooks, Crosswater, Drummonds), £25k+ project values, and a referral-led economy where Houzz reviews and Google review velocity matter more than paid spend. Outer Greater Manchester boroughs (Bolton, Wigan, Rochdale, Oldham, Tameside, Bury) operate at £4,000–£10,000 standard refit pricing typically using Howdens, Travis Perkins or City Plumbing trade-direct supply.",
    "The non-obvious 2026 win for Manchester independents is a triple-funnel structure combining tenement-equivalent retrofit specialism (the M19/M20/M21 Victorian terrace stock has many of the same soil-stack and joist constraints as Glasgow tenements), Disabled Facilities Grant capture across all ten Greater Manchester boroughs, and architect-referral nurture for the Spinningfields penthouse refit cycle. Greater Manchester councils administer one of the largest DFG budgets outside London — Bolton, Wigan, Rochdale and Tameside Home Improvement Agencies process hundreds of accessibility bathroom applications per year up to £30,000 per applicant, and most boroughs' approved-contractor lists struggle to find enough WaterSafe-registered firms who understand OT-specified level-access wet-rooms. The 2019 Bathstore collapse closed all Manchester area Bathstore showrooms (Trafford Park, Ashton, Stockport) and left thousands of Greater Manchester homeowners with paid deposits and unfinished bathrooms — that trust hangover is now a structural advantage for any independent who can prove staged-payment safety, named subcontractor credentials and a five-year trading history. Add a structured Houzz Pro / Instagram DM capture funnel that responds within 90 seconds to 9pm enquiries, and Manchester independent bathroom studios running this stack typically convert 38–48% of qualified enquiries to paid design appointments versus 18–25% on a manual-response baseline.",
  ],
  stats: [
    { value: "£15,000–£30,000", label: "typical Spinningfields / NOMA / MediaCityUK / Salford Quays penthouse master-suite refit value" },
    { value: "£8,000–£18,000", label: "typical M20 / M21 Didsbury / Chorlton Victorian terrace family-bathroom refit value" },
    { value: "£25,000+", label: "typical Altrincham / Hale / Bowdon / Wilmslow Cheshire-edge bespoke project value" },
    { value: "£25–£45", label: "typical Houzz Pro qualified-lead fee per Manchester enquiry", source: "Kerblabs client accounts" },
    { value: "Up to £30,000", label: "DFG accessibility grant per applicant across all 10 Greater Manchester boroughs" },
    { value: "10", label: "Greater Manchester boroughs each with distinct DFG and bathroom search behaviour" },
  ],
  painPoints: [
    {
      title: "Ripples Manchester, Bathroom Eleven and the Cheshire-edge premium independents outspending you",
      body: "Ripples Manchester and Bathroom Eleven run unified bidding on 'bespoke bathroom designer Hale', 'wet room installer Didsbury', 'walk-in shower Altrincham' with regional marketing budgets and depot-funded showroom presence. Independent fitters and designers in Chorlton, Withington, Stockport, Marple and the Trafford corridor cannot match cost-per-click but win the long tail (specific suite type × specific postcode), response speed at 9pm, and architect-referral nurture, which the chains are structurally bad at because their lead handling routes through national appointment-booking systems and they don't carry the WaterSafe-approved plumber on direct payroll.",
    },
    {
      title: "M-postcode CPC variance you're not exploiting",
      body: "'Bespoke bathroom Hale' (WA15) and 'bathroom fitter Bolton' (BL1) look like the same query but behave nothing alike — CPC, intent, project value and close rate vary 4–6x across Greater Manchester postcodes. One Manchester-wide Google Ads campaign averages everything into mediocrity. M-postcode-stratified bidding with WA14/WA15/SK9 (Cheshire-edge bespoke), M20/M21 (Didsbury/Chorlton mid-premium), M1/M3/M50 (city-centre penthouse), and BL/OL/WN/SK outer-borough (standard refit) landing pages typically lifts ROAS by 40–60% inside 90 days.",
    },
    {
      title: "9pm Houzz, Instagram and contact-form enquiries dying overnight",
      body: "Greater Manchester homeowners researching £10k–£30k bathrooms DM Instagram, save Pins to Houzz and submit website enquiries between 8pm and 11pm — particularly after MediaCityUK and Spinningfields evening commutes. Single-designer studios and 2–10-staff fitting firms cannot manually triage 15–40 evening enquiries a week, so 60–80% are dead by morning to a faster Ripples or Bathroom Eleven reply. AI receptionist plus Houzz Pro and Instagram DM auto-routing closes that gap inside 90 seconds and routinely adds £25,000–£70,000 in monthly recovered design-appointment value.",
    },
    {
      title: "DFG accessibility specialism completely under-marketed across Greater Manchester's 10 boroughs",
      body: "Bolton, Wigan, Rochdale, Tameside, Oldham, Bury, Salford, Trafford and Stockport councils together administer one of the largest DFG pipelines outside London — hundreds of accessibility bathroom applications per year, each up to £30,000 council-funded, with most borough Home Improvement Agency lists actively short of WaterSafe-approved contractors. Yet most Manchester independents have no DFG-specific landing page, no OT/HIA referral intake flow, and no GBP attribute for 'Wheelchair-accessible entrance'. We rebuild around named DFG specialism, with separate intake routing, council PO number capture, and a content hub explaining the DFG application process to homeowner-led searches.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us compete with Ripples Manchester, Bathroom Eleven and the Cheshire-edge premium independents?",
      a: "Out-spending the regional showroom anchors on Google Ads is the wrong battle. The right battle is hyperlocal long-tail and architect-referral defensibility. We build out 20–35 postcode × suite-type landing pages (wet room installer Didsbury, walk-in shower Chorlton, freestanding bath master-suite Hale, bespoke bathroom Altrincham, penthouse refit Spinningfields, accessibility bathroom Bolton), each with named-designer credentials, KBSA / BIID badges, named WaterSafe-approved plumber, NICEIC Part P fitter, and Houzz / Instagram portfolio embeds with named M20, M21, WA14, WA15 and SK9 projects. We then run a tight branded plus long-tail Google Ads campaign with M-postcode-stratified bidding, and route every enquiry through AI receptionist with 90-second response across phone, Houzz Pro, Instagram DM and contact form. Manchester independent bathroom studios running this approach have consistently outperformed regional-chain spend by 2–3.5x ROAS with average project value 25–35% higher.",
    },
    {
      q: "How do you handle Greater Manchester's 10-borough fragmentation and the difference between Cheshire-edge bespoke and outer-borough standard refits?",
      a: "Greater Manchester isn't one bathroom market — it's at least three. The Cheshire-edge belt (WA14 Altrincham, WA15 Hale, SK9 Wilmslow, SK10 Knutsford) is a £25k+ bespoke market where households expect named-designer continuity, Lefroy Brooks / Crosswater / Drummonds brassware and a 12–16 week timeline. Inner south Manchester (M20 Didsbury, M21 Chorlton, M19 Levenshulme, M14 Fallowfield, M16 Whalley Range) is an £8–18k Victorian-terrace refit market where rear-extension and en-suite-addition work dominates. Outer boroughs (BL Bolton, WN Wigan, OL Oldham, SK Stockport outer, M Salford outer, BD Bury) are £4–10k standard-refit markets using Howdens / City Plumbing / Travis Perkins trade-direct supply. We build separate funnels for each: tone, photography, brassware specs, lead time framing, deposit-protection language and follow-up sequences are calibrated differently for a Hale architect-led project vs a Bolton DFG accessibility install vs a Spinningfields penthouse master-suite.",
    },
    {
      q: "How do you handle Disabled Facilities Grant work with Bolton, Wigan, Rochdale, Tameside and the other Greater Manchester councils?",
      a: "DFG is one of the most undervalued lead sources for Manchester bathroom firms. Greater Manchester councils together process hundreds of DFG accessibility bathroom applications per year — each up to £30,000 council-funded — and most borough Home Improvement Agency approved-contractor lists are actively short of WaterSafe-registered firms who understand OT-specified level-access wet-rooms, grab-rail and seat installations, raised WCs and Changing Places Toilet specification under Building Regs 2021. We build a dedicated DFG funnel: a 'DFG approved bathroom contractor Greater Manchester' landing page with separate Bolton / Wigan / Rochdale / Tameside / Oldham / Bury / Salford / Trafford / Stockport sub-pages, AI receptionist routing for OT and HIA referrals (separate intake fields, council PO number capture, named-applicant safeguarding language), GBP attribute optimisation for 'Wheelchair-accessible entrance' and 'Mobility-accessible', and a homeowner content hub explaining the DFG application pathway. Most Manchester independents who run this funnel capture 8–15 council-paid installs per year worth £80,000–£200,000 of stable additional revenue with zero deposit risk.",
    },
    {
      q: "How do you handle the M19/M20/M21 Victorian terrace refit specialism that drives most South Manchester bathroom enquiries?",
      a: "South Manchester's pre-1939 terraced housing has structural quirks that mainland-bathroom-fitter generic marketing completely ignores: limited soil-stack relocation options, joists running in awkward directions for shower-tray install, plaster-and-lath walls behind tile substrates, and rear-extension knock-throughs that need party-wall coordination. We rebuild your site around named Victorian-terrace case studies on actual Didsbury, Chorlton, Levenshulme and Withington streets — with before/after photography, technical detail on soil-stack runs and joist reinforcement, and explicit Building Control / LABC notification handling for full bathroom rewires. This positions the firm correctly for the £8–18k Victorian-terrace family-bathroom refit market, where Wickes' generic showroom funnel and Wren's flat-pack approach simply can't compete on technical credibility. Architects and structural engineers specifying terrace work in M20/M21 then start referring you directly because the Houzz Pro portfolio shows you understand the fabric.",
    },
  ],
  approach:
    "For Manchester bathroom fitters and designers, our 90-day playbook is: (1) stratify your service area into 3–4 M-postcode tiers (WA14/WA15/SK9/SK10 Cheshire-edge bespoke £25k+, M20/M21/M19/M14/M16 Victorian terrace £8–18k, M1/M3/M50 city-centre penthouse £15–30k, BL/WN/OL/SK outer borough standard £4–10k) and rebuild Google Ads, landing pages and Houzz Pro listings accordingly; (2) deploy AI receptionist with bathroom-specific qualifying flow plus 90-second auto-response across phone, Houzz Pro, Instagram DM and contact form to capture the 60%+ of enquiries arriving outside 9–5; (3) build a dedicated DFG accessibility funnel targeting all 10 Greater Manchester councils for council-paid £30k installs; (4) launch a deposit-conversion automation sequence with explicit 'why we're not Bathstore' staged-payment reassurance, KBSA / BIID / WaterSafe / Gas Safe / NICEIC credentials and 'why us not Ripples / Bathroom Eleven / Wickes' breakdown; and (5) drive Google review velocity to 6–10 new reviews per month through automated post-completion SMS to dominate M-postcode-level local pack against the regional anchors.",
};
