import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "bathroom fitter marketing Swansea",
    "bathroom designer marketing Swansea",
    "Swansea Bathroom Studio alternative SEO",
    "Welsh-language bathroom fitter Swansea Abertawe",
    "wet room installer Swansea Google Ads",
  ],
  secondaryKeywords: [
    "Mumbles SA3 premium bathroom designer",
    "Sketty SA2 bespoke bathroom Swansea",
    "Welsh-language bathroom fitter Gorseinon Pontarddulais",
    "Killay West Cross bathroom installer",
    "Uplands Brynmill student HMO bathroom Swansea",
    "SA1 SA2 SA3 SA4 bathroom fitter SEO",
    "DFG accessibility bathroom Swansea Council",
    "ffitiwr ystafell ymolchi Abertawe",
  ],
  heroSubhead:
    "Swansea is the only UK bathroom market where Welsh-language client communications are genuinely essential west of the city — Gorseinon, Pontarddulais, Loughor, Penclawdd and the Gower fringe carry one of the highest concentrations of Welsh first-language households in Wales, and bilingual Welsh / English signal placement materially shifts conversion in those catchments. Mumbles (SA3), Sketty (SA2) and the Gower-edge close £10,000–£20,000 premium master-bathroom refits, while Swansea Bathroom Studio anchors the local independent tier. Wickes Swansea Llansamlet, Wren Swansea and B&Q Swansea Enterprise Park pull the £4–10k DIY-route customer. Add Swansea Council DFG funnel up to £30k per applicant, SA-postcode CPCs running 35–55% below Cardiff equivalents, and the £200m Bay Campus university-staff catchment, and Swansea bathroom independents have a defensible bilingual-and-Mumbles-premium moat the chains structurally cannot fake.",
  marketContext: [
    "Swansea's bathroom market is structurally distinct from Cardiff or Bristol because Welsh-language client communications matter genuinely rather than tokenistically across the western catchment. Roughly 11–13% of Swansea county residents speak Welsh per Census 2021, but the concentration is dramatically asymmetric: Gorseinon, Pontarddulais, Loughor, Penclawdd and the Gower fringe carry Welsh first-language household density approaching 30–40% in some wards, while Mumbles, Sketty and the SA1 waterfront sit at single-digit Welsh-speaker percentages. For bathroom firms serving the western catchment (SA4 Gorseinon / Pontarddulais and the Gower-fringe Welsh-medium school catchments), genuine bilingual capability — Welsh-language landing pages with hreflang correctly applied for high-intent terms ('ffitiwr ystafell ymolchi Abertawe', 'cawod cerdded i mewn Pontarddulais', 'ystafell ymolchi DFG Gorseinon'), Welsh-language Google Business Profile attributes, named bilingual team members on the about page, and bilingual quote documents — converts at materially higher rates than English-only marketing. Bolting on token Welsh translation across an English-first generic site backfires (looks performative, generates auto-translated grammatical errors) but credible bilingual placement in genuinely Welsh-speaking catchments is one of the strongest commercial differentiators available to any Swansea SME. Swansea Bathroom Studio anchors the local independent mid-tier alongside a tail of SA-postcode specialists. Wickes Swansea Llansamlet, Wren Swansea and B&Q Swansea Enterprise Park compete for the £4–10k middle band, with Howdens Swansea trade-direct supply dominating the speed-led depot-collected market.",
    "Move into Mumbles / Oystermouth (SA3), Sketty (SA2), Killay, West Cross and Langland and the market shifts to £10,000–£20,000 premium master-bathroom refits driven by the Swansea University staff catchment from Singleton Park and the £200m+ Bay Campus, NHS consultant households from Morriston Hospital, and the post-2020 Cardiff-commuter and London / Home Counties remote-worker inflow into the SA2 / SA3 belt. Mumbles in particular carries the highest premium-bathroom spend density in South West Wales — average property values comfortably above £500,000, year-round local affluence, and a heavy summer tourism overlay that drives Mumbles-seafront salon, restaurant and accommodation operators to commission concierge-spec staff-bathroom and front-of-house refits. Houzz Pro lead fees in SA2 and SA3 typically run £15–£28 per qualified enquiry — significantly below Cardiff CF14 / CF23 and Bristol BS6 / BS8 equivalents. The Uplands and Brynmill student-belt around Swansea University generates a parallel landlord-led HMO-bathroom refit pipeline on 5–7 year refresh cycles at £4,000–£8,000 project values, with September lettings velocity driving compressed void-window scheduling. Outer Swansea (SA5 Cockett, SA6 Morriston, SA7 Bonymaen, SA8 Pontardawe) operates at £5,000–£10,000 standard refit pricing.",
    "The non-obvious 2026 win for Swansea bathroom independents is a triple-funnel structure: bilingual Welsh / English signal placement for the western catchment, Mumbles / Sketty (SA2 / SA3) premium-credential authority, and Swansea-and-Swansea-Bay DFG capture across Neath Port Talbot, Carmarthenshire and Pembrokeshire. Swansea Council Home Improvement Agency processes 90–160 DFG accessibility bathroom applications per year — each up to £30,000 council-funded — and Neath Port Talbot, Carmarthenshire and Pembrokeshire councils together add several hundred more across the Swansea Bay City Region pipeline, with Wales identified as having one of the most acute regional shortages of WaterSafe-approved accessibility bathroom contractors (Healthwatch Wales 2024). The 2019 Bathstore collapse closed the Swansea Enterprise Park retail-park branch alongside Better Bathrooms the same year, leaving hundreds of SA-postcode homeowners with paid deposits and unfinished bathrooms — that trust hangover is now a structural advantage for any independent who can prove staged-payment safety, named WaterSafe / Gas Safe / NICEIC subcontractor credentials and a five-year-plus trading history. CPCs across SA-postcodes run 35–55% below Cardiff CF-postcode equivalents — 'bathroom fitter Swansea' clears £1.80–£3.50 per click in our 2024–2025 client accounts versus £4–7 for Cardiff — and most SA-postcode SERPs are still dominated by directories and weakly optimised local sites. Swansea bathroom independents threading credible bilingual Welsh / English placement, SA2 / SA3 premium-credential authority, Swansea Bay City Region DFG funnel, and explicit Wickes Llansamlet / Wren Swansea / B&Q DIY-route differentiation typically convert 36–46% of qualified enquiries to paid design appointments versus 17–22% on a manual-response baseline.",
  ],
  stats: [
    { value: "£10,000–£20,000", label: "typical Mumbles (SA3) / Sketty (SA2) / Killay / West Cross premium master-bathroom refit value" },
    { value: "£4,000–£8,000", label: "typical Uplands / Brynmill / Mount Pleasant student-rental HMO refit project value" },
    { value: "£1.80–£3.50", label: "Google Ads CPC range for 'bathroom fitter Swansea' — 35–55% below Cardiff", source: "Kerblabs client accounts" },
    { value: "11–13%", label: "Swansea Welsh speakers — concentration up to 30–40% in Gorseinon / Pontarddulais wards", source: "ONS Census 2021 (Welsh language)" },
    { value: "Up to £30,000", label: "DFG accessibility grant per applicant via Swansea Council Home Improvement Agency" },
    { value: "~20,000", label: "Swansea University students supporting Uplands / Brynmill HMO-refit volume pipeline", source: "Swansea University" },
  ],
  painPoints: [
    {
      title: "Welsh-language signal placement done badly — generic site translation backfires while named placement in genuine western-catchment Welsh-speaking wards converts dramatically",
      body: "Swansea's Welsh-language asymmetry is dramatic — Mumbles and Sketty sit at single-digit Welsh-speaker percentages while Gorseinon, Pontarddulais, Loughor, Penclawdd and Gower-fringe Welsh-medium school catchments carry 30–40% Welsh first-language household density. Token Welsh translation across an entire English-first site backfires (looks performative, generates auto-translated grammatical errors). What actually converts: a small number of dedicated Welsh-language landing pages with hreflang correctly applied for SA4 / SA8 high-intent terms ('ffitiwr ystafell ymolchi Abertawe', 'cawod cerdded i mewn Pontarddulais', 'ystafell ymolchi DFG Gorseinon'), Welsh-language GBP attributes if the team genuinely supports Welsh-language enquiries, named bilingual team members surfaced on the about page, and bilingual quote documents available on request. Most Swansea bathroom firms either ignore Welsh entirely or auto-translate everything.",
    },
    {
      title: "Mumbles / Sketty (SA2 / SA3) premium-credential buyer competing on credentials, not price — under-credentialed listings lose share",
      body: "The Mumbles, Oystermouth, Sketty, Killay, West Cross and Langland buyer behaves like a Bristol BS6 Cotham or Cardiff CF14 Cyncoed customer — research-heavy, Houzz-led, often a Swansea University staff member from Singleton Park or the £200m+ Bay Campus, NHS consultant from Morriston Hospital, or post-2020 Cardiff-commuter / London-relocator, and rewards KBSA / BIID badges, named WaterSafe-approved plumber, Gas Safe register number and NICEIC Part P fitter on every quote. Mumbles in particular carries the highest premium-bathroom spend density in South West Wales with average property values comfortably above £500,000. Most Swansea fitters whose work covers SA2 / SA3 bury credentials on a generic about page rather than surfacing them on every Mumbles, Sketty and Killay landing page.",
    },
    {
      title: "Uplands / Brynmill student-rental HMO refit volume specialism uncaptured despite ~20,000 Swansea University students supporting genuine landlord-portfolio repeat-volume relationships",
      body: "Swansea University's ~20,000 students concentrated across Uplands, Brynmill, Mount Pleasant and parts of St Thomas / Bonymaen support a HMO landlord refit cycle that almost no Swansea bathroom firm currently markets to properly. HMO landlords run aggressive 5–7 year bathroom-refresh cycles to maintain September lettings velocity, place 3–10 refits per year per portfolio, and reward firms that can deliver compressed 3–5 week design-to-install windows in void periods. Project values cluster £4,000–£8,000 with Roper Rhodes Aspen / Hudson Reed-equivalent budget ranges, Mira Sport showers, Howdens trade-direct supply, and easy-clean wall panels. Yet most Swansea firms either treat HMO work as low-margin afterthought or have no HMO-specific intake / quoting / scheduling infrastructure.",
    },
    {
      title: "Swansea Bay City Region DFG specialism completely under-marketed despite Wales having most acute regional WaterSafe-contractor shortage",
      body: "Swansea Council HIA processes 90–160 DFG accessibility bathroom applications per year — each up to £30,000 council-funded — and Neath Port Talbot, Carmarthenshire and Pembrokeshire councils together add several hundred more across the Swansea Bay City Region pipeline, with Wales identified as having one of the most acute regional shortages of WaterSafe-approved accessibility bathroom contractors. Most council approved-contractor lists are short of WaterSafe-registered firms who understand OT-specified level-access wet-rooms in Edwardian-terrace and Valleys-cottage constraints. Yet most Swansea independents have no DFG-specific landing page, no separate authority sub-pages, no OT/HIA referral intake flow, no GBP attribute for 'Wheelchair-accessible entrance', and no Welsh-language DFG content for the SA4 / SA8 catchment.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs handle bilingual Welsh / English content for our Swansea bathroom marketing — and where does it actually convert versus where is it tokenistic?",
      a: "Welsh-language signal placement matters genuinely in Swansea but the asymmetry is dramatic and most bathroom firms get the calibration badly wrong. Census 2021 shows 11–13% of Swansea county residents speak Welsh, but Mumbles and Sketty sit at single-digit percentages while Gorseinon, Pontarddulais, Loughor, Penclawdd and Gower-fringe Welsh-medium school catchments carry 30–40% Welsh first-language household density — making bilingual capability essential west of the city and largely irrelevant in SA1 / SA2 / SA3. Where it actually converts: a small number of dedicated Welsh-language landing pages with hreflang correctly applied for SA4 / SA8 high-intent terms ('ffitiwr ystafell ymolchi Abertawe', 'cawod cerdded i mewn Pontarddulais', 'ystafell ymolchi DFG Gorseinon', 'dylunydd ystafell ymolchi Loughor'), Welsh-language GBP attributes if the team genuinely supports Welsh-language enquiries, named bilingual team members surfaced on the about page, and bilingual quote documents available on request. Where it backfires: auto-translated whole-site Welsh content, token Welsh phrases in a generic English-first site, performative Welsh dragon imagery without underlying capability. We audit your team's actual Welsh-language capability first, then build the minimum-viable Welsh-language footprint that converts SA4 / SA8 search volume without overcommitting to capability you don't have. Swansea bathroom firms with credible bilingual placement typically capture 8–15% additional western-catchment market share that English-only Cardiff competitors miss entirely — and Welsh-language Bay-Campus university-staff inbound is an additional bonus.",
    },
    {
      q: "How do you handle the Mumbles / Sketty (SA2 / SA3) premium-belt funnel differently from the SA4 / SA8 western-Welsh-speaking catchment and the Uplands student-HMO catchment?",
      a: "Three genuinely different funnels with completely different ad copy, content, lead-routing and conversion mechanics. For SA2 / SA3 Mumbles / Sketty / Killay / West Cross / Langland premium: research-heavy Houzz-led buyer, Swansea University Singleton Park / Bay Campus staff and Morriston Hospital consultant household base plus post-2020 Cardiff-commuter inflow, £10–20k average project value, named-designer continuity / KBSA / BIID / WaterSafe / Gas Safe / NICEIC credential surfacing on every Mumbles, Sketty and Killay landing page, Houzz Pro Pro-tier optimisation with SA3-postcode-tagged completed projects. For SA4 / SA8 Gorseinon / Pontarddulais / Loughor western-Welsh-speaking catchment: bilingual Welsh / English landing pages with hreflang, Welsh-language GBP attributes, named bilingual team member, traditional small-town economy with strong local-business loyalty, £6–14k average project value, content that respects Welsh-medium-school household context. For Uplands / Brynmill / Mount Pleasant student-HMO landlord catchment: portfolio-landlord intake routing, void-window 3–5 week scheduling protocols, standardised £4–8k quoting templates, Howdens trade-direct supply emphasis, named completed-HMO portfolio with anonymised landlord attribution. The three funnels run in parallel with completely separated Google Ads campaigns, separated Houzz Pro listings, and separated AI-receptionist intake routing.",
    },
    {
      q: "How do you handle the Swansea Bay City Region DFG funnel — Swansea, Neath Port Talbot, Carmarthenshire and Pembrokeshire?",
      a: "The Swansea Bay City Region DFG pipeline is one of the most undervalued lead sources for Swansea bathroom firms because the contractor shortage is genuinely acute and most independents have no DFG infrastructure. Swansea Council HIA processes 90–160 DFG accessibility bathroom applications per year (each up to £30k council-funded), and Neath Port Talbot, Carmarthenshire and Pembrokeshire councils together add several hundred more — with Wales identified as having one of the most acute regional shortages of WaterSafe-approved accessibility bathroom contractors. We build a dedicated DFG funnel: a 'DFG approved bathroom contractor Swansea and Swansea Bay' landing page with separate Swansea Council / Neath Port Talbot / Carmarthenshire / Pembrokeshire sub-pages, AI receptionist routing for OT and HIA referrals (separate intake fields, council PO number capture, named-applicant safeguarding language), GBP attribute optimisation for 'Wheelchair-accessible entrance' and 'Mobility-accessible' because council case-officers genuinely search the local pack when filling contractor lists, Welsh-language DFG content for the Carmarthenshire and SA4 / SA8 catchments, and a homeowner content hub explaining the DFG application pathway. Swansea bathroom independents running this multi-authority funnel typically capture 8–14 council-paid installs per year worth £80,000–£200,000 of stable additional revenue with zero deposit risk.",
    },
    {
      q: "How do we differentiate from Wickes Swansea Llansamlet, Wren Swansea and B&Q Swansea Enterprise Park given the 2019 Bathstore Enterprise Park collapse trust hangover?",
      a: "The 2019 Bathstore Swansea Enterprise Park retail-park collapse plus Better Bathrooms the same year left a measurable trust hangover that gets reactivated whenever a Swansea customer is asked for a deposit on a £6–20k bathroom — and Wickes Swansea Llansamlet, Wren Swansea and B&Q Swansea Enterprise Park all run aggressive installed-bathroom finance against the £4–10k middle band. We rebuild your website around five differentiators that retailer-installed and DIY-route routes structurally cannot match: (1) named designer continuity from brief through Virtual Worlds CAD render to install supervision and snagging — versus Wickes Llansamlet's salesperson-to-installer handover; (2) supplier flexibility across Roper Rhodes, Crosswater, Hansgrohe, Mira, Aqualisa, Burlington and trade-direct ranges rather than retailer-locked white-label suites; (3) named local installation crew with KBSA, BIID, FMB or Trustmark credentials, plus explicit WaterSafe approved plumber number, Gas Safe register number and NICEIC Part P registration on every quote; (4) honest 6–10 week lead time framing with deposit-protection wording that explicitly references the 2019 Bathstore Enterprise Park and Better Bathrooms collapses and how your firm's payment-staging differs (deposit held in client account, staged release against named install milestones); and (5) project management — site protection, dust management on Mumbles Edwardian and Sketty 1930s-semi stock, parking-permit handling around SA1 / SA2 RPZs, LABC notification — that B&Q DIY-route customers learn the hard way they actually need.",
    },
  ],
  approach:
    "For Swansea bathroom fitters and designers, our 90-day playbook is: (1) stratify your service area into 4 SA-postcode tiers (SA2 / SA3 Mumbles / Sketty / Killay / West Cross / Langland premium £10–20k separate Houzz-led funnel, SA4 / SA8 Gorseinon / Pontarddulais / Loughor western-Welsh-speaking catchment £6–14k separate bilingual funnel, SA1 / SA2 Uplands / Brynmill student-HMO landlord-led £4–8k separate volume funnel, SA5 / SA6 / SA7 Cockett / Morriston / Bonymaen standard £5–10k); (2) build credible bilingual Welsh / English content footprint with hreflang correctly applied, Welsh-language GBP attributes, named bilingual team member, and bilingual quote documents — only where team capability genuinely supports it; (3) deploy AI receptionist with bathroom-specific qualifying flow plus 90-second auto-response across phone, Houzz Pro, Instagram DM and contact form, with selective Welsh-language greeting routing where catchment supports it; (4) build a dedicated Swansea Bay City Region DFG accessibility funnel for council-paid £30k installs across Swansea, Neath Port Talbot, Carmarthenshire and Pembrokeshire with bilingual content where appropriate; (5) launch a deposit-conversion automation sequence with explicit 'why we're not Bathstore Enterprise Park / Better Bathrooms' staged-payment reassurance, KBSA / BIID / WaterSafe / Gas Safe / NICEIC credentials and 'why us not Wickes Llansamlet / Wren Swansea / B&Q Enterprise Park DIY-route' breakdown; and drive Google review velocity to 6–10 new reviews per month through automated post-completion SMS in English plus selectively in Welsh to dominate SA-postcode-level local pack against Swansea Bathroom Studio.",
};
