import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "mobile car detailer marketing Manchester",
    "ceramic coating Manchester marketing",
    "paint correction Manchester SEO",
    "Manchester mobile car valet lead generation",
    "Cheshire-edge supercar detailer marketing",
  ],
  secondaryKeywords: [
    "Hale Bowdon Alderley Edge supercar detailer",
    "Manchester United City player ceramic coating",
    "Brilliant Detailing Northern Detailing competitor Manchester",
    "Gtechniq accredited applicator Manchester",
    "GYEON Quartz approved detailer Cheshire",
    "Didsbury Altrincham mobile valet marketing",
    "MediaCity Salford Quays car detailing",
    "Trafford Wilmslow paint correction marketing",
  ],
  heroSubhead:
    "Greater Manchester is the second-strongest mobile detailing market in the UK after London — driven by the Cheshire-edge wealth corridor (Hale, Bowdon, Alderley Edge, Wilmslow), the Manchester United and Manchester City player-population concentrations in Hale and Wilmslow with their density of Bentley, Aston Martin, Lamborghini, Ferrari and Rolls-Royce inventory, and a deep professional-belt market through Didsbury, Altrincham and Worsley willing to pay £1,500–£4,000 for full ceramic-coat treatment on Range Rovers, S-Classes and X7s. Spinningfields executive demand layered on top of MediaCityUK tech professionals, plus the Trafford and Didsbury family-fleet ceramic-coat market, gives Manchester independents 8–14 distinct postcode-level catchments. Kerblabs builds independent mobile-detailer marketing that captures Hale supercar work, Didsbury family ceramic-coats and city-centre apartment subscription wash flow without forecourt hand-wash undercutting.",
  marketContext: [
    "Greater Manchester's mobile detailing market is structurally polycentric in a way that no other UK city outside London matches. The Cheshire-edge belt — Hale, Bowdon, Alderley Edge, Wilmslow, Knutsford, Prestbury — concentrates one of Europe's densest non-London supercar populations, driven heavily by Manchester United and Manchester City first-team and academy populations who live almost exclusively in WA15 (Hale), WA14 (Altrincham/Bowdon), SK9 (Wilmslow/Alderley Edge) and SK10 (Prestbury/Macclesfield-fringe). Bentley Continental GT, Lamborghini Urus, Ferrari Roma, Aston Martin DBX, Rolls-Royce Cullinan and Range Rover SVR inventory across these four postcodes is exceptionally high, with ceramic-coat job values running £2,000–£5,000 routinely and PPF full-front-end at £1,800–£3,500. Hale Barns and Bowdon detailers servicing the player population work largely on referral — but the catchment is buildable for new entrants who position credibly with Gtechniq Accredited Applicator, GYEON Quartz Approved or CarPro CQuartz Finest Reserve credentials surfaced correctly. Beyond Cheshire-edge, the Didsbury/West Didsbury professional belt (M20), Altrincham (WA14), Worsley (M28) and Hale (WA15) anchor the city's executive ceramic-coat market — Range Rover Sport, BMW X5/X7, Audi RS, AMG E63 and Porsche Cayenne owners with £40,000–£90,000 vehicle inventory paying £1,200–£3,000 for full-correction + ceramic packages.",
    "Manchester's central market is sharply different. Spinningfields, the Northern Quarter, Ancoats, NOMA and MediaCityUK pull a young-professional ceramic-coat market focused on £25,000–£45,000 vehicles (BMW M-Sport, Audi S-line, Mercedes AMG-Line, Tesla Model 3 and Y, Polestar 2) with average ceramic-coat tickets of £600–£1,500 and a strong appetite for monthly maintenance subscriptions (£35–£60/month). The MediaCityUK tech corridor (BBC, ITV, dock10, Booking.com, AutoTrader) supports a particularly strong subscription-wash market because the time-poor 25-40 demographic concentrated there will pay a premium for mobile-driveway-or-car-park service rather than booking a Saturday at a static studio. Apartment-driveway parking constraints across central Manchester force most city-centre detailing to happen at workplace car parks — Spinningfields, Old Trafford office park, MediaCityUK underground — which is a niche worth marketing to directly with B2B-friendly content. Outer Greater Manchester (Stockport, Bolton, Oldham, Wigan, Bury, Rochdale, Trafford) operates at lower price points — £80–£200 maintenance valets, £500–£1,200 single-stage correction — but with notably cheaper Google Ads CPCs and a different competitive set including a heavy concentration of informal forecourt hand-car-wash operators (around 800+ across Greater Manchester per Trades Union research) routinely breaching Water Industry Act wastewater rules.",
    "Manchester Google Ads CPCs in detailing keywords run at £4–£10 for 'ceramic coating Manchester', £3–£8 for 'paint correction Manchester', £2–£5 for 'mobile car valet Manchester', and £6–£12 for 'supercar detailer Manchester' in 2024–2025. Borough-level CPCs drop sharply: 'ceramic coating Hale' at £3–£6, 'mobile valet Stockport' at £1.50–£3, 'paint correction Didsbury' at £2.50–£5. The strategic implication is the same as London but at a lower price point: borough-stratified SEO + Google LSA + Maps optimisation + Cheshire-edge supercar-specialist content authority reliably produces £30–£65 cost-per-acquired-job versus £140–£280 on Bark, MyBuilder and Checkatrade. Brand-certification credentials carry exceptional weight in Hale, Bowdon, Wilmslow and Prestbury — supercar owners spending £2,500+ on a coating expect Gtechniq, GYEON or CarPro accreditation, manufacturer warranty validity and demonstrable training credentials. Brilliant Detailing, Northern Detailing and a long tail of established Cheshire-edge boutique studios dominate brand search, but the catchment is large enough that 4–8 new ceramic-coat applications per month plus 40–80 maintenance subscriptions are realistic for a properly positioned new entrant within 9 months.",
  ],
  stats: [
    { value: "£2,000–£5,000", label: "typical Hale/Bowdon/Wilmslow supercar multi-stage correction + ceramic-coat job value" },
    { value: "£4–£12", label: "Google Ads CPC range for Manchester detailing keywords 2024–2025", source: "Kerblabs client accounts" },
    { value: "10", label: "Greater Manchester boroughs each with distinct mobile-detailing market dynamics" },
    { value: "~800+", label: "informal forecourt hand car wash sites across Greater Manchester", source: "Trades Union research estimate" },
    { value: "£35–£60/month", label: "typical MediaCityUK/Spinningfields maintenance-wash subscription pricing" },
    { value: "£1,200–£3,000", label: "typical Didsbury/Altrincham/Worsley executive ceramic-coat package value" },
  ],
  painPoints: [
    {
      title: "Cheshire-edge supercar market completely under-marketed without applicator credentials surfaced",
      body: "Hale, Bowdon, Alderley Edge, Wilmslow and Prestbury concentrate one of Europe's densest non-London supercar populations, driven heavily by Manchester United and Manchester City first-team and academy. Bentley, Lamborghini, Ferrari, Aston Martin, Rolls-Royce ceramic-coat jobs routinely hit £2,000–£5,000. But these owners check applicator credentials before handing over keys — Gtechniq Accredited Applicator, GYEON Quartz Approved, CarPro CQuartz Finest Reserve, Kamikaze Collection Approved status carry manufacturer warranty validity (5, 7, 9 years). Most independent Manchester detailer GBPs and websites bury these credentials. We surface them through schema markup, dedicated logo placement, certification numbers and warranty period prominence.",
    },
    {
      title: "Forecourt hand-wash competitors undercutting through Water Industry Act breaches",
      body: "Greater Manchester has roughly 800+ informal forecourt hand-car-wash operators, particularly concentrated in Oldham, Bolton, Wigan and outer Trafford. Most routinely breach Water Industry Act 1991 wastewater capture requirements — surfactants, brake dust and microplastics drained directly into surface water, often on closed petrol forecourts with poor environmental compliance. Compliant mobile detailers using water-recovery mats, bunded containment or closed-loop deionised systems are structurally more expensive but invisible to customers unless surfaced. We add a dedicated 'how we wash legally' content hub, EA waste-carrier licence number in GBP, and water-recovery photographs to job-completion posts.",
    },
    {
      title: "MediaCityUK and Spinningfields subscription-wash market barely tapped",
      body: "Tech and broadcast professionals at BBC MediaCityUK, ITV, dock10, Booking.com, AutoTrader, plus Spinningfields legal and finance staff, represent one of the strongest UK subscription-wash markets — time-poor, digital-first, willing to pay £35–£60/month for fortnightly mobile-driveway or workplace-car-park visits. Most independent Manchester detailers convert under 8% of one-time customers into subscriptions because there's no automated nurture sequence, no GoCardless billing setup, and no B2B workplace-parking partnership. We rebuild the funnel and the workplace B2B outreach to lift subscription conversion to 25–45% within 12 months.",
    },
    {
      title: "Aggregator dependency at 40-55% with Bark/Checkatrade taking £25-£60 per shared lead",
      body: "Most Greater Manchester independent detailers source 35–55% of new jobs through Bark, MyBuilder, Checkatrade or Treatwell-equivalent platforms, paying £20–£60 per shared lead with conversion rates of 20–30%. That's £900–£3,500 monthly lead-buying with no email list, no remarketing rights and no client data ownership when the platform changes its rules. We build parallel direct-acquisition (borough-level Google LSA + Google Ads + Maps + workplace B2B outreach) that typically reduces aggregator dependency from 45% to 15% inside 6–9 months at half the cost-per-job.",
    },
  ],
  faqs: [
    {
      q: "How do you actually break into the Hale, Bowdon and Wilmslow supercar player market that's referral-locked?",
      a: "Three structured routes that stack rather than compete. First, applicator-credential signalling: Gtechniq Accredited Applicator, GYEON Quartz Approved, CarPro CQuartz Finest Reserve and Kamikaze Collection Approved status surfaced rigorously across landing pages, schema, GBP and quote PDFs — these credentials are checked by player agents and personal-assistants before any £3,000+ booking. Second, supercar dealership and OPC outreach: Bentley Manchester, Aston Martin Manchester, Porsche Centre Hatfield/Wilmslow, McLaren Manchester, Lamborghini Manchester (when opened), JCT600 Bentley/Lamborghini all need pre-delivery prep partners and ceramic-coat referral relationships. Third, named-area landing pages with genuinely local content: 'ceramic coating Hale Barns', 'paint correction Bowdon WA14', 'mobile detailing Alderley Edge SK9' with real local references (specific roads, named local concours events at Tatton Park, etc) drive surprising long-tail traffic at sub-£4 CPC. Manchester clients running this stack typically book 2–4 supercar £3,000–£5,000 jobs per month inside 9–12 months.",
    },
    {
      q: "Can the AI receptionist handle the volume difference between a £35 MediaCityUK subscription wash and a £4,000 Hale Range Rover ceramic coating?",
      a: "Yes — that's the core qualifying flow. The first three questions establish job tier (maintenance/mini valet/full valet/correction/ceramic/PPF/supercar), then vehicle reg captures via DVLA lookup confirms make/model/year/paint hardness, then postcode confirms catchment tier (city-centre subscription, executive belt, Cheshire-edge supercar). MediaCityUK and Spinningfields enquiries route to the subscription-conversion flow with workplace-parking confirmation. Didsbury/Altrincham/Worsley enquiries trigger the executive ceramic-coat funnel with on-site survey appointment and SMS photo capture. Hale/Bowdon/Wilmslow supercar enquiries trigger a different protocol entirely — discrete same-day callback from senior technician, treatment-risk insurance verification, supercar PPE protocol, formal scope-of-works template, and Gtechniq/GYEON/CarPro warranty registration. The detailer never sorts generic enquiries again, and high-value Cheshire-edge enquiries don't sit in voicemail while a £4,000 ceramic-coat job evaporates.",
    },
    {
      q: "How do you handle the Stockport, Bolton, Wigan and Oldham budget end without cannibalising the Cheshire-edge premium positioning?",
      a: "We build clearly separated funnels rather than pretending one brand voice fits both. Outer Greater Manchester operates at materially lower price points (£60–£150 maintenance valets, £400–£1,000 single-stage correction) and a different customer expectation. We typically build a secondary landing page targeting 'mobile car valet Stockport', 'mobile detailing Bolton', 'car valet Oldham' etc with appropriate price band positioning, separated from the Cheshire-edge premium content. Google Business Profile service-area definitions are tuned to your actual operating radius rather than blanket 'Greater Manchester' coverage. AI receptionist scripts adapt tone and pricing band based on postcode lookup. Some detailers run two sub-brands (one for budget/maintenance volume, one for premium/ceramic) which we support with separate domain strategies. Most operators find that a single brand with clearly tiered service pages works fine — the volume customers don't care that you also do supercar work, and the supercar customers care about your applicator credentials, not your bottom-tier offerings.",
    },
    {
      q: "How important is Manchester's 10-borough geographic fragmentation for local SEO and GBP strategy?",
      a: "Decisive. Greater Manchester isn't one search market — it's ten plus the Cheshire fringe. Ranking in M20 (Didsbury) is independent of ranking in WA15 (Hale), SK9 (Wilmslow), SK4 (Heaton Moor) or BL1 (Bolton). Kerblabs builds borough-tuned GBP strategies: location-tagged review collection, borough-specific landing pages with genuine local detail (executive housing density, supercar concentration, school catchments, regeneration-zone proximity), and review velocity calibrated to the competitive intensity of each ward. A Stockport mobile detailer's GBP plan looks nothing like a Hale supercar specialist's. We track Maps rankings weekly across 50+ Greater Manchester postcodes and adjust signals against borough-level competitors rather than 'Manchester' as a single market. Borough-level CPCs drop dramatically vs city-wide bidding, and conversion improves because the customer sees themselves reflected in the landing-page content.",
    },
  ],
  approach:
    "For Greater Manchester mobile detailers, our 90-day playbook is: (1) build borough-stratified Google Business Profile and Local Service Ads coverage across the 6–10 boroughs you actually service (Cheshire-edge, Didsbury/Altrincham executive belt, MediaCityUK/Spinningfields city-centre, outer borough volume), with category stacking (Car Detailing Service + Car Wash + Auto Restoration); (2) deploy AI 24/7 receptionist with postcode-aware tier routing (maintenance/executive/Cheshire-edge supercar), DVLA reg lookup, SMS photo capture for £400+ enquiries, and ULEZ-equivalent compliance signalling; (3) build supercar-dealership B2B funnel (Bentley Manchester, Porsche Centre Wilmslow, Aston Martin Manchester, McLaren Manchester) plus pre-delivery PPF positioning; (4) surface Gtechniq/GYEON/CarPro accreditation, EA waste-carrier credentials and named trade-effluent disposal partner; and (5) drive Google review velocity to 8–12 new reviews per month with borough-level keyword density (Hale, Bowdon, Didsbury, Altrincham, Wilmslow, Worsley, Stockport, Trafford).",
};
