import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "cleaning company marketing Edinburgh",
    "domestic cleaner marketing Edinburgh",
    "Festival cleaning Edinburgh August marketing",
    "end of tenancy cleaning lead generation Edinburgh",
    "Airbnb turnover cleaning Edinburgh",
  ],
  secondaryKeywords: [
    "Festival Cleaning Co Edinburgh Domestic Cleaning competitor",
    "Edinburgh Fringe August Airbnb explosion turnover cleaner",
    "EH1 EH2 EH3 New Town Old Town premium domestic Edinburgh",
    "Stockbridge Morningside Bruntsfield Trinity premium domestic",
    "Edinburgh LEZ June 2024 cleaning van compliance",
    "Edinburgh University Heriot-Watt Napier student EoT EH8 EH9 EH10",
    "Tenancy short-let Edinburgh control area cleaning",
    "Festival accommodation cleaning Edinburgh August teams",
  ],
  heroSubhead:
    "Edinburgh's cleaning market is uniquely shaped by the August Festival explosion — the world's largest arts festival drives Airbnb turnover volume to 4–8x normal levels for 25 days across EH1, EH2, EH3, EH7, EH8 and EH9, with festival-period turnover cleaning specialists running dawn-to-midnight rotas at premium rates. The Edinburgh LEZ enforced from 1 June 2024 charges non-compliant cleaning vans £60/day inside the city centre. New Town (EH1/EH3), Old Town (EH1), Stockbridge (EH3), Morningside (EH10), Bruntsfield (EH10) and Trinity (EH5) support £22–£28/hr premium domestic rates. The University of Edinburgh, Heriot-Watt and Napier drive an EH8/EH9/EH10/EH16 student EoT peak in late May/June. Edinburgh's short-term-let control area regime (in force from October 2022, full enforcement from October 2023) reshaped the Airbnb landscape — many hosts now operate under licence requiring documentation of cleaning standards. Named competitors include Festival Cleaning Co, Edinburgh Domestic Cleaning, Maid2Clean Edinburgh, Bright & Beautiful Edinburgh plus ISS, Mitie, OCS commercial giants. Kerblabs builds the festival-aware, LEZ-compliant marketing system Edinburgh independent cleaners (1–25 staff) actually need.",
  marketContext: [
    "Edinburgh's cleaning market is shaped by three structural forces unique to Scotland's capital. First, the August Festival period is the most concentrated single-month cleaning revenue opportunity anywhere in the UK. The Edinburgh International Festival, Edinburgh Fringe (the world's largest arts festival with 3,500+ shows and 2.5M+ ticket sales), Edinburgh International Book Festival, the Royal Edinburgh Military Tattoo and the Edinburgh Art Festival together drive 4M+ visitor attendances across August. Airbnb turnover volume runs at 4–8x normal levels for 25–30 days, festival-period rentals routinely run £200–£500/night vs £80–£150 baseline, and concentrated turnover cleaning demand emerges across EH1 (Old Town/Royal Mile), EH2 (New Town/Princes Street), EH3 (New Town West/Stockbridge), EH7 (Leith Walk/Easter Road), EH8 (Newington/St Leonards), EH9 (Marchmont/Newington) and increasingly EH6 Leith. Festival-period turnover cleaners run dawn-to-midnight rotas, with established festival-cleaning teams charging £90–£160 per turnover (vs £55–£90 normal Edinburgh rates) and weekly retainers at £600–£1,800 per property. Most independent Edinburgh cleaners under-resource August and lose massive revenue, or over-promise and burn staff out by the second week.",
    "Second, Edinburgh's short-term-let control area regime (in force across the entire city since October 2022, full licensing enforcement October 2023) has reshaped the Airbnb landscape. Hosts operating non-primary-residence short-lets now require a licence from the City of Edinburgh Council, with documentation requirements including cleaning standards, health-and-safety compliance and insurance. This has reduced casual hosting but increased professional-host density and quality expectations. Cleaning operators positioned as licensed-host-friendly (with documented cleaning protocols, COSHH compliance evidence, public liability £5m+, employer's liability, key-holding insurance) command 20–30% premium rates over generic Airbnb cleaning. Third, the Edinburgh LEZ enforced from 1 June 2024 charges £60/day for non-compliant vans inside the city-centre LEZ zone — bounded approximately by Princes Street, the Cowgate, Holyrood Park, Lauriston Place and Lothian Road. The penalty doubles on repeat offences (£120, £240, £480) within 90 days. The LEZ has bifurcated the cleaning market: LEZ-compliant operators with Euro 6 fleet hold the EH1/EH2/EH3 city-centre commercial and Old Town/New Town Airbnb work, while non-compliant operators have retreated to outer EH postcodes.",
    "Premium Edinburgh domestic catchments support the UK's third-highest cleaning rates after London and Reading: New Town (EH1, EH3), Old Town (EH1), Stockbridge (EH3), Morningside (EH10), Bruntsfield (EH10), Marchmont (EH9), Trinity (EH5), Inverleith (EH3), Murrayfield (EH12), Cramond (EH4), Barnton (EH4) and the wider Lothian commuter belt support £22–£28/hr domestic rates with weekly/fortnightly recurring books filling within weeks. The University of Edinburgh (40,000+ students), Heriot-Watt and Edinburgh Napier collectively house around 60,000+ students with peak tenancy-end dates clustering across EH8 Newington/St Leonards, EH9 Marchmont/Newington, EH10 Bruntsfield/Greenhill and EH16 Liberton in late May and June (Scottish academic year ends earlier than English). Letting agents (Cullen Property, Umega Lettings, Rettie & Co Lettings, Belvoir Edinburgh, Northwood Edinburgh, Slater Hogg & Howison, Allen & Harris) push 10–25 EoT jobs per week per branch. Edinburgh Google Ads CPCs in cleaning keywords are higher than other Scottish cities — 'cleaner Edinburgh' clicks at £2.50–£5, 'end of tenancy cleaning Edinburgh' at £3.80–£7.50, 'office cleaning Edinburgh' at £4.50–£10, 'Airbnb cleaning Edinburgh' at £3–£7 with Festival-period spikes adding 30–60% across August. Postcode-level CPCs are markedly lower — 'cleaner Stockbridge', 'cleaner Morningside' click at £1.60–£3.40.",
  ],
  stats: [
    { value: "4–8x", label: "Edinburgh August Festival Airbnb turnover volume vs normal — concentrated 25-day window", source: "Festivals Edinburgh / VisitScotland" },
    { value: "£60/day", label: "Edinburgh LEZ penalty for non-compliant cleaning vans (doubling £120/£240/£480 on repeat) — live since June 2024", source: "City of Edinburgh Council" },
    { value: "October 2023", label: "Edinburgh short-term-let licensing full enforcement — host documentation requirements lift cleaning standards bar", source: "City of Edinburgh Council" },
    { value: "£22–£28/hr", label: "New Town, Old Town, Stockbridge, Morningside, Bruntsfield, Trinity premium domestic rate range" },
    { value: "60,000+", label: "Edinburgh student population (UoE, Heriot-Watt, Napier) driving May–June EoT peak", source: "Universities Scotland" },
    { value: "£90–£160", label: "Festival-period turnover clean rate — vs £55–£90 normal Edinburgh Airbnb turnover" },
  ],
  painPoints: [
    {
      title: "Festival August capacity unmanaged — 4–8x volume spike either lost or breaks operations",
      body: "Edinburgh's August Festival drives Airbnb turnover volume to 4–8x normal levels for 25–30 days across EH1, EH2, EH3, EH7, EH8 and EH9. Most independent Edinburgh cleaners either under-resource and lose massive revenue (turning away £30k–£80k of festival-period bookings) or over-commit and burn staff out by the second week of August. We build dedicated April–May capacity-planning campaigns starting four months ahead with festival-pricing tier (£90–£160 per turnover vs £55–£90 baseline), surge-staffing through Connecteam/Deputy, partnership agreements with Glasgow/Stirling/Falkirk cleaner overflow, festival-host outreach starting in March, and pre-July recurring-customer expectation management."
    },
    {
      title: "Edinburgh short-term-let control area documentation requirement unaddressed",
      body: "Edinburgh's short-term-let licensing regime (full enforcement October 2023) requires hosts to document cleaning standards, health-and-safety compliance and insurance. Cleaning operators positioned as licensed-host-friendly with documented cleaning protocols, COSHH compliance evidence, public liability £5m+, employer's liability, key-holding insurance and structured turnover-checklist photography command 20–30% premium rates over generic Airbnb cleaners. Most independent Edinburgh operators don't surface this licensing-friendly positioning anywhere. We rebuild around licensed-host documentation packages, branded cleaning-standards reports per turnover, and structured outreach to professionalised host networks."
    },
    {
      title: "EH8/EH9/EH10/EH16 May–June student EoT peak unmanaged — UoE/Heriot-Watt/Napier volume going elsewhere",
      body: "Edinburgh's 60,000+ student population drives a late May/June tenancy-turnover EoT peak across EH8 Newington/St Leonards, EH9 Marchmont/Newington, EH10 Bruntsfield/Greenhill, EH16 Liberton, with concentrated volume because Scottish academic year ends earlier than English. Volume runs 4–7x normal levels with letting agents (Cullen Property, Umega Lettings, Rettie & Co Lettings, Belvoir Edinburgh, Northwood, Slater Hogg & Howison, Allen & Harris) pushing 10–25 EoT jobs per week per branch at £160–£340 per property. We build dedicated May–June capacity-planning campaigns with seasonal pricing, student-letting-agent B2B outreach, and Scottish PRT-aware deposit-return SLA aligned to SafeDeposits Scotland, Letting Protection Scotland and MyDeposits Scotland."
    },
    {
      title: "Edinburgh LEZ £60/day daily charge unmarketed — compliant fleet investment invisible to customers",
      body: "Edinburgh cleaning operators have spent £18,000–£35,000 per Euro 6 van to stay LEZ-compliant for EH1/EH2/EH3 city-centre work since June 2024, but most don't surface that fact anywhere in their marketing. New Town/Old Town professional-household and licensed-host customers care — non-compliant operators get refused at gated developments and stair-access common-stair properties, and the £60/day repeat-offender escalation (£120, £240, £480) is genuinely punishing. We rebuild messaging to put LEZ-compliant fleet, Euro 6 certification, Edinburgh LEZ vehicle-check screenshots and aggressive-LEZ-compliance positioning directly into landing pages."
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat Festival Cleaning Co, Edinburgh Domestic Cleaning, Maid2Clean Edinburgh, Bright & Beautiful Edinburgh and the Bark/TaskRabbit aggregators in Edinburgh specifically?",
      a: "Three-phase Edinburgh-specific playbook. Phase one: Google Business Profile category stacking (House Cleaning Service + Commercial Cleaning Service + Carpet Cleaning Service + Window Cleaning Service + Janitorial Service) with postcode-level service-area definition, BICSc and CHSA membership schema, DBS-vetting credential schema, LEZ-compliant fleet schema, short-term-let-licensing-friendly positioning, and structured review campaigns targeting 10–18 new reviews per month with named area keywords (New Town, Old Town, Stockbridge, Morningside, Bruntsfield, Marchmont, Trinity, Inverleith, Murrayfield, Cramond, Leith). Phase two: Google Local Service Ads with the Google Guaranteed badge — on Edinburgh cleaning keywords this consistently lands at £30–£60 cost-per-acquired-job versus £90–£220 on Bark, TaskRabbit, Helpling and Handy. Phase three: postcode-stratified Google Ads with separate campaigns per area (EH1/EH2/EH3 city centre/New Town/Old Town with festival-period budget loading in August, EH8/EH9/EH10/EH16 student/premium with May–June EoT peak loading, EH3/EH4 Stockbridge/Cramond/Murrayfield premium), plus a Festival-period Airbnb host funnel and a May–June student-EoT funnel. Edinburgh cleaning clients typically reduce aggregator dependency from 45% to 12% inside 6 months while growing total job volume 40–60% via the August Festival capture."
    },
    {
      q: "How do we capture the August Festival Airbnb turnover explosion without burning out staff or lowering quality?",
      a: "Edinburgh's August Festival period is the single biggest concentrated cleaning revenue opportunity in the UK calendar, and most independents either under-resource (losing £30k–£80k of festival bookings to turnover-cleaning specialists) or over-commit (burning staff out by week two and producing complaints). We build a five-component approach: (1) capacity planning starting in April — surge staffing through Connecteam or Deputy, partnership agreements with Glasgow/Stirling/Falkirk cleaner overflow, fixed-fee subcontracting for the peak 25-day window; (2) festival-pricing tier (£90–£160 per turnover vs £55–£90 baseline, plus £600–£1,800/property weekly retainer) with transparent festival-period uplift signalling; (3) festival-host B2B outreach starting in March — direct outreach to Festival Cottages, Festival Beds and the major festival-accommodation aggregators, plus the Edinburgh Hosts Forum and Edinburgh Festival Accommodation host networks; (4) structured turnover-checklist photography and licensed-host documentation packages for the post-October-2023 STL licensing regime; (5) post-festival recovery — automated rebooking sequences for festival hosts converting to year-round monthly retainers at £400–£1,200/month per property. Edinburgh cleaning clients running this typically book 60–180 festival-period turnovers across August at £100–£140 average per turnover, generating £8k–£25k peak-month revenue on top of normal trading."
    },
    {
      q: "How do we capture the EH8/EH9/EH10/EH16 May–June student tenancy-turnover EoT volume from UoE, Heriot-Watt and Napier without breaking operationally?",
      a: "Edinburgh's late May/June student EoT peak is unusually concentrated because Scottish academic year ends earlier than English. Volume across EH8 Newington/St Leonards, EH9 Marchmont, EH10 Bruntsfield, EH16 Liberton runs at 4–7x normal levels. We build a four-component approach: (1) capacity planning starting in March — surge staffing via Connecteam/Deputy, agency overflow agreements; (2) student-letting-agent B2B outreach to Cullen Property, Umega Lettings (Edinburgh student specialists), Rettie & Co Lettings, Belvoir Edinburgh, Northwood Edinburgh, Slater Hogg & Howison, Allen & Harris, plus University of Edinburgh Accommodation, Heriot-Watt Accommodation, Napier Accommodation and Edinburgh Unite Students/Vita Student PBSA operators; (3) dedicated May–June landing pages with student-EoT-specific pricing (£160–£340 per property, deposit-return-guarantee aligned to SafeDeposits Scotland/LPS/MyDeposits Scotland, oven/external-window add-ons, 24-hour turnaround SLA); (4) post-EoT host conversion — many EoT properties convert immediately to August Festival short-let, so we run automated host-conversion outreach offering combined EoT + Festival-period retainer packages."
    },
    {
      q: "Can the AI receptionist handle the difference between a £18/hr Leith domestic regular, a £200 Marchmont student EoT, a £140 New Town Festival turnover and a £100k commercial tender, including LEZ qualifying and STL licensing awareness?",
      a: "Yes — and it includes Edinburgh-postcode plus LEZ plus STL-licensing awareness in the qualifying flow. The first three questions are: which postcode is the property in (the receptionist explicitly confirms EH-postcode because pricing, drive-time, competitive set and LEZ compliance differ — EH1/EH2/EH3 inner LEZ require Euro 6 vans, while outer EH4/EH7/EH11 sit outside); is this a domestic recurring/one-off, a student/end-of-tenancy, an Airbnb turnover (with festival-period flag for August) or a commercial enquiry; and what's the urgency. Domestic regulars trigger banded hourly quoting against your area rate card. Student EoT triggers May–June UoE/Heriot-Watt/Napier letting-agent-aware flow with Scottish PRT-aware deposit-return wording. Airbnb turnover triggers post-October-2023-STL-licensing-friendly flow with documented cleaning-standards reporting, key-handover protocol and host monthly retainer offer — with festival-period flag triggering uplift pricing for August. Commercial enquiries trigger 30-minute on-site survey appointment with accreditation pre-screening (CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, Living Wage), LEZ-compliance documentation handover, and tender-document handover."
    },
  ],
  approach:
    "For Edinburgh cleaning firms, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + postcode-stratified Google Ads + Maps optimisation + named-cleaner DBS-profile pages + LEZ-compliant fleet + STL-licensing-friendly positioning) to reduce Bark/TaskRabbit/Helpling/Handy dependency from 45% to under 12%; (2) deploy AI 24/7 receptionist with EH-postcode-LEZ-and-STL-aware qualifying flow plus separate funnels for domestic recurring, May–June UoE/Heriot-Watt/Napier student EoT, August Festival turnover, year-round Airbnb turnover, and commercial tender — integrated to Jobber/ServiceM8/Service Fusion/Connecteam; (3) build a dedicated August Festival capture programme starting in March with festival-pricing tier, surge-staffing plans, festival-host B2B outreach (Festival Cottages, Festival Beds, Edinburgh Hosts Forum), and £8k–£25k peak-month revenue targeting; (4) build a student-letting-agent B2B funnel for the May–June EoT peak with Scottish PRT and SafeDeposits/LPS/MyDeposits Scotland alignment; (5) build commercial-tender accreditation funnel (CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, BICSc Accredited Trainer, Living Wage, LEZ-compliant fleet) for Edinburgh city-centre office contracts via Public Contracts Scotland; and (6) drive Google review velocity to 10–18 new reviews per month with postcode-level keyword density.",
};
