import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "cleaning company marketing Derby",
    "Rolls-Royce Toyota Alstom corporate cleaning Derby",
    "domestic cleaner marketing Derby",
    "end of tenancy cleaning lead generation Derby",
    "office cleaning company SEO Derby",
  ],
  secondaryKeywords: [
    "Derby Cleaning Services Maid2Clean Derby competitor",
    "Allestree Mickleover Littleover Quarndon premium domestic cleaning",
    "Rolls-Royce Sinfin Raynesway commercial cleaning tender",
    "Toyota Burnaston Alstom Litchurch Lane corporate cleaning Derby",
    "Foxtons Belvoir Hunters Derby letting agent panel cleaning",
    "DBS checked cleaner Allestree Mickleover Quarndon",
    "Pride Park Wyvern office cleaning tender Derby",
    "no Derby CAZ cleaning van advantage 2024",
  ],
  heroSubhead:
    "Derby's cleaning market is uniquely shaped by the UK's most concentrated advanced-engineering corporate-commercial pipeline — Rolls-Royce Civil Aerospace (14,000+ employees across Sinfin and Raynesway), Toyota's Burnaston plant, Alstom's Litchurch Lane train-manufacturing site, Pattonair, JCB Power Systems and the wider aerospace-and-rail tier-one supplier network drive substantial office, R&D-facility and managed-staff-accommodation cleaning demand at corporate-grade service levels. Allestree, Mickleover, Littleover and Quarndon support £18–£24/hr domestic rates with research-driven engineering-professional households. Derby has no CAZ — a structural cost advantage. Named competitors include Derby Cleaning Services, Maid2Clean Derby, Molly Maid Derby plus ISS, Mitie, OCS commercial giants. Letting agents (Belvoir Derby, Hunters, Boxall Brown & Jones, Frank Innes, Northwood, Connells) push 6–12 EoT jobs per week per branch. Kerblabs builds the Rolls-Royce/Toyota/Alstom-aware, engineering-professional-tuned marketing system Derby independent cleaners (1–25 staff) actually need.",
  marketContext: [
    "Derby's cleaning market is shaped by three structural forces unique to the UK's most concentrated advanced-engineering city. First, the corporate-commercial pipeline is unusually deep for a city of 261,000. Rolls-Royce Civil Aerospace is headquartered in Derby and employs more than 14,000 people across Sinfin (DE24) and Raynesway (DE21), Toyota's Burnaston plant (eight miles south-west, DE65) has produced more than five million cars since 1992 and runs 24/7 manufacturing operations, Alstom's Litchurch Lane (DE24) is the UK's only volume train-manufacturing facility employing 3,000+, and Pattonair, JCB Power Systems and a long tail of aerospace and rail tier-one suppliers ring the city. Annual office, R&D-facility, factory hygiene and managed-staff-accommodation cleaning contracts run £30k–£300k typically, plus framework agreements via ProContract, Find a Tender and the Royal Derby Hospital University Hospitals of Derby and Burton (UHDB) NHS Trust. Service-level requirements are exacting — DBS-checked staff vetting, ISO 9001/14001/45001, COSHH compliance, BICSc Accredited Trainer status, Living Wage employer registration, photographic cleaning audits, and increasingly aerospace-cleanroom-aware protocols at Sinfin and supplier sites — well above standard domestic Airbnb cleaning bar.",
    "Second, Derby's no-CAZ position is a structural advantage independent operators consistently fail to market. Derby has no Clean Air Zone, so DE-postcode cleaning vans avoid the £8/day Birmingham CAZ Class D, the £12.50 London ULEZ, the Bradford CAZ Class C £9/day and the Sheffield CAZ Class C £10/day — giving Derby operators credible competitive pricing when bidding regional commercial work into Nottingham (NG-postcodes, also no CAZ but local), Birmingham B-postcodes (with daily-charge avoidance built into bids), Leicester, Stoke-on-Trent and the wider East Midlands engineering supplier belt. Third, Derby's customer profile is the most research-driven consumer audience any UK regional cleaning operator sells to. Engineering, R&D and aerospace professionals at Rolls-Royce, Alstom and Toyota visit your website three or four times before booking, read every Google review, scrutinise Companies House and Care Inspectorate-equivalent records, and compare line-item quotes carefully. Glossy hero shots and discount headlines structurally under-perform here — what works is detailed service explanations, named DBS-vetted cleaner profiles, before-and-after galleries with context, COSHH/BICSc credential signalling, and continuous review velocity.",
    "Premium Derby domestic catchments support £18–£24/hr rates: Allestree (DE22) — Derby's most established affluent suburb to the north, with Markeaton Park on its doorstep and a high concentration of Rolls-Royce engineering-professional households; Mickleover (DE3) — premium western suburb dominated by 1990s-2010s detached new-builds with strong owner-occupier base; Littleover (DE23) — established premium southern suburb close to Mickleover with strong school catchments; Quarndon (DE22) — village-scale premium catchment north of Allestree; Chellaston (DE73) — fast-growing southern commuter belt off the A50 with newer family housing. The University of Derby's 17,000+ students drive a DE22/DE23 student-EoT peak in late June/July, with letting agents (Belvoir Derby, Boxall Brown & Jones, Frank Innes, Hunters, Northwood, Foxtons Derby, Connells, Reeds Rains) pushing 6–12 EoT jobs per week per branch in the peak window at £140–£300 per property. Derby Google Ads CPCs are 25–40% below equivalent Birmingham terms — 'cleaner Derby' clicks at £1.60–£3.20, 'end of tenancy cleaning Derby' at £2.40–£5, 'office cleaning Derby' at £3–£6.50, with postcode-level CPCs running £1.10–£2.40. Strategic implication: postcode-stratified Google Ads (DE1 Cathedral Quarter, DE3 Mickleover, DE22 Allestree/Quarndon, DE23 Littleover/Sunny Hill, DE24 Sinfin/Alvaston, DE73 Chellaston/Melbourne) plus a structured Rolls-Royce/Toyota/Alstom commercial-tender funnel reliably produces £20–£40 cost-per-acquired-job versus £75–£180 on aggregators.",
  ],
  stats: [
    { value: "£30k–£300k", label: "Derby annual office cleaning tender range — Rolls-Royce Sinfin/Raynesway, Toyota Burnaston, Alstom Litchurch Lane, UHDB, Derby City Council", source: "Kerblabs client accounts" },
    { value: "14,000+", label: "Rolls-Royce Civil Aerospace employees in Derby — UK's most concentrated advanced-engineering workforce driving corporate-cleaning demand", source: "Rolls-Royce" },
    { value: "No CAZ", label: "Derby has no Clean Air Zone — DE-postcode cleaning vans avoid Birmingham/London/Bradford/Sheffield daily-charge overhead — structural regional advantage", source: "Derby City Council" },
    { value: "£18–£24/hr", label: "Allestree, Mickleover, Littleover, Quarndon, Chellaston premium domestic cleaning rate range" },
    { value: "17,000+", label: "University of Derby student population driving DE22/DE23 June–July EoT peak", source: "HESA 2023/24" },
    { value: "£1.60–£6.50", label: "Derby cleaning keyword CPC range — 25–40% below Birmingham equivalents", source: "Kerblabs client accounts" },
  ],
  painPoints: [
    {
      title: "Rolls-Royce/Toyota/Alstom/UHDB commercial-tender pipeline going to ISS, Mitie, OCS by default",
      body: "Derby's commercial cleaning tender pipeline is the UK's most concentrated for an advanced-engineering city — Rolls-Royce Sinfin and Raynesway sites, Toyota Burnaston plant, Alstom Litchurch Lane, Pattonair, JCB Power Systems, plus University Hospitals of Derby and Burton (UHDB), University of Derby, Derby City Council and Derbyshire County Council framework agreements. Annual office, R&D-facility, factory hygiene and managed-staff-accommodation contracts run £30k–£300k typically. Without CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, BICSc Accredited Trainer status, Living Wage employer registration, COSHH compliance documentation, public liability £10M, and increasingly aerospace-cleanroom-aware protocols, independent cleaners are invisible to ISS, Mitie, OCS, Atlas FM, Nviro, Birkin Group and Bidvest Noonan."
    },
    {
      title: "Engineering-professional research-driven audience getting transactional marketing — losing high-value cosmetic/regular work",
      body: "Allestree, Mickleover, Littleover and Quarndon engineering-professional households are among the most research-driven consumer audiences any UK regional cleaning operator sells to. They visit websites three to four times before booking, read every Google review, scrutinise Companies House records, and compare line-item quotes carefully. Most independent Derby cleaning operators run transactional 'book now' marketing that structurally under-performs with this audience. We rebuild around long-form landing pages with detailed service explanations, named DBS-vetted cleaner profile pages, before-and-after galleries with context, COSHH/BICSc/Real Living Wage credential signalling, schema markup for credentials, and continuous Google review velocity targeting 12–20 new reviews per month."
    },
    {
      title: "No-Derby-CAZ regional advantage unmarketed — Birmingham/Sheffield/Leicester commercial work going elsewhere",
      body: "Derby's no-CAZ position is a structural cost advantage: DE-postcode cleaning operators can credibly service Birmingham B-postcodes (with £8/day-charge-avoidance built into bids), Sheffield S-postcodes (£10/day CAZ avoidance), Bradford BD-postcodes (£9/day CAZ avoidance), London (£12.50/day ULEZ avoidance), Nottingham, Leicester, Stoke-on-Trent and the wider East Midlands engineering supplier belt without the daily fleet overhead competitors carry. Most Derby cleaning operators don't market this regional reach at all. We build dedicated regional landing pages with explicit competitive-pricing-without-CAZ-overhead messaging."
    },
    {
      title: "Belvoir/Boxall Brown & Jones/Frank Innes letting-agent EoT panels closed-network — DBS-credential gap blocks entry",
      body: "Each Belvoir Derby, Boxall Brown & Jones, Frank Innes, Hunters, Northwood, Foxtons Derby, Connells, Reeds Rains and Leaders branch in your service area runs a preferred-supplier cleaning panel for end-of-tenancy work — 6–12 jobs per week per branch at £140–£420. Without DBS-checked staff register, public liability £5m, treatment-risk and key-holding insurance, deposit-return guarantee aligned to TDS/mydeposits/DPS, photographic before/after evidence and 24-hour turnaround SLA, you're invisible to the highest-volume EoT pipeline in DE-postcodes."
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us land Rolls-Royce, Toyota, Alstom, UHDB and University of Derby commercial cleaning tenders against ISS, Mitie, OCS and Birkin Group?",
      a: "Derby commercial cleaning tenders are won on accreditation depth, named-account case studies and procurement-portal visibility, not Google Ads. We build the accreditation infrastructure (CHAS Premium Plus, Constructionline Gold, SafeContractor, ISO 9001/14001/45001, BICSc Accredited Trainer status, Real Living Wage employer registration, COSHH compliance documentation, public liability £10M, employer's liability, and aerospace-cleanroom-aware protocols where relevant) and run structured outreach to: (1) Rolls-Royce Civil Aerospace procurement (Sinfin and Raynesway sites); (2) Toyota Manufacturing UK Burnaston procurement; (3) Alstom Litchurch Lane procurement; (4) Pattonair, JCB Power Systems and the wider aerospace and rail tier-one supplier network; (5) University Hospitals of Derby and Burton (UHDB NHS Trust) framework agreements via NHS Supply Chain and Find a Tender; (6) Derby City Council and Derbyshire County Council framework agreements via ProContract; (7) University of Derby procurement. Derby cleaning clients with the right accreditation stack typically open 2–5 tender opportunities within 6–9 months at £30k–£300k annual contract values."
    },
    {
      q: "How does Derby's engineering-professional research-driven audience change our marketing approach?",
      a: "Significantly. Engineering, R&D and aerospace professionals at Rolls-Royce, Alstom and Toyota are among the most research-driven consumer audiences any UK SME cleaning operator sells to. They visit your website three or four times before booking, read every Google review, scrutinise Companies House and ICO records, and compare line-item quotes carefully. Glossy hero shots and discount headlines under-perform structurally. What works is: (1) detailed long-form service-explanation landing pages per cleaning category — domestic recurring, end-of-tenancy, deep clean, oven, carpet, post-construction; (2) named DBS-vetted cleaner profile pages with photo, training credentials, COSHH ticket, BICSc training and tenure; (3) before-and-after galleries with context (e.g. 'Allestree 4-bed end-of-tenancy, 7-hour deep clean, deposit returned in full within 4 working days, TDS-aligned reporting'); (4) credential signalling — CHAS, Constructionline, ISO 9001/14001, BICSc Accredited Trainer, Real Living Wage, COSHH, public liability £5–£10m, employer's liability, treatment-risk, key-holding — surfaced prominently with schema markup; (5) continuous Google review velocity targeting 12–20 new reviews per month with named-cleaner and named-postcode review prompts. Derby cleaning clients running this typically lift average hourly rate 18–30% versus generic city-wide marketing."
    },
    {
      q: "Can the AI receptionist handle the difference between a £17/hr Sinfin domestic regular, a £180 University of Derby student EoT, a £75 Cathedral Quarter Airbnb turnover and a £150k Rolls-Royce Sinfin commercial tender?",
      a: "Yes — and it includes DE-postcode plus engineering-professional-aware qualifying flow. The first three questions are: which DE-postcode is the property in (the receptionist explicitly confirms because pricing, drive-time and competitive set differ — DE1 Cathedral Quarter, DE3 Mickleover premium, DE22 Allestree/Quarndon premium, DE23 Littleover premium, DE24 Sinfin/Alvaston working, DE73 Chellaston commuter, DE21 Spondon/Borrowash, plus DE6/DE7/DE56 outer); is this a domestic recurring/one-off, a student/end-of-tenancy, an Airbnb turnover or a commercial enquiry; and what's the urgency. Domestic regulars trigger banded hourly quoting against your DE-postcode rate card with DBS-vetted cleaner allocation, key-holding insurance offer, COSHH/BICSc credential signalling and weekly/fortnightly recurring offer. Student EoT triggers June–July University of Derby letting-agent-aware flow with TDS/mydeposits/DPS deposit-return wording, photographic evidence, and 24-hour turnaround SLA. Airbnb turnover triggers Cathedral Quarter/Pride Park/Westfield Derbion same-day window confirmation, linen/laundry add-on, and host monthly retainer offer. Commercial enquiries trigger 30-minute on-site survey appointment with accreditation pre-screening (CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, Real Living Wage, aerospace-cleanroom-aware protocols where relevant), Rolls-Royce/Toyota/Alstom/UHDB awareness, and tender-document handover."
    },
    {
      q: "Can Kerblabs help us leverage the no-Derby-CAZ regional advantage to win Birmingham, Sheffield and Nottingham commercial cleaning work?",
      a: "Yes — and it's the most underused Derby-specific positioning angle. Birmingham CAZ Class D charges non-compliant cleaning vans £8/day inside the A4540 ring road (live since June 2021). Sheffield CAZ Class C charges £10/day for non-compliant LCVs (live since February 2023). Bradford CAZ Class C charges £9/day for non-compliant LCVs (live since September 2022). London ULEZ charges £12.50/day across all 32 boroughs. Derby has no CAZ, so DE-postcode cleaning operators carry zero daily-charge fleet overhead when bidding into Birmingham B-postcode commercial work, Sheffield S-postcode work, Bradford BD-postcode work, Nottingham (NG-postcodes, also no CAZ but local-competitor parity), Leicester (LE-postcodes, also no CAZ), Stoke-on-Trent ST-postcodes and the wider East Midlands engineering supplier belt. We build dedicated regional landing pages — 'Cleaning company Birmingham — no CAZ overhead from Derby HQ', 'Office cleaning Sheffield — no CAZ daily charge', 'Cleaning company Nottingham from Derby' — with explicit competitive-pricing-without-CAZ-overhead messaging in copy, schema and ad-copy headlines. Derby cleaning clients running this typically open £40k–£150k of additional regional commercial revenue within 4–8 months."
    },
  ],
  approach:
    "For Derby cleaning firms, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + DE-postcode-stratified Google Ads + Maps optimisation + named-cleaner DBS-and-COSHH-and-BICSc-profile pages + regional campaigns leveraging no-Derby-CAZ advantage into Birmingham/Sheffield/Bradford/London) to reduce Bark/TaskRabbit/Helpling/Handy dependency from 45% to under 12%; (2) deploy AI 24/7 receptionist with DE-postcode-and-engineering-professional-aware qualifying flow plus separate funnels for domestic recurring, June–July University of Derby student EoT, Cathedral Quarter/Pride Park Airbnb turnover, and Rolls-Royce/Toyota/Alstom/UHDB commercial tender — integrated to Jobber/ServiceM8/Service Fusion/Connecteam; (3) build the Rolls-Royce / Toyota / Alstom / Pattonair / JCB Power Systems / UHDB / University of Derby / Derby City Council commercial-tender funnel (CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, BICSc Accredited Trainer, Real Living Wage, aerospace-cleanroom-aware protocols) for £30k–£300k annual contracts vs ISS, Mitie, OCS, Atlas FM, Birkin Group; (4) build a student-letting-agent B2B funnel for the June–July DE22/DE23 EoT peak (Belvoir Derby, Boxall Brown & Jones, Frank Innes, Hunters, Northwood, Foxtons Derby, University of Derby Accommodation); (5) build regional expansion campaigns leveraging no-Derby-CAZ advantage; and (6) drive Google review velocity to 12–20 new reviews per month with DE-postcode-level keyword density plus engineering-professional-trust review prompts.",
};
