import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "cleaning company marketing Cardiff",
    "domestic cleaner marketing Cardiff",
    "end of tenancy cleaning lead generation Cardiff",
    "office cleaning company SEO Cardiff",
    "Cardiff Bay corporate cleaning",
  ],
  secondaryKeywords: [
    "ABC Cleaning Cardiff Maid2Clean Cardiff competitor",
    "Cardiff Bay Mermaid Quay corporate cleaning tender",
    "CF10 CF11 CF14 Cardiff city centre commercial",
    "Pontcanna Llandaff Cyncoed Penylan premium domestic Cardiff",
    "Cardiff University Cardiff Met student EoT CF24 CF14 CF23",
    "Welsh language cleaner marketing west Cardiff Pontcanna",
    "Cardiff no Clean Air Zone advantage",
    "Hafren Hawkins ACS Cardiff letting agent EoT panel",
  ],
  heroSubhead:
    "Cardiff is Wales's capital and largest cleaning market, anchored by the Cardiff Bay corporate corridor (Mermaid Quay, the Welsh Government Senedd, BBC Cymru Wales at Central Square, Admiral Insurance HQ), a 70,000+ student population across Cardiff University and Cardiff Met driving a CF24/CF14/CF23 EoT peak in late June, and uniquely Welsh-language client communications expectations west of the city in Pontcanna, Canton, Treganna and the broader Welsh-speaking Cardiff catchment. Premium domestic catchments in Pontcanna (CF11), Llandaff (CF5), Cyncoed (CF23), Penylan (CF23), Roath Park, Lakeside and Whitchurch (CF14) support £20–£24/hr rates. Cardiff has no Clean Air Zone — a structural cost advantage over Bristol (CAZ live) and Birmingham (CAZ Class D) competitors bidding South Wales/South West work. Named competitors include ABC Cleaning Cardiff, Maid2Clean Cardiff, Bright & Beautiful Cardiff, Molly Maid Cardiff plus ISS, Mitie, OCS commercial giants. Kerblabs builds the Welsh-bilingual, no-CAZ-leveraging marketing system Cardiff independent cleaners (1–25 staff) actually need.",
  marketContext: [
    "Cardiff's cleaning market is shaped by three structural forces unique to Wales's capital. First, the Welsh-language and bilingual customer expectation west of Cathays Park is genuine and underserved. Pontcanna (CF11), Canton (CF11), Treganna, Riverside, parts of Whitchurch and the wider west-Cardiff catchment have meaningful Welsh-speaking populations (around 11% of Cardiff residents speak Welsh per the 2021 Census, with concentrations in west Cardiff substantially higher) and bilingual-friendly customer expectations. Welsh-language Facebook groups (Cymry Caerdydd, Pontcanna Welsh Speakers, Cardiff Welsh Mums), Welsh-medium school networks (Ysgol Treganna, Ysgol Glantaf, Ysgol Plasmawr) and the Welsh Language Commissioner active-offer principles for public-sector contracts mean cleaning operators positioned with genuine Welsh-language competence (Welsh-speaking cleaners on staff, bilingual landing pages, bilingual quote PDFs, Welsh-language WhatsApp Business) hold a meaningful competitive moat in west Cardiff that English-only operators cannot replicate. Second, the Cardiff Bay corporate corridor anchors the commercial cleaning tender pipeline. Mermaid Quay, the Welsh Government Senedd, BBC Cymru Wales at Central Square (the £100m HQ that opened 2020), Admiral Insurance HQ, the Welsh Government's Tŷ Hywel and main offices, plus the wider Cardiff Bay regeneration zone support £30k–£300k annual office-cleaning tender contracts.",
    "Public-sector cleaning frameworks via Sell2Wales (the Welsh Government procurement portal) plus the National Procurement Service (NPS) Wales framework are the dominant tender route, with Welsh-language competence and Welsh Language Standards compliance a meaningful soft-qualifying factor on public-sector contracts. Third, Cardiff has no Clean Air Zone — Cardiff Council reviewed and rejected CAZ implementation, choosing targeted measures instead — giving CF-postcode cleaning operators a structural cost advantage over Bristol (CAZ live since November 2022) and Birmingham (CAZ Class D £8/day) competitors when bidding regional commercial work into the South Wales/South West belt. Cardiff cleaning operators can credibly service Newport (NP postcodes), Bridgend (CF31), Caerphilly (CF83), Pontypridd (CF37), Barry (CF62) and the wider South Wales valleys without the daily fleet overhead competitors carry. Premium Cardiff domestic catchments differ from the student belt: Pontcanna (CF11), Llandaff (CF5), Cyncoed (CF23), Penylan (CF23), Lakeside, Roath Park, Whitchurch (CF14), Rhiwbina (CF14), Cathays Park's professional fringe, plus the wider Vale of Glamorgan commuter belt (Penarth CF64, Dinas Powys CF64) support £20–£24/hr domestic rates with weekly/fortnightly recurring books.",
    "The 70,000+ Cardiff University and Cardiff Met student population drives a late June tenancy-turnover EoT peak across CF24 (Cathays/Roath/Cardiff University core), CF14 (Heath/Birchgrove), CF23 (Penylan/Roath Park), and increasingly CF11 (Riverside/Canton). Volume runs 4–7x normal levels with letting agents (Hafren Property, Hawkins Lettings, ACS Property Cardiff, Belvoir Cardiff, CPS Homes, Northwood Cardiff, Reeds Rains Cardiff) pushing 10–25 EoT jobs per week per branch at £140–£300 per property. Cardiff Google Ads CPCs in cleaning keywords sit toward the lower-mid range — 'cleaner Cardiff' clicks at £1.90–£3.80, 'end of tenancy cleaning Cardiff' at £2.80–£5.50, 'office cleaning Cardiff' at £3.50–£7.50, 'glanhau Caerdydd' (Welsh) at £0.80–£2 (very low competition) across 2024–2025. Postcode-level CPCs are markedly lower — 'cleaner Pontcanna', 'cleaner Cyncoed', 'EoT Cathays' click at £1.30–£2.80. The strategic implication is unambiguous: postcode-stratified Google Ads + Welsh-language Pontcanna/Canton ads + Local Service Ads + Maps optimisation + a Cardiff Bay/Welsh Government commercial-tender funnel + the no-Cardiff-CAZ regional-expansion advantage into Bristol/South West work reliably produces £20–£45 cost-per-acquired-job versus £70–£180 on Bark, MyBuilder, TaskRabbit, Helpling and Handy.",
  ],
  stats: [
    { value: "11%", label: "Cardiff Welsh-language speakers — concentrated west of city in Pontcanna, Canton, Treganna, Riverside", source: "ONS Census 2021" },
    { value: "No CAZ", label: "Cardiff has no Clean Air Zone — structural advantage over Bristol CAZ and Birmingham CAZ Class D for regional work", source: "Cardiff Council" },
    { value: "70,000+", label: "Cardiff student population (Cardiff Uni, Cardiff Met) driving CF24/CF14/CF23 June EoT peak", source: "Universities UK" },
    { value: "£20–£24/hr", label: "Pontcanna, Llandaff, Cyncoed, Penylan, Whitchurch, Rhiwbina premium domestic rate range" },
    { value: "£1.90–£7.50", label: "Cardiff cleaning keyword CPC range — 30–50% below London equivalents", source: "Kerblabs client accounts" },
    { value: "Sell2Wales", label: "primary public-sector procurement portal — Welsh Language Standards compliance soft-qualifying", source: "Welsh Government" },
  ],
  painPoints: [
    {
      title: "Welsh-language west Cardiff catchment lost to bilingual community-network operators",
      body: "Pontcanna, Canton, Treganna, Riverside and the wider west-Cardiff catchment have meaningful Welsh-speaking populations and bilingual customer expectations. Welsh-medium school networks (Ysgol Treganna, Ysgol Glantaf, Ysgol Plasmawr), Welsh-language Facebook groups (Cymry Caerdydd) and Welsh-language WhatsApp networks reach catchments that English-only operators cannot. We build genuine Welsh-language positioning — bilingual landing pages, Welsh-speaking cleaners on staff with named profiles, bilingual quote PDFs, Welsh-language WhatsApp Business, structured outreach to Welsh-medium school newsletters and Cymry Caerdydd community networks — opening 30–60 new west-Cardiff Welsh-speaking domestic accounts in 6 months."
    },
    {
      title: "Cardiff Bay, Welsh Government and BBC Cymru Wales tenders won by ISS, Mitie, OCS by default",
      body: "Cardiff Bay (Mermaid Quay, the Welsh Government Senedd, Tŷ Hywel, BBC Cymru Wales Central Square, Admiral Insurance HQ) plus the wider Cardiff city-centre commercial corridor anchors the regional cleaning-tender pipeline at £30k–£300k annual contracts. Public-sector cleaning frameworks via Sell2Wales and NPS Wales weight Welsh Language Standards compliance as a soft-qualifying factor. Without CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, BICSc Accredited Trainer status, Living Wage employer registration, Welsh Language Standards compliance and structured tender-portal monitoring, independents are invisible to ISS, Mitie, OCS, Atlas FM, Nviro and Bidvest Noonan."
    },
    {
      title: "No-Cardiff-CAZ regional advantage unmarketed — Bristol/South West/Newport work going elsewhere",
      body: "Cardiff's no-CAZ position is a structural advantage over Bristol (CAZ live since November 2022) and Birmingham (CAZ Class D £8/day) competitors. CF-postcode cleaning operators can credibly service Newport (NP), Bridgend (CF31), Barry (CF62), Caerphilly (CF83), Pontypridd (CF37) and increasingly Bristol BS-postcode commercial work without the daily fleet overhead competitors carry. Most Cardiff cleaning operators don't market this regional reach. We build dedicated regional landing pages with explicit competitive-pricing-without-CAZ-overhead messaging."
    },
    {
      title: "CF24/CF14/CF23 June student EoT peak unmanaged — Cardiff Uni/Cardiff Met volume going elsewhere",
      body: "Cardiff's 70,000+ student population drives a late June tenancy-turnover EoT peak across CF24 (Cathays/Roath/Cardiff University core), CF14 (Heath/Birchgrove), CF23 (Penylan/Roath Park) and CF11 (Riverside/Canton). Volume runs 4–7x normal levels with letting agents (Hafren Property, Hawkins Lettings, ACS Property Cardiff, Belvoir Cardiff, CPS Homes, Northwood Cardiff, Reeds Rains Cardiff) pushing 10–25 EoT jobs per week per branch at £140–£300 per property. Most independent Cardiff cleaners turn away the work or melt operationally. We build dedicated June capacity-planning campaigns with seasonal pricing, student-letting-agent B2B outreach, and staff-rota surge planning via Connecteam/Deputy."
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat ABC Cleaning Cardiff, Maid2Clean Cardiff, Molly Maid Cardiff, Bright & Beautiful Cardiff and the Bark/TaskRabbit aggregators in Cardiff specifically?",
      a: "Three-phase Cardiff-specific playbook. Phase one: Google Business Profile category stacking (House Cleaning Service + Commercial Cleaning Service + Carpet Cleaning Service + Window Cleaning Service + Janitorial Service) with postcode-level service-area definition, BICSc and CHSA membership schema, DBS-vetting credential schema, Welsh Language Standards compliance schema, no-Cardiff-CAZ-fleet-cost-advantage messaging, and structured review campaigns targeting 8–14 new reviews per month with named area keywords (Pontcanna, Canton, Llandaff, Cyncoed, Penylan, Roath Park, Whitchurch, Rhiwbina, Cathays). Phase two: Google Local Service Ads with the Google Guaranteed badge — on Cardiff cleaning keywords this consistently lands at £20–£45 cost-per-acquired-job versus £70–£180 on Bark, TaskRabbit, Helpling and Handy. Phase three: postcode-stratified Google Ads with separate campaigns per area (CF10/CF11 city centre/Cardiff Bay commercial, CF11 Pontcanna/Canton bilingual, CF5 Llandaff premium, CF23 Cyncoed/Penylan/Roath Park premium, CF14 Whitchurch/Rhiwbina/Heath, CF24 Cathays student with June peak loading), plus Welsh-language Pontcanna/Canton/Treganna campaigns, a Cardiff Bay/Welsh Government commercial-tender funnel via Sell2Wales/NPS Wales, and regional expansion into Bristol/Newport/South Wales valleys leveraging the no-CAZ advantage."
    },
    {
      q: "How do we capture the Welsh-language west Cardiff market in Pontcanna, Canton, Treganna and Riverside?",
      a: "Cardiff's Welsh-language and bilingual market is one of the most underused niche advantages in UK cleaning marketing. We build a five-component approach: (1) genuine Welsh-language operational competence — recruit and retain 2–4 Welsh-speaking cleaners on staff with named profile pages, Welsh-language reviews, and Welsh-language WhatsApp Business contact; (2) bilingual landing pages — full Welsh translations of every key landing page with hreflang tags, Welsh quote PDFs, Welsh-language Facebook ad campaigns; (3) Welsh-medium school newsletter advertising — Ysgol Treganna, Ysgol Glantaf, Ysgol Plasmawr, Ysgol Mynydd Bychan parent newsletters and PTA networks reach the highest-density Welsh-speaking household catchment; (4) structured outreach to Welsh-language community networks — Cymry Caerdydd, Pontcanna Welsh Speakers, Welsh-medium church communities (Eglwys Dewi Sant), Welsh-language WhatsApp groups; (5) Welsh Language Standards compliance documentation for public-sector tender qualification. Cardiff cleaning clients running this typically open 30–60 new west-Cardiff Welsh-speaking domestic accounts in 6 months at premium £20–£24/hr rates."
    },
    {
      q: "How do we land Cardiff Bay, Welsh Government, BBC Cymru Wales and Admiral Insurance commercial cleaning tenders against ISS, Mitie, OCS?",
      a: "Cardiff commercial cleaning tenders are won on accreditation depth, named-account case studies, Welsh Language Standards compliance and Sell2Wales/NPS Wales procurement-portal visibility. We build the accreditation infrastructure (CHAS Premium Plus, Constructionline Gold, SafeContractor, ISO 9001/14001/45001, BICSc Accredited Trainer, Living Wage employer registration, COSHH compliance, public liability £10M, employer's liability, Welsh Language Standards compliance documentation, B Corp pursuit) and run structured outreach to: (1) Cardiff Bay property managers (Mermaid Quay management, Cardiff Council via Sell2Wales); (2) Welsh Government direct procurement (Senedd, Tŷ Hywel, Cathays Park main offices); (3) BBC Cymru Wales Central Square (BBC procurement); (4) Admiral Insurance HQ; (5) Cardiff & Vale University Health Board (NHS Wales) framework agreements via NPS Wales; (6) Cardiff Council frameworks via Sell2Wales; (7) Cardiff University, Cardiff Met procurement teams. Cardiff cleaning clients with the right accreditation stack and Welsh Language Standards compliance typically open 2–5 tender opportunities within 6–9 months at £30k–£300k annual contract values."
    },
    {
      q: "Can the AI receptionist handle bilingual Welsh/English enquiries and the difference between an £18/hr Ely domestic regular, a £200 Cathays student EoT, a £25/hr Pontcanna Welsh-speaking premium recurring and a £150k Cardiff Bay office tender?",
      a: "Yes — and the AI receptionist supports Welsh and English with automatic language detection, switching between languages mid-call as needed (a common Welsh-bilingual pattern). The qualifying flow includes Cardiff-postcode awareness in the first three questions: which postcode is the property in (the receptionist explicitly confirms CF-postcode because pricing, drive-time and competitive set differ — CF10/CF11 city centre/Cardiff Bay vs CF5/CF23 premium domestic vs CF24 student vs CF14 mid-market vs CF62/CF64 Vale of Glamorgan); is this a domestic recurring/one-off, a student/end-of-tenancy, or a commercial enquiry; and what's the language preference (Welsh/English/bilingual). Domestic regulars trigger banded hourly quoting against your area rate card with DBS-vetted, language-matched cleaner allocation. Student EoT triggers June Cardiff Uni/Cardiff Met letting-agent-aware flow with deposit-return wording aligned to TDS, mydeposits and DPS. Commercial enquiries trigger 30-minute on-site survey appointment with accreditation pre-screening (CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, Living Wage, Welsh Language Standards) and tender-document handover. Every call recorded and pushed into Jobber, ServiceM8 or Service Fusion."
    },
  ],
  approach:
    "For Cardiff cleaning firms, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + postcode-stratified Google Ads + Welsh-language Pontcanna/Canton ads + Maps optimisation + named-cleaner DBS-profile pages + regional campaigns leveraging no-Cardiff-CAZ advantage into Bristol BS/Newport NP/South Wales valleys) to reduce Bark/TaskRabbit/Helpling/Handy dependency from 40% to under 10%; (2) deploy bilingual Welsh/English AI 24/7 receptionist with CF-postcode-aware qualifying flow plus separate funnels for domestic recurring, June Cardiff Uni/Cardiff Met student EoT, and Cardiff Bay/Welsh Government commercial tender — integrated to Jobber/ServiceM8/Service Fusion/Connecteam; (3) build the Welsh-language west Cardiff funnel with Welsh-speaking cleaners on staff, bilingual landing pages, Welsh-medium school newsletter advertising and Welsh-language community network outreach; (4) build commercial-tender accreditation funnel (CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, BICSc Accredited Trainer, Living Wage, Welsh Language Standards compliance) for Cardiff Bay/Welsh Government/BBC/Admiral contracts via Sell2Wales/NPS Wales vs ISS, Mitie, OCS, Atlas FM, Birkin Group; (5) build a student-letting-agent B2B funnel for the June CF24/CF14/CF23 EoT peak (Hafren Property, Hawkins Lettings, ACS Property Cardiff, Belvoir, CPS Homes, Northwood, Reeds Rains); and (6) drive Google review velocity to 8–14 new reviews per month with postcode-level keyword density.",
};
