import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "cleaning company marketing Manchester",
    "domestic cleaner marketing Manchester",
    "end of tenancy cleaning lead generation Manchester",
    "office cleaning company SEO Manchester",
    "Airbnb cleaning Manchester marketing",
  ],
  secondaryKeywords: [
    "SuperClean Manchester Maid2Clean competitor",
    "Spinningfields office cleaning tender Manchester",
    "Northern Quarter Ancoats Airbnb turnover cleaner",
    "Didsbury Hale Altrincham premium domestic cleaning",
    "MediaCity Salford Quays commercial cleaning",
    "M14 M19 M20 M21 student EoT cleaning Manchester",
    "no Manchester ULEZ cleaning van advantage 2024",
    "Trafford Stockport Bury Bolton domestic cleaning marketing",
  ],
  heroSubhead:
    "Manchester's cleaning market is uniquely shaped by its ten-borough Greater Manchester geography, the post-2024 Manchester ULEZ scrap (giving M-postcode cleaning vans a structural cost advantage over Birmingham, Bradford and London competitors), the Northern Quarter and Ancoats Airbnb turnover boom, the Spinningfields/MediaCity/NOMA office-cleaning tender pipeline, and the M14–M21 student-rental EoT volume that peaks in late August through September across Rusholme, Fallowfield, Withington and Chorlton. Premium catchments in Didsbury, Hale, Altrincham, Bowdon and Wilmslow support £22–£28/hr domestic rates, while SuperClean Manchester, Maid2Clean Manchester, Molly Maid Trafford, Time For You franchises and ISS/Mitie/Birkin commercial giants squeeze independents on every front. Kerblabs builds the borough-stratified marketing system Greater Manchester independent cleaners (1–25 staff) actually need.",
  marketContext: [
    "Manchester's cleaning market is shaped by three structural forces unique to Greater Manchester. First, the ten-borough geography genuinely matters. Manchester (city), Salford, Trafford, Stockport, Tameside, Oldham, Rochdale, Bury, Bolton and Wigan each behave as distinct competitive markets with their own customer mental maps and three-pack dynamics. A Didsbury domestic cleaning customer rarely calls a Bolton operator; an Altrincham Cheshire-edge customer's competitive set is different from a Stockport town centre customer's. Single-Manchester-campaign marketing wastes 25–40% of every pound versus borough-stratified structure. Second, the post-2024 Manchester ULEZ scrap is now a real competitive advantage. Greater Manchester's Clean Air Zone proposals were rejected and replaced with targeted measures, meaning M-postcode cleaning vans avoid the £8/day Birmingham CAZ Class D, the £12.50 London ULEZ daily charge, and the Bradford/Bristol equivalents — giving Manchester operators a structural cost advantage when bidding regional commercial work into Cheshire (CW, SK), Lancashire (BB, PR), Liverpool (L), and the broader North West.",
    "Third, the Manchester student-rental EoT peak is unusually concentrated. The University of Manchester, Manchester Metropolitan, RNCM and Salford University collectively house around 100,000+ students with peak tenancy-end dates clustering across M14 (Rusholme), M15 (Hulme), M19 (Levenshulme), M20 (Withington), M21 (Chorlton) and parts of Salford in late August and September. EoT volume in this window runs at 4–8x normal levels, with letting agents (Manchester Student Homes, Castledene, Sugarhouse, Burnetts, Belvoir Manchester, Northwood) pushing 15–40 EoT jobs per week per branch at £140–£320 per property. Premium catchments differ entirely: Didsbury (M20), Chorlton (M21), Sale (M33), Altrincham/Hale (WA14/WA15), Bowdon, Wilmslow (SK9), Bramhall (SK7), Heaton Moor (SK4) support £22–£28/hr domestic rates with weekly/fortnightly recurring books filling within weeks. Spinningfields, MediaCity, NOMA, Allied London's St John's, and the Ancoats/New Islington commercial corridor support office cleaning tenders at £30k–£250k annual contract values, with named competitors SuperClean Manchester, Bright & Beautiful Manchester, Maid2Clean Manchester, Molly Maid Trafford, plus commercial giants ISS, Mitie, OCS, Atlas FM, Birkin Group and Nviro dominating the office-cleaning tender shortlists.",
    "Manchester Google Ads CPCs in cleaning keywords sit toward the upper-mid range of UK regional CPCs. 'Cleaner Manchester' clicks at £2.40–£4.80, 'end of tenancy cleaning Manchester' at £3.50–£7, 'office cleaning Manchester' at £4–£9, 'Airbnb cleaning Manchester' at £2.50–£5 across 2024–2025. Borough-level CPCs are markedly lower — 'cleaner Didsbury', 'EoT Fallowfield', 'office cleaner Stockport' click at £1.50–£3.20. The strategic implication is that ten-borough-stratified Google Ads (separate campaigns per relevant borough — central Manchester M1–M4, Didsbury M20, Chorlton M21, Salford M3/M5/M6, MediaCity, Trafford, Stockport, Altrincham WA14/WA15) plus Local Service Ads + Maps optimisation + a Northern-Quarter Airbnb host funnel + a structured letting-agent panel B2B funnel + a Spinningfields/MediaCity commercial-tender funnel + the no-Manchester-ULEZ regional-expansion advantage reliably produces £25–£55 cost-per-acquired-job versus £80–£200 on Bark, MyBuilder, TaskRabbit, Helpling and Handy. Kerblabs' Manchester cleaning clients running this stack typically reach 25–60 booked recurring weekly slots per cleaner and 8–18 letting-agent EoT jobs per week per branch relationship inside 6 months.",
  ],
  stats: [
    { value: "10 boroughs", label: "Greater Manchester — Manchester, Salford, Trafford, Stockport, Tameside, Oldham, Rochdale, Bury, Bolton, Wigan", source: "Greater Manchester Combined Authority" },
    { value: "No CAZ", label: "Manchester ULEZ scrapped 2024 — no daily charge for cleaning vans, structural regional advantage", source: "Greater Manchester Authority" },
    { value: "£22–£28/hr", label: "Didsbury, Chorlton, Hale, Altrincham, Wilmslow premium domestic cleaning rate range" },
    { value: "100,000+", label: "Manchester student population driving M14–M21 August–September EoT peak", source: "University of Manchester / MMU" },
    { value: "£2.40–£9", label: "Manchester cleaning keyword CPC range — 30–50% below London equivalents", source: "Kerblabs client accounts" },
    { value: "15–40/week", label: "EoT jobs per branch through Manchester student letting-agent panels in August–September peak" },
  ],
  painPoints: [
    {
      title: "Single-Manchester campaign wasting 25–40% of marketing budget on wrong-borough traffic",
      body: "Generic 'Manchester cleaning' Google Ads campaigns pull cross-borough traffic that doesn't convert because Didsbury customers don't call Bolton operators and Altrincham customers don't call Tameside operators. Greater Manchester's ten boroughs each behave as a separate competitive market. We rebuild marketing as ten separate borough-level campaigns with dedicated landing pages, separate ad groups, borough-specific GBP service-area signals — plus separate premium-catchment campaigns for Didsbury, Chorlton, Hale, Altrincham, Wilmslow, Bramhall and Heaton Moor. This typically cuts cost-per-lead by 25–40% versus single-Manchester campaigns."
    },
    {
      title: "M14–M21 student EoT peak unmanaged — capacity collapses or revenue leaks",
      body: "August and September student tenancy turnover across Rusholme, Fallowfield, Withington, Chorlton, Hulme and parts of Salford runs at 4–8x normal EoT volumes. Most independent Manchester cleaners either turn away work (capacity collapse) or try to handle it the same way they handle the rest of the year (operational chaos and deposit-return failures). We build dedicated August–September capacity-planning campaigns with seasonal pricing, student-letting-agent B2B outreach (Manchester Student Homes, Castledene, Sugarhouse, Burnetts, Belvoir Manchester, Northwood), staff-rota surge planning via Connecteam/Deputy, and pre-July recurring-customer holiday-cover offers."
    },
    {
      title: "No-Manchester-ULEZ regional advantage unmarketed — Cheshire/Lancashire/Liverpool work elsewhere",
      body: "Manchester's post-2024 no-CAZ position is a structural advantage: M-postcode cleaning operators can credibly service Cheshire (CW, SK postcodes), Lancashire (BB, PR), Merseyside (L postcodes — Liverpool has no CAZ either), and Stoke (ST) without the daily fleet overhead competitors carry. Most Manchester cleaning operators don't market this regional reach at all. We build dedicated regional landing pages with explicit competitive-pricing-without-CAZ-overhead messaging targeting Cheshire commuter belt, Liverpool L-postcode commercial work, and Lancashire premium-catchment domestic enquiries."
    },
    {
      title: "Spinningfields, MediaCity, NOMA office-cleaning tenders won by ISS, Mitie, Birkin by default",
      body: "Manchester's commercial cleaning tender pipeline is concentrated across Spinningfields (Allied London), MediaCity Salford Quays, NOMA, Ancoats/New Islington, Circle Square, Manchester Science Park and Trafford Park. Annual office-cleaning contracts run £30k–£250k typically, plus Hospital Trust, NHS Greater Manchester Mental Health, Manchester City Council and university (University of Manchester, MMU, Salford) framework agreements. Without CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, BICSc Accredited Trainer status, Living Wage employer registration and structured tender-portal monitoring (Contracts Finder, Find a Tender, ProContract, The Chest), independent cleaners are invisible to ISS, Mitie, OCS, Atlas FM, Nviro, Birkin Group and Bidvest Noonan."
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat Molly Maid, Maid2Clean Manchester, SuperClean Manchester, Time For You franchises and the Bark/TaskRabbit aggregators in Manchester specifically?",
      a: "Three-phase Manchester-specific playbook. Phase one: Google Business Profile category stacking (House Cleaning Service + Commercial Cleaning Service + Carpet Cleaning Service + Window Cleaning Service + Janitorial Service) with ten-borough service-area definition, BICSc and CHSA membership schema, DBS-vetting credential schema, and structured review campaigns targeting 10–18 new reviews per month with named borough keywords (Didsbury, Chorlton, Sale, Altrincham, Hale, Salford, Stockport, Trafford, Bolton, Bury). Phase two: Google Local Service Ads with the Google Guaranteed badge — on Manchester cleaning keywords this consistently lands at £25–£55 cost-per-acquired-job versus £80–£200 on Bark, TaskRabbit, Helpling and Handy. Phase three: ten-borough-stratified Google Ads with separate campaigns per relevant borough, plus a student-letting-agent B2B funnel for the August–September EoT peak (Manchester Student Homes, Castledene, Sugarhouse, Burnetts), a Spinningfields/MediaCity/NOMA commercial-tender funnel, an Ancoats/Northern Quarter Airbnb host funnel, and regional expansion campaigns leveraging the no-Manchester-CAZ advantage into Cheshire, Liverpool and Lancashire. Manchester cleaning clients typically reduce aggregator dependency from 45% to 12% inside 6 months while growing total job volume 35–55%."
    },
    {
      q: "How do we capture the M14–M21 student tenancy-turnover EoT volume in August and September without breaking operationally?",
      a: "The Manchester student EoT peak is the biggest concentrated cleaning revenue opportunity in the North West, and most independents either turn away the work or melt down trying to handle it. We build a four-component approach: (1) seasonal capacity planning starting in May — surge staffing through Connecteam or Deputy, agency-cleaner overflow agreements with vetted partners, fixed-fee subcontracting for the peak two weeks; (2) student-letting-agent B2B outreach to Manchester Student Homes, Castledene, Sugarhouse, Burnetts, Belvoir Manchester, Northwood Manchester, Reeds Rains Manchester, plus university-managed accommodation services (University of Manchester, MMU, Salford); (3) dedicated August–September landing pages with student-EoT-specific pricing (£140–£320 per property, deposit-return-guarantee, oven/external-window add-ons, 24-hour turnaround SLA aligned to TDS/mydeposits/DPS reporting); (4) pre-July recurring-customer messaging to manage expectations on holiday cover and capacity. Manchester clients running this typically book 60–150 student EoT jobs across the August–September window at average £230 per job, generating £14k–£35k peak-season revenue on top of normal trading."
    },
    {
      q: "Can the AI receptionist handle the difference between a £20/hr Wigan domestic regular, a £180 Fallowfield student EoT, a £75 Northern Quarter Airbnb turnover and a £75k Spinningfields office tender?",
      a: "Yes — and it includes ten-borough awareness in the qualifying flow. The first three questions are: which borough/postcode area is the property in (the receptionist explicitly confirms M-postcode, WA14/WA15 Altrincham/Hale, SK Stockport/Wilmslow, BL Bolton, BB Bury, OL Oldham, OL Rochdale, WN Wigan because pricing, drive-time and competitive set differ per borough); is this a domestic recurring/one-off, a student/end-of-tenancy, an Airbnb turnover or a commercial enquiry; and what's the urgency. Domestic regulars trigger banded hourly quoting against your borough rate card with DBS-vetted cleaner allocation, key-holding insurance offer, and weekly/fortnightly recurring offer. Student EoT triggers M14–M21 student-letting-agent-aware flow with TDS/mydeposits/DPS deposit-return wording, photographic evidence, and 24-hour turnaround SLA. Airbnb turnover triggers Northern Quarter/Ancoats/Castlefield/Salford Quays same-day window confirmation, linen/laundry add-on, and host monthly retainer offer. Commercial enquiries trigger 30-minute on-site survey appointment with the qualifying procurement contact, accreditation pre-screening (CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, Living Wage), and tender-document handover. Every call is recorded and pushed into Jobber, ServiceM8, Service Fusion or Workiz."
    },
    {
      q: "Can Kerblabs help us land Spinningfields, MediaCity, NOMA and Manchester university commercial cleaning tenders against ISS, Mitie, OCS and Birkin?",
      a: "Yes — but the playbook is structurally different from domestic marketing. Manchester commercial cleaning tenders are won on accreditation depth, named-account case studies and procurement-portal visibility, not Google Ads. We build the accreditation infrastructure (CHAS Premium Plus, Constructionline Gold, SafeContractor, ISO 9001/14001/45001, BICSc Accredited Trainer status, Living Wage employer registration, COSHH compliance documentation, public liability £10M, employer's liability, B Corp pursuit where green positioning matters) and run structured outreach to: (1) Spinningfields property managers (Allied London, Bruntwood Works); (2) MediaCity tenants directly (BBC, ITV, dock10, Kellogg's, Ericsson) plus Peel L&P managing the estate; (3) NOMA, Ancoats and New Islington commercial property managers; (4) Manchester City Council framework agreements via The Chest portal and Manchester procurement; (5) NHS Greater Manchester Mental Health Trust, MFT (Manchester Foundation Trust) framework agreements; (6) University of Manchester, MMU and Salford procurement teams. Manchester cleaning clients with the right accreditation stack typically open 2–5 tender opportunities within 6–9 months at £30k–£250k annual contract values."
    },
  ],
  approach:
    "For Manchester cleaning firms, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + ten-borough-stratified Google Ads + Maps optimisation + named-cleaner DBS-profile pages + regional campaigns leveraging no-Manchester-CAZ advantage into Cheshire/Liverpool/Lancashire) to reduce Bark/TaskRabbit/Helpling/Handy dependency from 45% to under 12%; (2) deploy AI 24/7 receptionist with ten-borough-aware qualifying flow plus separate funnels for domestic recurring, student EoT M14–M21, Northern Quarter/Ancoats/MediaCity Airbnb turnover, and Spinningfields/NOMA commercial tender — integrated to Jobber/ServiceM8/Service Fusion/Connecteam; (3) build a student-letting-agent B2B funnel for the August–September M14–M21 EoT peak (Manchester Student Homes, Castledene, Sugarhouse, Burnetts, Belvoir Manchester, Northwood) with seasonal capacity planning; (4) build commercial-tender accreditation funnel (CHAS Premium Plus, Constructionline Gold, ISO 9001/14001/45001, BICSc Accredited Trainer, Living Wage) for Spinningfields/MediaCity/NOMA/Manchester university contracts vs ISS, Mitie, OCS, Atlas FM, Birkin Group; (5) build Airbnb host outreach across Northern Quarter, Ancoats, Castlefield, Salford Quays, Deansgate Square; and (6) drive Google review velocity to 10–18 new reviews per month with borough-level keyword density.",
};
