import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "fencing contractor marketing Edinburgh",
    "Edinburgh fencing lead generation",
    "heritage iron railings Edinburgh",
    "Edinburgh Fencing Services marketing",
    "Heritage Iron Railings Edinburgh",
  ],
  secondaryKeywords: [
    "New Town Listed Building Consent fencing",
    "Georgian railings replacement Edinburgh",
    "Stockbridge Bruntsfield Morningside premium fencing",
    "automated gate installation Edinburgh",
    "Festival season storm response Edinburgh",
    "Edinburgh LEZ fencing van compliance",
    "Murrayfield Cramond automated gate",
    "EH3 EH9 EH10 conservation area fencing",
  ],
  heroSubhead:
    "Edinburgh is the UK's most heritage-encumbered fencing market outside central London. The New Town World Heritage Site (UNESCO inscribed 1995, covering most of EH1, EH2 and EH3) plus the Old Town WHS produce one of the strictest planning regimes in Britain — Listed Building Consent applies to enormous swathes of street frontage, original Georgian wrought-iron railings on Charlotte Square, Heriot Row, Moray Place, Great King Street and the wider New Town are individually listed Grade A and Grade B-listed, and replacement requires formal consent plus traditional sand-cast specifications sourced from named heritage foundries. Edinburgh Fencing Services and Heritage Iron Railings-tier specialists win by understanding the Listed Building Consent process, financial-services corporate-relocation premium across Stockbridge, Bruntsfield and Morningside, the Edinburgh LEZ (operational June 2024), and the Festival-season operational reality. Kerblabs is purpose-built for it.",
  marketContext: [
    "Edinburgh's fencing market is shaped by the most restrictive planning regime of any UK fencing catchment outside central London. The New Town World Heritage Site (UNESCO inscribed 1995) covers most of EH1, EH2, EH3 and parts of EH4 and EH7, with virtually every Georgian and Regency street-frontage carrying Listed Building Consent at Grade A, Grade B or Grade C(s) level. Original wrought-iron railings on Charlotte Square (the Robert Adam-designed centrepiece of the New Town), Heriot Row, Moray Place, Great King Street, Drummond Place, Royal Circus, Ann Street and the wider New Town stock are protected at street frontage and require formal Listed Building Consent applications to the City of Edinburgh Council Planning service for replacement work. The conservation officer pre-application consultation process typically runs 6–14 weeks before any work can commence, and replacement materials must match original sand-cast wrought-iron specifications — frequently sourced from Ballantine Bo'ness foundry (the historic Falkirk-area ironworks specialising in Edinburgh New Town heritage replacements), Britannia Architectural in Plymouth, or specialist Edinburgh-based heritage metalworkers (J & A Fraser at Bonnyrigg, Mackenzie Decorative Iron). Project values are exceptional: a typical New Town heritage railings replacement on a Grade B-listed terrace runs £8,500–£25,000 with full Listed Building Consent process, and full Charlotte Square or Moray Place restoration projects routinely cross £35,000–£90,000 once heritage stone repointing, original ironwork restoration, and full perimeter reinstatement are factored in. The Old Town WHS (Royal Mile, Grassmarket, Cowgate, Canongate) carries similar but distinct restrictions, with stone-and-iron blended boundary work the dominant specialism.",
    "Edinburgh's premium fencing catchment beyond the WHS New Town and Old Town is concentrated along the Stockbridge / Comely Bank, Bruntsfield / Morningside / Merchiston, Murrayfield / Ravelston, Cramond / Barnton and Trinity / Inverleith corridors. These EH3, EH4, EH9, EH10 and EH12 catchments host Edinburgh's highest concentration of financial-services and legal-professional households — Royal Bank of Scotland (NatWest Group), Standard Life Aberdeen, Baillie Gifford, Aegon, Scottish Widows, Brodies, Shepherd and Wedderburn, Dickson Minto and the wider £800B+ assets-under-management financial-services base — with corporate-relocation programmes producing £4,500–£28,000 hardwood-gate, automated-system and ornamental-ironwork project values. The pool of Edinburgh contractors capable of delivering automated-gate work (PSA TR1+/TR2 logbook competent, BFT/FAAC/CAME/Nice motor certified, Machinery Directive 2006/42/EC Force-Test compliant) plus heritage-iron-railings specialism with Listed Building Consent process competence is genuinely small — fewer than 12 firms across the entire Edinburgh catchment — and most bury one or both capabilities on a generic services page. Edinburgh's LEZ went operational on 1 June 2024 covering the city centre EH1, EH2, EH3 zone, charging £60 per breach (escalating to £480 for repeat offenders), making Euro 6 fleet compliance a non-negotiable for any operator working inner-city heritage, automated-gate or commercial palisade jobs. Operators with non-compliant vans now retreat to EH9 / EH10 Bruntsfield-Morningside, EH7 Leith and EH15 Portobello peripheral work.",
    "Edinburgh's commercial fencing demand is the strongest in Scotland and sits inside an unusually heritage-aware procurement pipeline. The Scottish Parliament estate at Holyrood, Royal Botanic Garden Edinburgh perimeter, Edinburgh Castle and Crown Estate Scotland sites, NHS Lothian estate (Royal Infirmary of Edinburgh, Western General, Royal Hospital for Children and Young People, Astley Ainslie), the Universities of Edinburgh, Heriot-Watt and Edinburgh Napier estate, City of Edinburgh Council schools and the Edinburgh tourism estate (Edinburgh Festival venues, Edinburgh Zoo, Royal Highland Centre at Ingliston) all source palisade, weldmesh, Heras-hire and security-perimeter through CHAS, Constructionline and Achilles SafeContractor accredited contractors via Public Contracts Scotland (PCS-Tender). Most Edinburgh fencing firms with the skillset don't pursue commercial work because their websites don't surface accreditations and they've never built a B2B funnel. Combined with Storm Babet (Oct 2023) which hit Edinburgh and the Lothians hard, Storm Isha + Storm Jocelyn (back-to-back, Jan 2024) producing exceptional EH-postcode fence collapse, the Festival-season operational reality (extreme August demand on the Old Town and New Town WHS, plus Royal Edinburgh Military Tattoo perimeter security at Edinburgh Castle Esplanade), and the structural reality that Glasgow-based competitors don't understand New Town Listed Building Consent process, Edinburgh fencing contractors running Kerblabs reach £55–£115 cost-per-acquired-job vs £180–£320 on Bark, MyBuilder and Checkatrade with average job values 35–55% above the Edinburgh market median.",
  ],
  stats: [
    { value: "514,000", label: "Edinburgh city population — Scotland's premium fencing market", source: "NRS 2023 estimate" },
    { value: "£8,500–£90,000", label: "New Town WHS Listed Building Consent heritage railings restoration project range" },
    { value: "£60", label: "Edinburgh LEZ penalty per breach (escalating to £480 repeat) — operational since 1 June 2024", source: "City of Edinburgh Council LEZ" },
    { value: "£800B+", label: "Edinburgh financial-services assets under management driving Stockbridge / Bruntsfield / Morningside corporate-relocation premium", source: "TheCityUK / Scottish Financial Enterprise" },
    { value: "1995", label: "New Town and Old Town UNESCO World Heritage Site inscription — Listed Building Consent across most EH1–EH4 street frontage" },
    { value: "EH1–EH17", label: "Edinburgh postcode coverage with district-stratified marketing approach" },
  ],
  painPoints: [
    {
      title: "Listed Building Consent and conservation-area planning paralysis killing 35%+ of New Town quote pipeline",
      body: "Around 35% of New Town, Old Town, Stockbridge and Bruntsfield fencing enquiries come from homeowners who don't yet realise their property requires Listed Building Consent at Grade A, Grade B or Grade C(s) level for street-frontage railings or gate replacement. Without pre-qualifying, your surveyor wastes an afternoon on a property that can't progress for 6–14 weeks pending consent, and the customer often vanishes during the wait. AI receptionist with conservation-status qualifying flow ('is your property listed Grade A, B or C(s)? in the New Town or Old Town WHS? have you spoken to City of Edinburgh Council planning portal?') filters this at first contact, frees 8–14 hours/week of surveyor time, and routes viable enquiries to the heritage-iron-railings premium funnel.",
    },
    {
      title: "Heritage iron railings premium specialism completely under-marketed despite Edinburgh's Britain-leading concentration",
      body: "Wrought-iron railings work on New Town Grade A and Grade B-listed Georgian and Regency stock is high-margin specialist work earning 40–60% gross margin vs 18–25% on retail closeboard. Project values £8,500–£90,000 per property. But most Edinburgh heritage-capable contractors have generic websites with stock photos saying nothing about Ballantine Bo'ness foundry, Britannia Architectural or J & A Fraser at Bonnyrigg sourcing, traditional sand-cast wrought-iron versus modern fabricated ironwork choice, or City of Edinburgh Council conservation officer pre-application process. We rebuild around named heritage case studies (Charlotte Square, Heriot Row, Moray Place, Great King Street, Drummond Place completions, named conservation officers signing off), making the firm visible to Knight Frank, Savills, Rettie & Co, Coulters, Lindsays and Murray Beith Murray New Town estate-agency referral networks plus heritage architects and Listed Building consultants.",
    },
    {
      title: "LEZ-compliant fleet investment with no marketing payoff — Glasgow undercutters now blocked from inner Edinburgh work",
      body: "Edinburgh LEZ (operational 1 June 2024) charges £60 per breach (escalating to £480 for repeat) for non-Euro 6 vans entering EH1, EH2, EH3 and the city centre zone. Compliant operators have absorbed £18,000–£42,000 per-van upgrade cost but rarely surface it in marketing. Glasgow-based undercutters and Lothian-fringe non-compliant operators can no longer service inner-Edinburgh work profitably. We put LEZ-compliant Euro 6 fleet, Edinburgh LEZ check-tool screenshots and named EH1–EH3 completed jobs into landing pages, GBP posts and quote PDFs, capturing the inner-Edinburgh heritage and corporate-relocation work non-compliant operators are pricing themselves out of.",
    },
    {
      title: "Storm Babet, Isha, Jocelyn revenue spike captured reactively — Festival-season operational complexity ignored",
      body: "Storm Babet (Oct 2023) hit Edinburgh and the Lothians with widespread fence damage; Storm Isha + Jocelyn (Jan 2024) produced exceptional EH-postcode fence collapse. Edinburgh crews fielded combined hundreds of calls and missed 60–80%. Pre-built storm-response landing pages live and ranked from September each year, AI receptionist surge capacity, and pre-loaded Meta / Google Ads creative ready to switch within 2 hours of a Met Office named-storm announcement converts the storm window from chaos into 50–110 captured enquiries per event. Festival-season (August) operational reality also matters: Royal Edinburgh Military Tattoo perimeter security, Edinburgh Festival Fringe venue safety fencing, and the seasonal restriction on Old Town WHS works during major events all shape marketing copy.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat Checkatrade, MyBuilder, Jacksons-network installers and Glasgow-based competitors in Edinburgh specifically?",
      a: "Three-phase Edinburgh-specific playbook. Phase one: Google Business Profile category stacking (Fence Contractor + Fencing Supplier + Gate + Driveway gate installer + Aluminium and steel fence installer) with EH-postcode service-area definition, AFI/FISS schema, BFT/FAAC/CAME/Nice automated-gate certification surfaced in markup, Listed Building Consent and heritage-iron-railings specialism schema, LEZ-compliant Euro 6 fleet schema, and structured review campaigns targeting 8–15 new reviews per month with named EH-postcode and area keywords (New Town, Old Town, Stockbridge, Bruntsfield, Morningside, Murrayfield, Cramond, Trinity, Leith, Portobello). Phase two: Google Local Service Ads with the Google Guaranteed badge — on Edinburgh fencing keywords this consistently lands at £55–£115 cost-per-job versus £180–£320 on Bark and MyBuilder. Phase three: EH-district-stratified Google Ads (separate campaigns for EH1/EH2/EH3 New Town heritage-premium LEZ-aware, EH4 Stockbridge/Comely Bank, EH9/EH10 Bruntsfield/Morningside premium, EH12 Murrayfield/Ravelston, EH4 Cramond/Barnton, EH7 Leith, EH15 Portobello) with budgets sized to each district's CPC, plus a dedicated Heritage Iron Railings microsite, plus a separate automated-gate microsite, plus a PCS-Tender commercial-palisade B2B funnel targeting the Scottish Parliament, NHS Lothian and Edinburgh universities. Edinburgh clients typically reduce aggregator dependency from 50% to 14% inside 6 months while growing total revenue 35–55%.",
    },
    {
      q: "How do you handle Listed Building Consent, conservation-area planning and the New Town WHS heritage iron railings work in our marketing?",
      a: "We build planning literacy into the entire customer journey — and Edinburgh has the highest planning-encumbered fencing demand of any UK city after central London. Quote enquiry forms include Listed Building Consent qualifying questions at Grade A, Grade B and Grade C(s) levels; AI receptionist asks the property's planning status and WHS designation as the second question after job type; the website includes an EH-postcode-by-postcode heritage-fencing content hub (different content for New Town vs Old Town vs Stockbridge vs Murrayfield vs Cramond) which doubles as long-tail SEO pulling thousands of monthly informational searches. Landing pages educate prospects on the City of Edinburgh Council Planning service Listed Building Consent process, like-for-like material requirements (traditional sand-cast wrought-iron specifications matched to Ballantine Bo'ness foundry, Britannia Architectural in Plymouth, J & A Fraser at Bonnyrigg or Mackenzie Decorative Iron sourcing), pre-application consultation pathways, and the realistic 6–14 week consent timeline. We surface PSA TR1+/TR2 logbook for heritage automated-gate retrofit projects, Machinery Directive 2006/42/EC Force-Test compliance, and BFT/FAAC/CAME/Nice motor certification. Named heritage case studies — Charlotte Square, Heriot Row, Moray Place, Great King Street, Drummond Place, Royal Circus, Ann Street completions — earn the firm citations from Edinburgh World Heritage, the Cockburn Association, listed-building consultant directories and the Knight Frank / Savills / Rettie & Co / Coulters / Lindsays New Town estate-agency referral network. Edinburgh fencing clients running this typically book 1–4 New Town heritage projects per quarter at £8,500–£35,000 average within 6–9 months.",
    },
    {
      q: "Can the AI receptionist handle financial-services corporate-relocation enquiries from Stockbridge, Bruntsfield and Morningside customers?",
      a: "Yes — and Edinburgh's financial-services corporate-housing programme is one of Scotland's most under-exploited B2B opportunities. Royal Bank of Scotland (NatWest Group), Standard Life Aberdeen, Baillie Gifford, Aegon, Scottish Widows, JP Morgan Chase Edinburgh, BlackRock Edinburgh, plus the major Edinburgh law firms (Brodies, Shepherd and Wedderburn, Dickson Minto, Burness Paull's Edinburgh office, Maclay Murray & Spens) all run corporate-housing programmes commissioning premium fencing work for senior executives and visiting international staff. The AI receptionist recognises corporate-relocation enquiry patterns (typically inbound from Crown Worldwide, Santa Fe, Sterling, Britannia or directly from in-house mobility teams), routes immediately to a credentialed B2B response pathway with PSA TR1+/TR2 logbook documentation, Machinery Directive 2006/42/EC Force-Test certificates, BFT/FAAC/CAME/Nice motor certification, public liability insurance documentation (£10M minimum required by most corporate-housing programmes), and named completed-job case studies in EH3 Stockbridge, EH9 Bruntsfield, EH10 Morningside and EH12 Murrayfield. Standard fencing flow runs alongside: job type, EH postcode, run-length, original fence type, photo capture via SMS link, household insurance claim status, Listed Building Consent / WHS status as the second question, and the boundary-dispute routing question that filters 15–20% of enquiries away from wasted survey time toward RICS-registered surveyors or Edinburgh property solicitors. Edinburgh clients running this typically capture 30–45% more booked jobs per van per month plus 1–3 corporate-relocation projects per quarter at £8,000–£25,000 average within 6–9 months.",
    },
    {
      q: "Is the Storm Babet, Isha and Jocelyn revenue spike worth optimising for in Edinburgh, given Festival-season operational restrictions?",
      a: "Yes — operators who plan for it routinely book 25–40% of annual revenue across four to six named-storm weeks each season, with the structural caveat that Festival-season (August) Old Town and New Town WHS works are largely restricted, so storm-window planning aligns naturally with the autumn-and-winter operational calendar. Edinburgh storm windows are now a recurring fixture: Storm Eunice (Feb 2022) caused localised damage despite peaking in southern England; Storm Babet (Oct 2023) hit Edinburgh and the Lothians hard with widespread EH-postcode fence damage and significant rural Lothian flooding; Storm Henk (Jan 2024) added incremental events; Storm Isha + Storm Jocelyn (back-to-back, Jan 2024) produced exceptional EH-postcode fence collapse with sustained 65mph+ winds. Our Edinburgh storm playbook: (1) pre-built storm-response landing pages live and ranked from September each year targeting 'storm fence repair Edinburgh', 'fence blown down Stockbridge', 'emergency fencing Morningside' and the EH-district long-tail; (2) AI receptionist storm-mode toggle with surge-capacity routing, photo-evidence prioritisation, Listed Building Consent emergency-repair fast-track for heritage callers, and 24/7 capture; (3) pre-loaded Meta and Google Ads creative ready to switch on within 2 hours of a Met Office Lothians named-storm announcement (CPC drops 40–60% during the storm itself); (4) automated post-storm review-request sequences targeting completed EH-postcode repairs to bank review velocity for the next quiet-season search; and (5) insurer-friendly quote templates aligned to the ABI Code of Practice with photographic evidence schedules and Listed Building Consent emergency-repair documentation accepted by Aviva, AXA, Direct Line, NFU Mutual, Royal London Mutual and the major Scottish insurers. Edinburgh clients running this playbook typically convert 65–80% of storm enquiries vs 25–35% reactive baseline.",
    },
  ],
  approach:
    "For Edinburgh fencing contractors, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + EH-district-stratified Google Ads + Maps optimisation) to reduce Bark/MyBuilder/Checkatrade dependency from 50% to under 13% while neutralising Glasgow competitors via New Town WHS Listed Building Consent specialism and LEZ-compliance content; (2) deploy AI 24/7 receptionist with Listed Building Consent / WHS qualifying flow at Grade A, B and C(s) levels, LEZ Euro 6 fleet positioning, financial-services corporate-relocation B2B routing pathway, boundary-dispute routing to RICS without giving advice, and storm-mode surge capacity toggleable inside 2 hours of a Met Office Lothians named-storm announcement; (3) build a dedicated Heritage Iron Railings microsite with named Charlotte Square / Heriot Row / Moray Place / Great King Street case studies, Ballantine Bo'ness and J & A Fraser foundry partnerships, plus a separate automated-gate microsite surfacing PSA TR1+/TR2 logbook, Machinery Directive 2006/42/EC Force-Test compliance and BFT/FAAC/CAME/Nice motor certification, with named EH3 / EH9 / EH10 / EH12 case studies plus financial-services corporate-housing manager outreach; (4) build a PCS-Tender commercial-palisade B2B funnel with CHAS, Constructionline and SafeContractor accreditation surfacing, targeting the Scottish Parliament estate, Royal Botanic Garden, NHS Lothian, Universities of Edinburgh / Heriot-Watt / Edinburgh Napier and the Edinburgh Festival venue estate; and (5) drive Google review velocity to 8–15 new reviews per month with named EH-postcode keyword density, plus pre-built storm-response landing pages live from September each year.",
};
