import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "fencing contractor marketing Bristol",
    "Bristol fencing lead generation",
    "fence installer SEO Bristol",
    "Bristol Fencing Services marketing",
    "South West fencing Google Ads",
  ],
  secondaryKeywords: [
    "Clifton heritage wall railings Bristol",
    "Listed Building Consent fencing Bristol",
    "Bristol CAZ Class D fencing van compliance",
    "Sneyd Park Stoke Bishop premium fencing",
    "automated gate installation Bristol",
    "Temple Quarter commercial palisade tender",
    "storm Eunice Bristol fence repair",
    "Jacksons Fencing approved installer Bristol",
  ],
  heroSubhead:
    "Bristol's fencing market sits inside the most heritage-encumbered planning regime of any UK city outside London. Listed Building Consent applies across enormous swathes of Clifton, Hotwells, Cotham, Redland and the Old City, where Georgian-era heritage stone walls topped with cast or wrought-iron railings are protected at street frontage and require formal consent for replacement. Bristol's CAZ Class D went live 28 November 2022 — covering the inner zone with £9 daily charges for non-compliant cars, £100 for non-compliant LGVs and HGVs — restructuring fleet economics. Bristol Fencing Services-tier independents win by understanding heritage iron railings specialism, Listed Building Consent process, the eco-conscious customer profile (sustainable timber, FSC certification, retrofit-aware perimeter), and the storm-window reality that Eunice (Feb 2022) hit the South West harder than almost anywhere else in the UK. Kerblabs is purpose-built for it.",
  marketContext: [
    "Bristol's fencing market is shaped by three structural forces no other South West city combines. First, the Clean Air Zone Class D went live on 28 November 2022, covering the inner zone bounded roughly by the M32, Cumberland Road and Temple Way, and charging £9 daily for non-compliant cars (Euro 4 petrol / Euro 6 diesel threshold), and £100 daily for non-compliant LGVs, HGVs, taxis and coaches. For fencing operators, that's £25,000+ per year of pure overhead per non-compliant Luton tipper or panel van entering the zone five days a week — a number that has driven near-universal Euro 6 fleet upgrades among inner-Bristol contractors and pushed remaining non-compliant operators to BS3 South Bristol, BS4 Brislington, BS5 East Bristol, BS13 Hartcliffe, BS14 Hengrove and Greater Bristol fringe (BS31 Keynsham, BS32 Bradley Stoke, BS37 Yate). The bifurcation matters: CAZ-compliant operators with Euro 6 fleet hold structural advantage on inner-BS1, BS2, BS6, BS7, BS8 and BS16 work that competitors can no longer service profitably. Most CAZ-compliant Bristol fencing firms don't surface this fact in marketing — a missed lever Kerblabs systematically exploits with CAZ check-tool screenshots in quote PDFs and Euro 6 schema in landing pages. Second, the heritage planning reality across Clifton, Hotwells, Cotham, Redland, Sneyd Park and the Old City: enormous swathes of street frontage carry Listed Building Consent requirements (Grade II and Grade II*), and conservation-area designations covering Bristol's most premium catchments mean even non-listed properties require conservation officer sign-off for street-frontage fence and gate work, including replacement of deteriorated cast-iron and wrought-iron railings on the Georgian and Regency stock that defines the city visually.",
    "Bristol's premium fencing catchment is uniquely heritage-iron-railings-driven. Clifton (BS8), Sneyd Park (BS9), Hotwells (BS8), Cotham (BS6), Redland (BS6) and Henleaze (BS9) host enormous concentrations of Grade II and Grade II* Georgian and Regency terraced stock with original cast-iron, wrought-iron or composite-iron-and-stone street frontage that requires formal Listed Building Consent for replacement. Project values are exceptional: a typical Clifton heritage-railings replacement on a Grade II terrace runs £6,500–£18,000 with full Listed Building Consent process, conservation officer pre-application consultation, traditional sand-cast lead specifications and bespoke ironwork sourced from heritage foundries (Britannia Architectural in Plymouth, Ballantine Bo'ness in Scotland, or specialist Bristol heritage metalworkers). Full Sneyd Park or Stoke Bishop Georgian estate boundary projects routinely cross £25,000–£60,000 once heritage stone repointing, original ironwork restoration, automated-gate retrofit, and full perimeter reinstatement are factored in. Standard residential closeboard, lap-panel and post-and-rail work in BS3 Bedminster, BS4 Brislington, BS5 Easton, BS7 Bishopston and BS16 Fishponds runs at conventional South West retail rates of £80–£140/m, but the heritage-iron-railings premium catchment is structurally separate and is captured by maybe four or five Bristol-based heritage specialists with proper Listed Building Consent process competence, conservation officer relationships and traditional ironwork sourcing networks.",
    "Bristol's commercial fencing demand is the strongest in the South West and sits inside the largest UK urban regeneration pipeline outside London. Temple Quarter (the £1B+ University of Bristol Enterprise Campus, Network Rail Temple Meads station expansion, Bristol Beacon, the Western Harbour redevelopment), plus Bedminster Green, Filton aerospace estate (Airbus, BAE Systems, GKN Aerospace, Rolls-Royce Filton), Bristol Port Company, NHS University Hospitals Bristol and Weston Trust grounds, the new Temple Island development and the South Bristol corridor regeneration all source palisade, weldmesh and Heras-hire through CHAS, Constructionline and Achilles SafeContractor accredited contractors via PCR 2015 procurement and the West of England Combined Authority frameworks. Most Bristol fencing firms with the skillset don't pursue commercial work because their websites don't surface accreditations. Bristol's eco-conscious consumer profile — the city was the UK's first European Green Capital (2015) and elected the UK's first Green Party-led council in 2024 — means FSC-certified timber, sustainable specification, retrofit-aware perimeter design and B Corp-style ethical positioning are real commercial signals not marketing language. Combined with Storm Eunice (Feb 2022) which hit the South West harder than almost anywhere else in the UK with 122mph gusts at the Isle of Wight and exceptional Bristol-area fence collapse, plus Storm Babet (Oct 2023) and Storm Isha + Jocelyn (Jan 2024), Bristol fencing contractors running Kerblabs typically reach £55–£105 cost-per-acquired-job vs £180–£320 on Bark, MyBuilder and Checkatrade with average job values 30–50% above the Bristol market median.",
  ],
  stats: [
    { value: "£9 / £100 per day", label: "Bristol CAZ Class D charge for non-compliant car / LGV-HGV-taxi — operational since 28 November 2022", source: "Bristol City Council CAZ" },
    { value: "£6,500–£60,000", label: "Clifton / Sneyd Park / Cotham heritage iron railings + Listed Building Consent project range" },
    { value: "122mph", label: "Storm Eunice peak gust Isle of Wight Feb 2022 — exceptional Bristol-area boundary fence collapse", source: "Met Office" },
    { value: "£1B+", label: "Temple Quarter regeneration pipeline driving commercial-perimeter and Heras-hire demand", source: "Bristol City Council / HCA" },
    { value: "1st", label: "UK European Green Capital (2015) — eco-conscious customer profile rewards FSC-certified timber", source: "European Commission 2015" },
    { value: "BS1–BS16 + BS30–BS37", label: "Bristol metro postcode coverage with district-stratified marketing" },
  ],
  painPoints: [
    {
      title: "Listed Building Consent and conservation-area planning paralysis killing 30%+ of Clifton quote pipeline",
      body: "Around 30% of Clifton, Hotwells, Cotham and Redland fencing enquiries come from homeowners who don't yet realise their property requires Listed Building Consent or conservation-area approval for street-frontage fence and gate replacement. Without pre-qualifying, your surveyor wastes an afternoon on a property that can't progress for 8–14 weeks pending consent, and the customer often vanishes during the wait. AI receptionist with conservation-status qualifying flow ('is your property listed Grade II or II*? in a conservation area? have you spoken to Bristol City Council planning portal?') filters this at first contact, frees 8–14 hours/week of surveyor time, and routes viable enquiries to the heritage-iron-railings premium funnel.",
    },
    {
      title: "Heritage iron railings premium specialism completely under-marketed",
      body: "Cast-iron and wrought-iron railings work on Clifton, Sneyd Park, Hotwells and Cotham Grade II and II* stock is high-margin specialist work earning 35–55% gross margin vs 18–25% on retail closeboard. Project values £6,500–£60,000 per property. But most Bristol heritage-capable contractors have generic websites with stock photos saying nothing about Britannia Architectural, Ballantine Bo'ness or specialist Bristol heritage foundry sourcing, traditional sand-cast versus modern fabricated ironwork choice, or conservation officer pre-application process. We rebuild around named heritage case studies (Grade II terraces, conservation-area completions, named conservation officers signing off), making the firm visible to conservation architects, listed-building consultants and Knight Frank / Savills / Hydes of Bristol estate agents who recommend specialists.",
    },
    {
      title: "CAZ Class D compliance, Storm Eunice spike and commercial Temple Quarter tenders all leaking value",
      body: "Three layered Bristol leakage problems. First, CAZ Class D compliant Euro 6 fleet (£9-£100/day non-compliance charges) has cost £18,000–£42,000 per van but doesn't appear in marketing. Second, Storm Eunice (Feb 2022) hit Bristol with exceptional fence collapse — most operators captured 30–60 calls reactively against a 100–180 potential. Third, Temple Quarter, Filton aerospace, Bristol Port and NHS University Hospitals Bristol source palisade and Heras through CHAS-accredited tenders most contractors never pursue. We fix all three: CAZ-compliant fleet positioning, pre-built storm-response landing pages, and a Temple Quarter / WECA commercial-tender B2B funnel.",
    },
    {
      title: "Eco-conscious customer expectations of FSC certification, retrofit-aware design ignored",
      body: "Bristol's eco-conscious consumer profile — UK's first European Green Capital, first Green Party-led council, B Corp-dense small-business economy — means FSC-certified timber, sustainable specification, low-embodied-carbon hardwood sourcing, retrofit-aware perimeter design and ethical labour positioning are genuine commercial signals. Most Bristol fencing firms run generic 'pressure-treated timber' marketing and lose to two or three operators leading with FSC chain-of-custody certification, M&M Timber heritage hardwood sourcing transparency, and B Corp-aligned messaging. We rebuild positioning around it.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat Checkatrade, MyBuilder, Jacksons-network installers and Bath / Cardiff undercutters in Bristol specifically?",
      a: "Three-phase Bristol-specific playbook. Phase one: Google Business Profile category stacking (Fence Contractor + Fencing Supplier + Gate + Driveway gate installer + Aluminium and steel fence installer) with BS-postcode service-area definition, AFI/FISS schema, BFT/FAAC/CAME/Nice automated-gate certification surfaced in markup, CAZ Class D Euro 6 compliance explicit, Listed Building Consent and heritage-iron-railings specialism schema, and structured review campaigns targeting 8–15 new reviews per month with named BS-postcode keywords (Clifton, Hotwells, Cotham, Redland, Sneyd Park, Henleaze, Bishopston, Southville, Bedminster, Easton). Phase two: Google Local Service Ads with the Google Guaranteed badge — on Bristol fencing keywords this consistently lands at £55–£105 cost-per-job versus £180–£320 on Bark, MyBuilder and Checkatrade. Phase three: BS-district-stratified Google Ads (separate campaigns for BS1/BS2/BS8 inner-CAZ-aware, BS6/BS9 Clifton/Sneyd Park heritage-premium, BS3/BS4/BS5 South and East Bristol mid-market, BS7/BS9 Bishopston/Henleaze family-suburban, BS16 Fishponds, BS31/BS37 Greater Bristol fringe) with budgets sized to each district's CPC, plus a dedicated heritage-iron-railings microsite with Listed Building Consent capability surfaced, plus a Temple Quarter / WECA commercial-palisade B2B funnel. Bristol clients typically reduce aggregator dependency from 50% to 14% inside 6 months while growing total revenue 30–55%.",
    },
    {
      q: "How do you handle Listed Building Consent, conservation-area planning and heritage iron railings work in our marketing?",
      a: "We build planning literacy into the entire customer journey. Quote enquiry forms include Listed Building Consent and conservation-area qualifying questions; AI receptionist asks the property's planning status as the second question after job type; the website includes a BS-postcode-by-postcode heritage-fencing content hub (different content for Clifton vs Cotham vs Redland vs Sneyd Park vs Hotwells) which doubles as long-tail SEO pulling thousands of monthly informational searches. Landing pages educate prospects on Listed Building Consent process, like-for-like material requirements (cast-iron vs wrought-iron, Code 6 lead specification, heritage-foundry sourcing through Britannia Architectural and Ballantine Bo'ness), pre-application consultation pathways with named Bristol City Council conservation officers, and the realistic 8–14 week consent timeline. We surface PSA TR1+/TR2 logbook for heritage automated-gate retrofit projects, Machinery Directive 2006/42/EC Force-Test compliance with completed-job force-test certificates, and BFT, FAAC, CAME and Nice motor certification. This filters survey time onto viable jobs and earns the firm citations from local conservation forums, the Bristol Civic Society, listed-building consultant directories and the Knight Frank / Savills / Hydes of Bristol Clifton estate-agent referral network — strong Bristol SEO signals that aggregators can't replicate.",
    },
    {
      q: "Can the AI receptionist handle Bristol's eco-conscious customer expectations of FSC-certified timber and sustainable specification?",
      a: "Yes — and this is one of Bristol's most overlooked competitive advantages. The AI receptionist surfaces FSC chain-of-custody certification, M&M Timber heritage hardwood sourcing transparency, retrofit-aware perimeter design (e.g. fences designed to integrate with EV charger cable runs, heat pump airflow clearances, retrofit insulation external wall projection allowance), and B Corp-style ethical positioning automatically when customer questions touch on sustainability or environmental specification. For Clifton, Stokes Croft, Montpelier, Easton and Southville customers — who systematically ask these questions — surfacing FSC certification meaningfully lifts conversion. Standard fencing flow runs alongside: job type, BS postcode, run-length in metres, original fence type, photo capture via SMS link, household insurance claim status, Listed Building Consent / conservation-area status as the second question, and the boundary-dispute routing question that filters 15–20% of enquiries away from wasted survey time toward RICS-registered surveyors or Bristol property solicitors (TLT, Burges Salmon, Osborne Clarke, Foot Anstey). Storm-mode toggle activates surge capacity within 2 hours of a Met Office named-storm announcement covering the South West. Bristol clients running this typically capture 35–55% more booked jobs per van per month vs untuned competitors.",
    },
    {
      q: "Is the Storm Eunice, Babet and Isha + Jocelyn revenue spike worth optimising for in Bristol, or too unpredictable?",
      a: "Storm Eunice (18 Feb 2022) was the largest single fencing-revenue event in modern Bristol history — the South West took the brunt of the storm, with 122mph gusts recorded at the Isle of Wight, sustained 70–85mph winds across the Bristol area, and exceptional fence collapse across BS3 Bedminster, BS5 Easton, BS6 Cotham, BS7 Bishopston, BS9 Henleaze and BS16 Fishponds. Operators who answered the phone booked six months of work in 10 days. Storm Babet (Oct 2023) caused localised but meaningful Bristol-area damage. Storm Henk (Jan 2024) added incremental wind events. Storm Isha + Storm Jocelyn (back-to-back, Jan 2024) hit the South West with sustained 65mph+ winds and produced exceptional Bristol fence-damage calls. Our Bristol storm playbook: (1) pre-built storm-response landing pages live and ranked from September each year targeting 'storm fence repair Bristol', 'fence blown down Clifton', 'emergency fencing Bedminster' and the BS-district long-tail; (2) AI receptionist storm-mode toggle with surge-capacity routing, photo-evidence prioritisation, Listed Building Consent fast-track flow for heritage emergency repairs, and 24/7 capture; (3) pre-loaded Meta and Google Ads creative ready to switch on within 2 hours of a Met Office named-storm announcement covering the South West (CPC drops 40–60% during the storm itself); (4) automated post-storm review-request sequences targeting completed BS-postcode repairs to bank review velocity; and (5) insurer-friendly quote templates aligned to the ABI Code of Practice with photographic evidence schedules and Listed Building Consent emergency-repair documentation accepted by Aviva, AXA, Direct Line, NFU Mutual, LV= and the Bristol-area mutual insurers. Bristol clients running this playbook typically convert 65–80% of storm enquiries vs 25–35% reactive baseline.",
    },
  ],
  approach:
    "For Bristol fencing contractors, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + BS-district-stratified Google Ads + Maps optimisation) to reduce Bark/MyBuilder/Checkatrade dependency from 50% to under 14% while neutralising Bath and Cardiff undercutters via heritage-iron-railings specialism and CAZ-compliance content; (2) deploy AI 24/7 receptionist with Listed Building Consent / conservation-area qualifying flow, CAZ Class D zone-aware fleet positioning, FSC-certified timber and eco-conscious customer messaging, boundary-dispute routing to RICS without giving advice, and storm-mode surge capacity toggleable inside 2 hours of a Met Office South West named-storm announcement; (3) build a dedicated heritage-iron-railings microsite with Listed Building Consent capability, named Britannia Architectural and Ballantine Bo'ness foundry partnerships, completed Grade II / II* case studies, plus a separate automated-gate microsite surfacing PSA TR1+/TR2 logbook, Machinery Directive 2006/42/EC Force-Test compliance and BFT/FAAC/CAME/Nice motor certification; (4) build a Temple Quarter / WECA commercial-palisade B2B funnel with CHAS, Constructionline and SafeContractor accreditation surfacing, targeting Temple Quarter, Filton aerospace, Bristol Port, NHS University Hospitals Bristol and Weston Trust grounds, and West of England Combined Authority frameworks; and (5) drive Google review velocity to 8–15 new reviews per month with named BS-postcode keyword density, plus pre-built storm-response landing pages live from September each year.",
};
