import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "fencing contractor marketing Birmingham",
    "Birmingham fencing lead generation",
    "West Midlands fencing SEO",
    "Birmingham Fencing Services marketing",
    "Midlands Fencing lead generation",
  ],
  secondaryKeywords: [
    "Solihull Sutton Coldfield premium fencing",
    "CAZ Class D compliant fencing van Birmingham",
    "automated gate installation Birmingham",
    "Edgbaston Harborne Moseley fencing contractor",
    "Knowle Dorridge Mere Green automated gates",
    "Jacksons Fencing approved installer Birmingham",
    "commercial palisade tender HS2 corridor",
    "B91 B93 B74 premium fencing",
  ],
  heroSubhead:
    "Birmingham's fencing market is the UK's largest after London and uniquely shaped by three forces no other city combines: a Clean Air Zone Class D operating since June 2021 (covering A4540 ring-road inner-Birmingham), the Solihull / Sutton Coldfield premium corridor where Knight Frank-grade households expect Jacksons Fencing-tier specification, and an HS2 Curzon Street regeneration cycle producing commercial-palisade, weldmesh and Heras-hire demand at a scale measured in tens of billions through the 2030s. Birmingham Fencing Services and Midlands Fencing-tier independents win by understanding CAZ-compliant van economics, B-postcode demographic variance from B5 Edgbaston to B91 Solihull to B74 Sutton Coldfield, and the storm-window reality that Eunice, Babet, Isha and Jocelyn all hit the West Midlands hard. Kerblabs is the only marketing system built for this complexity.",
  marketContext: [
    "Birmingham's fencing market is structurally larger and more demographically variant than any UK city outside London. The West Midlands metro area hosts 78,000+ active SMEs across a population of 2.9M, and the fencing demand profile splits sharply across postcode lines that change behaviour every two miles. The Clean Air Zone Class D — operational since 1 June 2021, covering all roads inside the A4540 Middleway with daily charges of £8 for non-compliant cars and £50 for non-compliant LGVs and HGVs — has restructured fencing-fleet economics meaningfully. Pre-Euro 6 diesel Luton tippers and panel vans now pay £50/day every operating day inside the zone, equivalent to £13,000+/year for five-day operators, forcing an upgrade or a retreat to outer Birmingham (Solihull, Sutton Coldfield, Bromsgrove, Halesowen, Walsall) and Black Country trade. CAZ-compliant Euro 6 fleet operators have absorbed the £18,000–£42,000 per-van upgrade cost and now hold structural advantage on inner-B1, B2, B3, B4, B5, B12, B15 and B18 work that competitors literally cannot service profitably. Most CAZ-compliant Birmingham fencing firms don't surface this fact anywhere in their marketing — a missed lever we systematically exploit.",
    "The Solihull, Knowle, Dorridge, Sutton Coldfield, Four Oaks and Mere Green premium corridor — B91, B93, B94, B74, B75, B76 — is one of the UK's strongest sub-markets for premium fencing and automated-gate work. Knight Frank, Savills, Strutt & Parker, DM & Co, Smart Homes and Aston Knowles operate across stock priced £750k–£3M+, with corporate-relocation density driven by JLR (Jaguar Land Rover at Solihull and Castle Bromwich), Deutsche Bank (Brindleyplace), HSBC UK (Birmingham HQ), KPMG, Deloitte, PwC Birmingham, Goldman Sachs and Mondelez. Premium fencing project values run £4,500 for a Knowle garden closeboard refresh to £22,000–£45,000 for Dorridge or Four Oaks executive-detached automated-gate-and-perimeter packages with BFT, FAAC, CAME or Nice motor systems, biometric or app-based access control, hardwood gates with stainless-steel ironmongery and stone-pillar capping. The pool of Birmingham contractors capable of delivering this work (PSA TR1+/TR2 logbook competent, BFT/FAAC/CAME/Nice motor certified, Machinery Directive 2006/42/EC Force-Test compliant) is genuinely small, and most bury the capability on a generic services page. Layered onto Solihull and Sutton premium work is the Edgbaston, Harborne, Moseley and Kings Heath middle-market — £2,500–£8,000 retail closeboard, ornamental ironwork and traditional stone-and-iron heritage work in B15, B17 and B13 conservation areas where Listed Building Consent or conservation-area approval is required for many street-frontage installations.",
    "Birmingham's commercial fencing demand is the largest in the UK outside London and sits inside the most predictable construction pipeline in the country. HS2 Curzon Street terminus, Paradise development, Smithfield regeneration, Eastside expansion, Perry Barr Commonwealth Games legacy estate, the BBC Midlands relocation site, the new Ulster University-style Knowledge Quarter campuses, plus JLR's Solihull and Castle Bromwich estates, the NEC complex, Birmingham Airport expansion, NHS Birmingham and Solihull ICB estate, and Walsall, Wolverhampton and Coventry distribution-park supply chains all source palisade, weldmesh, Heras-hire and security-perimeter fencing through CHAS, Constructionline and Achilles SafeContractor accredited contractors via Public Contracts Regulations 2015 procurement and the West Midlands Combined Authority frameworks. Most Birmingham fencing firms with the skillset don't pursue commercial work because their websites don't surface accreditations and they've never built a B2B funnel. Combined with CAZ-compliant fleet positioning, B-district-stratified Google Ads, automated-gate microsite, multilingual response capability for Sparkbrook, Small Heath, Bordesley Green, Handsworth and Alum Rock community-led residential demand (Urdu, Punjabi, Bengali), boundary-dispute routing to RICS, and pre-built storm-response landing pages, Birmingham fencing contractors running Kerblabs typically reach £55–£115 cost-per-acquired-job vs £180–£340 on Bark, MyBuilder and Checkatrade with average job values 30–45% above the Birmingham market median.",
  ],
  stats: [
    { value: "1.14M", label: "Birmingham city population — second largest UK fencing market", source: "ONS Census 2021" },
    { value: "£50/day", label: "Birmingham CAZ Class D charge for non-compliant LGV / HGV — operational since 1 June 2021", source: "Birmingham City Council CAZ" },
    { value: "£4,500–£45,000", label: "Solihull / Knowle / Sutton Coldfield premium fencing and automated-gate project range" },
    { value: "£100B+", label: "HS2 + Birmingham regeneration construction pipeline through 2030s — palisade and Heras demand", source: "HS2 Ltd / Birmingham City Council" },
    { value: "B1–B98 + WV / DY", label: "Birmingham metro postcode coverage with district-stratified marketing" },
    { value: "30–50%", label: "share of Birmingham fencing search controlled by Checkatrade, MyBuilder, Jacksons-network listings" },
  ],
  painPoints: [
    {
      title: "CAZ Class D compliant fleet investment with no marketing payoff",
      body: "Birmingham fencing contractors who upgraded to Euro 6 Luton tippers and panel vans for the 1 June 2021 Clean Air Zone Class D have spent £18,000–£42,000 per vehicle but barely surface that fact anywhere in their marketing. Inner-B-postcode customers and HS2-corridor commercial procurement teams care — non-compliant operators face £50/day charges that price them out of inner-city work entirely. We rebuild messaging to put CAZ-compliant Euro 6 fleet, Birmingham CAZ check-tool screenshots and named inner-B-postcode completed jobs into landing pages, GBP posts and quote PDFs, capturing the inner-Birmingham work non-compliant Black Country and Walsall operators are pricing themselves out of.",
    },
    {
      title: "Solihull, Knowle, Sutton Coldfield premium gate work lost to two competitors",
      body: "Birmingham's highest-margin fencing work — £4,500–£45,000 hardwood, automated-gate and perimeter projects across B91, B93, B94, B74, B75 — is captured by two or three contractors with proper PSA TR1+/TR2 logbook surfacing, Machinery Directive 2006/42/EC Force-Test compliance, and BFT/FAAC/CAME/Nice motor certification badges. Most Birmingham fencing firms with the skillset bury it on a generic services page and lose to specialists. We build a dedicated automated-gate microsite with named installation case studies in Knowle, Dorridge, Four Oaks and Mere Green, plus B2B outreach to JLR, HSBC UK, Deutsche Bank, KPMG, Deloitte, PwC Birmingham and Goldman Sachs corporate-relocation services.",
    },
    {
      title: "HS2 commercial palisade and Heras tender pipeline ignored despite £100B+ scale",
      body: "HS2 Curzon Street, Paradise, Smithfield, Eastside, Perry Barr, JLR Solihull, the NEC, Birmingham Airport, NHS Birmingham and Solihull ICB estate and the Walsall / Wolverhampton / Coventry distribution-park supply chains source palisade, weldmesh and Heras-hire through CHAS, Constructionline and Achilles SafeContractor accredited contractors via PCR 2015 procurement and West Midlands Combined Authority frameworks. Most Birmingham fencing firms with the skillset don't pursue commercial work because they don't surface accreditations and have never built a B2B funnel. We build it with named completed-job case studies and formal tender-response templates aligned to PCR 2015.",
    },
    {
      title: "Storm Eunice, Babet, Isha, Jocelyn revenue spike captured reactively — boundary disputes wasting survey time",
      body: "Storm Eunice (Feb 2022) hit Birmingham with 79mph gusts at Coleshill, Storm Babet (Oct 2023) caused West Midlands flooding-and-wind damage, and Storm Isha + Storm Jocelyn (Jan 2024) produced exceptional Birmingham fence-damage windows where crews fielded hundreds of combined calls but missed 60–80%. Pre-built storm-response landing pages live and ranked from September each year, plus AI receptionist surge capacity and pre-loaded Meta and Google Ads creative ready to switch within 2 hours of a Met Office named-storm announcement, capture 60–130 enquiries per event. Boundary-dispute calls (15–20% of enquiries) get routed to RICS-registered surveyors without giving advice, freeing 8–14 hours/week of installer time.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat Checkatrade, MyBuilder, Jacksons-network installers and the Black Country undercutters in Birmingham specifically?",
      a: "Three-phase Birmingham-specific playbook. Phase one: Google Business Profile category stacking (Fence Contractor + Fencing Supplier + Gate + Driveway gate installer + Aluminium and steel fence installer) with B-postcode service-area definition, AFI/FISS schema, BFT/FAAC/CAME/Nice automated-gate certification surfaced in markup, CAZ Class D Euro 6 fleet compliance explicit, and structured review campaigns targeting 8–18 new reviews per month with named B-postcode keywords (Edgbaston, Harborne, Moseley, Solihull, Knowle, Sutton Coldfield, Four Oaks, Mere Green, Sparkbrook, Bordesley Green, Handsworth). Phase two: Google Local Service Ads with the Google Guaranteed badge — on Birmingham fencing keywords this consistently lands at £55–£115 cost-per-job versus £180–£340 on Bark and MyBuilder. Phase three: B-district-stratified Google Ads (separate campaigns for B1–B5 city-core CAZ-aware, B15/B17/B13 Edgbaston/Harborne/Moseley middle-premium, B91/B93/B94 Solihull premium, B74/B75/B76 Sutton Coldfield premium, B11/B10/B19/B21 multilingual Sparkbrook/Bordesley Green/Handsworth, B70/B71 West Bromwich, WV/DY Black Country) with budgets sized to each district's CPC, plus a dedicated automated-gate microsite, plus an HS2-corridor commercial-palisade B2B funnel, plus multilingual WhatsApp Business automation for community-led residential demand. Birmingham clients typically reduce aggregator dependency from 50% to 14% inside 6 months while growing total revenue 35–60%.",
    },
    {
      q: "Can the AI receptionist handle Birmingham's multilingual Sparkbrook / Bordesley Green / Handsworth demand and the CAZ Class D inner-zone qualifying flow?",
      a: "Yes — and both are uniquely Birmingham levers. The AI receptionist recognises and routes Urdu, Punjabi, Bengali, Polish and Romanian speakers to appropriate response paths (multilingual SMS templates, WhatsApp Business follow-up, or live handoff to bilingual staff) — for fencing contractors operating across B11 Sparkhill, B10 Small Heath, B12 Balsall Heath, B19 Newtown, B21 Handsworth, B6 Aston, B8 Alum Rock and parts of Solihull, multilingual response capability typically lifts conversion on community-driven enquiries 30–50% versus English-only voicemail. Asian-heritage extended-family privacy fence demand — taller perimeter (typically 2.0–2.4m vs the standard 1.8m), denser closeboard or Venetian-slat design for visual privacy, often combined with automated pedestrian gate access — is a meaningful and underserved Birmingham segment. CAZ Class D qualifying runs alongside: when a customer's address resolves inside the A4540 Middleway, the receptionist surfaces CAZ-compliant Euro 6 fleet capability automatically and includes a Birmingham CAZ check-tool screenshot in the quote PDF; when outside the zone, normal pricing applies. Standard fencing flow runs through job type, postcode, run-length in metres, original fence type, photo capture via SMS link, household insurance claim status, and the boundary-dispute routing question that filters 15–20% of enquiries away from wasted survey time.",
    },
    {
      q: "How do we win the Solihull, Knowle, Sutton Coldfield and Four Oaks automated-gate work where customers compare us to Jacksons-network installers?",
      a: "Birmingham's premium automated-gate market — typical project values £6,500–£45,000 across B91, B93, B94, B74, B75 and B76 — is won on credentials, photographic evidence, named completed installations and corporate-relocation referral networks, not on price. We rebuild positioning around the credentials that matter to Knight Frank / Savills / Strutt & Parker households and JLR / HSBC / Deutsche Bank corporate-relocation customers: PSA TR1+/TR2 logbook competence surfaced prominently with named completed sites, Machinery Directive 2006/42/EC Force-Test compliance explained in plain English with completed-job force-test certificates, BFT, FAAC, CAME and Nice motor certification badges in markup and on landing pages, gate safety risk-assessment process documented with PDF templates, and a portfolio microsite of named completed installations across Knowle, Dorridge, Bentley Heath, Four Oaks, Mere Green and Little Aston with photographs of stainless-steel ironmongery, hardwood gates, intercom integration and biometric or app-based access control. We layer corporate-relocation B2B outreach: JLR (Solihull, Castle Bromwich), HSBC UK (Birmingham HQ), Deutsche Bank (Brindleyplace), KPMG, Deloitte, PwC Birmingham, Goldman Sachs and Mondelez plus the major Birmingham relocation services (Crown Worldwide, Santa Fe, Sterling, Britannia Bradshaw). Birmingham fencing clients running this typically book 2–5 automated-gate projects per month at £9,000–£24,000 average within 6–9 months.",
    },
    {
      q: "Is the Storm Eunice, Babet, Isha and Jocelyn revenue spike worth optimising for in Birmingham, or too unpredictable?",
      a: "It's the single most predictable revenue pattern in Birmingham fencing — operators who plan for it routinely book 25–40% of annual revenue across four to six named-storm weeks each season. West Midlands storm windows are now a recurring fixture: Storm Eunice (Feb 2022) hit Birmingham with 79mph gusts recorded at Coleshill plus exceptional B91 Solihull, B74 Sutton Coldfield and B17 Harborne fence loss; Storm Babet (Oct 2023) caused West Midlands flooding and 60mph+ wind damage; Storm Henk (Jan 2024) produced widespread B-postcode fence-collapse calls; and Storm Isha + Storm Jocelyn (back-to-back, Jan 2024) hit hard with sustained 65mph+ winds. Our Birmingham storm playbook: (1) pre-built storm-response landing pages live and ranked from September each year targeting 'storm fence repair Birmingham', 'fence blown down Solihull', 'emergency fencing Sutton Coldfield' and the B-district long-tail; (2) AI receptionist storm-mode toggle with surge-capacity routing, photo-evidence prioritisation, multilingual coverage for community-led areas, and 24/7 capture; (3) pre-loaded Meta and Google Ads creative ready to switch on within 2 hours of a Met Office named-storm announcement (CPC drops 40–60% during the storm itself because most Birmingham firms haven't pre-built ads); (4) automated post-storm review-request sequences targeting completed B-postcode repairs to bank review velocity for the next quiet-season search; and (5) insurer-friendly quote templates aligned to the ABI Code of Practice with photographic evidence schedules accepted by Aviva, AXA, Direct Line, NFU Mutual, LV= and Admiral. Birmingham clients running this playbook typically convert 60–75% of storm enquiries vs 25–35% reactive baseline.",
    },
  ],
  approach:
    "For Birmingham fencing contractors, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + B-district-stratified Google Ads + Maps optimisation) to reduce Bark/MyBuilder/Checkatrade dependency from 50% to under 16% while neutralising Black Country undercutters via CAZ-compliance content; (2) deploy AI 24/7 receptionist with multilingual coverage (Urdu, Punjabi, Bengali, Polish, Romanian), CAZ Class D zone-aware qualifying flow, boundary-dispute routing to RICS without giving advice, WhatsApp Business automation for community-led areas, and storm-mode surge capacity toggleable inside 2 hours of a Met Office named-storm announcement; (3) build a dedicated automated-gate microsite surfacing PSA TR1+/TR2 logbook, Machinery Directive 2006/42/EC Force-Test compliance and BFT/FAAC/CAME/Nice motor certification, with named B91/B93/B74 case studies plus JLR / HSBC / Deutsche Bank corporate-relocation outreach; (4) build an HS2-corridor commercial-palisade B2B funnel with CHAS, Constructionline and SafeContractor accreditation surfacing, targeting HS2 Curzon Street, Paradise, Smithfield, Eastside, Perry Barr, JLR estates, NHS Birmingham and Solihull ICB and West Midlands Combined Authority frameworks; and (5) drive Google review velocity to 8–18 new reviews per month with named B-postcode keyword density.",
};
