import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "fencing contractor marketing Swansea",
    "Swansea fencing company SEO",
    "Welsh-language fencing Swansea",
    "coastal salt-air fencing Swansea Gower",
    "automated gate installer Swansea marketing",
  ],
  secondaryKeywords: [
    "Swansea Fencing Services competitor",
    "Gower Fencing alternative",
    "ffensio Abertawe Welsh-language SEO",
    "Mumbles Sketty premium fence quote",
    "Gorseinon Pontarddulais Welsh-language fencing",
    "SA1 SA8 fencing borough SEO",
    "Gower coastal exposure fence specialist",
    "Checkatrade alternative Swansea fencer",
  ],
  heroSubhead:
    "Swansea fencing contractors trade across a uniquely layered South Wales market — the Gower coastal corridor punishing standard galvanised fixings with Atlantic-and-Bristol-Channel salt-air corrosion, the Welsh-language belt west of the city (Gorseinon, Pontarddulais, Loughor, Penclawdd) where Welsh-medium signage and bilingual GBP content earns measurable trust and ranking benefits, and a Mumbles–Sketty premium pocket pulling £130–£250/m contemporary slat and hardwood work. Swansea Fencing Services and Gower Fencing dominate the city-wide search alongside Checkatrade, MyBuilder and Jacksons-network installers. Storm Eunice (Feb 2022), Babet (Oct 2023) and Isha–Jocelyn (Jan 2024) routinely flatten thousands of SA-postcode and Gower-coastal fences. Kerblabs gives Swansea fencers the AI receptionist, SA-postcode SEO with Welsh-language coverage, Gower coastal-specialism funnel and Bristol-Channel storm-response stack to break aggregator dependency.",
  marketContext: [
    "Swansea's fencing market is shaped by three structural forces no other UK city combines in the same way. First, the Gower Peninsula and Swansea Bay coastal corridor. Mumbles (SA3), Oystermouth, Caswell, Langland, Bishopston and the wider Gower Peninsula sit in the path of Atlantic-and-Bristol-Channel south-westerlies, with salt aerosol carried up to 6–9 km inland from the coast knocking 35–55% off the lifespan of standard hot-dip galvanised steel post-bases, brackets and gate hardware. Specifications that work in Morriston (SA6) or Llansamlet (SA7) fail prematurely on Mumbles seafront, Caswell Bay-fringe and the Gower clifftop stock. Swansea fencers who specify properly (marine-grade 316 stainless fixings, Code 5+ galvanising, hardwood Iroko and Western Red Cedar over softwood, powder-coated aluminium over standard mild steel) command a premium and avoid 5–7 year replacement-cycle reputational damage on Mumbles and Gower work — but most don't surface this competence in marketing.",
    "Second, the Welsh-language essential west. Welsh-language community density rises sharply west of Swansea proper, with Gorseinon, Pontarddulais, Penclawdd, Llanrhidian, Loughor and the wider rural Gower-fringe carrying Welsh-speaker proportions well above Swansea's 11–13% city-average — in some communities approaching 30–45%. For fencing firms targeting this catchment, Welsh-language signage, bilingual GBP descriptions, Welsh-medium quote PDFs and Welsh-language ad creative ('ffensio', 'gosodwr ffensys', 'cyflenwr ffensys') earn measurable trust, conversion and local-pack ranking benefits that English-only competitors cannot match. The Swansea Council-and-City-and-County requirement for Welsh-language public-procurement-document-handling under the Welsh Language Standards (Wales) Measure 2011 also means commercial-tender work on Welsh-medium school perimeter, council park-fencing and bilingual-frontage commercial sites favours bilingual-capable fencers.",
    "Third, Swansea's premium-overflow and storm patterns. Mumbles–Sketty–Killay–West Cross drives the city's highest-spend fencing demand at £130–£250/m on contemporary slat, Iroko hardwood and powder-coated aluminium fencing plus £4,000–£10,000 automated swing-pair and sliding-gate installs. The Cardiff-comparison effect is real: Cardiff property prices average £290k+ versus Swansea's £200k, and the steady inflow of Cardiff-commuter and remote-worker households into Mumbles, Sketty, Killay and West Cross since 2020 has lifted per-metre pricing in those SA2/SA3 postcodes. Storm Eunice (February 2022) hit South Wales hard with documented 100mph+ gusts on the Gower; Babet (October 2023) and Isha–Jocelyn (January 2024) produced sequential events with 70–150 enquiries inside a 72-hour window. CPCs run £2.50–£4.50 — sharply lower than Cardiff or Bristol — making SA-postcode-stratified Google Ads viable alongside organic SEO. Swansea Fencing Services, Gower Fencing and Checkatrade competitors dominate the generic search; the winning play is bilingual SA-postcode local SEO with Welsh-language coverage west of Swansea, Gower coastal-specialism funnel, Mumbles-and-Sketty premium funnel, and Bristol-Channel storm-response.",
  ],
  stats: [
    { value: "£130–£250/m", label: "typical Mumbles (SA3) / Sketty / Killay premium contemporary-slat and hardwood fencing installed price range" },
    { value: "35–55%", label: "reduction in standard galvanised fitting lifespan in Gower and Mumbles coastal SA3 versus inland SA6/SA7" },
    { value: "11–13%", label: "Welsh speakers in Swansea overall — sharply higher (30–45%) in Gorseinon, Pontarddulais and rural west", source: "ONS Census 2021" },
    { value: "£4,000–£10,000", label: "typical Mumbles/Sketty/Killay automated swing-pair or sliding-gate install value with BFT/FAAC/CAME/Nice motors" },
    { value: "£2.50–£4.50", label: "Swansea Google Ads CPC range for 'fencing contractor [SA-postcode]' 2024–2025", source: "Kerblabs client accounts" },
    { value: "SA1–SA8", label: "Swansea-area postcode districts where coastal exposure, Welsh-language density and premium-overflow stratify sharply" },
  ],
  painPoints: [
    {
      title: "Atlantic-and-Bristol-Channel salt-air corrosion failures destroying Mumbles and Gower customer trust",
      body: "Swansea's SA3 (Mumbles, Oystermouth, Caswell, Langland, Bishopston) and the wider Gower Peninsula coastal stock punish standard hot-dip galvanised steel post-bases and softwood-only fence systems — typical replacement cycles in coastal SA3 are 5–8 years versus 12–18 years on equivalent inland SA6/SA7 stock. Mumbles homeowners on their second or third failed standard install actively search for 'coastal fencing Mumbles', 'salt-air resistant fencing Gower' and 'marine-grade fencing Swansea Bay' and find no specialists ranking. We rebuild the website around marine-grade 316 stainless fixings, Code 5+ galvanising, Iroko and Western Red Cedar specifications, build out coastal-fencing landing pages for the SA3 footprint, and drive review velocity from Mumbles-and-Gower customers to dominate the niche.",
    },
    {
      title: "Welsh-language west catchment invisible in English-only marketing",
      body: "Welsh-language community density west of Swansea (Gorseinon, Pontarddulais, Penclawdd, Llanrhidian, Loughor and the rural Gower-fringe) reaches 30–45% in some communities — and English-only fencing marketing converts measurably worse there than bilingual marketing. We build bilingual landing pages, Welsh-medium GBP descriptions, Welsh-language quote PDFs and Welsh-language ad creative ('ffensio', 'gosodwr ffensys', 'cyflenwr ffensys') for the western catchment, plus pursue Welsh-language commercial-tender work on Welsh-medium school perimeter, council park-fencing and bilingual-frontage commercial sites that the Welsh Language Standards (Wales) Measure 2011 effectively reserves for bilingual-capable fencers.",
    },
    {
      title: "Bristol-Channel storm-track damage volume across SA-postcodes dropping into voicemail",
      body: "Storm Eunice (February 2022) hit South Wales hard with documented 100mph+ gusts on the Gower; Babet (October 2023) and Isha–Jocelyn (January 2024) produced sequential events. Swansea fencing crews fielded 70–150 enquiries inside a 72-hour window with most going to voicemail. Each missed insurance-backed repair is £400–£1,500 and a full perimeter replacement is £2,500–£8,000 — a single missed storm week costs £25k–£50k of recoverable revenue. AI receptionist with photo-intake SMS, storm-mode triage and bilingual Welsh-English greeting captures the entire window without a dropped call.",
    },
    {
      title: "Mumbles–Sketty premium overflow and automated-gate enquiries routed through retail panel workflow",
      body: "The Mumbles (SA3) / Sketty (SA2) / Killay / West Cross belt produces a steady stream of £130–£250/m premium contemporary-slat and hardwood enquiries plus £4,000–£10,000 automated swing-pair and sliding-gate installs — a different funnel entirely from the £80–£130/m Morriston/Clydach retail volume work. Most Swansea fencers route these through the same form and quote them on the phone. Building parallel premium-and-automated-gate funnels typically grows premium-segment revenue 60–110% within 9 months because the Cardiff-commuter inflow into SA2/SA3 has lifted demand structurally.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat Swansea Fencing Services and Gower Fencing on SA-postcode searches?",
      a: "The wrong battle is trying to outrank Swansea Fencing Services or Gower Fencing on the generic 'fencing contractor Swansea' term. The right battle is SA-postcode-stratified local SEO with bilingual Welsh-language coverage where it matters. We build out separate GBP coverage and named-area landing pages for SA1 (city-centre/SA1 waterfront), SA2 (Sketty/Uplands/Brynmill), SA3 (Mumbles/Oystermouth/Bishopston/Gower), SA4 (Gorseinon/Pontarddulais — bilingual), SA5 (Cwmbwrla/Manselton), SA6 (Morriston/Clydach), SA7 (Llansamlet) and SA8 (Pontardawe), with genuinely local content — specific street types, fence styles common to the area's housing stock (Mumbles coastal-exposed marine-grade fixings, Sketty premium contemporary slat, Morriston retail close-board, Welsh-language GBP descriptions and quote PDFs for SA4). Swansea fencing clients running this stack typically rank in the top 3 for 8–14 SA-postcode searches inside 6 months and win bilingual commercial-tender work that English-only competitors cannot.",
    },
    {
      q: "Can the AI receptionist handle bilingual Welsh-English calls and storm volume on the Gower?",
      a: "Yes — bilingual Welsh-English greeting and qualifying flow is built in, and the AI handles Welsh-language calls (including Welsh place-names like Pontarddulais, Llanrhidian, Penclawdd) reliably with current-generation natural-language models. The greeting offers Cymraeg or English at first contact, and the qualifying flow runs in the chosen language end-to-end. During Storm Eunice (February 2022) — which hit South Wales with documented 100mph+ Gower gusts — and the Isha–Jocelyn double (January 2024), Swansea fencing crews running the AI receptionist captured 70–150 enquiries inside a 72-hour window with zero dropped calls. The AI takes the postcode (routing exposed Gower SA3 separately from inland SA6/SA7), photo intake via SMS link, captures household insurer name and claim reference, qualifies run-length and original fence type, books same-day boarding-up or full survey, and texts confirmation in the customer's chosen language. Storm-week revenue of £25k–£50k typically covers 12–18 months of Kerblabs fees.",
    },
    {
      q: "How do you help us pursue Welsh-language commercial-tender work that English-only competitors can't access?",
      a: "Yes — and the Welsh Language Standards (Wales) Measure 2011 effectively reserves Welsh-medium school-perimeter, council park-fencing and bilingual-frontage commercial-site procurement for bilingual-capable fencers. We build a separate B2B funnel with bilingual tender-response templates, Welsh-language case-study evidence (named completed Welsh-medium school or council-park work), CHAS/Constructionline/SafeContractor accreditations surfaced in schema, and bilingual landing pages targeting 'cyflenwr ffensys ysgolion Cymraeg', 'gosodwr ffensys cyngor Abertawe', 'commercial fencing contractor Swansea Welsh language', plus outreach to Swansea Council procurement, the West Glamorgan Education Consortium and the larger SA-region housing associations. Swansea fencing clients running this typically book 1–3 bilingual commercial framework wins per year alongside steady retail and coastal-specialism flow.",
    },
    {
      q: "How do you handle boundary-dispute enquiries from Swansea's older terraced and ex-industrial housing stock?",
      a: "This is built into the AI receptionist by default in both English and Welsh. Swansea's older terraced housing across SA1 (Sandfields, St Thomas), SA5 (Manselton), SA6 (Morriston ex-tinplate-and-steelworks streets) and parts of SA7 has a meaningful share of fence enquiries from properties in active boundary disputes — original ownership lines muddied by decades of ex-industrial housing reorganisations and informal repairs. The third question after job type and postcode is: 'Is there any current dispute with a neighbour about who owns this fence, or about exactly where the boundary line sits?' If the answer is yes, the AI never gives ownership advice — it explains, in the customer's chosen language, that fence ownership is not reliably shown on Land Registry title plans, that the 'T-mark' convention is informal and not legally binding, and that the customer should speak to a RICS-registered chartered surveyor or a property solicitor before commissioning fencing work that crosses a contested boundary. The enquiry is logged as 'boundary dispute' for follow-up. Swansea crews save 8–14 hours per month of unproductive site time.",
    },
  ],
  approach:
    "For Swansea fencing contractors, our 90-day approach is: (1) build SA-postcode-stratified Google Business Profile coverage and named-area landing pages with bilingual Welsh-English content for SA1 city-centre/waterfront, SA2 Sketty/Uplands/Brynmill, SA3 Mumbles/Oystermouth/Gower, SA4 Gorseinon/Pontarddulais (Welsh-language priority), SA5 Manselton/Cwmbwrla, SA6 Morriston/Clydach, SA7 Llansamlet and SA8 Pontardawe, with category-stacking (Fence Contractor + Fencing Supplier + Driveway gate installer + Gate); (2) build a parallel Gower coastal-salt-air specialism funnel surfacing marine-grade 316 stainless fixings, Code 5+ galvanising, Iroko and Western Red Cedar specifications and dedicated Mumbles-and-Gower coastal-fencing landing pages; (3) deploy AI 24/7 receptionist with bilingual Welsh-English greeting and qualifying flow, Bristol-Channel-storm-mode triage routing exposed Gower SA3 separately, photo-intake SMS, boundary-dispute RICS-referral qualifying flow, and insurance-claim capture; pre-build Swansea-and-Gower storm-response landing pages from September each year for Eunice / Babet / Isha capture; (4) build a parallel Mumbles-Sketty-Killay premium funnel surfacing premium specifications and Cardiff-commuter-tier positioning, plus a separate automated-gate funnel for the £4,000–£10,000 SA2/SA3 corridor surfacing BFT/FAAC/CAME/Nice motor competence and PSA TR1+/TR2 logbook compliance; plus a Welsh-language commercial-tender B2B funnel pursuing Welsh-medium school perimeter and council park-fencing work; and (5) drive Google review velocity to 8–15 new reviews per month tagged to SA-postcodes with bilingual review prompts to displace Swansea Fencing Services, Gower Fencing and Checkatrade in the local pack.",
};
