import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "funeral directors marketing Aberdeen",
    "Aberdeen funeral director SEO",
    "independent funeral director Aberdeen marketing",
    "John Fraser Mortlach competitor Aberdeen funeral",
    "Aberdeen direct cremation marketing",
  ],
  secondaryKeywords: [
    "Aberdeen Crematorium Hazlehead funeral director",
    "St Peter's Cemetery Trinity Cemetery Aberdeen",
    "oil industry expat repatriation funeral Aberdeen",
    "Aberdeen international funeral transport",
    "Aberdeen CMA Funerals Order 2021 Scotland",
    "Aberdeenshire Aberdeen city pre paid funeral plan",
    "Granite City funeral director Aberdeen",
    "Aberdeen Royal Infirmary funeral coordination",
  ],
  heroSubhead:
    "Aberdeen is Scotland's third-largest city and the UK's most distinctive funeral market because of its oil-and-gas industry expatriate population — repatriation funerals to Norway, the Netherlands, the United States, the Middle East and West Africa are routine work for Aberdeen specialist independents in a way no other UK city replicates. Aberdeen Crematorium at Hazlehead handles the city's cremation volume; St Peter's Cemetery, Trinity Cemetery, Allenvale Cemetery and Springbank Cemetery anchor the burial geography. Named local firms include John Fraser & Son and Mortlach Funeral Directors competing against Co-op Funeralcare's North-East Scottish estate. CPCs for 'funeral directors Aberdeen' run £3-£6, the average Scottish funeral cost is £4,061, and CMA pricing transparency under the 2021 Order applies in Scotland equally. Kerblabs builds AI funeral funnels for Aberdeen independents.",
  marketContext: [
    "Aberdeen is Scotland's third-largest city, with around 200,000 residents in the city itself and ~260,000 across Aberdeen city and the wider Aberdeenshire commuter belt. Annual deaths in Aberdeen run roughly 2,000-2,500 within the city and substantially more across Aberdeenshire including the oil-industry coastal towns of Stonehaven, Inverurie, Westhill, Banchory, Ellon and Peterhead. The Aberdeen funeral market is shaped by one structural feature no other UK city remotely shares: the international oil-and-gas industry expatriate population. Aberdeen has been the European oil capital since the 1970s North Sea discovery, and the resident expatriate community — Norwegian, Dutch, American, French, Brazilian, Indian, Nigerian, Angolan and Middle Eastern oil-industry employees and their families — generates routine demand for international repatriation funerals that no other UK independent funeral market handles at the same volume. A repatriation funeral involves: securing the death certificate and Scottish registrar paperwork, obtaining the relevant consular documentation (varies sharply by destination country — Saudi Arabia, UAE, Qatar, Norway, the United States and Brazil all have different embalming, documentation and casket requirements), arranging international air freight (typically through Amsterdam Schiphol or Frankfurt as European hubs, with Heathrow for transatlantic and Middle Eastern routes), coordinating with the receiving funeral director in the destination country, and handling specific embalming and casket protocols required for international transport (typically zinc-lined hermetic seal, specific export permits).",
    "Most Aberdeen independent funeral directors handle some repatriation work, but only a small number of named operators have the consular relationships, international logistics partnerships and specialist arrangers to handle high-volume oil-industry repatriation as a service line. John Fraser & Son and Mortlach Funeral Directors are among the named Aberdeen independents serving this segment alongside their domestic Aberdeen and Aberdeenshire work. The non-repatriation Aberdeen funeral market is more conventional: Aberdeen Crematorium at Hazlehead (operated by Aberdeen City Council, located at Hazlehead Park) handles the city's cremation volume; St Peter's Cemetery (King Street), Trinity Cemetery (Erroll Street), Allenvale Cemetery (Riverside Drive) and Springbank Cemetery (Countesswells Road) anchor the burial geography. Aberdeen has lower religious diversity than Glasgow or Edinburgh — the city's Muslim community is small and concentrated around the city centre and the University of Aberdeen catchment, with limited same-day Islamic burial volume. Christian and secular funerals dominate the domestic market.",
    "The competitive estate is dominated by Co-op Funeralcare's North-East Scottish branches, John Fraser & Son (one of Aberdeen's longest-standing family firms), Mortlach Funeral Directors, James Hogg Funeral Directors, Andrew Mortlach (operating across Aberdeenshire), and Funeral Partners-acquired branches. Aberdeen Google Ads CPCs for funeral keywords are lower than Glasgow or Edinburgh — 'funeral directors Aberdeen' £3-£6, 'direct cremation Aberdeen' £4-£9, 'pre paid funeral plan Aberdeen' £5-£12, 'repatriation funeral Aberdeen' very low CPC but exceptional conversion because the alternative provider set is tiny. The CMA Funerals Market Investigation Order 2021 applies in Scotland equally, and Aberdeen independents who are still semi-compliant face the same regulatory exposure. The oil-industry repatriation segment is genuinely under-marketed online — most international expatriate families use word-of-mouth, employer-HR referrals and embassy contact lists rather than Google search, but a minority of expatriate searches do start online and a properly built repatriation landing page can capture extremely high-value international work. Independents who win the next decade in Aberdeen combine 24/7 AI reception with international repatriation qualifying flow, CMA-compliant pricing pages, FCA-aware pre-need funnels, and review velocity in named neighbourhoods (Hazlehead, Cults, Rubislaw, Bridge of Don, Bucksburn, Stonehaven, Inverurie).",
  ],
  stats: [
    { value: "~2,000-2,500/yr", label: "deaths within City of Aberdeen", source: "National Records of Scotland" },
    { value: "European oil capital since 1970s", label: "drives unique oil-industry expatriate repatriation funeral demand" },
    { value: "£3-£6", label: "Google Ads CPC for 'funeral directors Aberdeen' 2024-2025" },
    { value: "£4,061", label: "average Scottish funeral cost 2024", source: "SunLife Cost of Dying Report" },
    { value: "Multiple destinations", label: "Norway, Netherlands, US, UAE, Saudi Arabia, Brazil, Nigeria, Angola routine repatriation routes" },
    { value: "~260,000", label: "Aberdeen city plus Aberdeenshire commuter belt population including Stonehaven, Inverurie, Westhill", source: "National Records of Scotland" },
  ],
  painPoints: [
    {
      title: "International oil-industry repatriation work flowing to a small named-specialist set",
      body: "Aberdeen's expatriate oil-industry population generates routine demand for international repatriation funerals, but most independent firms don't position for this work explicitly online. Without a dedicated repatriation landing page covering the consular documentation, embalming protocols, international air freight partnerships and destination-country funeral director relationships, you lose this exceptionally high-value work to the small number of Aberdeen specialists who do market for it. We build a structured repatriation funnel.",
    },
    {
      title: "Pure Cremation and Aura's cost-led marketing fitting Aberdeen's professional demographic",
      body: "Aberdeen's professional households across Cults, Rubislaw, Hazlehead and Westhill are receptive to direct cremation disruptors' £1,195 product. We build a credible local direct cremation page at competitive pricing so Aberdeen families who want unattended cremation choose a local Aberdeen family firm rather than a national TV-advertised brand handling their parent.",
    },
    {
      title: "Co-op Funeralcare's North-East estate dominance squeezing single-branch family firms",
      body: "Co-op Funeralcare's North-East Scotland branches use post-CMA pricing aggressively to defend volume across Aberdeen and Aberdeenshire. Long-standing family firms in Stonehaven, Inverurie, Ellon and Banchory can lose 20-30% of their at-need pipeline to a Co-op branch nearby within 18 months without active counter-marketing. We rebuild local SEO, GBP optimisation, review velocity and family-firm positioning to defend the catchment.",
    },
    {
      title: "CMA Funerals Order 2021 applies in Scotland but compliance is patchy across smaller Aberdeen firms",
      body: "Some Aberdeen smaller firms have absorbed the assumption that the CMA Order is 'an English thing' — it isn't. The CMA's jurisdiction is UK-wide and the 2021 Order applies equally in Scotland. Many Aberdeen single-branch firms have pricing buried, missing the standardised template, or lacking a Disclosure of Interests document. We rebuild your Standardised Price List page using the exact template, link it from primary navigation as 'Our Prices', and rank it for 'funeral prices Aberdeen' and named-area variants.",
    },
  ],
  faqs: [
    {
      q: "How do you build a credible international oil-industry repatriation funnel for an Aberdeen independent?",
      a: "Repatriation marketing is fundamentally different from domestic at-need marketing. The customer is often an HR manager at an oil-industry employer, an embassy or consular officer, or a family member of an expatriate worker, and the search journey starts with destination-country-specific queries: 'repatriation funeral Norway Aberdeen', 'death of expatriate UAE Aberdeen', 'send body to United States from Aberdeen'. We build a structured repatriation landing page covering the consular documentation requirements per major destination country (Norway, Netherlands, USA, Saudi Arabia, UAE, Qatar, Brazil, Nigeria, Angola, India), the embalming and casket protocols (zinc-lined hermetic seal, export permits, freight handling), the international air freight partnerships (Amsterdam Schiphol, Frankfurt, Heathrow), and the receiving-country funeral director relationships you've built. We add HR-manager and embassy-officer-targeted content in plain English that explains the process clearly. The AI receptionist's qualifying flow recognises repatriation references early ('we need to send him home', 'his family is in Norway', 'she died offshore') and triggers a specialist arrangement appointment with extra time for consular planning. Even capturing 1-3 repatriation jobs per month from this funnel is exceptional revenue given the £8,000-£25,000 typical job value.",
    },
    {
      q: "How does the AI receptionist handle a 3am bereavement call from Aberdeen with the warmth and dignity expected of a Granite City family firm?",
      a: "The AI's first words are warm, slow acknowledgement of the loss in plain English with a North-East Scotland-appropriate cadence — formal where needed, never rushed, never marketing-toned. Tone and pacing are tuned with your principal arranger so it matches the house style of an established Aberdeen family firm. The qualifying flow asks gently whether the family follows any specific tradition that matters for the arrangement (Christian, secular, other, repatriation-required), gathers the deceased's full name, current location (Aberdeen Royal Infirmary, Woodend, Roxburghe House hospice, home, care home, offshore platform if relevant), the caller's relationship and contact details, and immediate practical needs around removal. For offshore deaths or expatriate cases the AI flags repatriation-likely and routes accordingly. It confirms the duty arranger will call back within 30 minutes and pages your senior arranger with full transcript. The AI never asks for credit card details on a first call, never quotes a price, and never pushes optional services.",
    },
    {
      q: "How do you compete against Co-op Funeralcare's North-East Scottish estate without matching their marketing budget?",
      a: "Co-op Funeralcare wins on raw paid-search spend, brand awareness and branch density across Aberdeen and Aberdeenshire, and we don't try to match them on those battlegrounds. Independents win on three things Co-op is structurally bad at: hyperlocal review velocity in a single area (a 150-review independent in Cults, Hazlehead, Stonehaven or Inverurie crushes a Co-op branch with 30 reviews on local pack ranking), specialist-service depth (Co-op's training is generic and they don't market for international repatriation seriously, leaving that exceptionally high-value segment to specialists), and family-firm continuity (named multi-generational arranger answering at 3am beats a Co-op branch manager every time). We rebuild your local SEO with named-neighbourhood landing pages (Cults, Rubislaw, Hazlehead, Bridge of Don, Bucksburn, Stonehaven, Inverurie, Westhill, Banchory, Ellon), drive review velocity to 6-12 monthly reviews mentioning specific Aberdeen and Aberdeenshire areas, and surface your family-firm history and any specialist credentials prominently.",
    },
    {
      q: "Can an Aberdeen independent realistically rebuild pre-need plan revenue after the FCA clampdown and Safe Hands collapse?",
      a: "Yes. Aberdeen is a moderate-strength pre-need market — the city's professional households across Cults, Hazlehead, Rubislaw and Westhill historically buy pre-paid plans at solid rates, and Scottish overall pre-need adoption is above the UK average. Public awareness of the Safe Hands collapse and FCA regulation is high. We build a content-led, FCA-aware pre-need funnel: long-form educational pages explaining what FCA authorisation now means, why Safe Hands failed (Continuity of Care Trust, no FCA oversight, ~46,000 customers, ~£60m lost), the difference between trust-based and insurance-based plans, and exactly which FCA-authorised provider you distribute (Golden Charter has strong Scottish market share among independents and is FCA-authorised; some firms use Ecclesiastical). Lead capture routes to in-branch appointment or a regulated phone consultation with the provider. Aberdeen paid search for 'pre paid funeral plan Aberdeen' is £5-£12 CPC and converts well when the landing page leads with regulation and trust. Done well this rebuilds 4-12 qualified pre-need leads per month.",
    },
  ],
  approach:
    "For Aberdeen independent funeral directors, our 90-day playbook is: (1) deploy 24/7 AI receptionist with tone tuned to match an established Granite City family firm and an international repatriation qualifying flow that recognises offshore-death and expatriate-family references; (2) build a structured oil-industry repatriation landing page covering consular documentation per major destination country, embalming protocols, international air freight partnerships and receiving-country funeral director relationships; (3) rebuild your CMA Funerals Order 2021 Standardised Price List page (the Order applies in Scotland equally) ranking for 'funeral prices Aberdeen' and named-area variants; (4) launch a credible local direct cremation product page to defend Cults, Hazlehead and Westhill volume against Pure Cremation and Aura; and (5) drive Google review velocity to 6-12 monthly reviews mentioning Cults, Rubislaw, Hazlehead, Bridge of Don, Stonehaven, Inverurie, Westhill, Banchory and Ellon.",
};

export { industry } from "../industries/funeral-directors";
