import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "junk removal marketing Cardiff",
    "house clearance marketing Cardiff",
    "Cardiff rubbish removal SEO",
    "Cardiff bilingual Welsh English clearance",
    "Cardiff probate executor clearance marketing",
  ],
  secondaryKeywords: [
    "Natural Resources Wales NRW Waste Carrier registration",
    "Cardiff Bay turnover end of tenancy clearance",
    "University of Cardiff Met student clearance",
    "Pontcanna Cyncoed Lisvane premium probate clearance",
    "Welsh language Cymraeg clearance marketing",
    "AnyJunk Clearabee competitor Cardiff Wales",
    "Cathays Roath student turnover clearance Cardiff",
    "Cardiff Capital Region regeneration clearance",
  ],
  heroSubhead:
    "Cardiff's clearance market operates under Welsh-specific rules that English imports rarely handle correctly. Wales' waste regulator is Natural Resources Wales (NRW) under the Waste (Wales) Measure 2010 and the Environment (Wales) Act 2016 — a separate framework from the English Environment Agency, with distinct registration requirements and a Welsh-specific Statutory Code of Practice on the Carriage of Controlled Waste. Wales operates a higher household recycling rate target (70% by 2025, already at ~64%, the highest in the UK) and the Wales Recycling Targets create commercial-clearance pressure no English city has. Cardiff has no Clean Air Zone (proposal withdrawn 2022), giving operators a fleet-cost advantage. The Welsh-language opportunity is genuine — bilingual marketing, Welsh-language website content and Welsh-speaking AI receptionist capability differentiates Cardiff operators in Pontcanna, Roath, Canton and the broader Welsh-speaking professional cohort. Cardiff Bay turnover, the 60,000+ student population across Cardiff University and Cardiff Met, and Pontcanna / Cyncoed / Lisvane / Radyr premium catchments running £1,200–£3,000 probate clearances complete the picture.",
  marketContext: [
    "Cardiff's clearance market is shaped by three forces that distinguish it from comparable English cities. First, Welsh-specific waste regulation — Wales operates under Natural Resources Wales (NRW), a different regulator from the Environment Agency that covers England, with the Waste (Wales) Measure 2010, the Environment (Wales) Act 2016, and the Statutory Code of Practice on the Carriage of Controlled Waste in Wales (which has distinct provisions from the English Duty of Care Code). Wales has the UK's highest statutory recycling target — 70% by 2025, already at 64.7% household recycling rate (England runs ~44%, Scotland ~43%, Northern Ireland ~50%) — and the Welsh Government's Beyond Recycling strategy and Towards Zero Waste programme have created sustained commercial pressure on clearance operators to demonstrate high diversion-from-landfill rates. Welsh letting agents, solicitors and procurement teams notice when operators surface English Environment Agency credentials and English Duty of Care wording — it signals incompetence with Welsh territory. Second, Cardiff has no Clean Air Zone — the proposed CAZ was withdrawn in 2022 after the Welsh Government's 20mph default speed limit policy and other measures secured air-quality improvements without charging. This is a structural fleet-cost advantage over English CAZ cities (Birmingham, Bradford, Sheffield, London).",
    "Third, the Welsh-language opportunity is genuine and under-served. Cardiff has approximately 36,000 Welsh speakers (about 11% of the population), concentrated in Pontcanna, Canton, Roath, the Cathays / Welsh-medium school catchment, and the broader Welsh professional cohort working at S4C, BBC Cymru Wales, the Welsh Government, the Senedd, Welsh-medium education sector, and Welsh-language media. The Welsh Language (Wales) Measure 2011 gives Welsh equal status with English in Wales and creates statutory expectations for bilingual service across public-sector procurement. Operators with bilingual website content, Welsh-language Google Business Profile descriptions, Welsh-speaking AI receptionist capability (configurable), and Welsh-language case studies differentiate meaningfully in the Welsh-speaking professional catchment — and pull Welsh-medium-school-catchment family clearance work that English-only operators are invisible to. Cardiff Capital Region (the £1.2bn+ regional regeneration programme), Cardiff Bay ongoing turnover, Cardiff Central Square redevelopment, plus the Cardiff Parkway, Newport Knowledge Quarter and Bridgend regeneration corridors collectively produce sustained demolition-supply-chain demand.",
    "Cardiff Google Ads CPCs in clearance keywords sit at the lower-mid range: 'house clearance Cardiff' clicks at £1.40–£3.20, 'rubbish removal Cardiff' at £1.20–£2.80, 'student end of tenancy clearance Cardiff' at £2.20–£4.40 in June-July peak. Three-bed full house clearances run £450–£1,200 retail across Cardiff generally, with Pontcanna, Cyncoed, Lisvane, Radyr and the wider Vale of Glamorgan premium catchments supporting £900–£2,000 and probate clearances reaching £1,200–£3,000. Borough-stratified Google Ads + Local Service Ads + Maps optimisation reliably produce £18–£40 cost-per-acquired-job versus £80–£150 on Bark and aggregator platforms. Kerblabs' Cardiff clearance clients running this stack typically reach 6–10 booked jobs per week per van inside 6 months, with the Welsh-bilingual positioning and the Cardiff Bay / Capital Region B2B funnel each adding distinct channels.",
  ],
  stats: [
    { value: "64.7%", label: "Welsh household recycling rate — UK's highest, target 70% by 2025", source: "StatsWales / Welsh Government" },
    { value: "36,000+", label: "Cardiff Welsh speakers (approximately 11% of population) — bilingual marketing opportunity", source: "ONS Census 2021" },
    { value: "Withdrawn 2022", label: "Cardiff Clean Air Zone proposal — fleet-cost advantage over English CAZ cities" },
    { value: "£450–£1,200", label: "typical Cardiff three-bed full house clearance price range" },
    { value: "£900–£2,000", label: "Pontcanna / Cyncoed / Lisvane / Radyr premium catchment full house clearance" },
    { value: "£1.20–£4.40", label: "Google Ads CPC range for Cardiff clearance keywords 2024–2025", source: "Kerblabs client accounts" },
  ],
  painPoints: [
    {
      title: "English-imported brands using EA Waste Carrier language Welsh customers find wrong",
      body: "NRW (not Environment Agency) is Wales' waste regulator, the Waste (Wales) Measure 2010 and Environment (Wales) Act 2016 (not English equivalents) apply, and the Statutory Code of Practice on the Carriage of Controlled Waste in Wales has distinct provisions from English Duty of Care. English-imported clearance brands routinely surface EA registration numbers and English-specific compliance copy that signals to Welsh solicitors, letting agents and procurement teams that the operator doesn't know the territory. We rebuild every customer-facing surface with Welsh-specific compliance language and NRW Upper-Tier Waste Carrier registration prominence."
    },
    {
      title: "Welsh-language opportunity entirely missed by English-only operators",
      body: "Cardiff's 36,000+ Welsh speakers and the broader Welsh-medium-school catchment produce clearance demand that English-only marketing is invisible to. Bilingual website content, Welsh-language Google Business Profile descriptions, Welsh-speaking AI receptionist capability, and Welsh-language case studies differentiate meaningfully in Pontcanna, Canton, Roath, Cathays and the Welsh professional cohort. We build the Welsh-bilingual marketing infrastructure that captures this overlooked segment."
    },
    {
      title: "Cathays / Roath / Cardiff Bay student turnover crowded with under-prepared operators",
      body: "Cardiff's June-July student peak attracts dozens of operators competing for end-of-tenancy work across Cathays, Roath, Heath, the Cardiff Bay PBSA cluster, and Cyncoed (around Cardiff Met campus). Most show up without panel relationships with CPS Homes, Property Management Wales, Hunters Cardiff or the developer-managed PBSA blocks (Unite, Vita Student, Crown Place, Tramshed Tech), without capacity planning, and miss their share of the panel volume. We build the panel applications and capacity-planning infrastructure."
    },
    {
      title: "Pontcanna / Cyncoed / Lisvane / Radyr premium probate volume invisible without B2B funnel",
      body: "Cardiff's premium catchments produce steady probate clearance volume sourced through Cardiff solicitor networks (Hugh James — Cardiff-headquartered, plus Geldards, Capital Law, Acuity Law, Eversheds Sutherland's Cardiff office, Berry Smith, Wendy Hopkins Family Law, plus 150+ smaller firms across South Wales) and chartered surveyors. Without a probate-specific landing page, structured B2B outreach and STEP South Wales Branch positioning, you're invisible to £1,200–£3,000 per-job work."
    },
  ],
  faqs: [
    {
      q: "Is the Welsh-language bilingual marketing opportunity actually worth the investment for a clearance operator?",
      a: "Yes — and it's structurally under-served. Cardiff has 36,000+ Welsh speakers (~11% of population), with concentrations in Pontcanna, Canton, Roath, Cathays (around the Welsh-medium school catchment of Ysgol Mynydd Bychan, Ysgol Glan Morfa, Ysgol Pwll Coch and the secondary at Ysgol Plasmawr), plus the Welsh professional cohort working at S4C, BBC Cymru Wales, the Welsh Government, the Senedd, Welsh-medium education sector, plus Welsh-language media. The investment is modest: bilingual website (cy/en switcher, professionally translated by a Welsh-medium copywriter — costs £800–£2,500 for a clearance operator's site), Welsh-language Google Business Profile description (free), Welsh-speaking AI receptionist capability (configurable in our platform with a Welsh-language voice tier), Welsh-language case studies (1–2 per quarter), and Welsh-language Meta and Google Ads creative for the Welsh-medium-school-catchment audience. Welsh-language clearance searches are low-volume but high-intent — competition is essentially zero, conversion rates are 2–4x English-language equivalents in the Welsh-speaking catchment, and the positioning lifts Welsh Government, Senedd, S4C and BBC Cymru Wales B2B and corporate-relocation work. Cardiff clearance clients with bilingual infrastructure typically book 1–3 high-value Welsh-speaking-catchment jobs per month plus occasional Welsh public-sector and broadcaster work."
    },
    {
      q: "How exactly does Welsh waste regulation differ from England, and does it actually matter for marketing?",
      a: "Yes — meaningfully. Wales operates under Natural Resources Wales (NRW) as the regulator, with the Waste (Wales) Measure 2010 and the Environment (Wales) Act 2016 providing the statutory framework. Waste Carrier Registration in Wales uses Upper Tier (mandatory for clearance operators transporting third-party waste) and Lower Tier (own waste only) with NRW-issued certificates rather than EA-issued. The Statutory Code of Practice on the Carriage of Controlled Waste in Wales has distinct provisions including specific requirements around waste transfer notes for non-hazardous waste, and the Welsh Government's Beyond Recycling strategy creates commercial pressure for landfill diversion at higher rates than England requires. Welsh letting agents, solicitors and procurement teams (particularly Welsh public-sector procurement under the Wales Procurement Policy Statement) notice when operators surface EA Waste Carrier numbers and English-specific compliance copy. We rebuild every customer-facing surface with NRW Upper-Tier Waste Carrier registration prominently displayed, Welsh-specific Code of Practice wording, and recycling-rate evidence aligned with the Welsh 70% target. This typically lifts B2B conversion rates 25–35% with Welsh public-sector and Welsh-business customers."
    },
    {
      q: "How do we get onto Cardiff Capital Region or Cardiff Bay regeneration main-contractor frameworks?",
      a: "Three parallel workstreams. First, accreditation infrastructure — Constructionline Gold (mandatory for the larger Cardiff Capital Region packages), ISO 9001/14001/45001, NRW Upper-Tier Waste Carrier with named transfer-station partners (Veolia Cardiff, Suez Cardiff, Biffa, FCC), Hazardous Waste consignor registration with NRW (the Welsh equivalent of the English EA registration), Goods in Transit insurance £25k+, public liability £10M+. Second, main-contractor relationship mapping — Wates (significant Cardiff and South Wales presence), ISG (recently restructured), Galliford Try, Vinci Construction, Bouygues UK, plus Welsh-specific contractors (Andrew Scott, Knox & Wells, John Weaver Contractors, Encon Construction, Wynne Construction). Pre-qualified-supplier-list registration plus structured procurement-team outreach, ideally with Welsh-language capability where the contractor has Welsh-medium operations. Third, framework visibility — Cardiff Council frameworks, Cardiff Capital Region procurement, the National Procurement Service for Wales, Sell2Wales (Welsh-specific procurement portal), and the Welsh Government Construction Framework. We map and run all three in parallel, typically opening 1–3 framework opportunities per quarter inside the first six months."
    },
    {
      q: "Is the Pontcanna / Cyncoed / Lisvane / Radyr premium probate market really worth a dedicated B2B funnel?",
      a: "Yes — and the channel benefits from the Welsh-language differentiation alongside standard premium-catchment positioning. Cardiff probate solicitors include Hugh James (Cardiff-headquartered with substantial South Wales probate volume), Geldards (Cardiff and Nottingham), Capital Law, Acuity Law, Eversheds Sutherland's Cardiff office, Berry Smith, Wendy Hopkins Family Law, plus 150+ smaller firms across Cardiff, the Vale of Glamorgan, Newport, Bridgend and the broader South Wales footprint. Welsh-speaking probate solicitors specifically include the Welsh-medium-trained partners at Hugh James and Geldards plus a cluster of independent firms serving Welsh-speaking clients. Chartered surveyors handling contents valuations include Rogers Jones Auctioneers (Cardiff-based, leading Welsh fine-art auctioneer), Anthemion Auctions, plus a cluster of RICS-registered Cardiff and South Wales house-clearance valuers. We build a probate-specific landing page (bilingual where it serves Welsh-speaking catchments) optimised for 'probate house clearance Cardiff', 'executor clearance Pontcanna', 'clirio ty etifeddiaeth Caerdydd' (Welsh: probate house clearance Cardiff), 'probate clearance Cyncoed' etc., plus structured solicitor outreach (LinkedIn + targeted email + STEP South Wales Branch + Law Society Wales events). Cardiff clearance clients typically book 2–4 probate jobs per month at £1,200–£3,000 average within 6–9 months."
    },
  ],
  approach:
    "For Cardiff junk removal and house clearance firms, our 90-day playbook is: (1) rebuild every customer-facing surface with Welsh-specific compliance language — NRW Upper-Tier Waste Carrier registration, Welsh Code of Practice on Controlled Waste wording, recycling-rate evidence aligned with Welsh 70% target — replacing any English Environment Agency references; (2) install bilingual marketing infrastructure (cy/en website switcher, Welsh-language GBP description, Welsh-speaking AI receptionist option, Welsh-language case studies and creative) to capture the 36,000+ Welsh speakers and Welsh-medium-school catchment; (3) build student-letting and PBSA panel-application packs to CPS Homes, Property Management Wales, Hunters Cardiff, Unite, Vita Student, Crown Place and 6+ developer-management arms, submitted in January-April for June-July inclusion; (4) deploy a probate B2B funnel with Pontcanna/Cyncoed/Lisvane/Radyr landing pages and structured solicitor outreach to Hugh James, Geldards, Capital Law, Acuity Law and the Cardiff probate-firm network; and (5) drive Google review velocity to 8–14 new reviews per month with bilingual keyword density across both English and Welsh search terms.",
};
