import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "junk removal marketing Edinburgh",
    "house clearance marketing Edinburgh",
    "Edinburgh rubbish removal SEO",
    "Edinburgh festival short term let clearance",
    "Edinburgh probate confirmation executor clearance",
  ],
  secondaryKeywords: [
    "Edinburgh Low Emission Zone LEZ Euro 6 clearance",
    "STL licensing short term let Edinburgh impact",
    "festival August clearance turnover Edinburgh",
    "New Town Old Town listed tenement clearance",
    "Morningside Bruntsfield premium probate clearance",
    "SEPA Waste Carrier Registration Edinburgh",
    "AnyJunk Clearabee competitor Edinburgh Scotland",
    "Stockbridge Marchmont end of tenancy clearance",
  ],
  heroSubhead:
    "Edinburgh's clearance market has been rewritten by two policies most operators still don't market against properly. Edinburgh's STL (Short-Term Let) Control Area was approved September 2022 and the Scotland-wide STL licensing scheme became fully mandatory 1 October 2023 — collapsing thousands of unlicensed Airbnb units into either licensed-STL operation, conversion back to long-term let, or sale. That conversion process has produced a multi-year wave of full-flat clearance jobs as STL operators exit the market, plus ongoing turnover among compliant STLs after every Festival August. Edinburgh's LEZ went live 1 June 2024 covering the city centre with outright bans (not paid charging like London ULEZ) on non-Euro 6 diesel and non-Euro 4 petrol vehicles. Edinburgh's premium catchment — New Town, Morningside, Bruntsfield, Stockbridge, the Grange, Merchiston — produces the UK's highest concentration of listed Georgian and Victorian tenement clearances after London, with Confirmation-process executor work running £2,000–£5,500 per clearance. Add 47,000+ University of Edinburgh, Heriot-Watt and Edinburgh Napier students, the Festival-August short-let cleanup peak, and the Scotland-specific SEPA / Confirmation regulatory framework, and Edinburgh clearance operators need a Scotland-specific marketing system Kerblabs builds.",
  marketContext: [
    "Edinburgh's clearance market is shaped by three structural forces that distinguish it from every other UK city. First, STL licensing — Edinburgh became Scotland's first designated Short-Term Let Control Area on 5 September 2022, which means change-of-use planning consent is required to operate a property as an STL. Combined with the Scotland-wide STL licensing scheme (mandatory 1 October 2023), this has effectively shut down a large segment of the unlicensed Airbnb / Booking.com market in central Edinburgh that had grown to an estimated 12,000+ units by 2019. The conversion process has produced and continues to produce a multi-year wave of full-flat clearance work as exiting STL operators clear furniture, linens, kitchenware and contents to either return the property to long-term let, sell, or convert to alternative use. Compliant licensed STLs additionally drive ongoing turnover-and-refresh clearance after every Festival August (the August Edinburgh Festival, Fringe, International, Book Festival, and Tattoo collectively bring 4.4M+ visitor-attendance with most STL units fully booked across the four-week period and frequently refreshed at season end). Second, Edinburgh's LEZ went fully enforceable 1 June 2024 with outright bans (not charging) on non-compliant vehicles inside the LEZ boundary — Princes Street, the Royal Mile, the New Town, the Grassmarket and the broader Old/New Town World Heritage Site geography — with £60 first penalty doubling to £960 maximum.",
    "Third, Edinburgh's housing stock is dominated by listed Georgian and Victorian tenement flats — the New Town and Old Town are jointly UNESCO World Heritage Site, and the broader central Edinburgh stock includes substantial Category A, B and C listed buildings under Historic Environment Scotland's listing regime. Tenement clearance with listed-fabric handling is a Edinburgh specialism: original lath-and-plaster ceilings, sash-and-case windows, original cast-iron banisters and stair lighting, period skirting and cornicing all require protection during clearance, and the Edinburgh World Heritage Trust plus City of Edinburgh Council's Conservation team take a closer interest in clearance work than most council conservation teams elsewhere. Pricing is meaningfully higher than Glasgow tenement clearance: 3-bed top-floor New Town tenement clearance typically runs £900–£1,800, 4-bed at £1,400–£2,800, and full Georgian townhouse clearances in the New Town and Stockbridge premium catchment reach £4,000–£10,000 on multi-floor properties with 30+ years of accumulated contents. Premium catchments — New Town (EH3, EH2), Morningside (EH10), Bruntsfield (EH10), Stockbridge (EH3, EH4), the Grange (EH9), Merchiston (EH10), Murrayfield (EH12) — sustain £2,000–£5,500 probate clearances and routine end-of-tenancy work at £600–£1,800 per typical flat clearance.",
    "Edinburgh Google Ads CPCs in clearance keywords run higher than Glasgow but below London: 'house clearance Edinburgh' clicks at £2.20–£5.20, 'rubbish removal Edinburgh' at £1.80–£4.40, 'short term let clearance Edinburgh' (a Edinburgh-specific high-intent term) at £3.60–£7.40, 'festival clearance Edinburgh' at £4.80–£9.20 in August peak. Borough-stratified Google Ads + Local Service Ads + Maps optimisation reliably produce £30–£60 cost-per-acquired-job versus £140–£260 on Bark and aggregator platforms. The STL-exit funnel and Festival-turnover funnel are Edinburgh-specific channels that aggregators don't recognise — operators positioned for these capture a meaningful share of work that retail-search competitors never see. Kerblabs' Edinburgh clearance clients running this stack typically reach 6–11 booked jobs per week per van inside 6 months, with Confirmation-process executor work and STL-conversion work each adding 4–8 high-value jobs per month at £1,500–£5,500 average.",
  ],
  stats: [
    { value: "1 October 2023", label: "Scotland-wide Short-Term Let licensing fully mandatory — driving multi-year STL-exit clearance wave", source: "Scottish Government" },
    { value: "1 June 2024", label: "Edinburgh LEZ full enforcement — non-Euro 6 diesel banned from city centre with £60–£960 penalties", source: "City of Edinburgh Council" },
    { value: "4.4M+", label: "Edinburgh August festival attendance driving STL turnover-and-refresh clearance peak", source: "Edinburgh Festivals" },
    { value: "£900–£1,800", label: "typical Edinburgh 3-bed top-floor New Town tenement clearance" },
    { value: "£4,000–£10,000", label: "New Town / Stockbridge full Georgian townhouse probate clearance" },
    { value: "£2.20–£9.20", label: "Google Ads CPC range for Edinburgh clearance keywords (peaking on August festival terms)", source: "Kerblabs client accounts" },
  ],
  painPoints: [
    {
      title: "STL-exit clearance volume invisible without a dedicated funnel",
      body: "Scotland's STL licensing has effectively shut down thousands of unlicensed Edinburgh Airbnb / Booking.com units, producing ongoing full-flat clearance work as operators exit. This volume flows through STL property managers (Citystay, Destiny Scotland, Edinburgh Holiday Apartments, plus 150+ smaller operators), letting-agent conversions back to long-term let, and direct-from-owner sale-prep. Without an STL-conversion-aware landing page, structured outreach to STL property managers and Edinburgh letting agents handling conversions, this multi-year wave is invisible."
    },
    {
      title: "Festival-August turnover capacity chaos costing peak-week revenue",
      body: "Edinburgh's August Festival peak drives 4.4M+ visitor attendance and full STL occupancy across Edinburgh, with most operators refreshing units immediately post-festival (early September). Operators without capacity-planning infrastructure, sub-contracted vehicle availability and pre-built STL-property-manager relationships either turn work away in early September or surge-price chaotically. We build the capacity-planning infrastructure that turns Festival-end into a revenue spike captured cleanly."
    },
    {
      title: "LEZ-non-compliant fleet locked out of New Town / Old Town with no paid escape",
      body: "Edinburgh LEZ bans non-compliant vehicles outright (£60–£960 penalties) rather than charging like London ULEZ. Operators with pre-Euro-6 fleet have lost central Edinburgh work entirely. We help compliant operators surface compliance prominently (Edinburgh LEZ check-tool screenshots, Euro 6 certification on landing pages and GBP) to capture the inner-city work non-compliant competitors can't legally service."
    },
    {
      title: "Listed-tenement clearance under-priced because pricing model ignores fabric protection requirements",
      body: "New Town, Old Town, Stockbridge, Bruntsfield and Morningside have substantial listed-building coverage with original lath-and-plaster, sash-and-case windows, cast-iron banisters and period fabric requiring protection during clearance. Operators using generic flat-clearance pricing routinely lose 15–30% margin on listed-tenement work or cause damage that destroys customer satisfaction. We rebuild pricing with listed-fabric protection materials and protocols as primary inputs."
    },
  ],
  faqs: [
    {
      q: "How do we actually build the STL-exit clearance funnel in Edinburgh?",
      a: "Three components. First, an STL-conversion-aware landing page optimised for 'short term let clearance Edinburgh', 'Airbnb conversion clearance Edinburgh', 'STL exit clearance Edinburgh', plus content explaining the 1 October 2023 Scotland STL licensing implications and the 5 September 2022 Edinburgh STL Control Area. Second, structured B2B outreach to Edinburgh STL property managers (Citystay, Destiny Scotland, Edinburgh Holiday Apartments, Mansley Serviced Apartments, Stay Edinburgh, plus 150+ smaller operators identified through STL licensing register data which is publicly accessible), Edinburgh letting agents handling STL-to-long-term conversions (Murray & Currer, ESPC member firms, Edinburgh Letting Agents network), and direct-from-owner sale-prep work via Edinburgh estate agents (ESPC's network of 200+ member firms). Third, a 24-hour clearance SLA with Confirmation-process documentation for STL operators winding up estates after a deceased owner's STL business. Edinburgh clearance clients running this funnel typically book 4–8 STL-conversion jobs per month at £900–£3,500 average — work that aggregator platforms surface essentially never."
    },
    {
      q: "How do we actually capture the Festival-August / early-September turnover peak?",
      a: "The peak window is roughly 28 August through 15 September — the four-week period after the festivals end (Edinburgh Fringe traditionally runs to the last Sunday of August, with the International Festival, Book Festival and Tattoo concluding around the same time). Most Edinburgh STLs are fully booked across the entire August window and are refreshed (deep clean, replace damaged furniture, dispose of broken items, repair-and-replace where guests have caused issues) immediately post-festival. The capacity-planning approach: pre-book sub-contracted vehicle availability for 28 August through 15 September (typically 2–4 additional Luton tippers booked from named partners), pre-built relationships with the 30+ largest Edinburgh STL property managers, an AI receptionist with a Festival-aware booking flow that prioritises STL property-manager jobs against retail capacity, and a Festival-specific landing page optimised for STL turnover-and-refresh keywords. Edinburgh clearance clients running this approach typically capture 8–18 jobs per week in the peak window at £350–£900 per typical STL refresh, contributing 12–18% of annual revenue from a 3-week peak."
    },
    {
      q: "How does Scottish Confirmation differ from English Probate, and how does that change the executor clearance funnel?",
      a: "Confirmation in Scotland is the legal equivalent of English Probate, but with materially different process and language that solicitors notice. Confirmation is issued by the Sheriff Court (not the Probate Registry) following submission of an inventory listing heritable property (land and buildings) and moveable property (everything else, including contents) separately. The executor — once Confirmation is granted — has authority to deal with the deceased's estate. Edinburgh Confirmation solicitors include Brodies LLP (Edinburgh-headquartered with substantial probate volume), Burness Paull, Shepherd and Wedderburn, Anderson Strathern, Turcan Connell, Murray Beith Murray, Gillespie Macandrew, plus 200+ smaller Edinburgh and Lothian firms. Chartered surveyors handling moveable-property inventories include Lyon & Turnbull (Edinburgh-headquartered, the leading Scottish auctioneer for fine art and antiques), Bonhams Edinburgh, Sotheby's Edinburgh representation, plus a cluster of RICS-registered Edinburgh house-clearance valuers. We build a Confirmation-specific landing page optimised for 'executor house clearance Edinburgh', 'confirmation clearance New Town', 'executor clearance Morningside', plus structured solicitor outreach (LinkedIn + targeted email + Law Society of Scotland Edinburgh events + STEP Edinburgh Branch). Edinburgh clearance clients typically book 3–6 Confirmation jobs per month at £2,000–£5,500 average within 6–9 months."
    },
    {
      q: "Can we really compete against AnyJunk and Clearabee in Edinburgh given Scottish-specific compliance requirements they handle generically?",
      a: "Yes — and Scottish-specific compliance is your structural advantage, not a weakness. AnyJunk and Clearabee operate UK-wide with English-template compliance copy that surfaces Environment Agency Waste Carrier registration and Hazardous Waste Regulations 2005 — both of which are technically wrong for Scottish work, where SEPA Waste Carrier Registration and the Special Waste Regulations 1996 apply. Scottish letting agents, solicitors and procurement teams notice the difference. We rebuild your customer-facing surfaces with SEPA Upper-Tier Waste Carrier registration prominently displayed, Special Waste Regulations consignor registration where applicable, Confirmation-process executor copy, and Scotland-specific Duty of Care wording. Combined with Edinburgh-specific positioning (LEZ-compliant fleet, listed-tenement specialism, STL-conversion funnel, Festival-August turnover capacity), Scottish independents reliably outperform UK-wide nationals on borough-level Edinburgh search and B2B-channel work. Edinburgh clearance clients typically reduce aggregator dependency from 50% to 18% inside 6 months while growing total job volume."
    },
  ],
  approach:
    "For Edinburgh junk removal and house clearance firms, our 90-day playbook is: (1) build the STL-exit clearance funnel with structured outreach to Citystay, Destiny Scotland, Edinburgh Holiday Apartments and 150+ smaller STL property managers plus Edinburgh letting agents handling STL-to-long-term conversions; (2) install Festival-August capacity-planning infrastructure — pre-booked sub-contracted vehicles for 28 August through 15 September, AI receptionist with Festival-aware booking flow, STL property-manager priority routing; (3) surface LEZ-compliant Euro 6 fleet credentials and listed-tenement specialism prominently to capture inner-Edinburgh work; (4) deploy a Confirmation-aware probate B2B funnel targeting Brodies, Burness Paull, Shepherd and Wedderburn, Turcan Connell and the Edinburgh solicitor network with New Town/Morningside/Bruntsfield/Stockbridge landing pages; and (5) drive Google review velocity to 10–18 new reviews per month with seasonal keyword density across Festival-August and listed-fabric premium-catchment terms.",
};
