import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "junk removal marketing Nottingham",
    "house clearance marketing Nottingham",
    "Nottingham rubbish removal SEO",
    "Nottingham student turnover end of tenancy clearance",
    "Nottingham probate executor clearance marketing",
  ],
  secondaryKeywords: [
    "University of Nottingham Trent NTU student clearance",
    "Lenton Dunkirk Beeston student turnover clearance",
    "NET tram extension displacement clearance",
    "West Bridgford Mapperley premium probate clearance",
    "Nottingham Workplace Parking Levy WPL",
    "AnyJunk Clearabee competitor Nottingham East Midlands",
    "Environment Agency Upper Tier Waste Carrier Nottinghamshire",
    "Lace Market Hockley city centre clearance",
  ],
  heroSubhead:
    "Nottingham's clearance market sits at a peculiar regulatory inflection point. Nottingham introduced the UK's only Workplace Parking Levy (WPL) in 2012, charging £522 per workplace parking space per year — which has reshaped commercial fleet decisions across the city and increased pressure for compliant low-emission vehicles. Nottingham proposed a CAZ class B in 2020 but secured exemption after demonstrating sufficient air-quality improvements, which means no daily charge — though the WPL still applies. The 60,000+ student population across the University of Nottingham (37,000+) and Nottingham Trent (37,000+) drives a substantial June-July turnover peak concentrated in Lenton, Dunkirk, Beeston, Radford and the Park Estate. The NET (Nottingham Express Transit) tram extension and ongoing route work has produced periodic displacement clearance demand. Nottingham's premium catchments — West Bridgford (NG2), Mapperley (NG3), Sherwood, Wollaton (NG8), Burton Joyce, Ruddington — sustain £1,200–£3,000 probate clearances. Add the Lace Market and Hockley regeneration plus The Island Quarter £400m+ pipeline, and Nottingham clearance operators have a market Kerblabs is built to serve.",
  marketContext: [
    "Nottingham's clearance market is shaped by three structural factors. First, the Workplace Parking Levy — Nottingham is the UK's only city operating a WPL (since 2012), charging employers £522 per workplace parking space per year for sites with 11+ spaces. While this technically applies to employer parking rather than vehicle emissions, it has structurally pushed Nottingham commercial fleet decisions toward compliant low-emission vehicles and reshaped the city's commercial logistics economics. Nottingham proposed a Clean Air Zone class B in 2020 but secured exemption from charging implementation after Department for Environment, Food & Rural Affairs assessment confirmed sufficient air-quality compliance through alternative measures (the WPL contributing to that), which means Nottingham operators don't pay daily CAZ charges that Birmingham, Bradford and Sheffield operators do. Second, the student market — 60,000+ University of Nottingham and Nottingham Trent students concentrated in Lenton, Dunkirk, Radford, the Park Estate, Beeston (around University Park campus), plus the Trent University-adjacent Arboretum and city-centre PBSA — drives a June-July turnover peak with letting-agent panels (Smith & Stone, Walton & Allen, FHP Living, David James Estate Agents, plus the developer-managed PBSA Vita Student, Unite, IQ Student Accommodation) moving 6–14 clearance jobs per week each in peak weeks.",
    "Third, the NET tram extension programme has driven periodic property-displacement clearance: Phase 2 expansion completed in 2015 across Clifton, Wilford, Beeston, Toton and Chilwell, with route-corridor properties displaced through the construction phase. Ongoing maintenance and proposed Phase 3 routes (currently in feasibility) maintain a steady pipeline of compulsory-purchase property clearance through Nottingham City Transport's procurement framework. The Lace Market and Hockley regeneration is largely complete on conversion but produces ongoing residential turnover; The Island Quarter (£400m+ on the former Boots Island site, ongoing through 2026+) plus Broadmarsh redevelopment plus the Notts County / Nottingham Forest stadium-adjacent regeneration corridors add commercial and pre-demolition residential clearance demand. Premium catchments — West Bridgford (NG2), Mapperley (NG3), Sherwood, Woodthorpe, Wollaton (NG8), Burton Joyce, Ruddington (NG11), plus the wider Rushcliffe and Gedling premium villages — sustain £1,200–£3,000 probate clearances and £900–£1,800 retail full-house clearances.",
    "Nottingham Google Ads CPCs in clearance keywords sit at the lower-mid range of regional UK: 'house clearance Nottingham' clicks at £1.40–£3.40, 'rubbish removal Nottingham' at £1.20–£2.80, 'student end of tenancy clearance Nottingham' at £2.20–£4.60 in June-July peak. Three-bed full house clearances run £500–£1,200 retail across Nottingham generally, with the West Bridgford / Wollaton / Burton Joyce / Mapperley premium catchments supporting £900–£1,800 and probate clearances reaching £1,200–£3,000. Borough-stratified Google Ads + Local Service Ads + Maps optimisation reliably produce £18–£40 cost-per-acquired-job versus £80–£150 on Bark and aggregator platforms. Kerblabs' Nottingham clearance clients running this stack typically reach 6–10 booked jobs per week per van inside 6 months, with the Island Quarter / Broadmarsh regeneration B2B funnel and the West Bridgford / Wollaton premium-catchment probate funnel each adding distinct channels.",
  ],
  stats: [
    { value: "£522/year", label: "Nottingham Workplace Parking Levy per parking space (only UK city operating WPL)", source: "Nottingham City Council" },
    { value: "60,000+", label: "University of Nottingham and Nottingham Trent students driving June-July turnover spike", source: "HESA student data" },
    { value: "£400m+", label: "The Island Quarter regeneration on former Boots Island site driving ongoing demolition clearance", source: "Conygar Investment Company" },
    { value: "£500–£1,200", label: "typical Nottingham three-bed full house clearance price range" },
    { value: "£900–£1,800", label: "West Bridgford / Wollaton / Burton Joyce / Mapperley premium full house clearance" },
    { value: "£1.20–£4.60", label: "Google Ads CPC range for Nottingham clearance keywords 2024–2025", source: "Kerblabs client accounts" },
  ],
  painPoints: [
    {
      title: "Lenton / Dunkirk / Radford / Beeston student turnover crowded with under-prepared operators",
      body: "Nottingham's June-July student peak attracts dozens of operators competing for end-of-tenancy work across Lenton, Dunkirk, Radford, the Park Estate, Beeston (around University Park) and the Arboretum. Most show up without panel relationships with Smith & Stone, Walton & Allen, FHP Living or David James, without capacity planning, and miss their share of the 6–14 jobs/week each that letting-agent panels move. We build the panel applications and capacity-planning infrastructure that captures this volume cleanly."
    },
    {
      title: "The Island Quarter / Broadmarsh / NET tram regeneration pipelines flowing through frameworks you're not on",
      body: "The £400m+ Island Quarter (Conygar Investment Company), Broadmarsh redevelopment (Nottingham City Council-led, £100m+), NET Phase 3 tram extension feasibility, plus ongoing Trent Basin and Waterside regeneration collectively involve substantial pre-demolition residential, commercial and industrial clearance. Henry Boot, Galliford Try, Robertson Group, Wates, Vinci Construction, plus Nottingham-based contractors (G F Tomlinson, Bowmer + Kirkland's Nottingham depot, Stepnell, Robert Woodhead) source clearance subcontractors through Constructionline-tiered supply chains."
    },
    {
      title: "West Bridgford / Wollaton / Burton Joyce premium probate volume invisible without B2B funnel",
      body: "Nottingham's premium catchments produce steady probate clearance volume sourced through Nottingham solicitor networks (Browne Jacobson — Nottingham-headquartered, plus Freeths LLP, Geldards, Ellis-Fermor & Negus, Tallents, plus 200+ smaller firms across Nottinghamshire and Derbyshire) and chartered surveyors. Without a probate-specific landing page, structured B2B outreach and STEP East Midlands Branch positioning, you're invisible to £1,200–£3,000 per-job work."
    },
    {
      title: "Workplace Parking Levy compliance signalling under-used in B2B positioning",
      body: "Nottingham's WPL has structurally pushed commercial fleets toward low-emission vehicles since 2012. B2B customers (letting agents, property managers, main contractors, commercial landlords) preferentially work with operators whose fleet aligns with Nottingham's broader low-emission positioning. Most clearance operators don't surface Euro 6 fleet credentials and WPL-aware positioning, missing the B2B differentiation. We rebuild messaging to surface compliant fleet prominently across B2B touchpoints."
    },
  ],
  faqs: [
    {
      q: "How do we actually get onto Smith & Stone, Walton & Allen, FHP Living or David James student-letting panels for the June-July peak?",
      a: "Panel applications follow a specific format and timing matters — applications need to be submitted between January and April for June-July inclusion. We build a structured panel-application pack: case-study evidence (10–20 named Lenton, Dunkirk, Radford, Park Estate, Beeston end-of-tenancy clearances completed with before/after photography), public liability insurance certificate (£5M minimum, £10M preferred), Goods in Transit insurance (£25k minimum), Environment Agency Upper-Tier Waste Carrier certificate, Hazardous Waste consignor registration, Duty of Care policy document, sample Waste Transfer Notes, deposit-deduction documentation templates, a 24-hour SLA pricing schedule with peak-season capacity guarantees, and named sub-contracted vehicle agreements proving capacity. We then run targeted LinkedIn outreach to Smith & Stone, Walton & Allen, FHP Living, David James Estate Agents, plus Marshalls (Nottingham), Pygott & Crone, Carter Jonas Nottingham, plus the PBSA developer-management arms (Unite, IQ Student Accommodation, Vita Student's Nottingham development, Crosslane). Most clients reach 4–6 panels inside one application cycle, delivering 50–140 jobs across June-July at £80–£250 per-job pricing."
    },
    {
      q: "How do we get onto The Island Quarter, Broadmarsh or NET tram regeneration main-contractor frameworks?",
      a: "Three parallel workstreams. First, accreditation infrastructure — Constructionline Gold (mandatory for the larger Island Quarter and Broadmarsh packages), ISO 9001/14001/45001, Environment Agency Upper-Tier Waste Carrier with named transfer-station partners (Veolia Eastcroft, Suez Nottingham, Biffa, FCC), Hazardous Waste consignor registration, Goods in Transit insurance £25k+, public liability £10M+. Second, main-contractor relationship mapping — Conygar Investment Company (the lead developer on The Island Quarter), Nottingham City Council's Major Projects team (Broadmarsh), Henry Boot, Galliford Try, Robertson Group, Wates, plus Nottingham-based contractors (G F Tomlinson, Stepnell, Robert Woodhead, Bowmer + Kirkland's Nottingham depot). Pre-qualified-supplier-list registration plus structured procurement-team outreach. Third, framework visibility — Nottingham City Council frameworks, the East Midlands Combined County Authority frameworks, Pagabo's East Midlands framework, Scape Procure Midlands, and the NET tram operations procurement portal. We map and run all three in parallel, typically opening 1–3 framework opportunities per quarter inside the first six months."
    },
    {
      q: "Is the West Bridgford / Wollaton / Burton Joyce / Ruddington probate market really worth a dedicated B2B funnel?",
      a: "Yes — and the channel is meaningfully under-served. Nottingham's premium catchments produce steady probate volume, the Nottingham probate solicitor network is concentrated and accessible, and per-job pricing of £1,200–£3,000 (with the Burton Joyce / Ruddington / Plumtree larger-detached-property catchment reaching £2,500–£5,000 on substantial properties) is meaningful when you're booking 2–4 probate jobs per month at gross margins above retail. Browne Jacobson is Nottingham-headquartered with substantial East Midlands probate volume; Freeths LLP also Nottingham-based; Geldards covers Nottingham and Cardiff probate work; Ellis-Fermor & Negus covers Nottinghamshire and Derbyshire premium-catchment probate; Tallents covers the Newark and rural Nottinghamshire probate; plus 200+ smaller firms across Nottinghamshire, Derbyshire, Leicestershire and Lincolnshire. Chartered surveyors handling contents valuations include Mellors & Kirk Auctioneers (Nottingham-based, leading East Midlands fine-art auctioneer), Arthur Johnson Auctioneers, plus a cluster of RICS-registered house-clearance valuers. We build a probate-specific landing page optimised for 'probate house clearance West Bridgford', 'executor clearance Wollaton', 'probate clearance Burton Joyce' etc., plus structured solicitor outreach (LinkedIn + targeted email + STEP East Midlands Branch + Law Society Nottinghamshire events). Nottingham clearance clients typically book 2–3 probate jobs per month at £1,200–£3,000 average within 6–9 months."
    },
    {
      q: "How does the Workplace Parking Levy actually affect our clearance marketing positioning?",
      a: "WPL applies to employer parking (£522/year per space for sites with 11+ spaces) rather than vehicle emissions directly, but it has structural marketing implications. First, Nottingham B2B customers have been navigating WPL since 2012 and their procurement teams care about fleet emissions and sustainability credentials more than equivalent customers in non-WPL cities — surfacing Euro 6 fleet, low-emission positioning, and ISO 14001 environmental credentials lifts B2B conversion meaningfully. Second, the WPL revenue (~£10M annually) funds Nottingham public transport investment including the NET tram, which both creates the regeneration demolition pipeline (NET extensions) and signals Nottingham's broader low-emission economic policy direction. Third, in pricing-comparison content (informational SEO that pulls customers comparing regional clearance pricing), Nottingham operators can credibly position the WPL as 'the city that's been investing in clean transport longer than most' — which resonates with eco-aware customers and B2B buyers. Most Nottingham clearance operators don't surface any of this; the differentiation is genuinely available."
    },
  ],
  approach:
    "For Nottingham junk removal and house clearance firms, our 90-day playbook is: (1) build student-letting and PBSA panel-application packs to Smith & Stone, Walton & Allen, FHP Living, David James, Unite, IQ Student Accommodation, Vita Student and 6+ developer-management arms, submitted in January-April for June-July inclusion; (2) install B2B accreditation infrastructure (Constructionline Gold, ISO 9001/14001/45001) and run structured outreach to Conygar Investment Company, Henry Boot, G F Tomlinson, Stepnell and Nottingham main-contractor procurement for The Island Quarter / Broadmarsh / NET tram regeneration work; (3) deploy a probate B2B funnel with West Bridgford/Wollaton/Burton Joyce/Mapperley landing pages and structured solicitor outreach to Browne Jacobson, Freeths LLP, Geldards, Ellis-Fermor & Negus and the Nottingham probate-firm network; (4) surface Euro 6 fleet credentials and WPL-aware low-emission positioning across B2B touchpoints; and (5) drive Google review velocity to 8–14 new reviews per month with NG-postcode-specific keyword density.",
};
