import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "junk removal marketing Plymouth",
    "house clearance marketing Plymouth",
    "Plymouth rubbish removal SEO",
    "Plymouth probate clearance lead generation",
    "Devon estate clearance marketing",
  ],
  secondaryKeywords: [
    "Royal Navy Devonport HMNB MoD clearance Plymouth",
    "Mannamead Peverell Plympton St Maurice probate clearance",
    "Plymouth University student turnover clearance Mutley",
    "AnyJunk Clearabee competitor Plymouth South West",
    "PL1 PL2 PL3 PL4 PL7 house clearance SEO",
    "Plymouth no Clean Air Zone clearance vehicle advantage",
    "Babcock Devonport dockyard commercial clearance",
    "Royal William Yard Stonehouse end of tenancy clearance",
  ],
  heroSubhead:
    "Plymouth's clearance market is structurally unique among UK cities — HMNB Devonport is the largest naval base in Western Europe, generating continuous Royal Navy housing turnover and MoD-adjacent rental refurbishment work; the city has no Clean Air Zone (Plymouth chose ULEV behavioural measures instead), giving PL-postcode clearance operators a structural cost advantage; and a Plymouth-University 18,000-student belt around Mutley and Greenbank drives a heavy June-July turnover peak. Mannamead, Peverell and Plympton St Maurice premium catchments support £1,200–£3,000 full house probate clearances, while the older naval-pensioner cohort across Devonport, Stoke and Stonehouse generates a meaningful estate clearance pipeline most South West agencies miss. Add the Babcock dockyard commercial clearance pipeline, Royal William Yard regeneration and a market 25–35% cheaper to bid into than Bristol or Exeter, and Kerblabs builds the PL-postcode marketing system Plymouth clearance operators actually need.",
  marketContext: [
    "Plymouth's clearance market is shaped by three forces no other UK city combines. First, HMNB Devonport — the largest naval base in Western Europe — and Babcock's adjacent Devonport dockyard generate continuous Royal Navy housing turnover and MoD-adjacent rental refurbishment work that no other UK clearance market shares at this scale. Service families on 2–4 year postings cycle through married quarters in Devonport, Stoke, Stonehouse and the broader PL1/PL2 belt, generating end-of-tenancy clearance work timed precisely to posting cycles. The naval-pensioner retirement cohort across the same postcodes plus the wider Plymouth catchment generates probate clearance volume with naval memorabilia, ship-model archives, Royal Naval Association records and 1960s–1990s service-family contents complexity that requires sensitive handling. Devonport-specific work also includes commercial dockyard supply-chain clearance through Babcock's tier-one and tier-two suppliers — site clearance, workshop closure, equipment disposal — sourced through Babcock's preferred-supplier framework rather than open tender. Probate jobs in the naval-pensioner segment run £900–£2,400, full Devonport/Stoke/Stonehouse end-of-tenancy clearances £400–£900, and the dockyard commercial pipeline supports £2,500–£15,000 single-job values for operators with the right accreditation.",
    "Second, Plymouth has no Clean Air Zone — the city implemented ULEV behavioural measures (taxi licensing changes, ULEV uptake support, council fleet electrification) instead of a charging CAZ — so PL-postcode clearance operators avoid the daily fleet overhead that hits Bristol's £9 Class D, Bath's £9 Class C and Bradford's £9 Class C charges. This is a meaningful structural advantage when bidding regional commercial work into the broader South Hams, West Devon, south-east Cornwall and even reaching into Exeter (EX postcodes) and the Torbay belt without the Bristol-CAZ overhead Bristol-based operators carry. Third, the University of Plymouth's 18,000-student belt around Mutley Plain, Greenbank and North Hill plus Plymouth College of Art and Marjon drives a structurally heavy June-July turnover peak with letting-agent panels (Mansbridge Balment, Lang Town & Country, Connells Plymouth, Atwell Martin, Webbers, plus the major University of Plymouth accommodation services and Crown House / Astor House PBSA developers) moving 4–10 clearance jobs per week each in peak weeks. Plymouth's premium catchment — Mannamead, Peverell, Plympton St Maurice and parts of Plymstock — supports full house clearances of £1,200–£3,000, with probate clearances on the Edwardian Mannamead and Peverell stock reaching £2,000–£4,500.",
    "Plymouth Google Ads CPCs in clearance keywords sit toward the lower end of UK regional CPCs — a function of Plymouth's value-conscious customer base depressing typical job values, partly offset by Mannamead/Peverell/Plympton premium pockets. 'House clearance Plymouth' clicks at £1.40–£2.80, 'rubbish removal Plymouth' at £1.10–£2.40, 'probate clearance Plymouth' at £1.80–£3.40, with the highest-intent Mannamead, Peverell and Plympton St Maurice terms reaching £2.20–£4.00. By comparison, equivalent Bristol and Exeter searches click 30–50% higher. The strategic implication is that PL-postcode-stratified Google Ads + Local Service Ads + Maps optimisation + a structured naval-network and probate B2B funnel + student-cycle-aware booking flows + regional expansion into the South Hams, West Devon and south-east Cornwall leveraging the no-CAZ advantage reliably produce £20–£45 cost-per-acquired-job versus £85–£170 on Bark, MyBuilder and Checkatrade. Kerblabs' Plymouth clearance clients running this stack typically reach 7–11 booked jobs per week per van inside 6 months, with average job value 25–40% above the Plymouth market median because review velocity from named PL-postcode customers, naval-network referral positioning and the extended South West regional service area compound margin advantages.",
  ],
  stats: [
    { value: "No CAZ", label: "Plymouth has no Clean Air Zone — ULEV behavioural measures only, no daily charge for clearance vehicles", source: "Plymouth City Council" },
    { value: "Largest", label: "Naval base in Western Europe (HMNB Devonport) driving service-family clearance turnover", source: "Royal Navy" },
    { value: "264,200", label: "Plymouth population — clearance demand across PL1–PL9 plus wider South Hams catchment", source: "ONS Census 2021" },
    { value: "£1,200–£3,000", label: "Mannamead / Peverell / Plympton St Maurice premium full house clearance" },
    { value: "£1.40–£4.00", label: "Plymouth clearance keyword CPC range — 30–50% below Bristol and Exeter equivalents", source: "Kerblabs client accounts" },
    { value: "~18,000", label: "University of Plymouth students driving June-July clearance turnover spike", source: "University of Plymouth" },
  ],
  painPoints: [
    {
      title: "Royal Navy Devonport service-family turnover handled with generic end-of-tenancy marketing",
      body: "Plymouth's HMNB Devonport service-family turnover is structurally unique — postings run on 2–4 year cycles with concentrated move-in/move-out windows, married-quarters end-of-tenancy clearances need rapid turnaround often within posting deadlines, and the work is sourced through Defence Infrastructure Organisation (DIO) frameworks, Annington Homes (the major MoD-adjacent housing provider), and naval-family Facebook groups (Plymouth Navy Wives, Devonport Wives Club, Royal Naval Association Plymouth). Most Plymouth clearance operators don't market into this segment with naval-aware positioning at all. We build dedicated DIO-aware, Annington-aware and posting-cycle-aware marketing including service-family-focused landing pages and Facebook lead campaigns into the relevant Plymouth naval communities."
    },
    {
      title: "Babcock dockyard commercial clearance pipeline going to outsiders",
      body: "Babcock's Devonport dockyard generates continuous commercial clearance demand — site clearance, workshop closure, equipment disposal, Type 23 frigate refit supply-chain clearance — sourced through Babcock's preferred-supplier framework rather than open tender. Most local Plymouth clearance operators have neither the Constructionline Gold nor the structured Babcock procurement outreach to capture £2,500–£15,000 single-job dockyard commercial work. We build the accreditation infrastructure (Constructionline Gold, ISO 9001/14001/45001, MoD-relevant security clearances where applicable, Hazardous Waste consignor registration, marine-environment-aware waste handling, public liability £10M+) and run structured outreach to Babcock's procurement teams plus DIO framework applications."
    },
    {
      title: "No-CAZ regional advantage unused — South Hams, Exeter, Torbay work going elsewhere",
      body: "Plymouth's no-CAZ position is a structural advantage: PL-postcode operators can credibly service the South Hams (TQ7, TQ9), West Devon, south-east Cornwall (PL10–PL26 plus the broader Cornish PL-postcode belt), reach into Exeter (EX postcodes) and even the Torbay belt without the Bristol-CAZ overhead Bristol-based operators carry. Most Plymouth clearance operators don't market this advantage at all. We build dedicated regional landing pages for each major catchment, Google Ads campaigns into TQ/EX/PL-Cornwall postcodes, and explicit messaging around competitive pricing without CAZ overhead."
    },
    {
      title: "Drive-time geography wasting student-cycle and suburban marketing budget",
      body: "Plymouth has weak public transport and big distances between suburbs — a clearance operator in Mannamead and one in Plymstock can both technically be 'in Plymouth' but share almost no catchment because the Plym crossing and rush-hour Embankment Road traffic put them 25 minutes apart. Generic radius-based Google Ads waste 25–35% of budget chasing audiences outside realistic drive-time zones. We build local SEO and Google Ads around real drive-time polygons, write neighbourhood-specific landing pages for Plympton St Maurice, Mannamead, Crownhill, Devonport and Plymstock separately, and structure GBP services per suburb so each catchment gets distinct content."
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat Clearabee, AnyJunk, Junk Hunters and the Bark/MyBuilder aggregators in Plymouth specifically?",
      a: "Three-phase Plymouth-specific playbook. Phase one: Google Business Profile category stacking (Junk Removal Service + Waste Management Service + House Clearance Service + Rubbish Removal Service) with PL-postcode service-area definition extending into South Hams (TQ7, TQ9), West Devon, south-east Cornwall (PL10–PL26) and reaching the Exeter (EX) fringe leveraging the no-CAZ regional advantage, Environment Agency Upper Tier Waste Carrier registration schema, and structured review campaigns targeting 8–14 new reviews per month with named PL-postcode keywords (Mannamead, Peverell, Plympton St Maurice, Plymstock, Devonport, Royal William Yard, Mutley, Crownhill). Phase two: Google Local Service Ads with the Google Guaranteed badge — on Plymouth clearance keywords this consistently lands at £20–£45 cost-per-job versus £85–£170 on Bark and MyBuilder. Phase three: PL-stratified Google Ads (separate campaigns for PL1 city-centre/Stonehouse/Royal William Yard, PL2 Devonport service-family belt, PL3 Mutley/Mannamead/Peverell premium, PL4 Greenbank/Lipson student-mixed, PL5 Honicknowle/Crownhill, PL6 Derriford/Plympton fringe, PL7 Plympton St Maurice/St Mary, PL9 Plymstock/Hooe, plus regional South West campaigns leveraging no-CAZ advantage), plus a probate B2B funnel targeting Plymouth solicitors (Foot Anstey — Plymouth-headquartered, Wolferstans, Curtis Banks Plymouth, Bond Dickinson, plus 100+ smaller firms) and naval-network referral positioning that aggregators don't compete for. Plymouth clearance clients typically reduce aggregator dependency from 45% to 12% inside 6 months while growing total job volume 30–50%."
    },
    {
      q: "Can the AI receptionist handle the difference between a £150 Mutley student-flat clearance and a £4,500 Mannamead probate?",
      a: "Yes — that's the qualifying flow at the centre of the Plymouth build. The first three questions are: is this an end-of-tenancy/student/single-room job, a full house clearance, or a probate/executor clearance. Mutley, Greenbank and Lipson student-flat callouts trigger a fixed-price banded quote against your published price list and same-day calendar slot. End-of-tenancy clearances trigger a letting-agent-aware flow with deposit-deduction documentation aligned to Plymouth's letting-agent panels (Mansbridge Balment, Lang Town & Country, Connells Plymouth, Atwell Martin, Webbers) plus University of Plymouth accommodation services and the Crown House / Astor House PBSA developers. For Royal Navy Devonport service-family postings specifically, the receptionist handles the DIO/Annington-aware posting-cycle conversation, recognising the rapid-turnaround timing reality of military relocation. Probate triggers a 90-minute on-site survey appointment, formal scope-of-works template, written quotation with VAT and EWC waste codes, and a solicitor-friendly invoice format. For the naval-pensioner probate segment specifically — Devonport, Stoke and Stonehouse retirement cohort estates — the receptionist asks about specific contents complexity (naval memorabilia, ship-model archives, Royal Naval Association records) that drive accurate scope. Hoarder/insurance cases trigger a referral pathway with adjuster liaison and biohazard pricing. Babcock dockyard commercial enquiries trigger a separate B2B flow with Constructionline accreditation and procurement-language messaging."
    },
    {
      q: "How do you handle the Royal Navy Devonport service-family clearance market that needs DIO and Annington-aware positioning?",
      a: "We build a dedicated naval-aware sub-funnel because the buyer journey, timing constraints and trust signals are structurally different from civilian end-of-tenancy work. HMNB Devonport service-family postings run on 2–4 year cycles with concentrated move-in/move-out windows aligned to military assignment dates rather than civilian calendar months. Married-quarters end-of-tenancy clearances need rapid turnaround often inside the posting deadline, and the work is sourced through three channels: (1) Defence Infrastructure Organisation (DIO) framework agreements covering MoD housing maintenance and decommissioning across the broader Plymouth naval estate; (2) Annington Homes — the major MoD-adjacent housing provider managing thousands of former MoD properties — with their own preferred-supplier panels for end-of-tenancy clearance; (3) naval-family community channels including Plymouth Navy Wives Facebook group, Devonport Wives Club, Royal Naval Association Plymouth and the broader Royal Navy welfare networks. We build dedicated DIO-aware and Annington-aware landing pages with explicit posting-cycle awareness ('moving on draft? we clear MoD married quarters in under 48 hours'), Facebook lead campaigns into Plymouth naval communities, and structured outreach to DIO and Annington procurement teams. Plymouth clearance clients running this naval-aware approach typically capture 15–25 service-family clearance jobs per quarter at £400–£900 average, plus 1–3 dockyard commercial jobs at £2,500–£15,000 average within 9–12 months."
    },
    {
      q: "Can Kerblabs help us leverage Plymouth's no-CAZ position to win South Hams, Exeter and south-east Cornwall work?",
      a: "Yes — and it's one of the most underused structural advantages Plymouth clearance operators have. Bristol's CAZ Class D charges £9 daily for non-compliant LCVs, Bath's Class C charges £9, and Bristol-based operators carry £2,250+ annual fleet overhead per vehicle on regional work. Plymouth-based operators avoid all of this. We build dedicated regional landing pages for each major catchment (South Hams house clearance from Plymouth, Salcombe/Dartmouth/Totnes estate clearance, Tavistock/Okehampton West Devon clearance, Looe/Liskeard/Bodmin south-east Cornwall clearance, plus Exeter-fringe positioning where commercially viable), Google Ads campaigns into TQ7/TQ9/EX/PL-Cornwall postcodes, and explicit messaging around competitive pricing without CAZ overhead. The South Hams in particular has a substantial London and Home Counties second-home market — Salcombe, Dartmouth, Totnes — that generates premium probate and second-home clearance work flowing to operators willing to bid into TQ postcodes. For commercial clearance work — main-contractor procurement across the broader South West, MoD-adjacent work, regeneration fit-out — the Plymouth-based positioning frequently wins on price-and-availability. Clients running this regional expansion typically grow service-area revenue 30–50% within 9 months while keeping the core PL-postcode catchment unchanged."
    },
  ],
  approach:
    "For Plymouth junk removal and house clearance firms, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + PL-stratified Google Ads + South West regional campaigns leveraging no-CAZ advantage + Maps optimisation) to reduce Bark/MyBuilder/Checkatrade dependency from 45% to under 15%; (2) deploy AI 24/7 receptionist with PL-postcode-aware drive-time-zone qualifying flow plus separate funnels for student/end-of-tenancy, naval service-family, full house, probate (civilian and naval-pensioner) and dockyard commercial clearance; (3) build a probate B2B funnel with solicitor outreach to Foot Anstey, Wolferstans, Curtis Banks Plymouth and the South West STEP network plus naval-network referral positioning to capture £900–£4,500 Mannamead/Peverell/Plympton/Devonport estate clearances; (4) build naval-aware DIO and Annington Homes outreach plus Babcock dockyard procurement targeting for the structurally unique Plymouth naval clearance pipeline; and (5) drive Google review velocity to 8–14 new reviews per month with named PL-postcode and naval-community-aware keyword density.",
};
