import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "junk removal marketing Sheffield",
    "house clearance marketing Sheffield",
    "Sheffield rubbish removal SEO",
    "Sheffield student end of tenancy clearance",
    "Sheffield probate executor clearance marketing",
  ],
  secondaryKeywords: [
    "Sheffield Clean Air Zone CAZ C £10 LCV charge",
    "Crookes Broomhill Ecclesall student turnover clearance",
    "University of Sheffield Hallam student clearance",
    "Kelham Island Park Hill regeneration clearance",
    "Hallam premium probate clearance Dore Totley",
    "post industrial property clearance Attercliffe Tinsley",
    "AnyJunk Clearabee competitor Sheffield South Yorkshire",
    "Environment Agency Upper Tier Waste Carrier Sheffield",
  ],
  heroSubhead:
    "Sheffield's clearance market sits in the shadow of Leeds but with structurally different economics. Sheffield's Clean Air Zone (CAZ class C, live from 27 February 2023) charges £10 per day for non-compliant LCVs and £50 for HGVs — meaningfully more painful than Birmingham's £8 LCV charge — covering the inner ring road area broadly bounded by the Parkway, Park Square and the city centre. Sheffield Hallam (28,000+ students) and the University of Sheffield (30,000+) generate a substantial June-July student-turnover spike concentrated in Crookes, Broomhill, Ecclesall Road, Sharrow Vale and Highfield, but with notably lower retail clearance pricing than Leeds. Post-industrial property clearance across Attercliffe, Tinsley, Darnall and the Lower Don Valley produces ongoing demolition-supply-chain demand, while Hallam, Dore, Totley, Bradway and Fulwood — the affluent S10/S11/S17 belt — drive premium probate volume reaching £1,200–£3,500 per clearance. Add Park Hill, Kelham Island and the Heart of the City II regeneration pipeline, and Sheffield clearance operators have a market Kerblabs is built to serve.",
  marketContext: [
    "Sheffield's clearance market is shaped by three factors that distinguish it sharply from Leeds 35 miles north. First, the CAZ class C charging regime — operational from 27 February 2023, charging £10 per day for non-compliant LCVs (Euro 5 diesel or older), £50 for non-compliant HGVs and buses. This is meaningfully more aggressive than Birmingham CAZ class D's £8 LCV charge or Bradford CAZ class C's £9, and notably the zone covers the inner ring road area — the Parkway, Park Square, Sheaf Square, the broader city centre and parts of S1, S2 and S3 postcodes. Operators with Euro 5 or older diesel fleet have either upgraded (£18,000–£35,000 per Luton tipper Euro 6 replacement) or retreated to outer-Sheffield work in S6, S7, S10, S11, S17 and S35 plus Rotherham, Doncaster and Barnsley. Second, the student market — 58,000+ University of Sheffield and Sheffield Hallam students concentrated in Crookes, Broomhill, Ecclesall Road, Sharrow Vale, Highfield, Endcliffe and city-centre PBSA — produces a June-July turnover spike but at lower retail clearance pricing than Leeds (typical end-of-tenancy single-room clearance £80–£180 in Sheffield versus £100–£220 in Leeds for equivalent jobs).",
    "Third, post-industrial property clearance is a Sheffield-specific demand stream. Attercliffe, Tinsley, Darnall, Brightside and the Lower Don Valley have substantial pre-1980 industrial and mixed-use building stock undergoing slow conversion or demolition, with sporadic large-scale clearance work flowing through main-contractor frameworks (Henry Boot, Galliford Try, Wates, Robertson Group's North England operations, plus the Sheffield-specific J F Finnegan and Bowmer + Kirkland's Sheffield depot). The Heart of the City II regeneration (£500m+, completing in phases through 2025) plus Park Hill (the Grade II* listed brutalist redevelopment with Urban Splash and Manuel Builders, ongoing apartment turnover) plus Kelham Island and Castlegate add to the pipeline. The premium catchment — S10 (Broomhill, Crookes, Walkley, Fulwood), S11 (Hunters Bar, Nether Edge, Greystones, Banner Cross), S17 (Dore, Totley, Bradway, Whirlow) — is predominantly 1900–1980 owner-occupier housing with a rising probate volume from the original cohort now 70–90.",
    "Sheffield Google Ads CPCs in clearance keywords sit lower than Leeds and Manchester: 'house clearance Sheffield' clicks at £1.60–£3.80, 'rubbish removal Sheffield' at £1.20–£2.80, 'student end of tenancy clearance Sheffield' at £2.40–£5.20 in June-July peak. Three-bed full house clearances run £550–£1,400 retail across Sheffield generally, with the S10/S11/S17 premium catchments supporting £1,000–£2,400 and probate clearances reaching £1,200–£3,500. Borough-stratified Google Ads + Local Service Ads + Maps optimisation + post-industrial B2B funnel reliably produce £18–£40 cost-per-acquired-job versus £80–£160 on Bark and aggregator platforms. Kerblabs' Sheffield clearance clients running this stack typically reach 5–10 booked jobs per week per van inside 6 months, with the Heart of the City II / Park Hill / Kelham Island regeneration B2B funnel and the Hallam premium-catchment probate funnel each adding distinct channels.",
  ],
  stats: [
    { value: "£10/day", label: "Sheffield CAZ class C charge for non-compliant LCVs (live from 27 February 2023)", source: "Sheffield City Council Clean Air Zone" },
    { value: "58,000+", label: "University of Sheffield and Sheffield Hallam students driving June-July turnover spike", source: "HESA student data" },
    { value: "£550–£1,400", label: "typical Sheffield three-bed full house clearance price range" },
    { value: "£1,000–£2,400", label: "S10 / S11 / S17 (Hallam, Nether Edge, Dore, Totley) premium catchment full house clearance" },
    { value: "£500m+", label: "Heart of the City II Sheffield regeneration pipeline driving demolition-supply-chain clearance", source: "Sheffield City Council" },
    { value: "£1.20–£5.20", label: "Google Ads CPC range for Sheffield clearance keywords 2024–2025", source: "Kerblabs client accounts" },
  ],
  painPoints: [
    {
      title: "CAZ class C £10/day charge squeezing margins on inner-ring-road work",
      body: "Sheffield CAZ class C is more aggressive than Birmingham CAZ class D on LCV charges (£10/day vs £8/day) and covers a tighter inner-ring-road geography that affects city-centre, Heart of the City II, Park Hill and Kelham Island work. Operators with non-compliant fleet either pay £2,500+ per vehicle per year or lose city-centre work entirely. We help Euro-6-compliant operators surface that compliance prominently to capture the inner-Sheffield work non-compliant competitors are pricing themselves out of."
    },
    {
      title: "Crookes / Broomhill / Ecclesall student turnover crowded with under-prepared operators",
      body: "Sheffield's June-July student peak attracts dozens of operators competing for the same Hyde Park-equivalent volume across Crookes, Broomhill, Ecclesall Road, Sharrow Vale, Highfield and Endcliffe. Most show up without panel relationships, without capacity planning, and without 24-hour SLA discipline — and miss their share of the 8–18 jobs/week that Sheffield-specific letting agents move through preferred-supplier panels. We build the panel applications and capacity-planning infrastructure that captures this volume cleanly."
    },
    {
      title: "Heart of the City II / Park Hill / Kelham Island regeneration clearance flowing through frameworks you're not on",
      body: "Sheffield's £500m+ Heart of the City II programme, the ongoing Park Hill conversion, Kelham Island commercial conversion and Castlegate regeneration collectively involve substantial pre-demolition residential, commercial and industrial clearance. Henry Boot, Galliford Try, Wates and J F Finnegan source clearance subcontractors through Constructionline-tiered supply chains. Without ISO accreditation and a proper B2B tender-response toolkit, the entire Sheffield regeneration pipeline is invisible."
    },
    {
      title: "S10 / S11 / S17 Hallam premium probate volume invisible without solicitor B2B funnel",
      body: "Sheffield's Hallam, Nether Edge, Dore, Totley, Bradway and Fulwood produce steady probate clearance volume sourced through Sheffield solicitor networks (Irwin Mitchell — Sheffield-headquartered, plus Wake Smith, Taylor & Emmet, Bell & Buxton, Banner Jones plus 150+ smaller firms) and chartered surveyors. Without a probate-specific landing page, structured B2B outreach and STEP Yorkshire Branch positioning, you're invisible to £1,200–£3,500 per-job work."
    },
  ],
  faqs: [
    {
      q: "How does the Sheffield CAZ specifically affect our clearance pricing and marketing?",
      a: "Sheffield CAZ class C went live 27 February 2023, charges £10 per day for non-compliant LCVs (Euro 5 diesel or older), £50 for non-compliant HGVs/buses/coaches, and covers the inner ring road area broadly bounded by the Parkway, Park Square, Sheaf Square and the city centre — affecting most S1, parts of S2, S3 and S10. Operators with non-compliant fleet face £2,500+ per vehicle per year of pure overhead on inner-Sheffield work. The marketing implication is twofold. First, surface Euro 6 compliance prominently — landing pages, GBP posts, quote PDFs should include CAZ-compliant fleet schema, Euro 6 certification and Sheffield CAZ check-tool screenshots for the customer's address. Second, build separate inner-CAZ and outer-Sheffield campaigns — the inner-CAZ work commands meaningfully better pricing because non-compliant competitors are pricing themselves out, while outer-Sheffield work in S6, S7, S11, S17, S35 plus Rotherham, Doncaster and Barnsley operates at lower CPCs and broader competition. Sheffield clearance clients with Euro 6 fleet and proper CAZ marketing typically capture 35–50% more inner-ring-road work than non-compliant competitors."
    },
    {
      q: "Is Sheffield student turnover really worth the same panel-application infrastructure as Leeds?",
      a: "Yes, but with adjusted volume expectations. Sheffield's combined University of Sheffield + Sheffield Hallam student population is 58,000+ versus Leeds at 65,000+ — broadly comparable. The difference is geographic concentration: Sheffield student housing is more spread across S6 (Walkley, Crookes), S10 (Broomhill, Crookes Valley, Endcliffe), S11 (Sharrow Vale, Hunters Bar, Endcliffe Park), and the city centre PBSA market, while Leeds is much more concentrated in Hyde Park and Headingley. Sheffield letting agents include Hopkinson Estate Agents, William H Brown's student arm, Northwood, Saxton Mee, Eadon Lockwood & Riddle, plus the developer-managed PBSA blocks (Vita Student's Sheffield development, Unite, IQ Student Accommodation, Crosslane, Watkin Jones / Fresh). We build panel-application packs targeting 6–10 Sheffield letting agents and PBSA developer-management arms, submitted in January-April for June-July inclusion, delivering 40–120 jobs across the peak weeks at standardised £80–£220 per-job pricing. Lower volume than Leeds peak but meaningfully better margins because Sheffield CPCs are lower and aggregator competition is less surge-priced."
    },
    {
      q: "How do we get onto Heart of the City II, Park Hill or Kelham Island regeneration main-contractor frameworks?",
      a: "Three parallel workstreams. First, accreditation infrastructure — Constructionline (Bronze minimum, Gold preferred for the larger Heart of the City II packages), ISO 9001/14001/45001, Environment Agency Upper-Tier Waste Carrier with named transfer-station partners (Veolia Sheffield, Suez Sheffield Energy Recovery Facility, Biffa, FCC), Hazardous Waste consignor registration, Goods in Transit insurance £25k+, public liability £10M+. Second, main-contractor relationship mapping — Henry Boot (Sheffield-headquartered, the lead developer on Heart of the City II), Urban Splash and Manuel Builders for ongoing Park Hill conversion, Galliford Try, Wates, Robertson Group North, J F Finnegan (Sheffield-based contractor), plus Bowmer + Kirkland's Sheffield depot. Pre-qualified-supplier-list registration plus structured procurement-team outreach. Third, framework visibility — Sheffield City Council frameworks, the YORhub North East and Yorkshire construction framework, Pagabo's North England framework, and the Heart of the City II's own supplier portal. We map and run all three in parallel, typically opening 1–3 framework opportunities per quarter inside the first six months."
    },
    {
      q: "Is the Sheffield Hallam (S10/S11/S17) probate market really worth a dedicated B2B funnel given the lower per-job pricing than Leeds or London?",
      a: "Yes — Sheffield probate volume is steady, the channel is under-served, and per-job pricing of £1,200–£3,500 (with S17 Dore/Totley/Bradway reaching £2,500–£5,500 on larger detached properties) is meaningful when you're booking 2–4 probate jobs per month at gross margins above retail. The Sheffield probate solicitor network is concentrated and accessible: Irwin Mitchell is Sheffield-headquartered with significant probate volume, Wake Smith, Taylor & Emmet, Bell & Buxton, Banner Jones, Howells, Switalskis (Sheffield branch), plus 150+ smaller South Yorkshire firms. Chartered surveyors handling contents valuations include BBR Sheffield, Sheffield Auction Gallery, plus a cluster of RICS-registered house-clearance valuers. We build a probate-specific landing page optimised for 'probate house clearance Sheffield', 'executor clearance Dore', 'probate clearance Hallam', 'executor clearance Totley' etc., plus structured solicitor outreach (LinkedIn + targeted email + STEP Yorkshire Branch attendance + Law Society Sheffield-Hallamshire events). Sheffield clearance clients typically book 2–3 probate jobs per month at £1,200–£3,500 average within 6–9 months."
    },
  ],
  approach:
    "For Sheffield junk removal and house clearance firms, our 90-day playbook is: (1) surface CAZ class C Euro 6 fleet credentials prominently to capture inner-ring-road Heart of the City II / Park Hill / Kelham Island work; (2) build student-letting and PBSA panel-application packs to Hopkinson, William H Brown, Saxton Mee, Vita Student, Unite and 6+ developer-management arms, submitted in January-April for June-July inclusion; (3) install B2B accreditation infrastructure (Constructionline, ISO 9001/14001/45001, Hazardous Waste consignor) and run structured outreach to Henry Boot, J F Finnegan, Galliford Try and Sheffield main-contractor procurement; (4) deploy a probate B2B funnel with S10/S11/S17 (Hallam, Nether Edge, Dore, Totley) landing pages and structured solicitor outreach to Irwin Mitchell, Wake Smith, Taylor & Emmet and the Sheffield probate-firm network; and (5) drive Google review velocity to 8–14 new reviews per month with seasonal keyword density across student catchments in June-July and S10/S11/S17 premium catchments year-round.",
};
