import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "junk removal marketing Belfast",
    "house clearance marketing Belfast",
    "Belfast rubbish removal SEO",
    "Belfast probate clearance lead generation",
    "Northern Ireland house clearance marketing",
  ],
  secondaryKeywords: [
    "NIEA Northern Ireland Environment Agency waste carrier",
    "Stranmillis Malone Lisburn Road probate clearance Belfast",
    "Holywood Cultra estate clearance BT18",
    "cross border waste clearance Republic of Ireland",
    "AnyJunk Clearabee competitor Belfast NI",
    "Cathedral Quarter end of tenancy clearance Belfast",
    "post-Troubles hoarder clearance Belfast specialist",
    "BT9 Stranmillis Victorian villa probate",
  ],
  heroSubhead:
    "Belfast's clearance market sits inside Northern Ireland's distinct regulatory environment — the NIEA (Northern Ireland Environment Agency) governs waste carrier registration rather than the Environment Agency, the Windsor Framework affects cross-border waste movements with the Republic, there is no Clean Air Zone but landfill tax differentials between NI and the Republic create unusual operator dynamics, and the post-Troubles housing legacy has left a steady volume of hoarder, deceased-estate and decades-sealed-up house clearance work most GB operators have never encountered. Citi's 3,000+ Titanic Quarter staff plus the Lisburn Road / Stranmillis / Malone professional belt drive premium private-pay clearance demand reaching £1,800–£4,500 for full Edwardian villa clearances, while the Holywood and Cultra BT18 commuter belt routinely sees £2,500–£6,500 probate jobs. Add cross-border ROI demand, NI-specific solicitor networks and an HSCNI-different operating environment, and Kerblabs builds the BT-postcode marketing system Belfast clearance operators actually need.",
  marketContext: [
    "Belfast's clearance market is shaped by three forces no GB city shares. First, Northern Ireland's distinct waste regulatory framework: NIEA (the Northern Ireland Environment Agency, part of DAERA) governs waste carrier registration through the Waste Management Licensing Regulations (Northern Ireland), and the registration tiers, fee structures and audit cadence differ meaningfully from the England-and-Wales Environment Agency Upper Tier system. The Windsor Framework (formerly the Northern Ireland Protocol) further complicates cross-border waste movements between Northern Ireland and the Republic, and operators who run vehicles into ROI for cross-border clearance work must hold compliant Trans-Frontier Shipment of Waste documentation under EU Waste Shipment Regulation 1013/2006 rules — something virtually no GB-based operator understands. Belfast clearance customers, particularly commercial customers and probate solicitors, increasingly check NIEA waste-carrier registration as a hard trust filter. Second, the post-Troubles housing legacy: between roughly 1969 and 2007, a meaningful share of Belfast's housing stock saw extended periods of partial occupation, paramilitary-related disruption, or families relocating to England and leaving Belfast properties partly furnished and sealed for decades. The clearance volume from the resulting estate, hoarder and decades-sealed-up house work continues today, particularly in Falls and Shankill (BT12/BT13), inner east Belfast, and parts of north Belfast — these jobs run £1,500–£4,500 with significant biohazard and historical-content complexity that needs trauma-informed clearance pricing.",
    "Belfast pricing structure is meaningfully different from GB equivalents. There is no Clean Air Zone in Belfast — the city has been considered for one but not implemented — so fleet costs are lower than Bristol or Bradford, but landfill tax in Northern Ireland operates differently from GB, and the cross-border haulage to the Republic creates competitive pressure on commercial-skip pricing. Single-room clearance pricing in Belfast Council postcodes runs £80–£200 for a single room with furniture, with full one-bed flat clearances at £250–£500 in the Cathedral Quarter, Botanic and Queen's Quarter HMO market. Three-bed full house clearances run £600–£1,400 across BT5, BT6, BT8, BT12, BT13 and BT15. The premium catchment is where Belfast pricing genuinely scales: Stranmillis, Malone Road, Lisburn Road premium belt and Cherryvalley support full Edwardian / Victorian villa clearances of £1,800–£4,500, and the Holywood / Cultra BT18 belt — Northern Ireland's highest-disposable-income area, with established professional and tech-services households — sees probate clearances reaching £2,500–£6,500 on the larger detached stock. Hoarder clearance is unusually prevalent in Belfast for the structural reasons above, with insurance-funded biohazard work running £2,000–£10,000 and most flowing through Health Trust adult social care referrals, the Northern Ireland Hoarding Network or solicitor instruction.",
    "Belfast Google Ads CPCs in clearance keywords sit meaningfully below GB equivalents — a function of fewer national advertisers bidding into NI postcodes plus an NI-only auction dynamic. 'House clearance Belfast' clicks at £1.80–£3.60, 'rubbish removal Belfast' at £1.20–£2.80, 'probate clearance Belfast' at £2.20–£4.20, with the highest-intent BT9 Lisburn Road / Stranmillis and BT18 Holywood / Cultra terms reaching £2.80–£4.80. By comparison, Dublin equivalent searches click at €3.20–€7.40. The strategic implication is that Belfast clearance operators have an unusually cheap window to dominate local SERPs while CPCs remain low — and a structurally available cross-border opportunity into Counties Down, Antrim, Armagh and the broader Belfast metropolitan area that GB-based aggregators cannot service due to NIEA registration and Windsor Framework complexity. BT-postcode-stratified Google Ads + Local Service Ads + Maps optimisation + cross-border ROI campaigns + a probate solicitor B2B funnel reliably produce £25–£55 cost-per-acquired-job versus £100–£200 on Bark, MyBuilder and Checkatrade. Kerblabs' Belfast clearance clients running this stack typically reach 7–11 booked jobs per week per van inside 6 months, with average job value 20–30% above the Belfast market median because review velocity from named BT-postcode customers, NIEA registration display and properly handled cross-border ROI demand pull premium pricing.",
  ],
  stats: [
    { value: "345,418", label: "Belfast LGD population — clearance demand concentrated across BT1–BT17", source: "NISRA Census 2021" },
    { value: "£1,800–£4,500", label: "typical Stranmillis / Malone / Lisburn Road Edwardian villa clearance" },
    { value: "£2,500–£6,500", label: "Holywood / Cultra BT18 premium probate clearance" },
    { value: "£190k", label: "average Belfast house price — meaningfully below UK average, affects clearance economics", source: "NI Land & Property Services 2024" },
    { value: "£1.80–£4.80", label: "Belfast clearance keyword CPC range — 30–45% below Dublin, 15–25% below Manchester", source: "Kerblabs client accounts" },
    { value: "11,500+", label: "Citi + Allstate + Liberty IT + Kainos Belfast tech workforce driving premium private-pay clearance", source: "Belfast tech employer reports" },
  ],
  painPoints: [
    {
      title: "NIEA waste carrier registration invisible despite being a hard trust filter for Belfast solicitors",
      body: "Belfast probate solicitors, executors and commercial customers actively check NIEA waste-carrier registration before instructing — and most clearance operators bury or omit the registration number entirely. Generic 'we recycle where possible' copy doesn't satisfy NI customers who've read enough Belfast Telegraph stories about rogue operators dumping in the Castlereagh Hills or along the Antrim coast. We surface NIEA Upper Tier Waste Carrier registration number, named NI transfer-station partner (Bryson Recycling, RiverRidge Recycling at Mallusk, Dargan Road Materials Recovery Facility), Duty of Care wording and recycling-rate evidence prominently across the website, quote PDFs and AI receptionist scripts."
    },
    {
      title: "Cross-border ROI demand left on the table because GB operators can't service it",
      body: "Belfast-based clearance operators with proper Trans-Frontier Shipment of Waste documentation can legitimately service Counties Louth, Monaghan, Cavan and the broader Republic of Ireland border belt, where Drogheda, Dundalk and Monaghan customers actively look north for Belfast-based clearance services. Most Belfast operators don't market into ROI at all and miss €1,500–€4,500 estate-clearance jobs flowing to Dublin operators who don't actually have the cross-border compliance built. We construct ROI-targeted Google Ads campaigns with EUR pricing, ROI-compliant landing pages aligned to Irish ASAI rather than UK ASA, and explicit Windsor Framework / TFS compliance display."
    },
    {
      title: "Post-Troubles hoarder and decades-sealed-up clearance volume sourced through wrong channels",
      body: "Belfast has an unusually high concentration of hoarder, deceased-estate and decades-sealed-up house clearance work — a structural legacy of Troubles-era population displacement, paramilitary disruption and emigration. This work is sourced through Belfast Health and Social Care Trust adult social care referrals, the Northern Ireland Hoarding Network, NIHE (Northern Ireland Housing Executive) referrals for tenant deceased estates, and Belfast solicitor instruction — not Bark or general Google. Without trauma-informed clearance pricing, biohazard insurance display and proper Health Trust panel application, you're invisible to £2,000–£10,000 jobs flowing to two or three specialists who built the channel."
    },
    {
      title: "GB-templated marketing failing the Belfast market structurally",
      body: "Most clearance operators in Belfast inherit GB-built websites that reference 'Environment Agency' instead of NIEA, 'England and Wales' regulations, 'NHS' rather than HSCNI, and Rightmove/Zoopla rather than PropertyPal — every one of which signals to NI customers that the operator doesn't understand local regulation. Belfast customers read carefully and discount providers who can't demonstrate NI fluency. We rebuild every customer touchpoint to NI-specific reality: NIEA wording, HSCNI-aware probate language, PropertyPal integration for estate-agent referrals, BT-postcode service-area definition, and Windsor Framework cross-border content where commercially relevant."
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us beat Clearabee, AnyJunk, Junk Hunters and the Bark/MyBuilder aggregators in Belfast specifically?",
      a: "Three-phase Belfast-specific playbook. Phase one: Google Business Profile category stacking (Junk Removal Service + Waste Management Service + House Clearance Service + Rubbish Removal Service) with BT-postcode service-area definition, NIEA Upper Tier Waste Carrier registration schema (Northern Ireland-specific, not Environment Agency), named NI transfer-station partner (Bryson Recycling, RiverRidge, Dargan Road MRF), and structured review campaigns targeting 8–14 new reviews per month with named BT-postcode keywords (Stranmillis, Malone, Lisburn Road, Cathedral Quarter, Ballyhackamore, Holywood, Cultra). Phase two: Google Local Service Ads with the Google Guaranteed badge — on Belfast clearance keywords this consistently lands at £25–£55 cost-per-job versus £100–£200 on Bark and MyBuilder. Phase three: BT-stratified Google Ads (separate campaigns for BT1/BT2 city-centre and Cathedral Quarter, BT9 Lisburn Road premium probate, BT4 Ballyhackamore family suburbs, BT18 Holywood/Cultra premium belt, plus cross-border ROI campaigns into Counties Down/Antrim/Armagh and Drogheda/Dundalk where compliant), plus a probate B2B funnel targeting Belfast solicitors (Carson McDowell, Tughans, Pinsent Masons Belfast, A&L Goodbody Belfast, Cleaver Fulton Rankin, plus 250+ smaller firms) that aggregators don't compete for. Belfast clearance clients typically reduce aggregator dependency from 45% to 12% inside 6 months while growing total job volume 30–50%."
    },
    {
      q: "Can the AI receptionist handle the difference between a £150 BT7 student-flat clearance and a £6,000 Holywood probate?",
      a: "Yes — that's the qualifying flow at the centre of the Belfast build. The first three questions are: is this an end-of-tenancy/student/single-room job, a full house clearance, or a probate/executor clearance. Botanic and Queen's Quarter (BT7) student-flat callouts trigger a fixed-price banded quote against your published price list and same-day calendar slot. End-of-tenancy clearances trigger a letting-agent-aware flow with PropertyPal-aligned deposit-deduction documentation (rather than GB Rightmove templates) and Duty of Care wording NI landlords actually need. Probate triggers a 90-minute on-site survey appointment, formal scope-of-works template, written quotation with VAT and EWC waste codes, and a solicitor-friendly invoice format aligned to Northern Ireland probate (grant of probate, letters of administration) processes. Hoarder/deceased-estate cases trigger a referral pathway with Belfast Health and Social Care Trust liaison and biohazard pricing. Cross-border ROI enquiries trigger a separate Republic of Ireland flow with EUR pricing, Irish ASAI-compliant communication and Trans-Frontier Shipment of Waste documentation. The clearance operator never has to sort generic enquiries again."
    },
    {
      q: "How do you handle NIEA waste regulations and cross-border ROI complexity in marketing copy and quote pipelines?",
      a: "We build NIEA and cross-border awareness directly into the customer journey, because Belfast customers and solicitors read for regulatory specificity. NIEA Upper Tier Waste Carrier registration number is displayed prominently in the website header, footer, GBP, quote PDFs and email signatures — not buried on a contact page. Named NI transfer-station partners (Bryson Recycling at Mallusk and Lisburn, RiverRidge Recycling, Dargan Road MRF, plus Suez NI operations where relevant) are listed with annual recycling rates published. The website includes a BT-postcode clearance complexity content hub (different content for BT1 Cathedral Quarter vs BT9 Stranmillis vs BT18 Holywood vs BT4 Ballyhackamore) which doubles as long-tail SEO. For cross-border ROI work, a dedicated 'house clearance Drogheda from Belfast', 'estate clearance Dundalk', 'rubbish removal Monaghan' content cluster surfaces with EUR pricing, ROI-compliant copy aligned to ASAI rather than UK ASA, and explicit Windsor Framework / Trans-Frontier Shipment of Waste documentation handling. Quote PDFs include the relevant NIEA registration certificate and, where applicable, the TFS notification number for cross-border shipments."
    },
    {
      q: "Can Kerblabs really land the £2,500–£6,500 Holywood, Cultra, Stranmillis and Malone probate work in Belfast's tight network?",
      a: "Yes — Belfast's probate network is meaningfully smaller than London's or Manchester's, which makes systematic outreach genuinely effective once it's properly built. Probate clearance in Belfast is sourced through three channels: (1) Belfast probate solicitors and executors — Carson McDowell, Tughans, Pinsent Masons Belfast office, A&L Goodbody, Cleaver Fulton Rankin, Mills Selig, Worthingtons Solicitors, Murphy O'Rawe, and the Belfast offices of Eversheds Sutherland and Arthur Cox, plus 250+ smaller firms with strong concentration around Lisburn Road, Royal Avenue and Donegall Square; (2) STEP Northern Ireland Branch members and the Law Society of Northern Ireland Probate and Trust Committee, who hold regular CPD events that double as networking opportunities for credible clearance partners; and (3) chartered surveyors and contents valuers including Ross's Auctioneers (the major NI auction house), McAfee Auctioneers, Wilson's Auctions, and Belfast-based RICS valuers who routinely refer onward clearance work. We build a structured B2B outreach programme: solicitor-firm targeted LinkedIn and email outreach with case studies of completed Belfast probate clearances, formal panel-application packs aligned to Northern Ireland probate processes, attendance at STEP NI and Law Society probate events, and a probate-specific landing page optimised for 'probate house clearance Belfast', 'executor clearance Holywood', 'estate clearance Stranmillis' and the longer-tail BT-postcode terms. Belfast clearance clients running this typically book 1–4 probate jobs per month at £2,000–£5,500 average within 6–9 months."
    },
  ],
  approach:
    "For Belfast junk removal and house clearance firms, our 90-day playbook is: (1) build parallel direct-acquisition (Google LSA + BT-stratified Google Ads + Maps optimisation) to reduce Bark/MyBuilder/Checkatrade dependency from 45% to under 15%; (2) deploy AI 24/7 receptionist with BT-postcode-aware qualifying flow plus separate funnels for student/end-of-tenancy, full house, probate, hoarder/deceased-estate and cross-border ROI customers; (3) build a probate B2B funnel with solicitor outreach to Carson McDowell, Tughans, Pinsent Masons Belfast, A&L Goodbody, Cleaver Fulton Rankin and the STEP NI network to capture £2,000–£6,500 Stranmillis/Malone/Holywood/Cultra estate clearances; (4) surface NIEA Upper Tier Waste Carrier credentials and named NI transfer-station partner (Bryson, RiverRidge, Dargan Road) prominently to break the rogue-operator suspicion default and signal regulatory fluency NI customers value; and (5) drive Google review velocity to 8–14 new reviews per month with named BT-postcode density plus structured cross-border ROI landing pages where commercially relevant.",
};
