import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "kitchen fitter marketing Stoke-on-Trent",
    "kitchen designer Stoke SEO",
    "Hanley Burslem kitchen marketing",
    "Stoke Kitchen Centre Google Ads",
    "Howdens kitchen fitter Stoke-on-Trent",
  ],
  secondaryKeywords: [
    "Stoke six towns kitchen designer",
    "Trentham premium kitchen marketing Stoke",
    "Stoke Kitchen Centre alternative",
    "Newcastle-under-Lyme kitchen extension",
    "Bet365 Etruria employee kitchen marketing",
    "Tunstall Burslem Howdens kitchen fitter",
    "ST postcode budget kitchen Stoke",
    "Longton Fenton kitchen renovation",
  ],
  heroSubhead:
    "Stoke-on-Trent's kitchen market is structurally unique because the city is six federated towns — Tunstall, Burslem, Hanley, Stoke, Fenton, Longton — each with its own high street and customer base, with the wider Newcastle-under-Lyme borough adjacent. The dominant £8,000–£15,000 budget specification reflects average house prices around £155k (among UK's most affordable), with Trentham, Westlands and Endon supporting £18–35k premium pull. Stoke Kitchen Centre and the six-towns family-run independents own the £8–14k specification with strong physical-store and Facebook word-of-mouth flow. Wren operates a Festival Park retail flagship, Howdens runs 4+ Staffordshire depots, and Wickes installed-kitchens competes through Festival Park and Newcastle retail parks. Kerblabs gives Stoke independents the AI receptionist, six-towns hyperlocal targeting, pay-day-cycle automation and review velocity to win without Birmingham-agency markup.",
  marketContext: [
    "Stoke-on-Trent's kitchen market reflects one of the most affordable property markets in England — average house prices around £155,000, average earnings a notch below the UK mean — and that economic reality shapes the dominant specification band. The £8,000–£15,000 typical Stoke kitchen is a Howdens-supplied or Symphony / Magnet Trade-supplied Shaker, in-frame painted or slab-handleless specification across the six towns of Tunstall (ST6), Burslem (ST6), Hanley (ST1), Stoke (ST4), Fenton (ST4) and Longton (ST3), plus the wider Newcastle-under-Lyme borough (ST5). Customer behaviour is genuinely six-towns specific: a Burslem salon's customers very rarely travel to Longton, an Endon dentist's catchment looks completely different from one in Tunstall, and a kitchen-fitter campaign built for 'Stoke' as a single place wastes 25–40% of every pound. Stoke Kitchen Centre, the six-towns family-run independents and the Newcastle-under-Lyme Westlands designer firms own this band by understanding the federated-town geography, the pay-day-cycle spending pattern, and the Facebook-dominant word-of-mouth flow that drives 40–55% of new bookings in ST postcodes.",
    "The Trentham, Westlands, Newcastle-under-Lyme and Endon premium tier supports £18,000–£35,000 in-frame painted, German rigid (Schuller, Nolte) and Shaker work for the higher-earning professional households driven by Bet365's 5,000+ Etruria headquarters, JCB Power Systems, Vodafone Stoke, and the long-tail logistics-cluster management around the Festival Park / Etruria Valley belt. Bet365 alone has materially reshaped the Stoke premium kitchen demand pipeline since 2015, generating 200–400 incoming professional households per year settling in Trentham, Westlands and the Newcastle-under-Lyme commuter belt. The most contested £15,000–£20,000 mid-market band falls in Trentham, Westlands and the upper-Newcastle-under-Lyme belt where Wren's Festival Park flagship, Magnet Trade, Wickes installed-kitchens and a tier of established Stoke independents fight for architect-led extension projects. Houzz Pro lead fees here run £12–£28 per qualified enquiry — among the lowest in the UK because national chains underspend in the Stoke auction. Tunstall, Hanley, Longton, Fenton and Burslem high-street volume work runs £6,000–£12,000 Howdens-supplied or Symphony Trade-supplied through 4+ Staffordshire depots.",
    "The 2026 win for Stoke independents is the six-towns hyperlocal-stratification pivot plus Bet365 / Trentham premium specialism. Stoke independents that surface KBSA credentials, named-designer continuity, named six-towns case studies (with explicit Tunstall / Burslem / Hanley / Stoke / Fenton / Longton / Trentham / Westlands references), Bet365-employee-aware finance-options literacy, and the unusually strong Facebook community group presence (Mickleover-equivalent groups exist across all six towns) consistently lift average project value 20–35% versus generic 'kitchen fitter Stoke' positioning. Pay-day-cycle automation matters more here than in higher-income markets — Stoke households strongly prefer end-of-month deposit timing aligned with monthly salary cycles. Add a structured Houzz Pro / Instagram DM funnel responding within 90 seconds to evening enquiries, and Stoke independent kitchen studios running this stack typically convert 36–46% of qualified enquiries to paid design appointments versus 18–24% on a manual-response baseline.",
  ],
  stats: [
    { value: "£18,000–£35,000", label: "typical Trentham / Westlands / Newcastle-under-Lyme / Endon premium kitchen project value" },
    { value: "£8,000–£15,000", label: "typical Stoke six-towns Howdens-supplied / Symphony Trade kitchen project value" },
    { value: "£155k", label: "average Stoke house price — among UK's most affordable cities, shapes specification budget", source: "Land Registry" },
    { value: "5,000+", label: "Bet365 Etruria HQ employees driving Stoke premium kitchen demand uplift since 2015", source: "Bet365" },
    { value: "4+", label: "Howdens depots across Staffordshire supplying Stoke six-towns independents" },
    { value: "£12–£28", label: "typical Houzz Pro qualified-lead fee per Stoke enquiry — among UK's lowest regional rates", source: "Kerblabs client accounts" },
  ],
  painPoints: [
    {
      title: "Wren Festival Park, Wickes installed-kitchens and B&Q-supplied own-installation crowding the £8–15k six-towns volume band",
      body: "Wren's Festival Park retail park flagship, Wickes installed-kitchens through Festival Park and Newcastle retail parks, B&Q-supplied own-installation through Hanley and Newcastle stores, and Magnet Trade through their Stoke depot all run unified West Midlands bidding on 'kitchen fitter Hanley', 'kitchen fitter Burslem' and 'kitchen designer Trentham'. Stoke Kitchen Centre, the six-towns family-run independents and the Westlands designer firms win on named-fitter continuity, 4–6 week design-to-install lead times versus Wren's slipping 8–12 weeks, post-completion review velocity, and Facebook community group word-of-mouth — but most under-market all four.",
    },
    {
      title: "Six-towns geography ignored in single-campaign 'Stoke' targeting wastes 25–40% of every pound",
      body: "Stoke is six federated towns plus Newcastle-under-Lyme — Hanley, Burslem, Tunstall, Stoke, Fenton, Longton, Newcastle — each with its own high street, demographic skew and competitive set. Most Stoke independents run a single 'kitchen fitter Stoke-on-Trent' Google Ads campaign that averages all six towns into mediocrity, missing the postcode-specific intent that drives 80%+ of conversions. We rebuild around six-towns stratified bidding (ST1 Hanley, ST3 Longton, ST4 Stoke / Fenton, ST5 Newcastle, ST6 Burslem / Tunstall) plus dedicated Trentham / Westlands / Endon premium landing pages, which routinely cuts cost-per-lead by 25–40% versus single-campaign targeting.",
    },
    {
      title: "Stoke Facebook community group word-of-mouth not captured systematically",
      body: "Stoke's Facebook community group presence is unusually strong across all six towns plus Newcastle-under-Lyme — Hanley Buy / Sell / Recommend, Burslem Community, Tunstall Community, Stoke Community, Longton Community, Trentham Community, Newcastle-under-Lyme Community — and 40–55% of kitchen-fitter recommendations flow through 'who would you recommend?' threads in these groups. Wren and Wickes cannot meaningfully participate because community moderators police commercial posting heavily. Most Stoke independents fail to systematically engage these groups, fail to schedule organic post cadence, and miss the structural word-of-mouth advantage entirely.",
    },
    {
      title: "Bet365 / JCB / Vodafone employee finance and shift-aware pricing under-marketed",
      body: "Bet365's 5,000+ Etruria HQ employees, plus JCB Power Systems, Vodafone Stoke and the wider logistics-cluster workforce drive a steady premium kitchen demand pipeline across Trentham, Westlands and Newcastle-under-Lyme. Bet365 in particular runs employee-finance schemes and corporate-relocation packages that include kitchen-renovation eligibility for incoming professional staff. Most Stoke independents either don't know these exist or bury them on a credentials page. We surface Bet365 / JCB / Vodafone employee-finance literacy explicitly in landing-page copy, AI receptionist qualifying flow ('are you working at Bet365 / JCB / Vodafone Stoke?'), and quote documents — and rebuild around shift-aware ad scheduling that lands during the windows Bet365 24/7 operations staff actually browse (early morning 6-8am, lunch 12-2pm, post-shift 9-11pm).",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us compete with Wren Festival Park, Wickes and B&Q for the six-towns £8–15k volume kitchen market?",
      a: "Out-spending Wren and Wickes on Google Ads is the wrong battle in a market where margins are tighter than Cheshire or Manchester. The right battle is named-fitter continuity, 4–6 week design-to-install lead times versus Wren's slipping 8–12 weeks, KBSA credentials, post-completion review velocity, six-towns Facebook community group word-of-mouth, and pay-day-cycle deposit timing. We build out 18–28 town × postcode landing pages (Shaker kitchen Hanley, in-frame painted Burslem, German rigid Trentham, Howdens-supplied Tunstall, slab-handleless Newcastle-under-Lyme), each with named-fitter profiles, KBSA badges, named six-towns case studies on actual streets the prospect lives near, Gas Safe and NICEIC subcontractor coverage, and Houzz / Instagram portfolio embeds. We then run a tight long-tail Google Ads campaign with ST1 / ST3 / ST4 / ST5 / ST6 stratified bidding at £1.20–£3 CPC, organise systematic Facebook community group engagement, and route every enquiry through AI receptionist with 90-second response. Stoke independents running this approach have consistently outperformed single-'Stoke' campaign spend by 2.2–3.5x ROAS.",
    },
    {
      q: "How do you handle the six-towns Facebook community group word-of-mouth pipeline?",
      a: "Stoke's six-towns Facebook community groups (Hanley Buy / Sell / Recommend, Burslem Community, Tunstall Community, Stoke Community, Longton Community, Trentham Community, Newcastle-under-Lyme Community) drive 40–55% of kitchen-fitter recommendations through 'who would you recommend?' threads — substantially higher than the UK average, in part because Facebook still punches above its UK-average weight for over-35s in ST postcodes. Wren and Wickes cannot meaningfully participate because community moderators police commercial posting heavily. Independent kitchen firms have a structural advantage if they show up authentically — through completed-project posts with permission, before-and-after galleries on real six-towns streets, and named-fitter responses in recommendation threads. We set up community-aware Meta Ads targeting these specific groups, schedule organic post cadence with Stoke-shot creative (not stock imagery), and use AI to draft response templates for the inevitable recommendation threads while keeping the brand voice authentic. This pairs well with Google Search and Houzz Pro and routinely captures 25–35% of new enquiries at near-zero CPC across the six towns.",
    },
    {
      q: "How do you handle the Bet365, JCB and Vodafone employee kitchen demand pipeline?",
      a: "Bet365's 5,000+ Etruria HQ workforce, plus JCB Power Systems and Vodafone Stoke, drive a steady premium kitchen demand pipeline particularly in Trentham, Westlands and the Newcastle-under-Lyme commuter belt where these employees consistently cluster. Bet365 in particular runs 24/7 operations and runs employee-finance schemes and corporate-relocation packages that include kitchen-renovation eligibility for incoming professional staff. We rebuild around shift-aware ad scheduling that lands during the windows Bet365 staff actually browse (early morning 6-8am, lunch 12-2pm, post-shift 9-11pm) rather than conventional 9-5 windows, surface Bet365 / JCB / Vodafone employee-finance literacy explicitly in landing-page copy and quote documents, configure AI receptionist with 'are you working at Bet365 / JCB / Vodafone?' as the third qualifying question, and integrate a dedicated employee-priority quote pipeline. Stoke independents running this approach consistently win 25–35% of incoming Bet365-employee kitchen specifications that would otherwise default to Wren Festival Park.",
    },
    {
      q: "Is the Stoke market really worth investing in given lower average earnings and £155k average house prices?",
      a: "Yes — and lower average earnings are easy to misread. Stoke households tend to spend a higher share of income locally because the city is comparatively self-contained, and the cost base for SMEs (rent, salaries, ad CPCs, ad CPMs) is dramatically lower than Manchester or Birmingham. Google Ads CPCs for 'kitchen fitter Stoke' run £1.20–£3 versus £4–£9 in equivalent Birmingham / Manchester searches, Houzz Pro lead fees run £12–£28 versus £25–£50 elsewhere, and competition in the six-towns local pack is genuinely winnable. Bet365, JCB, Vodafone and the warehouse cluster also bring in a layer of higher earners that pulls demand for premium £18–35k Trentham / Westlands kitchens, and London-relocator inflow into Trentham, Newcastle-under-Lyme and Endon is steady. A well-run Stoke independent at £10–18k average project value with 30–40% gross margin can be more profitable than a Manchester equivalent at £20k with 25% margin — because the cost base differential is dramatic.",
    },
  ],
  approach:
    "For Stoke-on-Trent kitchen fitters and designers, our 90-day playbook is: (1) stratify your service area into the six federated towns plus Newcastle-under-Lyme plus the Trentham / Westlands premium pocket — each as a distinct campaign tier (ST1 Hanley, ST3 Longton, ST4 Stoke / Fenton, ST5 Newcastle-under-Lyme, ST6 Burslem / Tunstall, plus Trentham / Westlands / Endon premium £18–35k overlay) and rebuild Google Ads, landing pages and Houzz Pro listings accordingly; (2) deploy AI receptionist with kitchen-specific qualifying flow including 'are you working at Bet365 / JCB / Vodafone?' as third question, six-towns geography awareness, shift-aware ad scheduling for 24/7 employee browsing windows, and 90-second auto-response across phone, Houzz Pro, Instagram DM, six-towns Facebook community group enquiries and contact form; (3) launch a deposit-conversion automation sequence covering post-design-appointment SMS, week 1–3 nurture with KBSA / Gas Safe / NICEIC credentials, Bet365 / JCB / Vodafone employee-finance literacy, pay-day-cycle deposit timing, and 'why us not Wren Festival Park / Wickes / B&Q' breakdown; (4) build out 25–35 hyperlocal style × six-towns landing pages with named-fitter profiles, named six-towns case studies, Trentham / Westlands premium portfolio examples and Houzz / Instagram archive embeds; (5) systematically engage the six-towns Facebook community groups with Stoke-shot creative; and (6) drive Google review velocity to 6–10 new reviews per month through automated post-completion SMS to dominate borough-level local pack across ST1 / ST3 / ST4 / ST5 / ST6.",
};
