import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "kitchen fitter marketing Derby",
    "kitchen designer Derby SEO",
    "Allestree premium kitchen marketing",
    "Derby Kitchen Studio Google Ads",
    "Howdens kitchen fitter Derby",
  ],
  secondaryKeywords: [
    "Littleover Mickleover premium kitchen designer",
    "Rolls-Royce Sinfin relocation kitchen specialist",
    "Toyota Burnaston employee kitchen marketing",
    "Derby Kitchen Studio alternative",
    "Quarndon Allestree German rigid kitchen Derby",
    "Chellaston Spondon kitchen extension Derby",
    "Derby Schuller Nolte Leicht kitchen showroom",
    "Alstom Litchurch Lane kitchen designer",
  ],
  heroSubhead:
    "Derby's kitchen market is one of the highest average-project-value markets in the East Midlands because the engineering-professional concentration — Rolls-Royce Civil Aerospace (14,000+ at Sinfin and Raynesway), Toyota Burnaston (3,000+), Alstom Litchurch Lane (3,000+ train manufacturing) and JCB Power Systems — drives sustained £12,000–£25,000 typical specification with strong £25–45k Allestree / Mickleover / Littleover / Quarndon premium pull. Derby Kitchen Studio and the Allestree independents own the £18–35k mid-premium specification, while Wren operates a Pride Park retail park flagship, Howdens runs 4+ Derbyshire depots, and Wickes installed-kitchens competes through Wyvern and Meteor Centre retail parks. Kerblabs gives Derby independents the AI receptionist, Rolls-Royce-aware funnel, deposit-conversion automation and review velocity to win against research-driven engineering buyers.",
  marketContext: [
    "Derby's kitchen market is shaped by one of the most concentrated high-skill, high-earning professional populations in the UK outside London. Rolls-Royce Civil Aerospace's Sinfin and Raynesway sites employ over 14,000 directly; Toyota Burnaston employs 3,000+ producing 5m+ vehicles since 1992; Alstom Litchurch Lane is the UK's only volume train-manufacturing facility with 3,000+ engineering staff; and JCB Power Systems, Pattonair and a long tail of aerospace and rail tier-one suppliers ring the city. The practical effect on the kitchen market is dramatic: Derby has the most research-driven kitchen-buying audience in the East Midlands. Engineering professionals at Rolls-Royce, Toyota and Alstom typically visit the showroom 3–4 times before committing, scrutinise GDC-equivalent KBSA credentials, read every Google review, compare line-item quotes carefully against Wren and Howdens-direct, and demand itemised drawings before deposit. Average project values reflect this: £12,000–£25,000 typical across Allestree, Mickleover, Littleover, Chellaston and Spondon, with £25,000–£45,000 in the Allestree / Quarndon / Mickleover premium top tier.",
    "The premium specification belt — Allestree, Quarndon, Mickleover, Littleover and Darley Abbey — supports £25,000–£45,000 German rigid (Schuller, Nolte, Leicht, Häcker), in-frame painted and bespoke Shaker work for senior Rolls-Royce engineers, Toyota plant management, Alstom project leads and the older established professional households along the Markeaton Park corridor. Derby Kitchen Studio, the Allestree independents and the Friar Gate-area designer firms own this band by understanding engineering-professional decision-making, supplier flexibility (Schuller, Nolte, Leicht, Häcker rather than single-factory lock-in), and the named-designer continuity that volume chains structurally cannot match. The most contested £15,000–£25,000 mid-market band falls in Mickleover, Littleover, Chellaston, Oakwood, Spondon and Borrowash where Tom Howley's Nottingham satellite (45 mins), John Lewis of Hungerford, Wren's Pride Park flagship and a tier of established Derby independents fight for architect-led extension projects. Houzz Pro lead fees here run £15–£35 per qualified enquiry. Normanton, Sinfin and the inner-southern wards run a £8,000–£14,000 Howdens-supplied volume tier with Wickes installed-kitchens providing the dominant retail-funnel competition.",
    "The 2026 win for Derby independents is the engineering-professional research-driven content pivot plus Rolls-Royce / Toyota / Alstom relocation-aware funnel. Derby independents that surface KBSA credentials, named-designer continuity, named Rolls-Royce / Toyota / Alstom case studies, and detailed treatment-style technical landing-page content (Schuller factory-tour photography, named worktop fabricator partnerships, named Gas Safe / NICEIC subcontractor profiles) consistently lift average project value 20–35% versus generic 'kitchen fitter Derby' positioning. Derby's engineering-professional audience reads long-form technical content thoroughly — the city consistently shows above-UK-average dwell times and pages-per-session on detailed kitchen specification pages. Add a structured Houzz Pro / Instagram DM funnel responding within 90 seconds to evening enquiries, and Derby independent kitchen studios running this stack typically convert 38–48% of qualified enquiries to paid design appointments versus 18–24% on a manual-response baseline.",
  ],
  stats: [
    { value: "£25,000–£45,000", label: "typical Allestree / Quarndon / Mickleover / Darley Abbey premium German rigid kitchen project value" },
    { value: "£15,000–£25,000", label: "typical Mickleover / Littleover / Chellaston / Oakwood mid-market Shaker / extension project value" },
    { value: "£12,000–£20,000", label: "typical Spondon / Borrowash / Chaddesden engineering-professional kitchen project value" },
    { value: "14,000+", label: "Rolls-Royce Civil Aerospace Derby employees driving high-skill kitchen demand", source: "Rolls-Royce" },
    { value: "4+", label: "Howdens depots across Derby and Derbyshire supplying independents" },
    { value: "£15–£35", label: "typical Houzz Pro qualified-lead fee per Derby enquiry", source: "Kerblabs client accounts" },
  ],
  painPoints: [
    {
      title: "Wren Pride Park, Tom Howley Nottingham and Wickes installed-kitchens crowding the £15–25k Mickleover middle",
      body: "Wren's Pride Park retail park flagship, Tom Howley's Nottingham showroom (a 45-minute drive that pulls Derby premium customers regularly), John Lewis of Hungerford and Wickes installed-kitchens through Wyvern and Meteor Centre retail parks all run unified East Midlands bidding on 'kitchen designer Mickleover', 'Shaker kitchen Allestree' and 'extension kitchen Chellaston'. Derby Kitchen Studio, the Allestree independents and the Friar Gate-area designer firms win on named-designer continuity, KBSA credentials, supplier flexibility (Schuller, Nolte, Leicht, Häcker rather than single-factory lock-in) and detailed engineering-grade technical content — but most under-market all four.",
    },
    {
      title: "Rolls-Royce, Toyota and Alstom engineering-professional research-driven decision-making misunderstood",
      body: "Engineering professionals at Rolls-Royce Sinfin / Raynesway, Toyota Burnaston, Alstom Litchurch Lane, JCB and Pattonair are among the most research-driven kitchen-buying audiences in the UK. They visit the showroom 3–4 times before deposit, scrutinise KBSA credentials, read every Google review, compare line-item quotes against Wren and Howdens-direct, and demand itemised drawings before commitment. Glossy hero shots and discount headlines under-perform. What works is detailed treatment-style technical content (Schuller / Nolte / Leicht / Häcker factory-tour photography, named worktop fabricator partnerships, named Gas Safe / NICEIC subcontractor profiles), longer-form landing pages, before-and-after galleries with engineering-grade context. Most Derby independents publish thin content and miss this entire audience.",
    },
    {
      title: "Evening Houzz, Instagram and Mickleover / Allestree Facebook community group enquiries dying overnight",
      body: "Derby engineering professionals enquire about £15–35k kitchens between 8.30pm and 11pm after their commute home from Sinfin or Burnaston, post 'who would you recommend?' threads in the unusually active Mickleover / Allestree / Chellaston Facebook community groups, and DM Instagram from the office during lunch breaks. Single-designer Derby studios cannot manually triage 12–25 evening enquiries per week; 60–75% are dead by morning. AI receptionist plus Houzz Pro, Instagram DM and Facebook community group auto-routing routinely adds £18,000–£50,000 in monthly recovered design-appointment value for Derby independents.",
    },
    {
      title: "Rolls-Royce / Toyota / Alstom relocation pipeline and named case studies completely under-marketed",
      body: "Rolls-Royce Sinfin, Toyota Burnaston, Alstom Litchurch Lane and JCB Power Systems together cycle 400–700 incoming engineering professionals into Derby each year on relocation. They settle into Allestree, Mickleover, Littleover, Quarndon and Chellaston, and renovate kitchens within 12–18 months of arrival commissioning £15–35k specifications. Most Derby independents have generic websites with stock photos that say nothing about Rolls-Royce / Toyota / Alstom relocation literacy, named Sinfin / Burnaston / Litchurch Lane case studies, or accelerated 10–14 week lead times for time-poor relocators. We rebuild around named relocator case studies — making the firm visible to the engineering-professional audience that Tom Howley Nottingham captures by default.",
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs help us reach the Rolls-Royce, Toyota and Alstom engineering-professional kitchen audience?",
      a: "The Derby engineering-professional audience is genuinely different from a typical kitchen-buying market and rewards a different content strategy than glossy lifestyle imagery. We rebuild around detailed treatment-style technical content: named Schuller / Nolte / Leicht / Häcker factory partnerships with factory-tour photography, named worktop fabricator partnerships (silestone, dekton, neolith with named local fabricators), named Gas Safe / NICEIC / WRAS subcontractor profiles with register numbers visible, longer-form landing pages explaining build sequencing and material specification, and before-and-after galleries with itemised CAD drawings. We surface KBSA / BIID member-directory placement, named-designer continuity (the same designer takes the brief, draws the CAD, supervises the install and handles snagging), and detailed 12–20 week project-management timelines. Derby engineering professionals at Rolls-Royce, Toyota and Alstom convert at unusually high rates on this content because it matches their professional decision-making style — they read every word, cross-reference, and respond to firms that meet their professional standards. Average project value typically lifts 20–35% within 6 months because the spec gets fully scoped at first call rather than discount-anchored.",
    },
    {
      q: "How do you handle the Rolls-Royce / Toyota / Alstom corporate-relocation kitchen pipeline?",
      a: "Rolls-Royce Sinfin / Raynesway, Toyota Burnaston, Alstom Litchurch Lane and JCB Power Systems together cycle 400–700 incoming engineering professionals into Derby each year on 3–5 year postings. They settle into Allestree, Mickleover, Littleover, Quarndon, Chellaston and Oakwood, and renovate kitchens within 12–18 months of arrival commissioning £15–35k specifications under accelerated timelines. We rebuild around named relocator case studies, surface Rolls-Royce / Toyota / Alstom corporate-relocation literacy explicitly in landing-page copy, configure AI receptionist with 'are you relocating with Rolls-Royce / Toyota / Alstom?' as the third qualifying question, and integrate a dedicated relocator-priority quote pipeline turning design-appointment to factory-order in 14 days versus the 4–6 week independent baseline. Derby independents running this approach consistently win 25–40% of incoming Rolls-Royce / Toyota / Alstom relocator kitchen specifications that would otherwise default to Tom Howley Nottingham or Wren Pride Park.",
    },
    {
      q: "We get a lot of enquiries through Mickleover and Allestree Facebook community groups — how do you handle that?",
      a: "Derby's suburban Facebook community groups (Mickleover Community, Allestree Community, Chellaston Community, Oakwood Community, Spondon Community) are unusually active by UK standards and drive a meaningful share of kitchen-fitter recommendations through 'who would you recommend?' threads. Wren and Howdens-direct cannot meaningfully participate in these groups because the community moderators police commercial posting heavily. Independent kitchen firms have a structural advantage if they show up authentically — through completed-project posts with permission, before-and-after galleries on real Mickleover / Allestree streets, and named-designer responses in recommendation threads. We set up community-aware Meta Ads targeting these specific groups, schedule organic post cadence with Derby-shot creative (not stock imagery), and use AI to draft response templates for the inevitable recommendation threads while keeping the brand voice authentic. This pairs well with Google Search and Houzz Pro and routinely captures 15–30% of new enquiries at near-zero CPC.",
    },
    {
      q: "We're a Spondon / Chaddesden / Sinfin Howdens-supplied installer at £10–18k. Is this approach realistic at our price point?",
      a: "Yes — and the Spondon / Chaddesden / Sinfin economics are arguably better than the Allestree / Quarndon premium tier because Google Ads CPCs run £1.40–£3.50 versus £4–£8 in the premium suburbs, while project values average £12–18k and customer loyalty in the engineering-professional Sinfin and Pride Park-adjacent catchment is unusually durable. Howdens-supplied installers across Spondon, Chaddesden, Sinfin, Alvaston and Boulton have a structural advantage independent designer studios can't match: 4–8 week design-to-install lead times versus 16–20 weeks for German rigid, depot-collected materials simplifying scheduling (Derby and Burton Howdens depots both serve this catchment), and trade-account credit. We rebuild around the speed advantage, surface the named Howdens depot relationship, pair it with named Gas Safe / NICEIC subcontractor coverage, and run DE21 / DE22 / DE23 / DE24 Google Ads at £1.40–£3.50 CPC. Spondon / Chaddesden Kerblabs kitchen clients consistently book 6–11 design appointments per week from £260–£450 monthly Google Ads spend.",
    },
  ],
  approach:
    "For Derby kitchen fitters and designers, our 90-day playbook is: (1) stratify your service area into 4 distinct tiers (Allestree / Quarndon / Mickleover / Darley Abbey premium £25–45k; Mickleover / Littleover / Chellaston / Oakwood mid-market £15–25k; Spondon / Chaddesden / Sinfin / Alvaston Howdens-supplied £10–18k; Normanton / Pear Tree / Sinfin volume £8–14k) and rebuild Google Ads, landing pages and Houzz Pro listings accordingly; (2) deploy AI receptionist with kitchen-specific qualifying flow including 'are you relocating with Rolls-Royce / Toyota / Alstom?' as third question, and 90-second auto-response across phone, Houzz Pro, Instagram DM, Mickleover / Allestree Facebook community group enquiries and contact form; (3) launch a deposit-conversion automation sequence covering post-design-appointment SMS, week 1–3 nurture with KBSA / BIID / Gas Safe / NICEIC credentials, detailed Schuller / Nolte / Leicht / Häcker factory-tour content, Rolls-Royce / Toyota / Alstom corporate-relocation literacy and 'why us not Tom Howley Nottingham / Wren / Wickes' breakdown; (4) build out 25–35 hyperlocal style × postcode landing pages with engineering-grade technical content, named-designer profiles, named relocator case studies and Houzz / Instagram archive embeds; and (5) drive Google review velocity to 6–10 new reviews per month through automated post-completion SMS to dominate borough-level local pack across DE1 / DE3 / DE21 / DE22 / DE23.",
};
