import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "mobile mechanic marketing Swansea",
    "MOT garage Swansea SEO",
    "Swansea car servicing lead generation",
    "Owen's Garage alternative Swansea",
    "mechanic Google Ads Swansea",
  ],
  secondaryKeywords: [
    "Gorseinon Llansamlet industrial mobile mechanic SEO",
    "Welsh language garage marketing Swansea",
    "Class 4 Class 7 MOT Swansea",
    "Halfords alternative Swansea",
    "SA postcode garage SEO",
    "NRW oil disposal compliance Swansea",
    "Tata Steel Port Talbot fleet servicing",
    "DVLA Morriston staff fleet servicing",
  ],
  heroSubhead:
    "Swansea's mechanic market sits at the intersection of three forces no other Welsh city combines: the slow decline of Tata Steel Port Talbot's ICE-dominated workforce fleet (~3,000 jobs at the steelworks dropping further with the 2024 blast furnace closure), the steady growth of the DVLA Morriston headquarters (~6,000 staff with associated fleet), and a Welsh-language customer base in Gorseinon, Pontarddulais and Loughor where bilingual marketing earns measurable trust signals competitors won't replicate. Swansea has no Clean Air Zone — but Natural Resources Wales (NRW) operates the strictest waste oil disposal regime in the UK, and non-compliance carries fines and prosecution risk. Owen's Garage, Halfords Autocentres at Fforestfach, Kwik Fit at multiple SA sites, plus the Gorseinon and Llansamlet industrial-estate workshop clusters define a market where SA-postcode local SEO, Welsh-language content and NRW compliance positioning win.",
  marketContext: [
    "Swansea's mechanic market is structurally shaped by the decline of Tata Steel Port Talbot, the steady DVLA Morriston employment base, and Welsh-language commercial dynamics that don't exist anywhere else in the UK at this scale. Tata Steel Port Talbot is the largest single employer in South West Wales — historically ~4,000 direct jobs, falling toward ~2,500 with the September 2024 closure of both blast furnaces and transition to electric arc furnace operation by 2027–2028. The associated ICE-dominated workforce fleet (Tata staff personal vehicles plus contractor LCVs) has historically cycled through SA1, SA10 (Neath) and SA12 (Port Talbot) independents — a structurally declining pattern that requires repositioning toward the EAF transition workforce and the wider supplier base. The DVLA Morriston headquarters runs ~6,000 staff plus associated corporate and director fleet — a stable opposing trend that anchors SA6 and SA7 service flow.",
    "Swansea has no Clean Air Zone and no current Welsh Government direction to introduce one in the city centre (Cardiff has not introduced a CAZ either, despite NO2 limit exceedance in some streets — Welsh Government has favoured non-charging measures and 20mph default speed limits). However, Natural Resources Wales operates the strictest waste oil disposal and garage-effluent regime in the UK under the Environmental Permitting (England and Wales) Regulations 2016 plus Welsh-specific guidance. Swansea independents handling waste oil, antifreeze, brake fluid, batteries and waste tyres face NRW inspection at any time, with fines up to £50,000 or prosecution for non-compliance. Most SA-postcode workshop websites don't surface NRW compliance positioning despite it being a meaningful trust signal for environmentally-conscious customers and a hard barrier to entry against Bristol/Cardiff aggregators trying to operate in Swansea without local NRW knowledge.",
    "Welsh-language commercial dynamics are genuinely distinct. Roughly 11–13% of Swansea residents speak Welsh, concentrated more strongly in Gorseinon (SA4), Pontarddulais (SA4), Loughor and the rural Gower fringe than in the city centre. For some service categories — including independent mechanics, dental, family law, estate agency — Welsh-language Google Business Profile content, signage and bilingual landing pages can deliver measurable trust and ranking benefits in those specific catchments. Hourly labour rates in Swansea run £45–£70 retail, £40–£55 taxi-trade, £55–£85 fleet — slightly below Cardiff (£55–£80 retail) reflecting the lower commercial baseline. Average ticket values run full service £130–£270, brake jobs £140–£420/axle, clutch £400–£950, timing belt £350–£800. Competitive structure in Swansea rewards SA-postcode hyper-local SEO with a Welsh-language overlay where appropriate, NRW compliance positioning and Tata/DVLA fleet B2B specialism. Halfords Autocentres operates at Fforestfach and Llansamlet; Kwik Fit holds 5+ SA sites including Morriston, Gorseinon and the city centre; ATS Euromaster covers Swansea Enterprise Park; Formula One Autocentres has a Swansea site. Aggregator presence is moderate — Fixter operates limited Swansea coverage, ClickMechanic and BookMyGarage hold modest share. Google Ads CPCs run £2.50–£4.50 for 'mechanic Swansea' and £2–£3.50 for 'MOT Swansea', dropping to £1.50–£2.50 for SA-postcode searches.",
  ],
  stats: [
    { value: "~6,000", label: "DVLA Morriston Swansea staff with associated corporate and director fleet pool", source: "DVLA" },
    { value: "No CAZ", label: "Swansea CAZ status — no charging zone, but NRW waste-oil compliance regime applies", source: "Welsh Government / Natural Resources Wales" },
    { value: "£45–£70/hr", label: "Swansea independent garage retail hourly labour rate range" },
    { value: "£2.50–£4.50", label: "Google Ads CPC range for 'mechanic Swansea' 2024–2025", source: "Kerblabs client accounts" },
    { value: "11–13%", label: "Welsh speakers in Swansea (concentrated Gorseinon/Pontarddulais/Loughor) — bilingual marketing opportunity", source: "ONS Census 2021" },
    { value: "~3,000", label: "Tata Steel Port Talbot workforce post-2024 blast furnace closure with declining ICE fleet base", source: "Tata Steel UK" },
  ],
  painPoints: [
    {
      title: "Tata Steel Port Talbot ICE fleet decline misread as static market",
      body: "Tata Steel Port Talbot's September 2024 blast furnace closure (both BF4 and BF5) and transition to electric arc furnace operation by 2027–2028 has cut the workforce from ~4,000 toward ~2,500 — and the residual workforce skews younger and more EV-curious than the historic ICE-dominated base. SA10 (Neath) and SA12 (Port Talbot) independents that built capacity around Tata-staff ICE servicing face a structurally declining customer pool. We rebuild around three repositioning angles: (1) EAF transition workforce capture (younger demographic, more EV/hybrid considerations), (2) Tata supplier-base contractor fleet servicing (Class 7 LCV MOT, NRW-compliant waste handling, structured B2B outreach), and (3) Tata redundancy support service packages (pre-redundancy full-service-and-MOT bundles for staff facing role changes). Swansea independents running this routinely retain 60–80% of the historic Tata customer flow despite the workforce contraction.",
    },
    {
      title: "DVLA Morriston HQ corporate fleet flowing to dealers despite local proximity",
      body: "DVLA Morriston is Swansea's single largest employer at ~6,000 staff plus an associated corporate and director fleet pool. SA6 and SA7 independents within 10 minutes of the DVLA campus have natural geographic advantage but most under-market dedicated B2B outreach with the right credentials. Independents with IMI Master Technician credentials, named diagnostic tooling and ADAS recalibration capability can win post-warranty fleet at 25–35% below dealer rates. We build a corporate fleet landing page positioning credentials transparently, with structured LinkedIn outreach into DVLA facilities/fleet management plus the wider Morriston/Llansamlet corporate cluster (Admiral Group Swansea operations, the wider ONS data hub spillover). Swansea independents running this typically book 8–18 corporate fleet vehicles per month inside 12 months at fleet rates of £55–£85/hr.",
    },
    {
      title: "NRW waste-oil compliance positioning ignored despite genuine differentiation",
      body: "Natural Resources Wales operates the strictest waste oil disposal regime in the UK under the Environmental Permitting (England and Wales) Regulations 2016 — covering waste oil, antifreeze, brake fluid, batteries, waste tyres and garage-effluent. Non-compliance carries fines up to £50,000 or prosecution. Most SA-postcode independent websites don't surface NRW compliance — yet it's a measurable trust signal for environmentally-conscious customers and a hard barrier against Bristol/Cardiff aggregators. We build NRW compliance schema into Google Business Profile listings, surface NRW-registered waste carrier numbers prominently in landing pages, and build content authority on Welsh garage waste regulation that positions you as the obvious compliant choice. This also unlocks B2B opportunities with Welsh public-sector fleet (Swansea Council, NPT Council, Hywel Dda University Health Board, Swansea Bay UHB) where NRW compliance is a tendering prerequisite.",
    },
    {
      title: "Welsh-language Gorseinon/Pontarddulais catchment under-served by English-only marketing",
      body: "Gorseinon (SA4), Pontarddulais (SA4) and Loughor host concentrated Welsh-speaking communities where bilingual Google Business Profile content, signage and landing pages deliver measurable trust and ranking benefits — particularly for established service categories including independent mechanics, dental, family law and estate agency. Most SA4 independent websites are English-only, leaving the Welsh-language catchment open to any operator willing to invest in genuine bilingual content. We build proper bilingual landing pages (not token translation) for Gorseinon and Pontarddulais service-area pages, Welsh-language Google Business Profile descriptions, and content authority that captures Welsh-language search traffic. Critically — bilingual content only works when authentically built; token Google-Translate output is detectable and damages trust. Swansea independents with genuine Welsh-language capability who surface it consistently report 15–25% lift in SA4 conversion rates.",
    },
  ],
  faqs: [
    {
      q: "Is Welsh-language marketing actually worth investing in for a Swansea mechanic business?",
      a: "It depends entirely on which catchment you serve. In SA1 (city centre/waterfront), SA2 (Sketty/Brynmill — heavily English-first with student population), SA3 (Mumbles) and SA8 (Clydach/Pontardawe), Welsh-language marketing is a nice-to-have rather than a commercial driver — most customers are English-first and won't notice. In SA4 (Gorseinon, Pontarddulais, Loughor), SA5 (Cwmbwrla/Penlan) and parts of SA6 (Morriston), Welsh-language presence on your website, Google Business Profile and signage can deliver measurable trust and ranking benefit. We don't recommend bolting on token Welsh translation across an entire site — it's detectable and damages trust. For businesses with genuine Welsh-speaking staff capability, properly built bilingual landing pages targeted at SA4-specific catchments (Gorseinon, Pontarddulais, Loughor) plus Welsh-language Google Business Profile descriptions can be a meaningful differentiator no English-first competitor will replicate. SA4 customers researching local mechanics in Welsh return materially fewer English-only options, making the SERP genuinely winnable.",
    },
    {
      q: "How do we win DVLA Morriston and Admiral Group Swansea corporate fleet servicing work?",
      a: "Swansea corporate fleet B2B is one of the highest-margin opportunities for SA6 and SA7 independents within 10 minutes of the DVLA Morriston campus or the city-centre Admiral Group offices. DVLA Morriston runs ~6,000 staff plus corporate and director fleet pool; Admiral Group Swansea runs ~3,500 staff with associated fleet; the wider Llansamlet/Swansea Enterprise Park corporate cluster (including ONS data hub spillover) contributes additional pool. Most flows to franchised dealers in warranty period, but post-warranty fleet (4+ year-old vehicles) routinely flows to capable independents at 25–35% below dealer rates. We build a corporate fleet landing page positioning IMI Master Technician credentials, named diagnostic tooling, ADAS recalibration capability, NRW waste-oil compliance schema, and structured B2B outreach via LinkedIn into named facilities/fleet managers at DVLA, Admiral Group and the wider corporate cluster. Salesforce or HubSpot CRM tracks every vehicle's MOT and service interval. Swansea independents running this typically book 8–18 corporate fleet vehicles per month inside 12 months at fleet rates of £55–£85/hr.",
    },
    {
      q: "Does Swansea have a Clean Air Zone or environmental compliance we need to handle in customer marketing?",
      a: "Swansea has no live Clean Air Zone and no current Welsh Government direction to introduce one in the city centre. Welsh Government has historically favoured non-charging measures (improved traffic flow, 20mph default speed limits introduced September 2023, taxi-trade EV uplift incentives) over CAZ schemes — Cardiff has not introduced a CAZ either despite NO2 exceedance in some streets. However, Natural Resources Wales (NRW) operates the strictest waste oil disposal and garage-effluent regime in the UK under the Environmental Permitting (England and Wales) Regulations 2016 and Welsh-specific guidance. Swansea independents handling waste oil, antifreeze, brake fluid, batteries and waste tyres face NRW inspection at any time with fines up to £50,000 or prosecution for non-compliance. We surface NRW-registered waste carrier numbers and compliance positioning prominently in customer-facing copy — it's a measurable trust signal for environmentally-conscious customers and a hard barrier against Bristol/Cardiff operators trying to operate in Swansea without local NRW knowledge. The marketing focus is therefore NRW compliance authority, Welsh-language SA4 catchment, DVLA/Tata fleet B2B and SA-postcode local SEO rather than emissions-driven repair funnels.",
    },
    {
      q: "Can the AI receptionist handle Welsh-language enquiries for Gorseinon and Pontarddulais customers?",
      a: "Yes — Welsh-language qualifying flow is a configurable option for Swansea independents serving SA4 and SA5 catchments. The AI receptionist can be configured to detect Welsh-language input (cymraeg) and route into a bilingual handling flow, capturing vehicle registration, running DVLA Euro-class lookup and surfacing booking confirmation in Welsh or English per customer preference. For genuine Welsh-language depth (rather than token translation), we recommend pairing the AI with at least one Welsh-speaking team member during business hours for complex diagnostic or quotation conversations — the AI handles initial booking, simple FAQs and confirmation in Welsh, while complex technical conversation routes to a Welsh-speaking technician. Swansea independents running this in SA4 catchments report measurable conversion lift versus English-only competitors. The flow also routes Tata Steel Port Talbot enquiries (registration plate matched against Tata staff list where supplied) into a Tata-specific calendar, and DVLA Morriston enquiries into the corporate fleet calendar — keeping the high-value B2B work separated from routine SA-postcode bookings.",
    },
  ],
  approach:
    "For Swansea mobile mechanics and MOT garages, our 90-day playbook is: (1) deploy AI 24/7 receptionist with optional Welsh-language qualifying flow for SA4/SA5 catchments, NRW-compliance positioning surfaced in booking confirmation, multi-class MOT booking and Garage Hive or Garage Express integration; (2) build SA-postcode-stratified Google Business Profile coverage across SA1–SA8 with named-area landing pages distinguishing city/waterfront, Sketty/Mumbles, Morriston/Llansamlet (DVLA-adjacent), Gorseinon/Pontarddulais (Welsh-language overlay) and Neath/Port Talbot (Tata supplier base); (3) launch dedicated DVLA/Admiral corporate fleet, Tata Steel transition workforce, NRW compliance authority and ADAS recalibration landing pages; (4) build a corporate fleet B2B programme targeting DVLA Morriston, Admiral Group Swansea, ONS Newport spillover and Welsh public-sector fleet (Swansea Council, Hywel Dda UHB, Swansea Bay UHB) via Salesforce/HubSpot CRM where NRW compliance unlocks tendering eligibility; and (5) drive Google review velocity to 8–14 new reviews per month for SA-postcode local-pack dominance over Halfords Autocentres, Kwik Fit and Formula One Autocentres.",
};
