import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "med spa marketing Miami",
    "Miami medical spa SEO",
    "Botox marketing Miami",
    "lip filler marketing Brickell",
    "med spa Google Maps Miami",
  ],
  secondaryKeywords: [
    "Brickell med spa marketing",
    "Wynwood Botox clinic SEO",
    "Coral Gables medical aesthetics",
    "Coconut Grove filler clinic",
    "South Beach med spa Instagram",
    "Spanish-language med spa Miami",
    "FL medical director rule med spa",
    "Estetica Med Spa competitor",
    "SoBe Med Spa competition",
    "Riverchase Dermatology MedSpa Miami",
  ],
  heroSubhead:
    "Miami is the most aesthetics-saturated US metro per capita, with Brickell financial professionals, Wynwood creatives, Coral Gables old-money households, Coconut Grove waterfront residents and South Beach hospitality workers all driving year-round Botox, filler, laser and body-contouring demand. Bilingual English/Spanish search dominates — 'medspa cerca de mí' and 'bótox Miami' carry conversion intent equal to English-only queries. Beverly Hills MedSpa Miami, SoBe Med Spa, Estetica Med Spa and Riverchase Dermatology MedSpa anchor named local competition; Ideal Image and LaserAway press from the national-chain tier. Florida's medical-director rule (cosmetic medical procedures require licensed-MD ownership or direct supervision under FL Board of Medicine rules) is rigorously enforced after the 2024-2025 enforcement wave on non-compliant Miami spas. Kerblabs builds Miami med-spa funnels around bilingual Google Maps dominance in Brickell / Coral Gables / Wynwood / South Beach, FL-compliant ad creative, and after-hours Instagram DM capture — $0 upfront, $99 refundable hold, $1,200 only if we hit 2 of 3 KPIs over 60 days.",
  marketContext: [
    "Miami's med-spa market is shaped by an unusual mix of Latin-American capital, year-round beach-and-event culture, and Florida's specific regulatory framework. Miami-Dade County hosts approximately 2.7M residents, the densest concentration of Spanish-language consumers in the US (around 68% Hispanic/Latino), and a tourism economy that pulls 27M+ visitors annually — many of whom book aesthetics treatments during multi-day stays. The Brickell financial corridor (international banking, Latin American wealth-management) drives lunchtime Botox and filler from a high-disposable-income professional cohort. Wynwood and the broader Design District attract a creative under-40 demographic spending heavily on injectables, laser hair removal, body sculpting (CoolSculpting, Emsculpt) and the lip-filler / 'baby Botox' tier. Coral Gables old-money households drive premium MD-led aesthetics at fees clearing $1,200-$3,000 per syringe-cluster session. Coconut Grove waterfront residents and South Beach hospitality workers add a third tier of consistent volume. The bilingual dimension is decisive: Spanish-language search ('bótox Miami', 'medspa cerca de mí', 'rellenos labiales Coral Gables', 'depilación láser Brickell') carries equivalent intent to English search and is materially under-served by national-chain GBP listings that publish English-only profiles.",
    "Florida's medical-director rule is the regulatory backbone shaping who can operate. Under Florida Board of Medicine guidance, any office where cosmetic medical procedures (Botox, dermal fillers, laser hair removal classified as a medical procedure, IPL, microneedling with PRP, thread lifts) are performed must be owned by or under direct medical-director supervision of a Florida-licensed MD or DO — and the medical director carries personal responsibility for protocols, delegation and adverse-event response. The Florida Department of Health ran a multi-year enforcement push through 2023-2025 against med spas where the medical director was a paper signatory rather than an actively supervising physician, and Miami-Dade was a major focus given the volume of spas. Marketing that names the medical director, surfaces their FL medical license number, and clearly delineates which staff (MD, DO, ARNP, PA, RN) perform which procedures is now table-stakes for credibility and patient trust. Practices that hide or obscure their medical director risk patient drop-off as Miami consumers grow savvier — and risk Google Ads policy enforcement under healthcare advertising rules.",
    "Competitor density and ad-cost dynamics: Miami carries some of the highest US med-spa Google Ads CPCs — 'botox near me' Miami runs $18-$38 CPC, 'lip filler near me Brickell' $22-$45, 'CoolSculpting Coral Gables' $25-$55, 'medspa near me' generic $15-$32. Beverly Hills MedSpa Miami (no relation to the LA brand) operates from Coral Gables with strong long-established reviews, SoBe Med Spa anchors the South Beach catchment, Estetica Med Spa runs multi-location across Doral and Kendall, Riverchase Dermatology's MedSpa division operates dermatology-anchored aesthetics through several Miami-Dade offices, and Ideal Image / LaserAway / Skin Spa NY all run national-budget paid acquisition. The win for independent Miami med spas is bilingual hyperlocal GBP (separate GBP optimization for English and Spanish search), Instagram-first creative in Wynwood / South Beach / Coral Gables visual aesthetics, after-hours DM-to-deposit conversion (the highest US metro for evening Instagram aesthetic shopping), and FL medical-director transparency that the national chains and the lower-tier non-compliant spas can't credibly match.",
  ],
  stats: [
    { value: "2.7M", label: "Miami-Dade County population", source: "US Census 2023" },
    { value: "~68%", label: "Hispanic/Latino population — bilingual search dominant", source: "US Census ACS 2023" },
    { value: "$18-$45", label: "Google Ads CPC range for Miami Botox / filler queries", source: "Kerblabs client accounts" },
    { value: "27M+", label: "annual Miami-Dade visitors driving tourism-aesthetics demand", source: "Greater Miami CVB" },
    { value: "FL Board of Medicine", label: "medical-director rule enforced for cosmetic procedures", source: "FL DOH 2024" },
    { value: "$650-$1,400", label: "typical Miami Botox + filler session ticket" },
  ],
  painPoints: [
    {
      title: "English-only GBP missing 60%+ of Brickell / Coral Gables / Doral Spanish-language search",
      body: "Most Miami med spas publish a single English-only Google Business Profile and write English-only website copy. Roughly two-thirds of Miami-Dade households speak Spanish at home, and a meaningful share of 'bótox', 'rellenos labiales' and 'medspa cerca de mí' search volume flows to whichever competitor surfaces Spanish-language profile content first. We build dual-language GBP optimization, Spanish-language posts, and Spanish review-response templates so your spa captures the half of the market the national chains structurally ignore.",
    },
    {
      title: "FL medical-director rule trust gap — patients now check before booking",
      body: "After the FL DOH 2023-2025 enforcement wave and Miami Herald coverage of non-compliant spas, Miami aesthetics consumers increasingly check 'who is the medical director' before booking Botox or filler. Spas without a named, license-numbered MD/DO on their About page leak high-intent traffic to compliant competitors. We surface your medical director (FL ME-number visible, headshot, credentials, supervision protocol summary) on every landing page and GBP description.",
    },
    {
      title: "Ideal Image, LaserAway and Skin Spa NY outbidding on every map-pack and PPC term",
      body: "National chains run unlimited paid budgets on 'CoolSculpting Miami', 'laser hair removal Brickell' and 'Botox near me'. Independent spas can't compete on raw spend. The structural win is hyperlocal map-pack dominance for named-neighborhood queries (Brickell, Wynwood, Coral Gables, Coconut Grove, South Beach) with neighborhood-named GBP posts, named-clinician photos, and 8-15 fresh monthly reviews mentioning the specific neighborhood and procedure.",
    },
    {
      title: "After-hours Instagram DMs going cold — Miami's highest-converting channel left on read",
      body: "Miami consumers shop aesthetics on Instagram between 8pm and 2am — South Beach hospitality workers, Wynwood creatives and Brickell professionals all swipe at night. Independent Miami spas using front-desk-only response lose 50%+ of evening DMs to faster competitors. AI receptionist with English/Spanish auto-response, deposit-link booking inside the DM, and missed-call text-back closes the gap inside week one.",
    },
  ],
  faqs: [
    {
      q: "How do you handle Florida's medical-director rule in marketing copy?",
      a: "We don't give legal advice, but we structure every Miami med-spa landing page, ad and GBP description around FL Board of Medicine expectations. That means: (1) the medical director's full name and FL ME-license number visible on the About page and ideally the GBP profile; (2) clear delineation of which procedures are MD-performed, which are ARNP/PA-performed under supervision, and which RN/aesthetician work falls outside the medical-procedure definition; (3) honest scope language — no 'minimally invasive surgery' claims for procedures that aren't, no 'FDA-approved Botox alternative' claims for unapproved products; (4) honest before/after photo handling with patient written consent (HIPAA-compliant) and no representation of typical results without disclaimer. We also avoid naming POM (prescription-only medication) brand names like Botox, Dysport, Juvederm or Restylane in paid ad creative where Google Ads healthcare policy flags them, instead using compliant generic descriptors ('wrinkle relaxer', 'hyaluronic acid filler') with brand specificity reserved for the landing-page interior.",
    },
    {
      q: "Is bilingual Google Business Profile and ad strategy really worth the extra work in Miami?",
      a: "Yes, decisively. Miami-Dade is roughly 68% Hispanic/Latino with the densest concentration of native-Spanish-speaking consumers of any major US metro. Spanish-language aesthetics search ('bótox Miami', 'medspa cerca de mí Brickell', 'rellenos labiales Coral Gables', 'depilación láser Doral', 'tratamiento facial Wynwood') has search volume comparable to English-language equivalents across the Brickell / Doral / Hialeah / Kendall / Coral Gables footprint. Most national chains and a meaningful share of independents publish English-only GBPs, English-only websites and English-only Instagram captions — leaving Spanish-language map-pack and organic traffic structurally under-competed. We build dual-language GBP posts (separate post calendars in EN and ES), Spanish-language landing-page variants for your top procedures, Spanish review-response templates, and Spanish Instagram content covering at minimum 40% of your posting calendar. Miami spas running this typically see 30-60% lift in total enquiry volume inside 90 days, almost all of it net-new from previously uncaptured Spanish-language demand.",
    },
    {
      q: "Which Miami neighborhoods generate the highest-ticket med-spa demand?",
      a: "Coral Gables generates the highest average ticket — old-money households, established MD-led aesthetics tradition, and an aesthetic that rewards understated 'no-look' Botox and natural-filler work at $1,200-$3,000+ per session-cluster. Brickell drives the highest volume of mid-to-premium professional lunchtime injectables at $500-$1,100 per session — short windows, deposit-paid bookings, and high lifetime-value because the cohort returns every 3-4 months. South Beach generates the highest pre-event demand spike (Art Basel, F1, Miami Music Week, NYE) with hospitality and event-industry workers booking deep-discount packages in the weeks before each event. Wynwood and Edgewater drive the youngest cohort (under-30 creatives, lip filler and 'baby Botox' entry-level treatments). Coconut Grove blends waterfront-resident wellness spend with a meaningful body-sculpting (CoolSculpting, Emsculpt) book. We build separately-tagged GBP posts and landing-page variants for each neighborhood so your map-pack position holds across all five rather than spreading thin.",
    },
    {
      q: "How do you compete with Beverly Hills MedSpa Miami, SoBe Med Spa, Estetica Med Spa and Riverchase Dermatology's MedSpa?",
      a: "Not by trying to match their established review counts head-on. Beverly Hills MedSpa Miami (Coral Gables-based, unrelated to the LA brand) has years of GBP review velocity; SoBe Med Spa anchors South Beach; Estetica runs multi-location reach across Doral and Kendall; Riverchase carries dermatology-anchored authority across multiple Miami-Dade offices. Independent spas win on three structural advantages: (1) named-clinician E-E-A-T — your MD or ARNP with credentials, board memberships, supervised-procedure scope visible on landing pages and profile photos, which the multi-location and national-chain models structurally dilute; (2) Spanish-language depth — Beverly Hills MedSpa Miami and SoBe Med Spa publish primarily in English while serving a market where bilingual surface is decisive; (3) bookable-from-Instagram DM response within minutes during 8pm-2am evening shopping hours, where front-desk-only competitors lose 50%+ of leads overnight. We layer in hyperlocal GBP posts naming Brickell / Wynwood / Coral Gables / Coconut Grove / South Beach by week, 8-15 fresh monthly reviews referencing the specific neighborhood and procedure, and Instagram Reels content optimized for the South Florida aesthetic. Miami spas running this typically hit map-pack top 3 on at least one major procedure-and-neighborhood query inside 60 days.",
    },
    {
      q: "What does the $0 upfront, $99 hold, $1,200 success-fee pricing actually mean for a Miami med spa?",
      a: "It means we carry the performance risk, not you. You pay a $99 refundable hold to lock the engagement and signal commitment — that's the only money that leaves your account up front. We then spend 60 days running GBP optimization, review-velocity build, Instagram and after-hours DM response setup, FL-compliance audit of your existing creative, and bilingual landing-page production. At the end of 60 days we measure against three KPIs: (1) Google Business Profile views up 40% versus your trailing 60-day baseline; (2) calls or driving-direction taps from GBP up 30%; (3) map-pack top-3 ranking on at least one of your target 'Botox near me [neighborhood]' or 'medspa near me [neighborhood]' queries. If we hit at least 2 of 3, you pay the $1,200 performance fee. If we miss, your $99 is refunded and you owe nothing. For context: a single recovered Botox-and-filler patient at the typical Miami session ticket of $650-$1,400 covers the fee on the first visit, and recurring 3-4 month return cadence means even one new long-term patient is worth multiples of the fee in year-one revenue.",
    },
  ],
  approach:
    "For Miami independent med spas our 60-day playbook is: (1) audit and rebuild your GBP for bilingual surface — English and Spanish post calendars, neighborhood-tagged posts for Brickell / Wynwood / Coral Gables / Coconut Grove / South Beach, named-clinician photos with FL medical-director surfaced; (2) deploy AI receptionist with English/Spanish auto-response, Instagram DM capture, deposit-link booking inside DM, and missed-call text-back for the 8pm-2am evening shopping window; (3) run an FL-compliance audit of existing ad creative and rewrite to honor FL Board of Medicine medical-director rule and Google Ads healthcare policy on POM brand names; (4) launch review-velocity engine targeting 8-15 fresh 5-star reviews per month with named-neighborhood and named-procedure prompts; (5) build separately-tagged landing-page variants per neighborhood with bilingual versions for top procedures (Botox, lip filler, laser hair removal, CoolSculpting); (6) measure against the three KPIs (GBP views +40%, calls/directions +30%, map-pack top-3) at day 60. Pricing: $0 upfront, $99 refundable hold, $1,200 only if we hit 2 of 3 KPIs.",
};
