import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "med spa marketing Los Angeles",
    "Beverly Hills medical spa SEO",
    "West Hollywood Botox marketing",
    "Santa Monica med spa Google Maps",
    "Pasadena medical aesthetics marketing",
  ],
  secondaryKeywords: [
    "Beverly Hills 90210 med spa",
    "West Hollywood injectables clinic",
    "Santa Monica filler clinic SEO",
    "Brentwood medical spa marketing",
    "Pasadena Botox clinic",
    "CA physician supervision med spa rule",
    "Epione Beverly Hills competitor",
    "Skin Pharmacy LA",
    "About Face West Hollywood",
    "Lasky Aesthetics Beverly Hills",
  ],
  heroSubhead:
    "Los Angeles is the global capital of aesthetic medicine — Beverly Hills (90210) anchors physician-led celebrity-grade injectables and surgery-adjacent aesthetics, West Hollywood drives the highest-volume LGBTQ+ and entertainment-industry Botox-and-filler book in the country, Santa Monica blends wellness-aesthetic crossover with high-disposable-income tech and entertainment professionals, Brentwood serves an old-money family medicine-adjacent demographic, and Pasadena anchors the San Gabriel Valley premium tier. Epione Beverly Hills anchors named local competition; Skin Pharmacy (multi-location), About Face Aesthetics West Hollywood, Lasky Aesthetics (Beverly Hills, plastic-surgery-affiliated) and the Kate Somerville Skin Health Experts footprint press from the established-MD tier. The California Medical Board has been the most aggressive US regulator on med-spa physician-supervision enforcement — the 2024-2025 enforcement actions on non-compliant LA spas were widely covered. Kerblabs builds LA med-spa funnels around Beverly Hills / West Hollywood / Santa Monica hyperlocal map-pack dominance, CA-compliant physician-supervision creative, and Instagram-Reels-led discovery — $0 upfront, $99 refundable hold, $1,200 only if we hit 2 of 3 KPIs over 60 days.",
  marketContext: [
    "Los Angeles is the global benchmark for medical aesthetics — no metro generates more annual aesthetic-procedure volume, more cultural influence on what 'good Botox' looks like, or more named-celebrity-injector reputation. LA County hosts roughly 9.7M residents across a sprawling 4,000+ square-mile footprint, but the med-spa market is heavily concentrated in five corridors. Beverly Hills (ZIP 90210, 90211, 90212) is the historic anchor — Epione Beverly Hills, Lasky Aesthetics, Kate Somerville Skin Health Experts, the Beverly Hills Plastic Surgery Group's medical-spa division, and 30+ board-certified dermatologists and plastic surgeons with named celebrity clienteles drive premium $2,000-$6,000 per session-cluster spending. West Hollywood (90069, 90046) drives the highest-volume LGBTQ+ and entertainment-industry injectables market in the US — About Face Aesthetics, Lyma West Hollywood, and a dense cluster of mid-premium aesthetic medicine clinics serve a cohort that books 5-8 sessions per year. Santa Monica (90401, 90402, 90403, 90404) blends wellness-aesthetic crossover (IV therapy + Botox + skincare) with high-disposable-income tech (Silicon Beach), entertainment and media-professional residents. Brentwood (90049) drives an old-money family-medicine-adjacent demographic spending consistently across MD-led aesthetics, laser and CoolSculpting. Pasadena (91101, 91103, 91105) anchors the San Gabriel Valley premium tier with Caltech / JPL / academic-medical-center adjacency.",
    "California's regulatory framework is the most aggressive US enforcement environment for med-spa physician-supervision compliance. The California Medical Board, the California Board of Registered Nursing, and the California Department of Consumer Affairs have jointly enforced physician-supervision requirements under Business & Professions Code §2052 and §2725 — cosmetic medical procedures (Botox, dermal fillers, laser hair removal classified as medical, IPL, microneedling with PRP, thread lifts, cosmetic sclerotherapy) require either an MD/DO performing the procedure or a properly-delegated RN/NP/PA under direct physician supervision with a written delegation protocol. The Medical Board ran multiple enforcement actions through 2023-2025 against LA-area med spas where the medical director was a paper signatory rather than an actively supervising physician, and several high-profile spas faced license suspensions and consent decrees. California also enforces the corporate-practice-of-medicine doctrine — medical practices must be owned by California-licensed physicians (or specific exceptions for hospital-employed structures), and non-physician investors are restricted. For marketing, that means: surfaced medical director identification (CA medical license number, board certification, supervision protocol summary) on every landing page is now table-stakes. Spas operating through MSO/captive-PC structures must surface their physician governance transparently to maintain Google Ads healthcare-policy compliance and patient trust.",
    "Competitor density and ad-cost dynamics: LA med-spa Google Ads CPCs run $20-$45 for 'botox Beverly Hills', $25-$52 for 'lip filler West Hollywood', $28-$58 for 'CoolSculpting Beverly Hills', $18-$38 for 'medspa Santa Monica', and $15-$32 for the generic 'medspa Los Angeles'. Epione Beverly Hills has years of established GBP review velocity and named-celebrity-clientele backlinks; Lasky Aesthetics anchors plastic-surgery-adjacent aesthetics in Beverly Hills; About Face Aesthetics West Hollywood has a dominant West Hollywood book; Skin Pharmacy operates multiple LA locations with strong dermatology-anchored reviews; Kate Somerville Skin Health Experts holds Melrose Place with a celebrity-skincare brand halo; LaserAway, Ideal Image, and Skin Spa NY (West Coast expansion) all run national-budget paid acquisition. The structural win for independent LA med spas is named-physician E-E-A-T at the level of an actual board-certified dermatologist or plastic surgeon, ZIP-tagged hyperlocal GBP optimization (90210 vs 90069 vs 90404 vs 90049 vs 91101 are completely different markets), Instagram-Reels-led discovery (LA is the highest-conversion Instagram-Reels market for aesthetics in the US), and a CA-compliant physician-supervision surface that the non-compliant tier visibly lacks after the 2024-2025 enforcement wave.",
  ],
  stats: [
    { value: "9.7M", label: "LA County population — largest US metro for aesthetics volume", source: "US Census 2023" },
    { value: "$15-$58", label: "Google Ads CPC range for LA Botox / filler queries", source: "Kerblabs client accounts" },
    { value: "CA Medical Board", label: "most aggressive US regulator on med-spa physician supervision", source: "CA MBC enforcement 2024-2025" },
    { value: "$1,200-$3,200", label: "typical LA Botox + filler session ticket (premium tier $2,000-$6,000)" },
    { value: "Beverly Hills + West Hollywood + Santa Monica", label: "three ZIP clusters generating ~60% of LA aesthetics revenue" },
    { value: "Instagram Reels", label: "highest-conversion discovery channel for LA aesthetics" },
  ],
  painPoints: [
    {
      title: "California physician-supervision enforcement gap — non-compliant spas now visibly named in CA Medical Board actions",
      body: "The CA Medical Board ran high-profile enforcement actions through 2023-2025 against LA med spas with paper-only medical directors, leading to license suspensions, consent decrees and Los Angeles Times coverage. Sophisticated LA aesthetics patients now check 'who is the supervising physician' before booking, and spas without a surfaced board-certified MD/DO with CA license number on the About page leak high-intent traffic to compliant competitors. We surface your medical director transparently with CA ME-number, board certification, fellowship training and supervision protocol summary on every page.",
    },
    {
      title: "Beverly Hills 90210 saturation — Epione, Lasky, Kate Somerville and 30+ board-certified competitors in a 1-mile radius",
      body: "Beverly Hills carries the densest concentration of premium aesthetic-medicine practices in the US. Epione Beverly Hills, Lasky Aesthetics, Kate Somerville Skin Health Experts and 30+ board-certified dermatologists and plastic surgeons compete inside a 1-mile radius. Generic 'medspa Beverly Hills' is unwinnable without unlimited spend. The structural opening is named-physician-credential depth at the level your competitors can't easily replicate (specific fellowship, society membership, journal publications, named-celebrity-discreet-clientele halo) combined with named-procedure landing pages.",
    },
    {
      title: "West Hollywood high-volume cohort booking 5-8 sessions per year — but only if you respond to Instagram DMs within minutes",
      body: "West Hollywood's LGBTQ+ and entertainment-industry cohort drives the highest US per-patient annual session count for med spas (5-8 sessions versus the 2-3 national average), but the cohort is Instagram-first and impatient — slow DM response loses the deal. Front-desk-only response loses 50-70% of evening DMs. AI receptionist with Instagram DM auto-response, deposit-link booking inside the DM, and missed-call text-back covers the West Hollywood evening shopping window where the cohort decides.",
    },
    {
      title: "Instagram Reels is now the dominant LA aesthetics discovery channel — your competitor's content production is industrialized",
      body: "LA aesthetics consumers discover spas primarily through Instagram Reels in 2026 — the named-clinician-injection-process-video format owns the LA aesthetics feed. Established competitors produce 4-8 Reels per week with consistent brand identity. Single-clinician independents without a content-production system lose discovery share month over month. Kerblabs builds the Reels production system (shot list, script template, recurring filming cadence, hook library) and the paid-amplification overlay for the highest-converting organic Reels.",
    },
  ],
  faqs: [
    {
      q: "How do you handle California's physician-supervision and corporate-practice-of-medicine rules in marketing?",
      a: "We don't give legal advice, but we structure every LA med-spa landing page, ad and GBP description around CA Medical Board and CA Board of Registered Nursing expectations. CA enforces physician supervision under Business & Professions Code §2052 and §2725 — cosmetic medical procedures require either an MD/DO performing the work or a properly-delegated RN/NP/PA under direct supervision with written delegation protocols. CA also enforces CPOM — medical practices must be physician-owned with specific MSO-structure exceptions. The CA Medical Board ran aggressive enforcement through 2023-2025 with multiple LA-area license suspensions. For marketing, that means: (1) supervising physician's full name, CA medical license number, and board certification visible on the About page and ideally the GBP; (2) clear delineation of which procedures are MD/DO-performed, which are RN/NP/PA-performed under written delegation, and which esthetician work falls outside the medical-procedure definition; (3) honest scope language matching CA cosmetic-procedure consent rules; (4) compliant Google Ads creative avoiding POM brand names (Botox, Dysport, Juvederm, Restylane, Sculptra) in ad text and using generic descriptors with brand specificity reserved for landing-page interior; (5) honest before/after photo handling with patient written consent and CA-compliant disclaimers. We also avoid 'medical spa' positioning in Google Ads creative where Google's healthcare-advertising policy requires specific landing-page disclosures.",
    },
    {
      q: "What's the right GBP and landing-page strategy for the LA ZIP clusters?",
      a: "LA is five-to-seven distinct markets that look like one metro on a map. 90210/90211/90212 (Beverly Hills) requires named-physician E-E-A-T at the level of an actual board-certified dermatologist or plastic surgeon with named-celebrity-discreet-clientele halo — landing pages and GBP posts emphasize fellowship training, journal publications, society membership (ASDS, ASAPS, AAD) and the specific scope of MD-performed work. 90069/90046 (West Hollywood) requires LGBTQ+-friendly visible positioning, Instagram-Reels-led visual identity, after-hours DM response, and the highest-velocity review engine. 90401/90402/90403/90404 (Santa Monica) blends wellness-aesthetic crossover — landing pages emphasize IV therapy + Botox stacking, wellness-package pricing, and Silicon Beach-friendly online-booking flow. 90049 (Brentwood) requires old-money family-medicine-adjacent positioning — long-form landing pages emphasizing 'natural results', established-MD continuity and discretion. 91101/91103/91105 (Pasadena) requires San Gabriel Valley positioning, Caltech/JPL/academic-medicine adjacency credentials, and conservative-positioning Reels content. Each cluster gets its own weekly GBP post calendar, separate review-velocity prompts, and dedicated landing-page variants.",
    },
    {
      q: "How do you compete with Epione Beverly Hills, Lasky Aesthetics, About Face West Hollywood and the established LA names?",
      a: "Not on raw GBP review count — Epione has years of accumulated velocity, Lasky has plastic-surgery-adjacent authority, About Face has the West Hollywood book locked. The structural advantages independents have: (1) named-physician E-E-A-T at depth — your actual board-certified dermatologist or plastic surgeon's specific fellowship training (e.g. ASDS-Mohs fellowship, ASAPS-credentialed cosmetic plastic surgery fellowship), specific journal publications, specific society leadership roles, surfaced on every landing page; (2) single-clinician-relationship continuity — LA aesthetics patients in particular value continuity with the same MD/DO injector across years, and chain/multi-location footprints structurally dilute this; (3) Instagram-Reels content depth — independent practices producing 4-8 high-quality named-clinician Reels per week with consistent brand identity can match or exceed chain content output because they have a single clinician brand to build around; (4) ZIP-tagged review velocity — 8-15 fresh monthly reviews mentioning the specific Beverly Hills / West Hollywood / Santa Monica / Brentwood / Pasadena neighborhood beats a chain's centralized accumulation; (5) after-hours DM response within minutes during 8pm-12am evening shopping where front-desk competitors close. Kerblabs builds the named-physician landing pages, the Reels production system, the ZIP-tagged GBP and review engine, and the AI receptionist for after-hours capture. LA spas running this typically grow monthly enquiry volume 50-100% inside 90 days against established competition.",
    },
    {
      q: "Why is Instagram Reels specifically so dominant for LA aesthetics discovery?",
      a: "LA aesthetics consumers in 2026 discover, evaluate and decide on med spas primarily through Instagram Reels — more than through Google search for the under-40 cohort, and meaningfully through Reels even for the over-40 cohort. The format that converts is named-clinician-led process video (the actual injector on camera explaining the procedure, showing pre-treatment marking, demonstrating injection technique, walking through after-care), branded with consistent visual identity and posted 4-8 times per week. The reasons LA over-indexes on this format: (1) the cohort is unusually saturated by Instagram (LA is the most Instagram-active US metro per capita), (2) LA aesthetics has a celebrity-named-injector culture going back to the 2010s that pre-dates Reels and primed the audience to know specific clinicians by name, (3) the Reels algorithm rewards LA aesthetics content highly because engagement and watch-completion are above-platform-average. We build the Reels production system: shot list templates, hook library (the first 1.5 seconds), script structures matched to procedure type, recurring filming cadence (one filming day per week producing 4-6 Reels), branded text-overlay templates, and the paid-amplification overlay where organic-winning Reels get a $50-$300 paid boost. LA spas running this typically grow Instagram follower count 30-60% inside 90 days and convert 15-35% of new followers into deposit-paid bookings within 60 days of follow.",
    },
    {
      q: "What does the $0 upfront, $99 hold, $1,200 success-fee pricing actually mean for an LA med spa?",
      a: "It means we carry the performance risk in the most competitive aesthetics market in the world. You pay a $99 refundable hold to lock the engagement — that's the only money that leaves your account up front. We then spend 60 days on ZIP-tagged GBP rebuild for your core LA neighborhoods, CA Medical Board-compliance audit of your physician-supervision surfacing, review-velocity engine setup, AI receptionist deployment for Instagram DM and after-hours capture, Instagram Reels production system kickoff (shot list, first batch of 8-12 Reels filmed), and named-physician landing-page production for your top procedures. At day 60 we measure against three KPIs: (1) Google Business Profile views up 40% versus your trailing 60-day baseline; (2) calls or driving-direction taps up 30%; (3) map-pack top-3 ranking on at least one of your target ZIP-and-procedure queries (e.g. 'Botox 90210', 'lip filler West Hollywood', 'CoolSculpting Santa Monica'). If we hit at least 2 of 3, you pay the $1,200 performance fee. If we miss, your $99 is refunded and you owe nothing. LA context: a single recovered patient at the typical LA session ticket of $1,200-$3,200 covers the fee on the first visit, and the West Hollywood / Beverly Hills high-frequency cohort returns 5-8 times per year — one new long-term patient is worth $6,000-$25,000 in year-one revenue.",
    },
  ],
  approach:
    "For LA independent med spas our 60-day playbook is: (1) ZIP-tagged GBP rebuild for your core LA neighborhoods (90210/90069/90404/90049/91101 as relevant) with weekly post calendars per ZIP, named-physician photos, and surfaced supervising MD/DO (CA medical license number, board certification, fellowship); (2) CA Medical Board-compliance audit of your physician-supervision surfacing on every page; (3) deploy AI receptionist for after-hours Instagram DM capture, deposit-paid booking flow inside DM, and missed-call text-back covering the LA 8pm-12am evening shopping window; (4) launch Instagram Reels production system — shot list, hook library, script templates, recurring filming day, first batch of 8-12 named-clinician-led Reels; (5) ZIP-tagged review-velocity engine targeting 8-15 fresh monthly 5-star reviews per ZIP cluster with named-clinician and named-neighborhood prompts; (6) named-physician landing-page variants per neighborhood and per top procedure (Botox, lip filler, CoolSculpting, laser hair removal, Sculptra); (7) measure against three KPIs (GBP views +40%, calls/directions +30%, ZIP-tagged map-pack top-3) at day 60. Pricing: $0 upfront, $99 refundable hold, $1,200 only if we hit 2 of 3 KPIs.",
};
