import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "med spa marketing Jacksonville",
    "Jacksonville medical spa SEO",
    "Botox marketing Jacksonville",
    "Ponte Vedra Beach med spa SEO",
    "San Marco Botox marketing",
  ],
  secondaryKeywords: [
    "Ponte Vedra med spa marketing",
    "Riverside Avondale aesthetics",
    "Mandarin filler clinic",
    "Mayo Clinic Jacksonville professional aesthetics",
    "FL medical director rule Jacksonville",
    "Naval Air Station Jax military aesthetics",
    "Jacksonville Beach med spa Instagram",
    "Riverchase Dermatology MedSpa Jacksonville",
    "Body Details Jacksonville",
    "Skin Care Jacksonville SEO",
  ],
  heroSubhead:
    "Jacksonville is Florida's largest city by geography (840+ square miles) and its lowest-CPC FL med-spa market — Ponte Vedra Beach concentrates the highest-income aesthetic buyers in the metro, San Marco / Riverside / Avondale anchor the boutique urban tier, and Mayo Clinic Jacksonville plus Naval Air Station Jax employ thousands of medical-professional and military households driving stable repeat demand. Body Details (FL-grown chain), Riverchase Dermatology MedSpa Jacksonville and Ideal Image press from the chain tier; Ponte Vedra and San Marco boutiques anchor the independent end. Florida's medical-director rule (FL Board of Medicine) is enforced across Duval County the same as the rest of the state. Kerblabs builds Jacksonville med-spa funnels around hyperlocal map-pack dominance in Ponte Vedra Beach / San Marco / Riverside / Avondale / Mandarin, FL-compliant ad creative, Mayo Clinic professional-referral channel, and after-hours Instagram DM capture — $0 upfront, $99 refundable hold, $1,200 only if we hit 2 of 3 KPIs over 60 days.",
  marketContext: [
    "Jacksonville-St. Augustine-Palatka is the 36th-largest US metro with roughly 1.6M residents across the footprint, and Duval County alone hosts ~1M. Geographically Jacksonville is the largest city in the contiguous US (840+ square miles) — which creates a structurally different map-pack dynamic than denser metros. Buyer concentration tracks four corridors: Ponte Vedra Beach / Jacksonville Beach / Atlantic Beach (the highest-income coastal corridor, PGA Tour headquarters, average session-cluster spend $900-$2,000); San Marco / Riverside / Avondale (the historic-urban boutique corridor, mixed creative-and-finance professional cohort, $600-$1,200 per session); Mandarin / Julington Creek (suburban-family aesthetics demand, $400-$800 per session); and the Northbank / Southbank financial-district corridor (downtown professional lunchtime injectables). Mayo Clinic Jacksonville (one of the three Mayo flagship campuses) employs ~7,500 staff and drives a credentialed-reviewer cohort comparable to Tampa General. NAS Jacksonville and NAS Mayport add a stable military-spouse aesthetics demographic with TRICARE-adjacent spending patterns.",
    "Florida's medical-director rule applies in Duval County identically to Miami-Dade, Hillsborough and Orange. The FL Board of Medicine requires cosmetic medical procedures to be performed by or under direct medical-director supervision of a Florida-licensed MD/DO. Mayo Clinic Jacksonville staff who book aesthetics elsewhere in town tend to verify the medical director's credentials more rigorously than the general consumer base, which both raises the bar for compliance and rewards transparent spas with disproportionate review-quality lift. Marketing copy needs to honor scope-of-practice clearly (MD-performed vs ARNP/PA-performed under supervision vs RN/aesthetician), surface FL ME-license numbers on the About page and ideally the GBP description, and avoid POM brand-name claims in paid ad creative under Google Ads healthcare policy — 'wrinkle relaxer' and 'hyaluronic acid filler' on the ad, brand specificity reserved for landing-page interior.",
    "Competitor density: Jacksonville is Florida's lowest-CPC major med-spa market — 'botox near me' Jacksonville runs $8-$18 CPC, 'lip filler near me San Marco' $10-$20, 'CoolSculpting Ponte Vedra' $15-$28. Body Details operates multiple Jacksonville-area locations with national-style paid acquisition. Riverchase Dermatology runs a MedSpa division through several Duval County offices. Ideal Image runs the standard national-budget footprint. The 840+ square-mile geography means map-pack dynamics are distinctly more 'named-neighborhood specific' than tighter metros — a spa in Mandarin will not rank in Ponte Vedra Beach search no matter how strong its profile is, and vice versa. The structural win for Jacksonville independents is hyperlocal map-pack dominance for the specific neighborhood served (rather than 'Jacksonville' as a generic), Mayo Clinic professional-referral GBP posts surfacing named-clinician credentials, NAS Jacksonville military-spouse-friendly scheduling and pricing language, and after-hours Instagram DM capture during the 8pm-1am window when Jacksonville Beach hospitality workers and Mandarin / Julington Creek parents shop aesthetics on phone.",
  ],
  stats: [
    { value: "1M+", label: "Duval County population", source: "US Census 2023" },
    { value: "840+", label: "square miles of Jacksonville (largest US city by area)", source: "US Census" },
    { value: "7,500+", label: "Mayo Clinic Jacksonville staff (credentialed-reviewer cohort)", source: "Mayo Clinic" },
    { value: "$8-$28", label: "Google Ads CPC range for Jacksonville Botox / filler / CoolSculpting (lowest in FL major metros)", source: "Kerblabs client accounts" },
    { value: "FL Board of Medicine", label: "medical-director rule enforced across Duval County", source: "FL DOH" },
    { value: "$400-$2,000", label: "typical Jacksonville Botox + filler session ticket across corridors" },
  ],
  painPoints: [
    {
      title: "Jacksonville's 840-square-mile footprint kills generic 'Jacksonville' SEO — map-pack is named-neighborhood-specific",
      body: "Most spas optimize for 'med spa Jacksonville' as a generic query and rank nowhere meaningful. Jacksonville's geography means Google effectively treats Ponte Vedra Beach, San Marco, Mandarin and Northbank as separate map-pack universes. A spa in Mandarin will not rank in Ponte Vedra Beach search and vice versa. The win is committing to one or two named-neighborhood corridors and dominating them — weekly neighborhood-tagged GBP posts, 8-15 fresh monthly reviews mentioning the specific neighborhood, named-clinician photos with FL ME-license surfaced.",
    },
    {
      title: "Mayo Clinic Jacksonville professional referral channel untapped — your highest-trust 7,500-staff cohort is invisible",
      body: "Mayo Clinic Jacksonville is one of the three Mayo flagship campuses and employs ~7,500 staff. Medical professionals book aesthetics at roughly 2-3x the rate of comparable income brackets and bring three structural advantages: credentialed reviews mentioning named clinicians, hospital-floor word-of-mouth referrals, and steady 3-4 month return cadence. Most Jacksonville med spas have no GBP post calendar or landing-page variant targeting this audience. We build it with credential-aware copy and review-prompt sequences structured for medical-professional reviewers.",
    },
    {
      title: "NAS Jacksonville military-spouse demographic structurally underserved",
      body: "Naval Air Station Jacksonville and NAS Mayport host roughly 25,000 active-duty personnel and dependents combined. Military spouses are a stable aesthetics demographic — TRICARE doesn't cover cosmetic procedures, but the deployment-cycle pattern creates a distinct buyer behavior: aesthetic spend often clusters in the 2-3 weeks before a service member returns from deployment. Most Jacksonville med spas have no scheduling, payment-plan or content addressing this audience. We build military-spouse-friendly landing-page variants with honest scope language and deployment-cycle-aware GBP post calendars.",
    },
    {
      title: "Body Details and chain operators outbidding on every Ponte Vedra / San Marco PPC term",
      body: "Body Details (Florida-grown chain), Ideal Image and the Riverchase Dermatology MedSpa office press from the multi-location tier with paid budgets independent spas can't match. The structural win is hyperlocal map-pack depth in the specific neighborhood served, named-clinician E-E-A-T on the About page and GBP, and after-hours Instagram DM capture where chain operators with front-desk-only response leak 40-60% of evening leads.",
    },
  ],
  faqs: [
    {
      q: "How does Jacksonville's 840-square-mile geography change med-spa SEO strategy?",
      a: "Decisively. Jacksonville is the largest city in the contiguous US by area, and Google's map-pack treats Ponte Vedra Beach, San Marco / Riverside / Avondale, Mandarin / Julington Creek, and the Northbank / Southbank downtown corridor as effectively separate ranking universes. A spa physically located in Mandarin will not appear in 'med spa near me' search results from Ponte Vedra Beach no matter how strong its profile is, because the geographic distance exceeds Google's local-pack proximity threshold for that query category. The strategic implication: don't optimize for 'med spa Jacksonville' as a generic query — that's a losing race against chain operators with multiple locations. Instead, commit to one or two named-neighborhood corridors served from your physical address, dominate the map-pack for those, and use the leftover content surface to target adjacent corridors only through long-form SEO (where proximity matters less) rather than map-pack (where it's decisive). Jacksonville spas running this typically hit map-pack top-3 in their primary named corridor within 60 days but accept that secondary corridors will trail by 90-180 days.",
    },
    {
      q: "How do you handle Florida's medical-director rule in Jacksonville marketing copy?",
      a: "The same FL Board of Medicine framework we apply across all Florida med-spa accounts. We don't give legal advice, but every Jacksonville landing page, GBP description and ad creative is structured around: (1) the medical director's full name and FL ME-license number visible on the About page and ideally surfaced in the GBP profile description; (2) clear delineation of which procedures are MD-performed, which are ARNP/PA-performed under direct supervision, and which RN/aesthetician work falls outside the medical-procedure definition; (3) honest scope language — no 'minimally invasive surgery' claims for procedures that aren't, no 'FDA-approved Botox alternative' claims for unapproved products; (4) HIPAA-compliant before/after photo handling. We avoid naming POM (prescription-only medication) brand names like Botox, Dysport, Juvederm or Restylane in paid ad creative where Google Ads healthcare policy flags them, using compliant generic descriptors ('wrinkle relaxer', 'hyaluronic acid filler') with brand specificity reserved for the landing-page interior. Mayo Clinic Jacksonville staff who book aesthetics elsewhere in town tend to verify the medical director's credentials more rigorously than the general consumer base, which both raises the compliance bar and rewards transparent spas with disproportionate review-quality lift.",
    },
    {
      q: "Which Jacksonville neighborhoods generate the highest-ticket med-spa demand?",
      a: "Ponte Vedra Beach / Jacksonville Beach / Atlantic Beach generates the highest average ticket — the PGA Tour headquarters corridor, established old-money households mixed with newer remote-work transplants, average session-cluster spend $900-$2,000. San Marco / Riverside / Avondale is the historic-urban boutique corridor — mixed creative-and-finance professional cohort, $600-$1,200 per session with strong repeat economics. Mandarin / Julington Creek drives suburban-family aesthetics — preventive Botox, seasonal body contouring at $400-$800 per session. The Northbank / Southbank downtown corridor is professional lunchtime injectables at $500-$900 per session. We build separately-tagged GBP posts and landing-page variants for the corridor(s) you physically serve so map-pack position holds where it matters.",
    },
    {
      q: "Is the Mayo Clinic Jacksonville professional-referral channel really worth building for?",
      a: "It's the single highest-leverage cohort in the metro. Mayo Clinic Jacksonville is one of the three Mayo flagship campuses, employs ~7,500 staff (physicians, residents, nurses, ARNPs, PAs, lab and imaging professionals), and the credentialed-reviewer halo it produces compounds disproportionately in map-pack and AI Overviews ranking signals. Medical professionals book aesthetics at roughly 2-3x the rate of comparable income brackets in non-medical roles, and they bring three structural advantages: (1) high-quality credential-aware Google reviews that mention named clinicians and specific procedures, which carry disproportionate weight in ranking signals; (2) word-of-mouth referrals inside hospital break rooms and unit Slacks that no paid acquisition channel can replicate; (3) repeat cadence — medical professionals understand the science of Botox, filler and laser treatments and tend to maintain steady 3-4 month return schedules rather than one-and-done. We build GBP post variants targeting Mayo Clinic staff specifically, surface MD/ARNP credentials clearly on the About page, and structure review-prompt sequences to capture credentialed-reviewer language.",
    },
    {
      q: "What does the $0 upfront, $99 hold, $1,200 success-fee pricing actually mean for a Jacksonville med spa?",
      a: "It means we carry the performance risk, not you — based on observed patterns from 27 FL med spa audits and the Kerblabs Spa Sprint Cohort 1 mechanic. You pay a $99 refundable hold to PayU to lock the engagement — that's the only money that leaves your account up front. We then spend 60 days running GBP optimization (neighborhood-specific given Jacksonville's geography), review-velocity build, Instagram and after-hours DM response setup, FL-compliance audit of your existing creative, Mayo Clinic professional-referral channel build, and (where relevant) NAS Jacksonville military-spouse-friendly landing-page variants. At Day 60 we measure against three KPIs: (1) GBP profile views +40% versus trailing 60-day baseline; (2) calls or directions taps from GBP +30%; (3) map-pack top-3 ranking on at least one of your target 'Botox near me [neighborhood]' or 'medspa near me [neighborhood]' queries — or a +3 position improvement if you weren't already in the top three. If we hit at least 2 of 3, you pay the $1,200 performance fee. If we miss, your $99 is refunded and you owe nothing. For context: Jacksonville's $8-$28 CPC range is the lowest in major FL metros, which structurally makes the math work in your favor — even one new long-term patient at the $400-$2,000 session-ticket range covers the fee on the first visit. $99 refundable, pay only if KPIs hit.",
    },
  ],
  approach:
    "For Jacksonville independent med spas our 60-day playbook is: (1) audit your physical location against Jacksonville's named-neighborhood map-pack geography and commit to one or two primary corridors (Ponte Vedra Beach / Jacksonville Beach, San Marco / Riverside / Avondale, Mandarin / Julington Creek, or Northbank / Southbank) — dominate the map-pack for those rather than spreading thin across the 840-square-mile footprint; (2) rebuild your GBP for hyperlocal map-pack — neighborhood-tagged post calendar, named-clinician photos with FL medical-director surfaced and ME-license number visible; (3) deploy AI receptionist with auto-response, Instagram DM capture, deposit-link booking inside DM, and missed-call text-back for the 8pm-1am evening shopping window; (4) build the Mayo Clinic Jacksonville medical-professional channel — GBP post variants, About page credential surface, review-prompt sequence structured for credentialed reviewers; (5) build the NAS Jacksonville military-spouse channel where relevant — deployment-cycle-aware landing-page variants, scheduling flexibility around return windows; (6) run an FL-compliance audit of existing ad creative and rewrite to honor FL Board of Medicine medical-director rule and Google Ads healthcare policy on POM brand names; (7) launch review-velocity engine targeting 8-15 fresh 5-star reviews per month with named-neighborhood and named-procedure prompts; (8) measure against the three KPIs (GBP views +40%, calls/directions +30%, map-pack top-3) at Day 60. Pricing: $0 upfront, $99 refundable hold, $1,200 only if we hit 2 of 3 KPIs. Patterns are observed across 27 FL med-spa audits — we do not promise specific revenue outcomes, only the KPI floor.",
};
