import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "optician marketing Glasgow",
    "Glasgow optometry SEO",
    "independent optician marketing Strathclyde",
    "free NHS sight test Glasgow marketing",
    "Glasgow myopia management SEO",
  ],
  secondaryKeywords: [
    "Black & Lizars competitor marketing Glasgow",
    "West End optometry SEO Glasgow",
    "Bearsden private optician marketing",
    "Newton Mearns paediatric myopia management",
    "Pollokshields multilingual optometry",
    "Cameron Optometry competitor marketing",
    "OCT scan Glasgow marketing",
    "Glasgow contact lens DD marketing",
  ],
  heroSubhead:
    "Glasgow's optical market is structurally different from anywhere in England — NHS Scotland's universal free sight test (no means-test, no eligibility check, free for every adult and child) means GOS-volume economics work nothing like Specsavers' English playbook. Black & Lizars dominates the Scottish independent landscape, Specsavers operates 15+ Greater Glasgow branches, Vision Express, Boots and Optical Express add 25+ more, and Glasgow's West End and Southside independents compete on clinical specialism rather than price. Pollokshields' South Asian heritage community drives meaningful paediatric myopia management demand. Kerblabs gives Greater Glasgow independents the AI receptionist, NHS-Scotland-aware funnels and OCT/myopia management positioning needed to win.",
  marketContext: [
    "Greater Glasgow's optical market runs on completely different economics from any English city, and the marketing that works in Manchester or Birmingham fails in Glasgow within the first month. NHS Scotland funds a universal free eye examination for every Scottish resident — there is no GOS means-test, no eligibility check based on age or benefits, no £22.61 cap structure. Every adult and every child in Glasgow can walk into any GOC-registered optometrist and have a complete sight test funded by NHS Scotland with no out-of-pocket fee. The clinical examination fee paid to the practice (around £37-£42 depending on the supplementary tests claimed) is materially higher than England's £22.61, and the NHS Scotland system actively funds supplementary tests (retinal photography, OCT for clinically indicated cases, repeat examinations) that England's GOS structure does not. The net result: the entire Glasgow optical market — from Specsavers' 15+ branches across the conurbation to Black & Lizars and the long tail of independents — operates predominantly on NHS-funded volume, with private sight tests representing a small premium-tier slice rather than the routine fee-paying baseline that England knows.",
    "This changes the competitive picture profoundly. Specsavers' English £25 2-for-1 frame loss-leader still operates in Scotland, but the patient acquisition economics are different — there is no fee differential to drive patients toward Specsavers' free-test offer because every Scottish optician offers a free NHS-funded test. The differentiation question moves entirely onto clinical depth, frame range, contact lens fitting capability, OCT inclusion (where clinically indicated and NHS-funded versus a private add-on), and named-clinician E-E-A-T. Black & Lizars, the Scotland-headquartered independent group with a long-established Glasgow presence, competes credibly with Specsavers on volume and operates a clear named-clinician model. Independents in the West End (around Byres Road, Hyndland, Partick), Merchant City, the Southside (Shawlands, Strathbungo, Pollokshields) and the affluent suburban belt of Bearsden, Newton Mearns and Giffnock differentiate on premium frames (designer ranges at £300-£700), specialist clinical scope (IP-prescribing, paediatric myopia management, dry eye / IPL clinic, complex CL fitting), and concierge booking experience. Hakim Group's acquisition pace is now visible in Scotland and increasing through 2024-2025.",
    "The non-obvious Glasgow lever is the Pollokshields and Govanhill paediatric myopia management opportunity. Pollokshields and parts of Govanhill host a significant South Asian heritage community with bridal-cycle and family-led demand patterns similar to Birmingham's, plus the well-documented genetic and lifestyle predisposition to childhood myopia. The combination of universal free NHS sight tests (so every child gets examined regularly without parental cost barriers) plus growing community awareness of myopia management as a clinical option creates a paediatric myopia management opportunity at a density second only to Birmingham and West London in the UK. Most Greater Glasgow independents have not built dedicated MiSight, Stellest and atropine landing pages, have not captured Urdu/Punjabi/Gujarati-friendly review profiles, and have not run paid campaigns at the £2-£4 CPC these terms support. Independents that build this segment — combined with the favourable NHS-Scotland-funded examination economics — typically grow paediatric myopia revenue from a handful of children to 80-200 active patients within 18 months while maintaining strong NHS Scotland sight test volume across the broader catchment.",
  ],
  stats: [
    { value: "Universal free", label: "NHS Scotland sight test for all adults and children — no means-test", source: "NHS Inform / NHS Scotland" },
    { value: "£37-£42", label: "NHS Scotland eye examination fee paid to optometrist (vs £22.61 GOS England)" },
    { value: "15+", label: "Specsavers Greater Glasgow branches plus 25+ Boots, Vision Express and Optical Express" },
    { value: "£2-£4", label: "Google Ads CPC for 'myopia management Pollokshields / Govanhill / Newton Mearns'", source: "Kerblabs client accounts 2024-25" },
    { value: "£300-£700", label: "designer frame retail price band in Glasgow West End / Bearsden independents" },
    { value: "55%+", label: "of Greater Glasgow optical enquiries arrive outside 9-5", source: "Kerblabs aggregated client data" },
  ],
  painPoints: [
    {
      title: "NHS Scotland's universal free sight test eliminates the price-anchor differentiation Specsavers uses in England",
      body: "Specsavers' English £25 2-for-1 frame loss-leader and 'free NHS-funded sight test' positioning don't translate cleanly to Scotland because every Scottish optician already offers a free NHS-funded test. The competitive battleground moves entirely to clinical depth (OCT, IP-prescribing, paediatric myopia management, dry eye / IPL, complex CL fitting), frame range and named-clinician E-E-A-T. Independents that haven't built that differentiation lose share to Black & Lizars and Specsavers branches that have invested in premium positioning at scale.",
    },
    {
      title: "Black & Lizars' established Glasgow presence creates a competitive Scottish independent that Specsavers can't fully displace",
      body: "Black & Lizars operates a credible Scotland-wide independent model with named-clinician marketing, OCT inclusion as standard and strong contact lens DD retention. Independents that haven't built equivalent E-E-A-T at the local-practice level lose patients to Black & Lizars on the same NHS-funded test economics. The defence is hyperlocal review velocity, named-individual-optometrist landing pages, and specialist clinical scope marketed as separately bookable services.",
    },
    {
      title: "Pollokshields and Govanhill paediatric myopia segment under-marketed despite favourable NHS Scotland economics",
      body: "Glasgow's South Asian heritage paediatric myopia opportunity in Pollokshields, Govanhill and parts of the Southside is structurally larger than Edinburgh or Aberdeen and second only to Birmingham and West London nationally. Combined with universal free NHS sight tests removing the parental cost barrier on initial assessment, the conversion path to a £60-£90/month MiSight, Stellest or atropine programme is faster than in England. Almost no Greater Glasgow independent is marketing this segment credibly.",
    },
    {
      title: "Hakim Group acquisition pace now visibly active in Scotland",
      body: "Hakim Group's 200+ acquisition portfolio has historically been concentrated in the North West but is now visibly expanding into Scotland through 2024-2025. Independents that haven't built named-clinician GOC E-E-A-T, specialist clinical scope and contact lens DD retention are inside a clear three-to-five-year acquisition window — and the Scottish-specific NHS Scotland funding stability that made these practices historically attractive acquisition targets is precisely what makes them attractive now.",
    },
  ],
  faqs: [
    {
      q: "How does NHS Scotland's universal free sight test change marketing strategy versus an English campaign?",
      a: "Profoundly, and this is the single biggest mistake we see Glasgow practices make when they hire English-headquartered marketing agencies. NHS Scotland funds a universal free eye examination for every adult and child in Scotland — there is no means-test, no eligibility check, no GOS England-style £22.61 cap structure. Every Scottish optician offers a free NHS-funded test, so Specsavers' English 'free NHS-funded sight test' positioning has no differentiation power in Scotland. The marketing battleground moves entirely to: (1) clinical depth (OCT inclusion, IP-prescribing, paediatric myopia management, dry eye / IPL, complex contact lens fitting); (2) frame range and quality (designer frames at £300-£700 in West End and Bearsden independents); (3) named-clinician E-E-A-T (GOC number, College of Optometrists higher qualifications, IP entitlement); and (4) hyperlocal review velocity in a single postcode. We never run English-template 'free eye test' creative in Glasgow — every Scottish patient already knows the test is free. We market on what makes your practice clinically different from the Specsavers branch on the next street.",
    },
    {
      q: "How do we compete with Black & Lizars across Glasgow's West End, Southside and suburban belt?",
      a: "Black & Lizars is the most credible Scottish independent competitor in Greater Glasgow and operates a well-tuned named-clinician model with OCT inclusion as standard and strong contact lens DD retention. The play for any Glasgow independent that isn't Black & Lizars is the same as competing with Hakim Group elsewhere — build named-individual-clinician GOC E-E-A-T at the local-practice level, build out specialist clinical scope (IP-prescribing, paediatric myopia management, dry eye / IPL clinic, complex CL fitting, low vision) as separately marketed services with their own SEO and paid campaigns, capture Google reviews from named neighbourhoods at 12-20 per month mentioning specific Glasgow areas (Hyndland, Byres Road, Partick, Shawlands, Strathbungo, Pollokshields, Bearsden, Newton Mearns, Giffnock), and run a contact lens DD growth programme that converts existing CL patients off annual cash boxes. Done well, this approach holds independent valuation against both Black & Lizars expansion and Hakim acquisition pressure, and grows the practice independently of Specsavers branch pricing.",
    },
    {
      q: "How do we grow paediatric myopia management in Pollokshields, Govanhill or Newton Mearns?",
      a: "Glasgow's paediatric myopia opportunity benefits from a structural advantage no English city has: universal free NHS Scotland sight tests remove the parental cost barrier on initial assessment, so children get examined regularly and progressing myopia is identified earlier. The conversion path from identified progression to a £60-£90/month MiSight, Stellest or low-dose atropine programme is faster than in England. We build a dedicated myopia management landing page covering MiSight 1-day, Stellest spectacle lenses and atropine where clinically appropriate, with named optometrist credentials, anonymised progression data, transparent monthly fee structure, and FAQs in plain English explaining what myopia is, why progression matters long-term (axial elongation, retinal detachment, myopic maculopathy), and what each option does. We support Urdu, Punjabi and Gujarati communication via WhatsApp Business in Pollokshields and Govanhill catchments. We capture Google reviews from named local parents (with consent). We run paid campaigns at £2-£4 CPC against 'myopia management Pollokshields / Govanhill / Newton Mearns / Bearsden / Giffnock'. Independents we work with in Glasgow typically grow paediatric myopia revenue from a handful of children to 80-200 active patients within 18 months.",
    },
    {
      q: "How does the AI receptionist handle clinical eye-symptom calls in Glasgow — particularly emergency referrals to Gartnavel General Eye Pavilion?",
      a: "The AI receptionist is explicitly designed and trained never to give clinical or triage advice — that would breach GOC supervision rules and the College of Optometrists' guidance. If a Glasgow caller describes a symptom, the AI follows pre-agreed escalation logic. Sudden vision loss, flashes/floaters with curtain or shadow, sudden onset double vision, severe red painful eye, suspected stroke or chemical splash trigger an immediate hand-off script ('this needs urgent eye assessment — please call NHS 24 on 111, attend Gartnavel General Eye Pavilion, or call your GP') and the call is flagged to the duty optom. Routine symptoms (gradual blur, mild grit, dry eye complaints, headache after screen use, presbyopia onset) are triaged into a same-day or next-day NHS-funded sight test slot. The AI never gives clinical interpretation. Every call is recorded, transcribed and dropped into Optix, Ocuco, iScan or your PMS with symptom keywords flagged. The NHS Scotland sight test funding means no booking-cost friction — patients can be booked into a same-day NHS-funded slot for clinical investigation, which is one of the genuine workflow advantages NHS Scotland gives Glasgow practices over English equivalents.",
    },
  ],
  approach:
    "For Greater Glasgow independent opticians, our 90-day playbook is: (1) reset all 'free NHS sight test' messaging — every Scottish optician offers it, so the differentiation battleground is clinical depth and named-clinician E-E-A-T; (2) build named-individual-clinician GOC landing pages with College of Optometrists higher qualifications, IP entitlement, paediatric specialism and dry eye specialism as the core Black & Lizars and Specsavers differentiation defence; (3) deploy AI receptionist plus missed-call text-back to capture the 55%+ of enquiries arriving outside 9-5; (4) launch a Pollokshields / Govanhill / Newton Mearns paediatric myopia management programme with multilingual support and £2-£4 CPC paid campaigns; and (5) drive Google review velocity to 12-20 monthly reviews mentioning named Glasgow neighbourhoods plus run a contact lens DD growth and lapsed reactivation programme targeting 30-50% CL DD growth in 12 months.",
};
