import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "oven cleaner marketing Cardiff",
    "oven cleaning lead generation Cardiff",
    "Cardiff oven cleaning SEO",
    "Caerdydd glanhau ffwrn",
    "letting agent oven cleaning panel Cardiff",
  ],
  secondaryKeywords: [
    "Ovenu Cardiff Cardiff Oven Cleaning Service competitor",
    "Whitchurch Llanishen AGA range cooker cleaning",
    "Penarth Pontcanna oven cleaning",
    "Six Nations Principality Stadium short-let oven turnover",
    "AOCP DBS oven cleaner Cardiff",
    "CF14 CF64 CF11 letting agent EoT panel",
    "Cathays student-let oven cleaning June July",
    "bilingual Welsh English oven cleaning Cardiff",
  ],
  heroSubhead:
    "Cardiff is the Welsh capital oven cleaning market with three structurally distinct demand layers and a bilingual surface that almost no national franchise touches. Whitchurch, Llanishen, Penarth and the CF14/CF64 affluent suburban belt drive the highest concentration of premium private AGA, Rayburn and range-cooker work in South Wales at £150-£250 per visit. Cathays and Roath sustain a 65,000-student dense June-July EoT turnover spike on University of Cardiff and Cardiff Met halls and HMO turnover. Six Nations, autumn internationals and Principality Stadium concerts pull 1.5m+ event-day visitors a year through CF10 and CF11 short-let stock. Ovenu Cardiff and Cardiff Oven Cleaning Service hold the dominant Local Pack. Welsh-language client comms remain limited even in Welsh-medium households. Kerblabs builds the CF-postcode-stratified, bilingual-aware oven cleaning marketing system Cardiff independents need.",
  marketContext: [
    "Cardiff oven cleaning operates across three sharply defined demand layers, and the operators who compress them into a single 'Cardiff' campaign lose money in three directions. First, the affluent suburban belt: CF14 (Whitchurch, Llanishen, Cyncoed), CF23 (Lisvane, Cyncoed), CF64 (Penarth, Dinas Powys) and CF5 (Radyr, Pentyrch) carry the highest disposable-income households in South Wales, with a long-established AGA, Rayburn and Falcon book pricing £150-£250 per visit. Single-oven retail in CF14 and CF64 prices at £65-£90 against a £55-£75 wider Cardiff norm. The catchment treats annual servicing as part of household management; rebooking rates above 70% are achievable here with disciplined 12-month re-engage automation. Second, the student-let economy: Cardiff University, Cardiff Metropolitan and the University of South Wales together host 65,000+ students, concentrated heavily through CF24 (Cathays), CF10 (city-centre apartments), parts of CF11 (Riverside) and CF14, with HMO turnover concentrated in a sharp June-July EoT spike that is the single largest annual demand event in Cardiff oven cleaning. Specialist EoT operators with a 4-hour turnaround commitment and deposit-deduction-friendly photo evidence pull thousands of jobs across this 6-week window.",
    "Third, the event-tourism layer: Cardiff hosts more major-event days per capita than almost any UK city — Six Nations rugby, autumn internationals, Wales football, Principality Stadium concerts, the Boat Show, Royal Welsh and a year-round visitor flow toward Cardiff Castle, Cardiff Bay, Wales Millennium Centre and the Doctor Who Experience legacy. Total event-day footfall exceeds 1.5m per year, with concentrated short-let turnover demand across CF10 and CF11 on rapid 4-hour changeovers at £55-£80 per oven. The CF10 Cardiff Bay redevelopment — Senedd, BBC Cymru Wales' Central Square HQ, Wales Millennium Centre, Capital Quarter — has produced thousands of apartment units running through Foxtons-tier (limited Cardiff presence), Hern & Crabtree, Peter Alan, Allen & Harris and the dozens of Cardiff independents who operate the lettings panels. The bilingual surface is a structural commercial opportunity that almost no national chain captures. 11.6% of Cardiff residents speak Welsh; Welsh-language Google Business Profile attributes, hreflang-correct landing pages and bilingual AI receptionist greetings carry useful search volume on queries like 'glanhau ffwrn Caerdydd', 'glanhwr ffwrn Pontcanna' that have almost no competition.",
    "Competitive structure: Ovenu Cardiff holds the dominant franchise position; Cardiff Oven Cleaning Service runs the most established independent local-pack profile; Ovenclean operates a smaller franchise. Google Ads CPCs run £1.80-£3.40 for 'oven cleaning Cardiff' against £0.80-£1.80 for postcode-level queries (CF14, CF64, CF11, CF24). The strategic implication is unambiguous: Cardiff-wide paid acquisition is structurally weaker than postcode-stratified Local SEO + Google LSA + bilingual Welsh/English schema + student-let EoT seasonal funnel + event-day short-let B2B. Bilingual Welsh-language signals often deliver the fastest ranking lifts because competition is so thin. Done correctly the stack reliably produces £20-£40 cost-per-acquired-job versus £40-£90 on Bark and Checkatrade.",
  ],
  stats: [
    { value: "£65-£90", label: "CF14/CF64 (Whitchurch/Llanishen/Penarth) single-oven retail price band" },
    { value: "£150-£250", label: "Whitchurch/Llanishen/Penarth AGA, Rayburn or Falcon range-cooker clean band" },
    { value: "65,000+", label: "Cardiff students driving June-July EoT oven turnover spike", source: "HESA 2023/24" },
    { value: "11.6%", label: "of Cardiff residents speak Welsh — bilingual search opportunity", source: "Census 2021 / ONS" },
    { value: "1.5m+", label: "annual event-day visitors driving Six Nations/Principality short-let turnover demand", source: "Visit Cardiff" },
    { value: "£1.80-£3.40", label: "Google Ads CPC for 'oven cleaning Cardiff' 2024-2025", source: "Kerblabs client accounts" },
  ],
  painPoints: [
    {
      title: "Ovenu Cardiff and Cardiff Oven Cleaning Service holding the CF-postcode Local Pack on brand search",
      body: "Both operators run sustained review velocity and category-stacked Google Business Profiles across CF1-CF24. Independents without GBP category stacking (Oven Cleaning Service + Cleaning Service + House Cleaning Service), 6-12 monthly reviews and explicit AOCP membership, DBS-checked status and aluminium-safe non-caustic chemistry surfaced cannot crack top three on 'oven cleaning Cardiff'. We rebuild the GBP, drive postcode-tagged review velocity (CF14, CF64, CF11, CF24, CF10) and ladder dedicated landing pages for Whitchurch, Penarth, Pontcanna, Cathays and Cardiff Bay where the franchises run thin.",
    },
    {
      title: "Bilingual Welsh-language search opportunity completely under-targeted by national chains",
      body: "Welsh-language search volume in Cardiff is real and consistently under-targeted. 'Glanhau ffwrn Caerdydd', 'glanhwr ffwrn Pontcanna' and similar queries carry useful conversion intent and almost no competition. Even for businesses serving primarily English-speaking customers, adding Welsh-language signals to schema, GBP attributes and landing-page hreflang is a low-cost authority lift. Welsh-language client comms remain limited across Cardiff oven cleaning despite 11.6% of residents speaking Welsh and significantly higher proportions in Welsh-medium school catchments — leaving a structural ranking advantage for any operator willing to build for it correctly.",
    },
    {
      title: "Cathays and Roath June-July student-let EoT spike going to whoever picks up the phone first",
      body: "65,000+ students cycling through Cardiff University, Cardiff Met and the University of South Wales drive a sharp June-July EoT turnover spike concentrated in CF24 (Cathays), CF10 (city-centre apartments), CF11 (Riverside) and CF14. HMO landlords running 6-30 properties need oven cleans booked into 4-hour changeover windows often back-to-back across two or three properties on the same morning. Most independents are elbow-deep in another job when the call comes in and lose the contract within 90 seconds. We deploy AI receptionist with student-let-aware qualifying flow and capture recurring slot patterns across the June-July window before the landlord rings the next firm.",
    },
    {
      title: "Six Nations and Principality Stadium short-let event-day turnover under-served",
      body: "Cardiff hosts 1.5m+ event-day visitors annually through Six Nations, autumn internationals, Wales football and Principality Stadium concerts, with concentrated short-let turnover across CF10 and CF11. Short-let landlords need rapid 4-hour same-day changeovers on event-cluster weekends. Without a dedicated event-aware short-let panel, Cardiff oven cleaners miss the recurring £55-£80 per-oven turnover work that compounds across a 6-8 event-week annual calendar.",
    },
  ],
  faqs: [
    {
      q: "Do you actually support bilingual English/Welsh marketing for Cardiff oven cleaning specifically?",
      a: "Yes. We build hreflang-correct bilingual landing pages, run Welsh-language Google Business Profile attributes where appropriate, and configure AI receptionist with bilingual greetings for businesses whose customers expect them. Welsh-language search volume in Cardiff is real and consistently under-targeted by national chains — 'glanhau ffwrn Caerdydd', 'glanhwr ffwrn Pontcanna', 'glanhau Aga Llanishen' and similar queries carry useful conversion intent and almost no competition. Even for businesses serving primarily English-speaking customers, adding Welsh-language signals to schema and GBP is a low-cost authority lift that materially shifts CF14, CF64 and CF24 rankings. We don't force bilingual content where it isn't natural, but for Cardiff oven cleaners targeting Welsh-medium school catchments, public-sector contractors or Senedd-area lettings it's often the deciding factor in winning the brief. Current-generation UK English voice models handle Welsh-accented English and Welsh place names — Heol y Plas, Heol Don, Cyncoed, Llanishen — better than legacy IVR systems, and we test with real Cardiff callers before going live.",
    },
    {
      q: "How does Kerblabs help us beat Ovenu Cardiff and Cardiff Oven Cleaning Service on Whitchurch, Penarth and Pontcanna Local Pack rankings?",
      a: "Postcode-stratified Local SEO is the answer because the Local Pack on 'oven cleaning Whitchurch', 'oven cleaning Penarth', 'oven cleaning Pontcanna' and 'oven cleaning Cathays' is genuinely separate from 'oven cleaning Cardiff'. We build out a Google Business Profile with category stacking (Oven Cleaning Service + Cleaning Service + House Cleaning Service), CF-postcode-tagged review collection (so a Whitchurch customer's review names Whitchurch and surfaces in CF14 Local Pack), borough-level service area definitions, AOCP membership schema, DBS-checked status surfaced and bilingual Welsh/English attributes called out. On top of that we run Google Local Service Ads with the Google Guaranteed badge — on Cardiff oven cleaning keywords this lands at £20-£40 cost-per-job versus £40-£90 on Bark and Checkatrade. Cardiff oven cleaning clients running this stack typically rank top 3 Local Pack for 6-10 named-area searches inside 6 months and reduce franchise-network and aggregator dependency from 50% to under 20%.",
    },
    {
      q: "How do we capture the June-July student-let EoT spike across Cathays, Roath and CF10 apartment stock?",
      a: "Treat the June-July window as the single largest annual demand event in Cardiff oven cleaning, and build the operation around it. Phase one: we map every student-let landlord and lettings agent across CF24 (Cathays), CF10 (Capital Quarter, Bay apartments), CF11 (Riverside) and CF14 (university-adjacent HMOs), plus the dedicated student-letting agencies (CPS Homes, North Cardiff Properties, Daniels Estates, Belvoir Cardiff, Watts Property), and rank by tenancy turnover. Phase two: we build a student-let landing page with 4-hour turnaround commitment, transparent banded pricing (£55-£75 single, £85-£110 double, hob/extractor add-ons), AOCP, DBS-checked technicians and £5m public liability surfaced. Phase three: targeted LinkedIn and direct-email outreach to property managers in March-April with a 30-second video walk-through and June-July panel-application pack. Cardiff oven cleaning clients running this typically sign 3-6 panels in the March-May window, each worth 8-25 cleans across the June-July peak alone, fundamentally shifting Q3 economics.",
    },
    {
      q: "Will the AI receptionist actually price-quote a Whitchurch AGA differently from a Cathays student-let single-oven callout?",
      a: "Yes — that's the core qualifying flow. The AI receptionist (across phone, WhatsApp Business and SMS, 24/7) qualifies every enquiry against the Cardiff-specific questions that price the job: oven type and brand, property type and CF-postcode (CF14 Whitchurch/Llanishen vs CF24 Cathays student-let vs CF10 Bay apartment carries entirely different price logic), last cleaned timeframe, language preference (English/Welsh), and any add-ons. The AI then routes to a different appointment type, urgency level, price band and follow-up sequence. Cathays student-let callouts trigger a £55-£75 quote and 4-hour same-day turnaround slot. Range-cooker CF11 jobs trigger a £100-£140 quote and 90-minute slot. Whitchurch AGA enquiries trigger a different intake entirely: confirmation of cooker model, age, last service date, paint condition (Code 6 enamel checks), an in-home survey commitment for first-time customers, a £150-£250 written quote with AOCP, DBS, £5m public liability surfaced, and a 4-5 hour booking slot. Six Nations / event-week short-let enquiries trigger event-aware scripting with road-closure context for Westgate Street and Park Street.",
    },
  ],
  approach:
    "For Cardiff independent oven cleaners, our 90-day playbook is: (1) build CF-postcode-stratified GBP and Local Service Ads coverage across 8-12 postcodes (CF14 Whitchurch/Llanishen/Cyncoed, CF64 Penarth, CF11 Pontcanna/Canton, CF24 Cathays/Roath, CF5 Radyr/Pentyrch, CF23 Lisvane, plus city-centre CF10 Bay) with bilingual English/Welsh hreflang, AOCP, DBS-checked, aluminium-safe non-caustic chemistry and £5m PLI surfaced; (2) deploy AI 24/7 receptionist with Cardiff-specific qualifying flow (oven type, CF-postcode, AGA/Rayburn brand, language preference, event-day flag) and separate funnels for single-oven retail, range-cooker, AGA/Rayburn premium, June-July student-let EoT, Six Nations event short-let and city-centre apartment turnover; (3) build a June-July student-let funnel with 4-hour turnaround commitment and panel-application packs targeting CPS Homes, Daniels, Belvoir Cardiff, Watts Property; (4) build a Whitchurch/Llanishen/Penarth AGA, Rayburn and Falcon range-cooker landing page with named case studies and 30-45% average-job-value uplift; (5) launch the 12-month re-engage SMS with bilingual options, pre-Six-Nations event-week overlay, pre-Christmas slot booking and pre-summer-let turnaround prompts to compound rebooking rate to 60-75% inside 18 months.",
};
