import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "oven cleaner marketing Swansea",
    "oven cleaning SEO Swansea",
    "Mumbles AGA cleaner marketing",
    "Welsh language oven cleaning Swansea",
    "Swansea end of tenancy oven cleaning marketing",
  ],
  secondaryKeywords: [
    "Sketty oven cleaner SEO",
    "Mumbles oven cleaning premium",
    "Uplands student let oven cleaning",
    "Swansea Oven Cleaning competitor",
    "Ovenclean Swansea franchise alternative",
    "Ovenu Swansea independent marketing",
    "Gorseinon glanhau popty bilingual",
    "SA1-SA8 oven cleaning Google Ads",
  ],
  heroSubhead:
    "Swansea is Wales's second city and one of the more under-served oven cleaning markets in the UK — a 246,000-strong coastal economy where Welsh-language presence in west-Swansea catchments is genuinely commercially significant, the Mumbles, Sketty and West Cross premium belt supports £140–£210 AGA work, and the Swansea University September peak across Uplands and Brynmill drives a compressed four-week EoT spike. Materially cheaper than Cardiff, lower CPCs at £1.50–£2.80, modest competitive density (Swansea Oven Cleaning, one Ovenclean franchise, one Ovenu territory plus a long tail of single-van independents), and a customer base that genuinely rewards local — bilingual GBP content in Gorseinon and Pontarddulais delivers measurable ranking and trust gains, Mumbles tourism overlays add summer commercial-kitchen volume, and Cardiff agencies pitching into SA postcodes routinely miscalibrate everything.",
  marketContext: [
    "Swansea's oven cleaning market is shaped by three forces no other Welsh city replicates at the same combination of intensity. First, the Welsh-language commercial dynamic. Roughly 11–13% of Swansea residents speak Welsh according to the 2021 Census, concentrated more strongly in Gorseinon, Pontarddulais, Loughor, Penclawdd and the rural Gower fringe than in the SA1 city centre, Mumbles or Sketty. For oven cleaning operators serving the SA4 and SA14 catchments specifically, Welsh-language content on the website (a properly translated 'glanhau popty' service page, not a Google-translate token effort), bilingual Google Business Profile posts, bilingual quote PDFs and Welsh-language signage on the van deliver a measurable trust and ranking benefit that no English-first competitor will replicate. We don't recommend bolting on token translation across an entire site — but for businesses with a real Welsh-speaking customer base in the western SA postcodes, properly built bilingual content can be a meaningful differentiator that converts at materially higher rates than English-only campaigns. The same dynamic does not apply meaningfully in SA1, SA2 or SA3 (Mumbles, Sketty, Uplands) — most customers there are English-first and won't notice — so the bilingual investment has to be targeted, not blanket.",
    "Second, the Mumbles, Oystermouth, Langland, Sketty, West Cross and Killay premium belt. These suburbs along the western edge of Swansea Bay support the city's highest household incomes — Mumbles in particular routinely lists detached coastal property at £500k+, with a separate boutique restaurant and independent retail scene that drives summer tourism overlay throughout the May-to-September Gower and Oxwich Bay wedding season. AGA, Rayburn, Lacanche and Falcon range cooker density in this belt is notably higher than the rest of the city, partly because of the housing stock, partly because of the consultant and University-staff household concentration around Singleton Park, Morriston Hospital and the SA2 / SA3 professional-services belt. AGA cleans here run £140–£210 per job against £55–£75 single-oven retail in Morriston, Clydach and Townhill; commercial-kitchen deep cleans for the Mumbles seafront restaurant cluster, the Gower wedding-venue circuit (Oxwich Bay Hotel, King Arthur Hotel, Fairyhill, Oldwalls Gower) and the long tail of independent eateries along Newton Road and Mumbles Road run £240–£520 per visit. Most Swansea oven cleaners undermarket all of this — generic websites with no AGA chemistry detail, no Mumbles landing page, no Gower wedding-venue commercial-kitchen schema.",
    "Third, the Swansea University September tenancy turnover. Around 20,000 students across the Singleton Park and Bay Campus drive a compressed late-August to mid-September EoT peak across Uplands, Brynmill, Mount Pleasant, St Thomas and Bonymaen — Swansea letting agents (Belvoir Swansea, Astleys, Dawsons, John Francis, Roberts & Co, Peter Alan Swansea, the Pinnacle and Rhys Davies HMO networks) and the wider EoT cleaning firms collectively push thousands of oven cleans through the four-week window. The competitive structure is moderate density. Swansea Oven Cleaning has the longest-established city-wide profile; Ovenclean operates one franchise territory covering Swansea and Llanelli; Ovenu has one franchisee active in the SA postcodes; Gower Ovens, Bay Oven Cleaning and the long tail of single-van independents fight over the rest. Google Ads CPCs on 'oven cleaning Swansea' run £1.50–£2.80, sharply lower in long-tail SA-postcode and town-level queries (£0.60–£1.20 for 'oven cleaner Mumbles', 'oven cleaning Sketty', 'oven cleaner Gorseinon'), and the Local Pack outside SA1 city centre is genuinely winnable. The Cardiff-comparison pricing pressure is the underlying reason most Swansea oven cleaners undersell their work — Cardiff CPCs and prices run 25–40% higher across the board, and Cardiff agencies pitching into Swansea routinely miscalibrate budgets, creative and positioning to SA-postcode reality.",
  ],
  stats: [
    { value: "11–13%", label: "Welsh speakers in Swansea concentrated in SA4 / Gorseinon / Pontarddulais", source: "ONS Census 2021" },
    { value: "£55–£75", label: "typical Swansea single-oven retail price (Morriston, Clydach, Townhill, Bonymaen)", source: "Kerblabs Swansea client data" },
    { value: "£140–£210", label: "typical Mumbles / Sketty / West Cross AGA, Rayburn or range cooker clean", source: "Kerblabs Swansea client data" },
    { value: "£1.50–£2.80", label: "Google Ads CPC range for 'oven cleaning Swansea' 2024–2025", source: "Kerblabs client accounts" },
    { value: "20,000", label: "Swansea University students driving September EoT peak across Uplands, Brynmill, Mount Pleasant", source: "Swansea University" },
    { value: "SA1–SA8", label: "Swansea-area postcode districts addressable per van" },
  ],
  painPoints: [
    {
      title: "Welsh-language opportunity in Gorseinon and Pontarddulais ignored by every competitor",
      body: "Around 11–13% of Swansea residents speak Welsh, concentrated heavily in Gorseinon, Pontarddulais, Loughor, Penclawdd and the rural Gower fringe. For oven cleaning operators serving these SA4 and SA14 catchments, properly built bilingual content (a real 'glanhau popty' service page, bilingual GBP posts, bilingual quote PDFs, Welsh-language van signage) delivers measurable trust and ranking gains that no English-first competitor will match. Most Swansea operators ignore this entirely. We build targeted bilingual content for the western SA catchments without diluting the SA1, SA2, SA3 English-first campaigns.",
    },
    {
      title: "Mumbles, Sketty and Gower wedding-venue AGA and commercial premium under-marketed",
      body: "Mumbles, Oystermouth, Langland, Sketty and West Cross support a real £140–£210 AGA, Rayburn, Lacanche and Falcon range cooker market driven by consultant, University-staff and professional households, and the May-to-September Gower wedding-venue circuit (Oxwich Bay Hotel, Oldwalls Gower, King Arthur Hotel, Fairyhill) drives £240–£520 commercial-kitchen deep cleans. Most Swansea operators have generic websites with no AGA chemistry detail, no Mumbles landing page, no Gower wedding commercial-kitchen schema. We rebuild around named case studies, separate landing pages and B2B outreach to Gower wedding-venue principals.",
    },
    {
      title: "Cardiff agencies pitching into Swansea miscalibrating budgets and creative",
      body: "Cardiff agencies routinely pitch into Swansea on price and bigger client lists but miss SA-postcode nuance — they don't know Mumbles and Sketty behave differently from Killay, that Morriston Hospital footfall changes drive-time patterns, that the Gower wedding economy spikes salon and beauty demand from May to September, or that Welsh language matters in SA4. They miscalibrate budgets to Cardiff CPCs (£3–£4 on 'oven cleaning Cardiff') when SA-postcode CPCs run £1.50–£2.80, and waste 30–50% of spend on misaligned creative.",
    },
    {
      title: "September Swansea University EoT peak under-captured by retail-only operators",
      body: "The four-week tenancy turnover from late August through mid-September across Uplands, Brynmill, Mount Pleasant, St Thomas and Bonymaen produces a 3–4x weekly oven-clean volume against February. Swansea letting agents (Belvoir, Astleys, Dawsons, John Francis, Roberts & Co, Peter Alan, the Pinnacle and Rhys Davies HMO networks) push thousands of oven cleans through the window — but most independent operators run the same retail funnel and miss it. We build a structured letting-agent and EoT cleaning principal acquisition motion targeting the panels three months before the peak.",
    },
  ],
  faqs: [
    {
      q: "How important is Welsh language for oven cleaning marketing in Swansea — really?",
      a: "It depends entirely on which part of the city and which catchment you're serving, and getting this calibration right matters commercially. In SA1 (city centre and waterfront), SA2 (Sketty, Uplands, Brynmill) and SA3 (Mumbles, Oystermouth, Langland, West Cross), Welsh-language content is a nice-to-have rather than a commercial driver — most customers are English-first and won't notice. In SA4 (Gorseinon, Loughor, Penclawdd, Pontarddulais), Welsh-language presence on your website, Google Business Profile, signage and quote PDFs delivers a measurable trust and ranking benefit, particularly for established services like oven cleaning where the customer base values local commitment. We don't recommend bolting on token Welsh translation across an entire site — that gets correctly identified as superficial and converts worse, not better. For businesses with a real Welsh-speaking customer base in the SA4 and SA14 catchments, properly built bilingual content (a genuinely translated 'Glanhau Popty Abertawe' service page, bilingual GBP posts, bilingual quote PDFs, Welsh-language van signage where the operator is comfortable) can be a meaningful differentiator no English-first competitor will replicate. We build it as a targeted overlay on the western SA catchments, not a blanket investment, which means the Mumbles and Sketty English-first campaigns aren't diluted while the Gorseinon catchment captures the bilingual signal. Operators running this typically see materially higher conversion rates on SA4 enquiries and rank top-three for 'glanhwr popty Gorseinon' and similar Welsh-language queries within 90 days.",
    },
    {
      q: "Mumbles and Sketty have AGA, Rayburn and Gower wedding-venue work — how do we surface it?",
      a: "Mumbles, Oystermouth, Langland, Sketty, West Cross and Killay support the densest AGA, Rayburn, Lacanche and Falcon range cooker concentration in any Welsh city we've worked, partly because of the housing stock and the household income profile, partly because of the consultant and Swansea University professor cohort. AGA cleans here run £140–£210 per job against £55–£75 single-oven retail in Morriston and Clydach; commercial-kitchen deep cleans for the Mumbles seafront restaurant cluster, the Gower wedding-venue circuit (Oxwich Bay Hotel, Oldwalls Gower, King Arthur Hotel, Fairyhill) and the long tail of independent eateries along Newton Road and Mumbles Road run £240–£520 per visit. We build the specialism into the funnel at every layer. Separate landing pages target 'AGA cleaner Mumbles', 'AGA cleaning service Sketty', 'Rayburn cleaning Langland', 'Lacanche specialist West Cross', 'commercial kitchen clean Gower wedding venue', 'TR19 deep clean Mumbles restaurant', each with named case studies, before-and-after gallery, AGA-specific aluminium-safe potassium hydroxide chemistry detail, AOCP credentials and PLI evidence. The AI receptionist asks oven type and brand as the first qualifying questions and routes AGA, Rayburn and commercial enquiries to a separate premium-priced flow. Direct B2B outreach goes to Gower wedding-venue principals, the South Wales AGA-Rayburn dealer network and the Mumbles seafront restaurant principals.",
    },
    {
      q: "How do we compete with Cardiff agencies pitching into Swansea?",
      a: "By being deeply Swansea-specific in ways Cardiff agencies cannot fake. Cardiff agencies often pitch on price and bigger client lists, but they routinely miss the SA-postcode nuance — they don't know Mumbles and Sketty behave differently from Killay, that Morriston Hospital footfall and shift patterns change drive-time at peak hours, that the May-to-September Gower and Oxwich Bay wedding economy spikes commercial-kitchen demand, or that Welsh language matters in SA4. They miscalibrate budgets to Cardiff CPCs (£3–£4 on 'oven cleaning Cardiff' against £1.50–£2.80 in Swansea), miscalibrate creative to Cardiff Bay premium positioning when most of Swansea is mid-market, and miscalibrate review-velocity targets. We sit closer to the ground: Swansea-shot creative rather than stock images or Cardiff Bay reskins, proper SA1 vs SA2 vs SA3 vs SA4 vs SA6 campaign segmentation, bilingual targeting where it actually converts, and reporting tied to booked revenue. For most local Swansea SMEs, that beats a Cardiff agency on the metrics that matter — even if the Cardiff pitch deck looks slicker. Several of our Swansea oven cleaning clients moved to us from Cardiff agencies after spending 12–18 months on campaigns that never quite fit the SA postcodes.",
    },
    {
      q: "How do we capture the September Swansea University EoT peak?",
      a: "Capacity has to be built in advance, not improvised. The four-week tenancy turnover window from late August through mid-September produces a 3–4x weekly volume against February — Swansea University's roughly 20,000 students across Singleton Park and the Bay Campus drive an EoT spike across Uplands, Brynmill, Mount Pleasant, St Thomas and Bonymaen, with Swansea letting agents (Belvoir Swansea, Astleys, Dawsons, John Francis, Roberts & Co, Peter Alan, the Pinnacle and Rhys Davies HMO networks) and the wider EoT cleaning firms pushing thousands of oven cleans through the window. We start the acquisition programme 90–120 days ahead with phase one mapping: every Swansea letting agent and EoT cleaning principal by tenancy turnover, ranked by Singleton Park and Bay Campus catchment density. Phase two builds a panel-application pack with EoT-cleaning-friendly pricing (£45–£60 per single oven at panel volume), before-and-after photo grids, same-day turnaround commitment, AOCP credentials, public liability evidence and Duty of Care wording. Phase three is targeted LinkedIn and email outreach to lettings managers and EoT cleaning principals. Phase four — and this matters — is dispatch capacity: AI receptionist with EoT-mode routing, ServiceM8 or Powered Now job dispatch, and either second-van capacity or a sub-contractor framework through the four-week peak. Swansea operators running this typically add £20,000–£40,000 of September revenue against retail-only competitors.",
    },
  ],
  approach:
    "For Swansea independent oven cleaners, our 90-day playbook is: (1) build SA-postcode-aware landing-page architecture with separate value-tier campaigns for Morriston, Clydach, Townhill and Bonymaen and premium-tier campaigns for Mumbles, Sketty, West Cross, Killay and Langland; (2) build a targeted Welsh-language content overlay for Gorseinon, Pontarddulais, Loughor and the SA4 catchment ('Glanhau Popty Abertawe' service page, bilingual GBP posts, Welsh-language van signage) without diluting the English-first SA1, SA2 and SA3 campaigns; (3) deploy AI receptionist with 24/7 capture, oven-type and brand qualifying, and postcode-aware tier routing; (4) build a dedicated AGA, Rayburn, Lacanche, Falcon and commercial-kitchen specialism architecture for Mumbles, Sketty, the Gower wedding-venue circuit (Oxwich Bay, Oldwalls, King Arthur, Fairyhill) and the Mumbles seafront restaurant cluster; and (5) build a structured letting-agent and EoT cleaning principal acquisition motion (Belvoir, Astleys, Dawsons, John Francis, Roberts & Co, Peter Alan) starting 90 days ahead of the late-August Swansea University EoT peak.",
};
