import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "oven cleaner marketing Derby",
    "oven cleaning lead generation Derby",
    "Derby oven cleaning SEO",
    "Rolls-Royce Toyota relocation EoT oven cleaning Derby",
    "letting agent oven cleaning panel Derby",
  ],
  secondaryKeywords: [
    "Derby Oven Cleaning competitor",
    "Allestree Mickleover AGA Rayburn cleaning",
    "Littleover Quarndon range cooker cleaning",
    "Sinfin Raynesway corporate-relocation oven clean",
    "AOCP DBS oven cleaner Derby",
    "DE21 DE22 DE23 letting agent EoT panel",
    "Belper Duffield premium oven cleaning",
    "Toyota Burnaston EoT relocation oven clean",
  ],
  heroSubhead:
    "Derby is the UK oven cleaning market most directly underwritten by a single corporate engine — Rolls-Royce Civil Aerospace at Sinfin and Raynesway employs 14,000+ people; Toyota's Burnaston plant has produced more than five million cars since 1992; Alstom Litchurch Lane runs the UK's only volume train-manufacturing facility; and Pattonair, JCB Power Systems and a long tail of aerospace and rail tier-one suppliers ring the city. That cycles thousands of skilled engineering professionals through DE-postcode rental stock annually, with EoT oven cleans bundled into nearly every check-out. Allestree, Mickleover, Littleover and Quarndon generate a parallel high-spec AGA and range-cooker book at £140-£230 per visit. Derby Oven Cleaning holds the dominant Local Pack. Kerblabs builds the DE-postcode-stratified oven cleaning marketing system Derby independents need.",
  marketContext: [
    "Derby oven cleaning is structurally underwritten by one of the most concentrated advanced-engineering economies in the UK, and operators who don't build for the corporate-relocation and EoT flow leave the most reliable recurring revenue in the city on the table. Rolls-Royce Civil Aerospace alone employs more than 14,000 across the Sinfin and Raynesway sites, with a continuous flow of contractors, suppliers and senior engineers cycling through Derby on 12-36 month assignments. Toyota Burnaston, eight miles south-west, has produced more than five million cars since 1992 and runs a stable but rotating workforce of approximately 3,000. Alstom's Litchurch Lane plant employs 3,000+ on UK rail manufacturing. Pattonair, JCB Power Systems and the long tail of aerospace and rail tier-one suppliers add several thousand more high-skill households. The corporate-relocation lettings flow runs through a network of Derby agencies — Hannells, Frank Innes, Ashley Adams, Belvoir Derby, Bagshaws Residential, Strutt & Parker — that bundle EoT oven cleaning into managed-property panels. This is a recurring, predictable, high-margin demand layer that templated franchise marketing barely engages.",
    "The premium suburban book runs through the northern and western belts. Allestree, Mickleover, Littleover, Quarndon and Duffield carry the highest household incomes in Derby, with detached-house range-cooker work across Stoves, Rangemaster, AGA, Rayburn and Falcon brands routinely pricing £140-£230 per visit. Single-oven retail in this corridor sits at £65-£90 against a £55-£75 wider Derby baseline. The catchment is unusually research-driven — engineering and aerospace professional households read every Google review, scrutinise GDC and trade-body credentials, and compare itemised quotes carefully. Trust signals matter more here than discounts: AOCP membership, DBS-checked status, £5m public liability and aluminium-safe non-caustic chemistry surfaced explicitly in landing pages, GBP profile and review responses move conversion materially. Annual cleans are diaried alongside the boiler service in Allestree and Mickleover specifically. The Cathedral Quarter regeneration plus the Infinity Park and Becketwell developments have lifted city-centre apartment stock and short-let turnover demand at £55-£75 per oven on rapid 4-hour changeovers.",
    "Suburban Derby has unusually active Facebook community groups across Mickleover, Allestree, Chellaston, Spondon and Oakwood — recommendation threads in those groups still drive a meaningful share of bookings. Competitive structure: Derby Oven Cleaning runs the most established independent local-pack profile across DE1-DE7 and DE21-DE24; Ovenu and Ovenclean both operate smaller franchises. Google Ads CPCs run £1.40-£2.60 for 'oven cleaning Derby' against £0.80-£1.80 for postcode-level queries (DE3, DE21, DE22, DE23, DE56). Derby CPCs run materially below Birmingham and Leeds equivalents but the gap is closing. Postcode-stratified Local SEO + LSA + Rolls-Royce/Toyota/Alstom corporate-relocation B2B + community-aware Facebook lead campaigns reliably produce £18-£40 cost-per-acquired-job versus £80-£180 on Bark and Checkatrade. The wider Derby travel-to-work area extends well beyond the council boundary into Belper (DE56), Mickleover, Etwall, Melbourne, Duffield and the Amber Valley, and tiered geo-targeting captures additional volume without diluting brand or stretching budget.",
  ],
  stats: [
    { value: "£65-£90", label: "DE22/DE3/DE23 (Allestree/Mickleover/Littleover) single-oven retail price band" },
    { value: "£140-£230", label: "Allestree/Mickleover/Quarndon AGA, Rayburn or Falcon range-cooker clean band" },
    { value: "14,000+", label: "Rolls-Royce Civil Aerospace employees driving DE-postcode corporate-relocation EoT volume", source: "Rolls-Royce" },
    { value: "3,000+", label: "Alstom Litchurch Lane rail manufacturing workforce — additional EoT corporate flow", source: "Alstom UK" },
    { value: "£1.40-£2.60", label: "Google Ads CPC for 'oven cleaning Derby' 2024-2025", source: "Kerblabs client accounts" },
    { value: "£32,500", label: "Derby median full-time gross annual earnings supporting premium AGA/Rayburn pricing", source: "ONS ASHE" },
  ],
  painPoints: [
    {
      title: "Derby Oven Cleaning and the local franchises holding the DE-postcode Local Pack on brand search",
      body: "Derby Oven Cleaning runs sustained review velocity and a category-stacked Google Business Profile across DE1-DE7 and DE21-DE24, with Ovenu and Ovenclean franchises layered on. Independents without GBP category stacking (Oven Cleaning Service + Cleaning Service + House Cleaning Service), 6-12 monthly reviews and explicit AOCP membership, DBS-checked status and aluminium-safe non-caustic chemistry surfaced cannot crack top three on 'oven cleaning Derby'. We rebuild the GBP, drive postcode-tagged review velocity (DE22 Allestree, DE3 Mickleover, DE23 Littleover, DE21 Spondon/Oakwood, DE56 Belper) and ladder dedicated landing pages for Allestree, Mickleover, Littleover, Quarndon and Belper.",
    },
    {
      title: "Rolls-Royce, Toyota and Alstom corporate-relocation EoT volume going to whichever cleaner the agent met first",
      body: "Hannells, Frank Innes, Ashley Adams, Belvoir Derby, Bagshaws Residential and the Derby corporate-relocation lettings agents push hundreds of monthly check-out oven cleans through preferred-supplier panels for Rolls-Royce, Toyota Burnaston, Alstom and Pattonair staff. Without a dedicated corporate-relocation B2B funnel — landing page with deposit-deduction-friendly photo evidence, panel-application kit, AOCP/DBS surfaced, fast-turnaround commitment for 12-36 month tenancies — independents are invisible to the people who could deliver a recurring 6-20 jobs/month book overnight.",
    },
    {
      title: "Allestree, Mickleover, Quarndon and Duffield AGA/Rayburn premium book invisible without specialism positioning",
      body: "DE22, DE3, DE23 and DE56 host one of the highest AGA, Rayburn and Falcon concentrations in the East Midlands, with annual cleans pricing £140-£230. Most Derby operators capable of this work have generic websites that say nothing about Code-6 enamel handling, AGA disassembly procedure or insurance cover for £15,000+ heritage cookers. The high-margin tail sits invisible without dedicated landing pages, named case studies, AOCP credentials surfaced and £5m public liability called out — typically 30-45% job value uplift inside six months once we build it.",
    },
    {
      title: "Local Facebook community-group recommendation engine going under-served despite outsized Derby influence",
      body: "Suburban Derby has unusually active Facebook community groups across Mickleover, Allestree, Chellaston, Spondon and Oakwood, with recommendation threads still driving a meaningful share of oven cleaning bookings. Most operators ignore this channel entirely or post inconsistently. We set up community-aware Facebook lead campaigns, schedule organic post cadence with technician-led short-form content from real DE-postcode jobs, and use AI to draft response templates for the inevitable 'who would you recommend?' threads — without taking the brand voice off-guard.",
    },
  ],
  faqs: [
    {
      q: "How does Derby's research-driven engineering-professional audience change our oven cleaning marketing approach?",
      a: "Significantly. Engineering, aerospace and R&D professionals at Rolls-Royce, Alstom, Toyota Burnaston, Pattonair and JCB Power Systems are among the most research-driven consumer audiences any UK SME will sell to — they will visit your website three or four times before booking, read every Google review, scrutinise AOCP and Companies House records, and compare line-item quotes carefully. Glossy hero shots and discount headlines under-perform here. What works is detailed service explanations (potassium hydroxide non-caustic chemistry, aluminium-safe formulation, why a bespoke quote beats a Bark £45 lowball), named technician profiles with AOCP credentials surfaced, before-and-after galleries from real DE-postcode jobs with brand context, transparent banded pricing, and continuous review velocity. Kerblabs builds the longer-form, more technical landing-page content this audience actually reads, then runs paid traffic into it. The result is materially higher conversion on the engineering-professional segment and stronger price discipline against franchise lowball quotes.",
    },
    {
      q: "How do you actually capture Rolls-Royce, Toyota and Alstom corporate-relocation EoT oven cleaning panels?",
      a: "Treat corporate-relocation panels as a B2B sales motion rather than retail marketing. Phase one: we map every corporate-relocation lettings agency operating in DE3 (Mickleover), DE22 (Allestree), DE23 (Littleover/Sinfin), DE21 (Oakwood/Spondon) and DE56 (Belper/Duffield) — the regional and national chains (Frank Innes, Hannells, Ashley Adams, Belvoir Derby, Bagshaws Residential), the Derbyshire independents and the dedicated corporate-relocation specialists who handle Rolls-Royce, Toyota and Alstom staff churn — and rank by tenancy turnover. Phase two: we build a corporate-relocation landing page with deposit-deduction-friendly pricing, structured before/after photo packs, same-day turnaround commitments for 12-36 month tenancy ends, AOCP membership, DBS-checked technicians, £5m public liability and Duty of Care wording. Phase three: targeted LinkedIn and email outreach to lettings managers and corporate-relocation specialists with a 30-second video walk-through and panel-application pack. Derby oven cleaning clients running this typically sign 3-6 panels in the first 90 days, each worth 6-20 jobs per month at sustainable margin.",
    },
    {
      q: "Will the AI receptionist actually price-quote a Quarndon AGA differently from a Sinfin single-oven callout?",
      a: "Yes — that's the core qualifying flow we build for Derby oven cleaners. The AI receptionist (across phone, WhatsApp Business and SMS, 24/7) qualifies every enquiry against the Derby-specific questions that price the job: oven type and brand (single, double, range, AGA, Rayburn, Falcon), property type and DE-postcode (DE22 Allestree vs DE24 Sinfin vs DE56 Quarndon carries entirely different price logic), Rolls-Royce/Toyota/Alstom relocation flag, last cleaned timeframe and any add-ons. The AI then routes to a different appointment type, urgency level, price band and follow-up sequence. Single-oven Sinfin callouts trigger a £55-£75 banded quote against your published price list and same-day calendar slot. Range-cooker DE3 jobs trigger a £100-£140 quote and 90-minute slot. Quarndon AGA enquiries trigger a different intake entirely: confirmation of cooker model, age, last service date, paint condition (Code 6 enamel checks), an in-home survey commitment for first-time customers, a £140-£230 written quote with AOCP, DBS, £5m public liability surfaced, and a 4-5 hour booking slot. Corporate-relocation EoT enquiries trigger letting-agent-aware flow with deposit-deduction-friendly photo packs.",
    },
    {
      q: "Is local Facebook still worth investing in for Derby oven cleaners?",
      a: "Yes — more than in many comparable UK cities. Suburban Derby has unusually active Facebook community groups across Mickleover, Allestree, Chellaston, Spondon and Oakwood, and recommendation threads in those groups still drive a meaningful share of bookings for local oven cleaners. We set up community-aware Facebook lead campaigns, schedule organic post cadence (technician-led short-form content from real DE-postcode jobs — Allestree AGA before/after, Mickleover NEFF double-oven, Littleover range-cooker), and use AI to draft polite, on-brand response templates for the inevitable 'who would you recommend for an oven clean?' threads — without taking the brand voice off-guard. It pairs well with Google Search and Local Service Ads rather than replacing them. Derby oven cleaning clients running the community-Facebook layer alongside Local Pack and LSA typically pull an additional 15-25% of monthly bookings from this channel alone, with cost-per-acquired-job materially below paid social benchmarks.",
    },
  ],
  approach:
    "For Derby independent oven cleaners, our 90-day playbook is: (1) build DE-postcode-stratified GBP and Local Service Ads coverage across 8-12 postcodes (DE22 Allestree, DE3 Mickleover, DE23 Littleover/Sinfin, DE21 Oakwood/Spondon, DE24 Chellaston, DE56 Belper/Duffield/Quarndon, plus city-centre DE1) with AOCP, DBS-checked, aluminium-safe non-caustic chemistry and £5m PLI surfaced; (2) deploy AI 24/7 receptionist with Derby-specific qualifying flow (oven type, DE-postcode, AGA/Rayburn brand, Rolls-Royce/Toyota/Alstom relocation flag) and separate funnels for single-oven retail, range-cooker, AGA/Rayburn premium, corporate-relocation EoT and DE1 short-let; (3) build a corporate-relocation B2B funnel targeting Frank Innes, Hannells, Ashley Adams, Belvoir Derby, Bagshaws Residential and the Derbyshire corporate-relocation specialists; (4) build an Allestree/Mickleover/Quarndon AGA, Rayburn and Falcon landing page with named case studies and 30-45% average-job-value uplift; (5) layer a community-aware Facebook campaign across Mickleover/Allestree/Chellaston/Spondon groups; (6) launch the 12-month re-engage SMS with pre-Christmas, six-month interim AGA and tenancy-end-timed corporate flows to compound rebooking rate to 60-75% inside 18 months.",
};
