import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "pressure washing marketing Edinburgh",
    "Edinburgh driveway cleaning lead generation",
    "exterior cleaning company SEO Edinburgh",
    "Edinburgh Pressure Washing local pack",
    "soft wash heritage stone cleaning Edinburgh",
  ],
  secondaryKeywords: [
    "New Town heritage stone soft wash Edinburgh",
    "EH1 EH3 EH9 EH10 driveway cleaning marketing",
    "Stockbridge Bruntsfield Morningside premium soft wash",
    "Festival Fringe period commercial frontage cleaning",
    "Edinburgh LEZ compliant van pressure washing",
    "ScotEPA waste carrier registered Edinburgh",
    "Listed Building soft wash New Town Old Town",
    "Scottish Water trade effluent consent Edinburgh",
  ],
  heroSubhead:
    "Edinburgh pressure washing operates against a market structure no other UK city replicates. The New Town and Old Town UNESCO World Heritage zones, Conservation Area regulations and Listed Building consent regime mean that high-pressure work on weathered Craigleith and Hailes sandstone, lime-mortar pointed Georgian terraces or Listed B and A properties triggers Listed Building enforcement notices and Conservation Officer informal blacklisting within a week. Low-pressure soft wash under 500 PSI is mandatory; specialist work £1,200–£5,000 per job. Edinburgh's Low Emission Zone, live since 1 June 2024, charges non-Euro-6 vans £60 daily inside the city-centre zone covering EH1, EH2 and parts of EH3. Festival Fringe August demand spikes commercial frontage cleaning 3–5x baseline. Edinburgh Pressure Washing dominates the EH local pack while Bruntsfield, Morningside, Stockbridge and the New Town pay £600–£2,500 routinely. Kerblabs gives Edinburgh operators the AI receptionist and heritage-soft-wash specialism positioning built for the EH-postcode market.",
  marketContext: [
    "Edinburgh pressure washing operates inside the most regulation-and-heritage-sensitive build environment in the UK and almost every operational decision flows from that constraint. The New Town and Old Town are jointly inscribed as a UNESCO World Heritage Site, Conservation Areas cover most of central and inner Edinburgh, Listed Building Consent under the Planning (Listed Buildings and Conservation Areas) (Scotland) Act 1997 is required for almost any meaningful exterior work to a Listed B or A property, and the City of Edinburgh Council Planning department maintains active enforcement against unauthorised works including pressure washing damage. The dominant central housing stock is Craigleith and Hailes sandstone — soft, weathered, lime-mortar pointed, decorated with carved sandstone detailing — and high-pressure TMC work on weathered Edinburgh sandstone pulls surface fines off the stone, blows lime-mortar pointing out of the joints, leaves visible track lines, removes carved detailing, and triggers Listed Building enforcement under the 1997 Act. The right specification is low-pressure soft wash under 500 PSI at the gun, sodium hypochlorite biocide for biological staining, hydrofluoric-free masonry cleaner only on tested patches, no abrasive blast media, no rotary nozzles within 600mm of pointing or carved detailing, and pre-clean / post-clean photographic chain-of-custody for the Conservation Officer if challenged. Operators who get this right command 40–60% premiums and become the named go-to for heritage-stone work across EH1, EH2, EH3, EH9, EH10 and the wider Old Town and New Town conservation footprint; operators who get it wrong end up named on the Edinburgh Conservation Officers' informal blacklist permanently and lose the most lucrative work in the city.",
    "Edinburgh's Low Emission Zone, live since 1 June 2024, charges non-Euro-6 diesel and non-Euro-4 petrol vehicles £60 daily (doubling on repeat breach) across the city-centre LEZ covering EH1, EH2 and parts of EH3, enforced via City of Edinburgh Council ANPR cameras at Princes Street, George Street, the Royal Mile, the Bridges and the Lothian Road junction. The market has bifurcated since June 2024: Euro-6-compliant operators with newer Transit, Vivaro, Caddy or Doblo trolley-vans hold the New Town, Old Town, Stockbridge-adjacent and city-centre commercial work — heritage-stone facade cleans, Princes Street and George Street commercial frontages, Royal Mile World Heritage Site, the Cowgate and Grassmarket — while non-compliant operators have either re-fleeted at £18,000–£35,000 per van or retreated to East Lothian (EH33, EH39, EH41, EH42), Midlothian (EH18, EH19, EH20), West Lothian (EH47-EH55) and the rural EH-postcodes. LEZ-compliant fleet positioning is genuinely a procurement filter at Edinburgh Council estates, the Royal Bank of Scotland (NatWest Group) at Gogarburn and St Andrew Square, Standard Life Aberdeen, Baillie Gifford, Aegon and Scottish Widows estates, the University of Edinburgh estates, Heriot-Watt estates, Edinburgh Castle and Historic Environment Scotland, the Royal Edinburgh Military Tattoo, Edinburgh Festival Fringe Society partner venues, and the larger Edinburgh BTR operators. Almost no Edinburgh pressure washing operator surfaces 'LEZ-compliant Euro-6 fleet' in marketing copy.",
    "Edinburgh's Festival-season demand pulse is the third structural force that reshapes pressure washing economics uniquely. The August Festival Fringe and Royal Edinburgh Military Tattoo together generate roughly £200M+ in direct economic impact and push tourism volumes 3–5x above the November baseline across the Old Town, Royal Mile, Grassmarket, Cowgate, the New Town and Leith. Commercial frontage cleaning demand spikes hard from late June through early September: pre-Festival pre-event cleans for the larger venue operators (Assembly, Pleasance, Underbelly, Gilded Balloon, Summerhall), the BIDs and street-trader frontages, the Princes Street Gardens commercial estate, Festival Fringe Society partner venues, the Royal Edinburgh Military Tattoo partner venues, and the venue-adjacent retail estate. Marketing strategy needs Festival overlay configuration: capacity-aware booking automation that prevents overbookings during peak weekends, multilingual review capability (German, French, Italian, US English search behaviours all surge), pre-Festival GBP photo refreshes, and Festival-period AI receptionist tone configuration that recognises tourism-related queries without being thrown off by them. Edinburgh job values track the premium market: domestic driveway cleans in EH4 South Queensferry / EH16 Liberton £250–£550, mid-market EH9 Newington / EH7 Leith Walk £350–£750, premium EH3 New Town / EH10 Morningside / EH9 Marchmont £600–£1,500, EH13 Colinton / EH4 Cramond / EH4 Barnton premium-suburban £700–£2,000, and the niche Listed-building heritage-stone soft-wash specialism £1,200–£5,000. Edinburgh Google Ads CPCs run higher than Glasgow — 'pressure washing Edinburgh' clicks £2.80–£6, 'soft wash Stockbridge' £4–£9 and 'heritage stone cleaning New Town' £6–£14 — but operators running borough-stratified SEO with heritage specialism positioning, LEZ-compliant fleet messaging and Festival-overlay configuration typically run cost-per-acquired-job at £40–£85 versus £170–£340 on Bark and Checkatrade.",
  ],
  stats: [
    { value: "£60/day", label: "Edinburgh LEZ penalty for non-Euro-6 trade vehicles inside the city-centre zone, live since 1 June 2024", source: "City of Edinburgh Council LEZ" },
    { value: "£1,200–£5,000", label: "EH1/EH2/EH3 Listed Building heritage-stone soft-wash specialism job range" },
    { value: "3–5x", label: "Festival Fringe period commercial frontage demand spike vs November baseline", source: "VisitScotland / Edinburgh Festivals Impact Study" },
    { value: "UNESCO", label: "World Heritage Site status across Old Town and New Town requires Listed Building Consent for exterior works" },
    { value: "£2.80–£14", label: "Edinburgh pressure washing keyword CPC range — heritage and specialism niches priced premium", source: "Kerblabs Edinburgh client accounts" },
    { value: "£200M+", label: "annual direct economic impact of Edinburgh Festival Fringe driving Festival-season commercial demand", source: "Edinburgh Festivals Impact Study" },
  ],
  painPoints: [
    {
      title: "New Town and Old Town heritage Craigleith / Hailes sandstone work being destroyed by high-pressure operators",
      body: "EH1, EH2 and EH3 heritage-stone facades — Craigleith and Hailes sandstone, lime-mortar pointed Georgian terraces, ashlar-block detailing, Listed B and A properties — need low-pressure soft wash under 500 PSI at the gun. High-pressure TMC operators pull surface fines, blow lime-mortar pointing out, leave visible track lines, remove carved detailing, and trigger Listed Building enforcement under the 1997 Act. Conservation Officers maintain informal blacklists. We rebuild around named EH1/EH2/EH3 heritage case studies with photographic chain-of-custody, low-pressure methodology copy, City of Edinburgh Council Conservation Area experience and named Conservation Officer working relationships.",
    },
    {
      title: "LEZ-compliant fleet investment with no marketing payoff",
      body: "Edinburgh operators upgrading to Euro-6 since June 2024 don't surface that fact anywhere customers can see it. Edinburgh Council estates, RBS at Gogarburn, Standard Life Aberdeen, Baillie Gifford, the University of Edinburgh estates, Edinburgh Castle and Historic Environment Scotland refuse non-compliant vans at gatehouse — but can't tell from your website. We rebuild messaging to put LEZ-compliant Euro-6 fleet, Edinburgh LEZ check-tool screenshots and ScotEPA Upper-Tier Waste Carrier credentials directly into landing pages, GBP posts and quote PDFs.",
    },
    {
      title: "Festival Fringe period commercial frontage demand opportunity unstructured",
      body: "August Fringe and Royal Edinburgh Military Tattoo drive 3–5x commercial frontage cleaning demand spikes from late June through early September across the Old Town, Royal Mile, Grassmarket, Cowgate, New Town and Leith. Pursuing it requires capacity-aware booking automation, pre-Festival venue-operator B2B outreach, multilingual review capability, and Festival-period AI receptionist tone. Default Mon-Fri 9-5 booking flows miss it. We launch the dedicated Festival-overlay funnel.",
    },
    {
      title: "Premium Stockbridge / Bruntsfield / Morningside fee-led market under-quoted by Glasgow-template operators",
      body: "Edinburgh's premium suburban belt is fee-led not volume-led — clients in EH3, EH4, EH9 and EH10 expect formal, considered, error-free communication and pay 25–40% above Glasgow comparables for the same procedures. Glasgow-template operators trying to scale into Edinburgh use volume-led tone and discount-led headlines and lose conversion at first quote. We rebuild Edinburgh-specific landing pages, AI receptionist tone profile and review-request flows for the premium fee-led register the Edinburgh market demands.",
    },
  ],
  faqs: [
    {
      q: "How do you market the New Town / Old Town heritage Craigleith and Hailes sandstone soft-wash specialism specifically?",
      a: "Heritage-stone soft-wash specialism is the highest-leverage Edinburgh-specific marketing differentiator and the work where good operators command the largest premiums in the entire UK pressure washing market. We rebuild your website around named EH1/EH2/EH3/EH9/EH10 heritage case studies — Craigleith sandstone Georgian terraces in Heriot Row, Moray Place and Royal Circus, Hailes sandstone Victorian villas in Newington and Marchmont, lime-mortar pointed Old Town tenements off the Royal Mile and the Grassmarket, Listed B and A properties across the New Town Conservation Area and the World Heritage buffer — with proper before/after photography that captures heritage-specific concerns (lime-mortar pointing intact, no surface fines pulled, biological staining lifted without bleaching the stone, ferrous run-staining from chimney bands and rainwater goods addressed with masonry-safe specification, carved sandstone detailing preserved). Method copy explicitly explains low-pressure soft wash under 500 PSI at the gun, sodium hypochlorite biocide application at minimum-effective concentration, hydrofluoric-free masonry cleaner only on tested patches, no abrasive blast media, no rotary nozzles within 600mm of pointing or carved detailing, and full photographic chain-of-custody for the Conservation Officer if challenged. We surface City of Edinburgh Council Conservation Area experience with named Conservation Officers we've worked with, the Listed Building Consent process, and produce a downloadable specification PDF that Conservation Officers and the Edinburgh heritage-architect community (Simpson & Brown, LDN Architects, Page\\Park, Donald Insall Associates Edinburgh, Historic Environment Scotland) can use. Operators running this typically book 3–7 heritage specialism jobs per month at £1,200–£5,000 each within 90 days — work the franchise networks and seasonal sole-traders cannot quote for.",
    },
    {
      q: "How do you handle the Edinburgh LEZ in marketing copy and quote pipelines?",
      a: "We bake LEZ-compliance into every customer touchpoint because the £60 daily charge is the difference between profit and loss on city-centre work. Landing pages display Euro-6 fleet certification with an Edinburgh LEZ check-tool screenshot for the registration plate. Quote PDFs include an LEZ-compliance line directly above the price so corporate procurement teams (Edinburgh Council estates, RBS at Gogarburn and St Andrew Square, Standard Life Aberdeen at Lothian Road, Baillie Gifford, Aegon, Scottish Widows, the University of Edinburgh estates, Heriot-Watt estates, Edinburgh Castle and Historic Environment Scotland, the Royal Edinburgh Military Tattoo, Edinburgh Festival Fringe Society partner venues, the larger Edinburgh BTR operators and the named heritage-property factor agents — Charles White, Ross & Liddell, Hacking & Paterson, Newton Property Management) don't have to ask. The AI receptionist captures the property's EH-postcode as the first qualifying question and confirms LEZ status to the customer when relevant. GBP posts include a periodic LEZ-compliance reminder alongside the ScotEPA Upper-Tier Waste Carrier registration. The compound effect: corporate clients gate-pass you on first attempt, EH3/EH4/EH10 customers tick the research box, and Festival-period commercial frontage work flows through reliably. None of this is theoretical — it's gate-pass vs turn-back at Gogarburn in 2026.",
    },
    {
      q: "How do you structure marketing around the Edinburgh Festival Fringe and Royal Edinburgh Military Tattoo?",
      a: "Festival-overlay marketing requires four operational shifts most Edinburgh operators don't make. First, capacity-aware booking automation prevents overbookings during peak weekends — the AI receptionist is configured to recognise August demand surge and either offer Festival-window same-day slots at premium rates or route to alternative pre/post-Festival windows for non-urgent domestic work. Second, B2B outreach to the Festival venue operators (Assembly Festival, Pleasance, Underbelly, Gilded Balloon, Summerhall, the Royal Edinburgh Military Tattoo, the BIDs covering Royal Mile, Grassmarket and George Street, the Princes Street Gardens commercial estate, Edinburgh Festival Fringe Society partner venues) starts in March-April for August window booking, with dedicated pre-Festival commercial frontage cleaning packages priced per venue. Third, multilingual review capability — German, French, Italian and US English search behaviours all surge during Fringe period — means GBP profiles list languages-spoken attributes appropriately and landing pages have multilingual review snippets. Fourth, Festival-period AI receptionist tone configuration recognises tourism-related queries without being thrown off, and post-Festival follow-up sequences capture re-cleaning relationships with venue operators rolling into the Christmas Markets, Hogmanay and the Edinburgh International Book Festival demand pulses. Edinburgh operators running this typically capture 8–18 Festival-period commercial frontage contracts per year at £400–£2,500 each, plus a meaningful Festival-period domestic premium, fundamentally lifting Q3 revenue 35–60%.",
    },
    {
      q: "What's the biggest difference marketing pressure washing in Edinburgh versus Glasgow?",
      a: "Edinburgh is fee-led and considered; Glasgow is volume-led and direct. The same independent pressure washing operator working in both cities would charge 25–40% higher fees in Edinburgh, see more multi-stage treatment planning (sample patches before main work, multi-day biocide-then-clean cycles, photographic chain-of-custody documentation), and would lose clients quickly to abrupt or impersonal communication. Edinburgh clients in EH3, EH4, EH9, EH10 expect formal, considered, error-free written follow-up; Glasgow clients value warmth, directness and speed above formality. Tourism seasonality is a major factor in Edinburgh and barely a factor in Glasgow. Heritage compliance regulation is structural in Edinburgh (UNESCO, Listed Building Consent, Conservation Areas) and lighter in Glasgow. The LEZ in Edinburgh is harder (£60/day vs Glasgow's £60/day but smaller central zone). We configure the same underlying AI stack with materially different tone profiles, response timing, review prompts and seasonal overlays depending on which city you operate in — Glasgow-template tone deployed unchanged in Edinburgh loses 25–40% conversion at first quote, and Edinburgh-template tone deployed unchanged in Glasgow lands as cold and over-formal.",
    },
  ],
  approach:
    "For Edinburgh pressure washing operators, the 90-day plan is: (1) rebuild website and quote PDFs with LEZ-compliant Euro-6 fleet, ScotEPA Upper-Tier Waste Carrier registration and Scottish Water trade-effluent compliance for full EH-postcode awareness; (2) build the heritage Craigleith / Hailes sandstone soft-wash specialism landing pages for EH1/EH2/EH3 with named Conservation Area case studies, City of Edinburgh Council Conservation experience and Listed Building Consent process documentation; (3) configure Edinburgh-specific premium fee-led AI receptionist tone profile — formal, considered, no aggressive upsell — for EH3/EH4/EH9/EH10 conversion lift; (4) deploy systematic before-and-after capture and EH-postcode-tagged social distribution across GBP, Facebook, Instagram Reels, TikTok and Nextdoor, with multilingual review capability for Festival-period tourism demand; and (5) launch the Festival-overlay B2B commercial frontage funnel with named Festival venue operator outreach (Assembly, Pleasance, Underbelly, Gilded Balloon, Summerhall, Royal Edinburgh Military Tattoo) plus the named heritage-property factor agents and corporate-estate facilities managers to capture both Festival-period spike and year-round premium.",
};
