import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "letting agent marketing Coventry",
    "property management marketing Coventry",
    "Coventry letting agent SEO",
    "landlord acquisition Coventry",
    "student HMO management Coventry",
  ],
  secondaryKeywords: [
    "Earlsdon HMO management Coventry",
    "Stoke Coventry student let",
    "Foleshill Article 4 Coventry",
    "Belvoir Coventry competitor",
    "Loveitts Coventry alternative",
    "JLR corporate accommodation Coventry",
    "Warwick University staff lettings",
    "Renters Rights Bill landlord marketing Coventry",
  ],
  heroSubhead:
    "Coventry lettings runs on three structurally distinct demand engines that few agencies market against properly: a 70,000+ student catchment driving the Earlsdon, Stoke and Cannon Park HMO economy, a Jaguar Land Rover and Manufacturing Technology Centre corporate-accommodation flow with very specific 6-12 month relocation patterns, and a Foleshill Article 4 direction restricting C3-to-C4 HMO conversions that has reshaped portfolio acquisition since 2021. Belvoir Coventry, Loveitts, Hunters and Northwood Coventry compete for visible high-street recall while Warwick University staff lettings sit in a separate referral channel most agencies don't even map. Kerblabs builds the Coventry-specific landlord-acquisition stack independents need.",
  marketContext: [
    "Coventry's PRS is dominated by the student let economy, anchored by Coventry University's ~36,000 students and the University of Warwick's ~30,000 students — together a combined catchment of more than 70,000 with deep HMO demand concentrated in Earlsdon (CV5), Stoke and Stoke Aldermoor (CV2), Cannon Park / Canley (CV4) and parts of Hillfields and Far Gosford Street (CV1). Mandatory HMO licensing applies to 5+ person, 2+ household properties citywide under the Housing Act 2004 amendments. Coventry City Council operates Additional HMO Licensing in specific designated areas, and the Foleshill Article 4 direction (introduced to remove the permitted-development right to convert C3 dwellings to C4 small HMOs in the affected ward) has reshaped portfolio acquisition since 2021 — landlords who held Foleshill stock that was C4-eligible under permitted development pre-Article 4 now need full planning consent for new conversions, fundamentally altering the yield-uplift play that drove Foleshill BTL through 2015-2020. The student let cycle runs the Coventry University academic year (the rigid June-September let window), the Warwick year (slightly later), and parent-guarantor flows from across the UK and overseas.",
    "The corporate-accommodation flow is Coventry's least-publicised acquisition channel. Jaguar Land Rover's Whitley HQ and the Gaydon site (just over the Warwickshire border but commuting in/out of Coventry) employ tens of thousands of high-skill engineers, many on 6-12 month relocation cycles between UK sites and from JLR's global operations. The Manufacturing Technology Centre, the National Automotive Innovation Centre at Warwick and the UK Battery Industrialisation Centre add thousands more engineering professionals, and Coventry University's academic recruitment operates a parallel international relocation flow. Premium let demand for two and three-bed properties in Earlsdon, Stivichall, Allesley, Coundon and the Westwood Heath / Cannon Park / Tile Hill catchment sits well above the city-average yield because corporate-relocation tenants typically take 6-12 month tenancies at £1,200-£2,000+ per month with company guarantees. Most generalist agency marketing doesn't differentiate this stock from student HMO at all.",
    "Compliance overhead in Coventry is meaningful and shifting. Property Ombudsman / PRS membership has been mandatory since October 2014, CMP since 1 April 2019, the Tenant Fees Act 2019 banned lettings fees to tenants, the EICR mandate has applied to all new tenancies since July 2020, the EPC C minimum for new tenancies is currently scheduled for 2025/26, and the Renters Rights Bill (Royal Assent 2025) is layering Section 21 abolition, the move from AST to periodic tenancies, the Decent Homes Standard for the PRS, mandatory landlord Ombudsman membership, the property portal database and the rent-bidding ban on top. Cost-per-click on Google for 'letting agent Coventry' runs £4-£7, 'HMO management Coventry' £3-£6, 'property management Coventry' £4-£6, supportive of strong landlord-acquisition economics on £8,000-£20,000 lifetime managed-instruction value. Belvoir Coventry (Belvoir's ~330-franchise national network), Loveitts (the long-established Coventry independent), Hunters Coventry, Northwood Coventry, Connells Coventry and a strong cohort of student-let specialists compete the high street.",
  ],
  stats: [
    { value: "70,000+", label: "Coventry + Warwick combined student population", source: "HESA 2023/24" },
    { value: "Apr 2021", label: "Foleshill ward Article 4 direction effective (C3 to C4 HMO restriction)" },
    { value: "£4-£7", label: "Google Ads CPC for 'letting agent Coventry' 2024-2025", source: "Kerblabs client accounts" },
    { value: "£235k", label: "average Coventry house price 2024", source: "HM Land Registry" },
    { value: "Oct 2014", label: "Property Ombudsman / PRS membership mandatory for letting agents in England" },
    { value: "5+", label: "person, 2+ household threshold for mandatory HMO licensing under the Housing Act 2004" },
  ],
  painPoints: [
    {
      title: "Foleshill Article 4 has fundamentally reshaped HMO portfolio acquisition and most agency content hasn't caught up",
      body: "The Foleshill Article 4 direction removed the permitted-development right to convert C3 dwellings to C4 small HMOs in the designated area, ending the standard yield-uplift play that drove Foleshill BTL acquisition through 2015-2020. Landlords with Foleshill stock that was C4-convertible pre-Article 4 now need full planning consent for new conversions, fundamentally altering the economics. Most Coventry agency websites either don't reference the Article 4 direction at all or treat it as a generic compliance footnote. Agencies that publish detailed Foleshill-specific Article 4 content — boundary references, application process for change-of-use planning, alternative-area HMO acquisition strategy, existing-use lawful development certificate guidance — pull portfolio-acquisition enquiries at multiples of the rate generic HMO content delivers.",
    },
    {
      title: "70,000+ student catchment runs the Earlsdon, Stoke and Cannon Park HMO market and generalist agencies miss the academic-cycle nuance",
      body: "Coventry University's ~36,000 students and Warwick's ~30,000 drive a deeply structured HMO let market across CV1, CV2, CV4 and CV5. The let cycle runs the Coventry University academic year (rigid June-September window for the autumn letting), the slightly later Warwick year, parent-guarantor processes for both UK and substantial international student cohorts, group-of-friends applications and a high turnover that makes management-fee economics very different from family lets. Most generalist agency websites treat student HMO as a footnote. Specialist student-let agencies (some named, some part of broader independents) own the Earlsdon, Cannon Park and Stoke catchments through named-street content, named-property HMO licence references and academic-cycle expertise.",
    },
    {
      title: "JLR / MTC / NAIC / WMG corporate accommodation flow is invisible to most generalist Coventry agency marketing",
      body: "Jaguar Land Rover's Whitley HQ, the Manufacturing Technology Centre, the National Automotive Innovation Centre, the UK Battery Industrialisation Centre and Warwick Manufacturing Group between them generate sustained 6-12 month corporate-relocation tenancy demand at £1,200-£2,000+ per month with company guarantees. The premium two and three-bed stock in Earlsdon, Stivichall, Allesley, Coundon, Westwood Heath and Cannon Park serves this demand well, and the company-guaranteed tenancy economics mean rent guarantee, void minimisation and faster-turn capability are the core pitch. Generic 'we'll list your property' agency content captures none of this. Agencies that build dedicated corporate-relocation landing pages, named-corporate-employer content authority and serviced-tenancy positioning capture an acquisition channel competitors don't even map.",
    },
    {
      title: "Belvoir Coventry, Loveitts, Hunters and Northwood dominate visible high-street brand recall and independents need a different playbook",
      body: "Belvoir Coventry (Belvoir's ~330-franchise national network), Loveitts (the long-established CV-postcode independent), Hunters Coventry and Northwood Coventry own most visible high-street brand recall and Rightmove featured-listing prominence in Coventry. Independents don't outspend them — they win on hyperlocal long-tail SEO around named micro-areas (Earlsdon specifically, Cannon Park specifically, Foleshill specifically, Stivichall, Allesley, Coundon, Westwood Heath, Tile Hill), Article 4 + corporate-accommodation content authority chains structurally don't publish, AI receptionist closing applicant viewing requests inside 90 seconds (chain branches lose 30-50% of out-of-hours calls), and Google review velocity at 8-15 monthly reviews mentioning named CV wards.",
    },
  ],
  faqs: [
    {
      q: "How do we build Foleshill Article 4 content authority that actually wins HMO portfolio enquiries?",
      a: "Foleshill Article 4 is the single most under-served HMO content opportunity in Coventry letting agency. The direction removed the permitted-development right to convert C3 dwellings to C4 small HMOs in the designated area, fundamentally changing portfolio acquisition economics. Most agency sites either ignore it or treat it as a footnote. The playbook: (1) a dedicated Foleshill Article 4 landing page with the precise direction reference, the boundary detail (which streets are in / out — boundary detail matters because portfolio landlords with stock straddling the line need clarity), the implications for existing C4 stock vs new conversions, the lawful development certificate process for pre-Article 4 conversions, and the change-of-use planning application route for new conversions; (2) a Coventry city-wide HMO licensing hub covering mandatory 5+ person licensing, Additional HMO Licensing in designated areas, and Article 4 directions citywide — many landlords don't realise multiple regimes can apply to the same property; (3) an alternative-area HMO acquisition guide for landlords priced out of Foleshill — Stoke, Earlsdon, Hillfields, Radford, Far Gosford Street comparative content; (4) a portfolio-licensing audit lead magnet for landlords with HMO stock across CV postcodes — typically pulls 10-30 audit requests per month per branch; (5) ongoing content updates as Coventry City Council lays new Article 4 directions, renews HMO licensing schemes or publishes consultation outcomes — we monitor council agenda papers so your content doesn't go stale.",
    },
    {
      q: "How do you handle the 70,000+ student let market against the named Coventry student-let specialists?",
      a: "Coventry student let is content-authority territory, not paid-search territory. The named student-let specialists own Earlsdon, Cannon Park, Stoke and parts of Hillfields because they own the named-street content, the academic-cycle expertise (the rigid June-September let window for Coventry University, the slightly later Warwick window, the parent-guarantor processes for substantial UK and international cohorts) and the named-property HMO licence references. The break-in playbook: (1) named-street HMO management pages for Earlsdon (Earlsdon Avenue, Albany Road, Earlsdon Street grid), Stoke (Walsgrave Road, Clay Lane), Cannon Park (Sir Henry Parkes Road, Westwood Heath Road), Hillfields (Far Gosford Street, Cox Street), each with named-property HMO licensing references, the Additional HMO Licensing scheme rules where applicable, and Renters Rights Bill periodic-tenancy framing for student tenancies; (2) a Coventry HMO Licensing authority hub covering both Mandatory licensing and Additional Licensing; (3) separate Coventry University and Warwick University academic-cycle content acknowledging the different term dates and let windows; (4) a student HMO portfolio acquisition lead magnet for landlords self-managing; (5) named HMO specialist E-E-A-T page with explicit student-let expertise. Independents executing this typically take 6-15 named Earlsdon / Cannon Park / Stoke properties per year from competitor agencies in their first 12-18 months.",
    },
    {
      q: "How do we tap the JLR / MTC / NAIC corporate-accommodation flow that's been invisible to our marketing?",
      a: "Coventry corporate accommodation is real, large, structurally underserved and runs on completely different economics from student HMO or family let. Jaguar Land Rover's Whitley HQ alone employs tens of thousands of engineers, many on 6-12 month relocation cycles between UK sites or from JLR's global operations. Add the Manufacturing Technology Centre, the National Automotive Innovation Centre, the UK Battery Industrialisation Centre and Warwick Manufacturing Group and the corporate-relocation cohort runs into the tens of thousands. The tenancies are typically 6-12 months at £1,200-£2,000+ per month with company guarantees — meaning rent guarantee, faster turnaround between tenants, void-minimisation capability and serviced-tenancy positioning are the core pitch. We build (1) a dedicated corporate-relocation landing page positioning your agency as the JLR / MTC / NAIC / WMG specialist with named-corporate-employer reference; (2) a serviced-let / executive-let content sub-brand acknowledging the different service expectation (furnishing, utility-included options, faster-turn between tenants, dedicated point-of-contact); (3) LinkedIn outreach to JLR / MTC / NAIC / WMG global mobility teams and the relocation specialists they appoint (Crown World Mobility, K2 Corporate Mobility, BGRS); (4) Google Ads geo-targeted to the specific corporate sites and the global mobility consultancies; (5) named corporate-let specialist E-E-A-T page. Independents executing this typically capture 6-15 corporate-relocation portfolio instructions in their first 12-18 months.",
    },
    {
      q: "How should we position our Coventry agency for the Renters Rights Bill commencement and Section 24 fallout?",
      a: "Position Renters Rights Bill commencement and Section 24 navigation as the single largest landlord-acquisition opportunity of the decade, with Coventry-specific framing. Coventry's PRS landlord cohort splits between local owner-occupier-turned-landlord stock (typically Section 24-impacted), professional buy-to-let portfolio holders (heavily Section 24-impacted), student-HMO specialists (compliance overhead acute), corporate-let landlords (rent guarantee and serviced-let economics insulate from some Section 24 effects), and a growing Limited company structure cohort (post-Section 24 restructuring). Each segment needs different framing. We build (1) a Renters Rights Bill content hub on your site covering Section 21 abolition, periodic tenancies replacing AST, the Decent Homes Standard for PRS, mandatory landlord Ombudsman, property portal database, rent-bidding ban — each with commencement-order timing as it's laid; (2) Section 24 / Limited company restructuring content authority — particularly relevant for the Coventry portfolio cohort considering SPV structuring; (3) student-HMO-specific Renters Rights Bill content acknowledging the periodic-tenancy implications for the rigid June-September let cycle; (4) corporate-let-specific Renters Rights Bill content acknowledging company-guaranteed tenancy implications; (5) a 'Renters Rights Bill readiness audit' lead magnet — typically pulling 15-40 audit requests per month per branch; (6) a retention sequence to existing landlord clients briefing them on each commencement phase. Coventry landlords are research-driven (engineering-professional cohort) and respond well to genuine technical authority — not generic 'Renters Reform is coming' bullet points.",
    },
  ],
  approach:
    "For Coventry independent letting agents and property managers, our 90-day playbook is: (1) build dedicated Foleshill Article 4 content authority plus citywide HMO licensing hub with portfolio-licensing audit lead magnet; (2) deploy named-street HMO content for Earlsdon, Cannon Park, Stoke and Hillfields with academic-cycle expertise for both Coventry University and Warwick; (3) build dedicated corporate-relocation / serviced-let positioning targeting JLR, MTC, NAIC, WMG and the global mobility consultancies; (4) deploy a Renters Rights Bill content hub plus 'readiness audit' landlord-acquisition lead magnet, with student-HMO and corporate-let specific framing; (5) deploy AI receptionist + missed-call text-back to capture out-of-hours viewing and maintenance calls and beat Belvoir / Loveitts / Hunters chain phone routing; (6) drive Google review velocity to 8-15 monthly reviews per branch mentioning named CV wards (Earlsdon, Cannon Park, Stoke, Stivichall, Allesley, Coundon, Foleshill); and (7) integrate Reapit / Alto / Jupix / Goodlord so AI-captured enquiries, viewing bookings and maintenance dispatches sync to the existing CRM workflow."
};
