import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "solicitor marketing Derby",
    "law firm SEO Derby",
    "Derby conveyancing solicitor SEO",
    "Rolls-Royce employment law Derby",
    "Derbyshire family law firm marketing",
  ],
  secondaryKeywords: [
    "Smith Partnership Derby legal cluster",
    "Geldards Derby East Midlands",
    "Allestree Mickleover family law SEO",
    "Littleover Quarndon private client solicitor",
    "Rolls-Royce Toyota Alstom commercial law",
    "Derby South PI corridor marketing",
    "AML compliant lead capture Derby law firm",
    "SRA Transparency Rules Derby conveyancing",
  ],
  heroSubhead:
    "Derby's legal market sits at the heart of UK advanced engineering — Rolls-Royce Civil Aerospace HQ (14,000+ employees), Toyota Burnaston (5M+ cars produced since 1992), Alstom Litchurch Lane (3,000+ train manufacturing workforce, the UK's only volume train factory), JCB Power Systems and the wider East Midlands aerospace and rail tier-one supplier base. The legal market is anchored by Smith Partnership (Derby-rooted regional firm with offices across the East Midlands) and Geldards (cross-Cardiff / Nottingham / Derby Top 100 with substantial Derby presence). Derby's high-skill engineering professional base concentrates HNW family work in Allestree, Mickleover, Littleover and Quarndon; Rolls-Royce / Toyota / Alstom drive substantial employment, IP and supply-chain commercial work; the Derby South PI corridor and historic engineering occupational disease legacy sustain ongoing PI work. Kerblabs builds postcode-stratified, SRA-compliant funnels for Derby independent firms.",
  marketContext: [
    "Derby's legal market is anchored by Smith Partnership (Derby-rooted regional firm with offices across the East Midlands and a strong consumer-side practice spanning family, conveyancing, private client and PI) and Geldards (cross-Cardiff / Nottingham / Derby Top 100 firm with substantial corporate, real estate, employment and dispute resolution practice). Around them, Derby mid-market firms include Flint Bishop (Derby-rooted with offices in Derby, Birmingham and Stafford, strong corporate and dispute resolution practice), Else Solicitors (Burton-on-Trent with Derby reach), Eddowes Waldron, Moody & Woolley, Howes Percival (Northampton-headquartered with East Midlands reach), and a long high-street tradition across the DE-postcode network and the wider Derbyshire geography. Three structural forces shape Derby legal marketing more than any other UK regional city. First, Rolls-Royce / Toyota / Alstom advanced-engineering employer concentration: Derby is the UK's most concentrated advanced-engineering city, with Rolls-Royce Civil Aerospace HQ employing 14,000+ across Sinfin and Raynesway sites (the largest single Derby employer), Toyota Burnaston employing 3,000+ at the UK's largest single-site car-assembly facility, Alstom Litchurch Lane employing 3,000+ at the UK's only volume train-manufacturing facility, JCB Power Systems, Pattonair, and a deep aerospace and rail tier-one supplier ring. This drives substantial commercial, employment, IP, share-scheme, supply-chain and regulatory work that flows through specialist firms. Second, a high-skill, high-earning STEM-graduate professional base: Derby has one of the highest UK concentrations of STEM graduates relative to population (driven by Rolls-Royce, Toyota and Alstom hiring patterns plus University of Derby, Nottingham Trent and Loughborough catchment proximity), with median full-time earnings ahead of the East Midlands average and a discerning, research-driven consumer base for legal services. Third, the Rolls-Royce occupational disease and engineering-employer's-liability claim base: the historic Derby engineering employer base (Rolls-Royce, predecessor companies, Bombardier / Alstom, the Pullman Coach Works, surrounding Derbyshire engineering and mining heritage) generates ongoing occupational disease (NIHL, HAVS, asbestos exposure on aircraft and rolling-stock manufacturing, vibration-related claims) and serious-injury claim base.",
    "Derby legal pricing splits sharply by Smith Partnership / Geldards tier vs mid-market vs high-street. Geldards commercial work bills at £230-£360 partner hourly; Smith Partnership and Flint Bishop mid-market work £170-£230; high-street firms across the DE-postcode network operate at £130-£175. Standard freehold residential conveyancing in Derby retails £900-£1,500 plus disbursements at high-street firms — close to Nottingham reflecting East Midlands median pricing, with a meaningful Allestree / Mickleover / Littleover / Quarndon / Duffield premium band on £400k-£900k family homes. Divorce work runs £1,000 fixed-fee at the simple end up to £20,000-£100,000+ for HNW DE22 / DE23 / Quarndon contested matters with substantial Rolls-Royce / Toyota / Alstom senior-engineer matrimonial work involving aerospace and engineering executive equity, share-scheme valuation and pension-on-service complexity. Personal injury concentrates around the M1 / A50 / A52 motorway and trunk road network, the Rolls-Royce / Toyota / Alstom employer's liability base, and the historic Derbyshire engineering and mining occupational disease legacy. Family law concentrates in HNW Allestree / Mickleover / Littleover / Quarndon / Duffield and volume work across the wider DE-belt. Immigration work concentrates around the University of Derby international student community plus Polish, Romanian, Bulgarian, Pakistani (substantial Pakistani community in Normanton and inner-Derby) and Eritrean communities. Named consolidator competition: Quality Solicitors panel firms (originally founded in the East Midlands), Co-op Legal Services, Slater + Gordon, Hugh James and Irwin Mitchell have meaningful Derby market share.",
    "Derby Google Ads CPCs in legal keywords run materially below Nottingham and Leicester. Through 2024-2025 we've consistently observed 'divorce solicitor Derby' clicking £10-£20, 'personal injury solicitor Derby' at £30-£52, 'immigration solicitor Derby' at £15-£28, 'conveyancing solicitor Derby' at £8-£16, and 'commercial solicitor Derby' at £12-£22. Postcode and engineering-specific queries ('solicitor Allestree', 'family law Mickleover', 'conveyancing Quarndon', 'Rolls-Royce executive divorce solicitor') click at 30-55% of the city-wide rate while converting at 2-3.5x the rate, with engineering-executive matrimonial queries showing strong conversion uplift. The strategic playbook for Derby independent firms therefore stratifies on three axes: Geldards / Smith Partnership commercial vs mid-market vs high-street; Allestree / Mickleover / Littleover / Quarndon HNW vs wider DE-belt volume; and engineering / aerospace / rail commercial specialism vs mainstream consumer work. Kerblabs' Derby independent solicitor clients running this stack typically reach 8-16 paid new matters per month within 6-9 months. Critical Derby-specific layers: (1) Rolls-Royce / Toyota / Alstom B2B employment, IP and supply-chain commercial funnel; (2) engineering-executive HNW matrimonial specialism with share-scheme valuation expertise; (3) Derby aerospace / rail occupational disease specialism for PI firms. Every lead drops into LEAP / Quill / Proclaim / Clio with structured AML metadata.",
  ],
  stats: [
    { value: "14,000+", label: "Rolls-Royce Civil Aerospace Derby employees — UK's most concentrated advanced engineering employer", source: "Rolls-Royce" },
    { value: "5M+", label: "Toyota Burnaston cars produced since 1992 driving automotive supply-chain commercial work", source: "Toyota Manufacturing UK" },
    { value: "3,000+", label: "Alstom Litchurch Lane workforce — UK's only volume train manufacturing facility", source: "Alstom UK" },
    { value: "£10-£20", label: "Google Ads CPC for 'divorce solicitor Derby' (2024-25)", source: "Kerblabs client accounts" },
    { value: "£900-£1,500", label: "typical Derby high-street residential conveyancing fee range" },
    { value: "£32,500", label: "Derby median full-time earnings driving high-skill consumer demand", source: "ONS ASHE" },
  ],
  painPoints: [
    {
      title: "Rolls-Royce / Toyota / Alstom B2B commercial and employment work hidden behind generic SEO",
      body: "Rolls-Royce Civil Aerospace HQ, Toyota Burnaston, Alstom Litchurch Lane, JCB Power Systems and the wider Derbyshire aerospace and rail tier-one supplier ring drive substantial commercial, employment, IP, share-scheme, supply-chain and regulatory work. Without sector-specific SEO ('aerospace supply chain commercial Derby', 'rolling stock IP advisory Alstom', 'Toyota supplier compliance solicitor', 'Rolls-Royce share scheme advisory') and LinkedIn-led B2B outreach to Derby corporate counsel, you're invisible."
    },
    {
      title: "Engineering-executive HNW matrimonial work marketed as commodity divorce",
      body: "Rolls-Royce, Toyota, Alstom and JCB senior engineering executive matrimonial work involves substantial complexity — aerospace and rail executive bonus and share-scheme valuation, pension-on-service splits with defined-benefit Rolls-Royce pension scheme expertise, mobile-engineer-at-overseas-Rolls-Royce-site international family complications, Toyota Japanese-parent-company share treatment, and Alstom French-parent-company tax implications. Firms running generic 'divorce solicitor Derby' campaigns lose this market to specialist firms."
    },
    {
      title: "Derby engineering occupational disease specialism under-marketed despite real Rolls-Royce / Alstom claim base",
      body: "The historic Derby aerospace and rail engineering employer base generates ongoing occupational disease (NIHL from aerospace and rolling-stock factory noise, HAVS from grinding and finishing, asbestos exposure on historic Rolls-Royce and Bombardier sites, vibration-related claims) and engineering-supply-chain serious injury work. Most firms market generic PI; firms that win are those with explicit aerospace/rail-employer-named landing pages and APIL specialism credentials."
    },
    {
      title: "Allestree / Mickleover / Quarndon HNW family work marketed alongside volume work, diluting positioning",
      body: "DE22 (Allestree), DE3 (Mickleover), DE23 (Littleover), Quarndon and Duffield host a separate HNW family law market with average matrimonial assets £450k-£1M+, distinct from the wider Derby volume market. Firms attempting to market both through a single funnel dilute positioning. The right approach is sharply differentiated parallel funnels — HNW Allestree / Mickleover targeting Resolution-accredited specialism with Rolls-Royce / Toyota engineering-executive context, and volume Derby targeting mainstream high-street."
    },
  ],
  faqs: [
    {
      q: "How does Kerblabs handle Rolls-Royce / Toyota / Alstom B2B commercial and employment work specifically?",
      a: "Derby is the UK city outside Sheffield where advanced-engineering specialism produces the largest measurable commercial-work conversion uplift. Rolls-Royce Civil Aerospace HQ (14,000+ Derby employees), Toyota Burnaston (3,000+ employees, 5M+ cars produced since 1992), Alstom Litchurch Lane (3,000+ employees, the UK's only volume train-manufacturing facility), JCB Power Systems and a deep aerospace and rail tier-one supplier ring generate substantial commercial, employment, IP, share-scheme, supply-chain and regulatory work that flows through specialist B2B channels. Our Derby B2B commercial playbook focuses on five layers: (1) sector-specific SEO around niche advanced-engineering topics ('aerospace supply chain commercial Derby', 'rolling stock IP advisory Alstom', 'Toyota supplier compliance solicitor', 'Rolls-Royce share scheme advisory', 'aerospace tier-one M&A Derby', 'rail franchise procurement advisory Derbyshire'); (2) LinkedIn-led B2B outreach to in-house counsel, procurement leads, HR directors and engineering R&D leaders at Rolls-Royce, Toyota, Alstom, JCB Power Systems and the wider tier-one supplier base; (3) thought leadership content tuned to Legal 500 / Chambers UK ranking submissions in IP, employment, real estate and corporate rankings; (4) attendance and speaking at SMMT (Society of Motor Manufacturers and Traders) events, Aerospace Defence Security and Space (ADS Group) events, RIA (Railway Industry Association), Derby and Derbyshire Chamber of Commerce, and East Midlands aerospace cluster events; (5) AI receptionist tuned for higher-stakes B2B intake with named-partner routing and conflict-check fields populated at first contact."
    },
    {
      q: "How do you handle engineering-executive HNW matrimonial work specifically?",
      a: "Derby has one of the strongest UK concentrations of advanced-engineering executive matrimonial work outside London, with Rolls-Royce Civil Aerospace, Toyota and Alstom senior executive base resident in Allestree, Mickleover, Littleover, Quarndon, Duffield and surrounding Derbyshire commuter villages. The work involves substantial complexity: Rolls-Royce defined-benefit pension scheme valuation methodology (one of the UK's largest corporate pension schemes, with complex pension-on-service split implications), Rolls-Royce share scheme treatment including LTIPs and equity vesting; Toyota Japanese-parent-company share treatment with cross-jurisdictional tax implications; Alstom French-parent-company share treatment with French-UK tax-treaty considerations; JCB private-company equity (JCB family ownership creates distinctive matrimonial-asset valuation issues); mobile-engineer overseas-deployment family complications (Rolls-Royce engineers frequently spend years on overseas Rolls-Royce site secondments creating complex international family law issues); and engineering-bonus structures with deferred compensation. Our Derby engineering-executive playbook builds: dedicated 'Rolls-Royce executive divorce solicitor Derby', 'aerospace executive matrimonial', 'rail engineering executive divorce', 'engineering pension scheme sharing solicitor' landing pages with technical share-scheme content; Resolution and IAFL membership amplification; referral relationship-building with East Midlands wealth managers (Brewin Dolphin Derby, Quilter Cheviot, Investec Wealth East Midlands) and Derby aerospace / rail-aware accountancy firms (BDO Derby, Hawsons, Smith Cooper); and AI receptionist tuned for high-stakes confidential intake with conflict-check fields populated at first contact."
    },
    {
      q: "We're a HNW family law specialist in Allestree / Mickleover / Quarndon. How do you grow new client acquisition there?",
      a: "The DE22 / DE3 / Quarndon HNW family law market is one of the strongest East Midlands matrimonial markets outside Stoneygate / Oadby (Leicester) and West Bridgford (Nottingham). The catchment combines Rolls-Royce, Toyota, Alstom and JCB executive wealth (the most concentrated UK aerospace and rail executive resident community outside Bristol), Derbyshire entrepreneurial wealth, retired professional-services wealth, and traditional Derby professional-family demographics. Average matrimonial asset values in Allestree and Quarndon frequently exceed £600k. Marketing for this segment is fundamentally different from generic 'divorce solicitor Derby': prospects research in private through accountant and IFA referrals, want named-partner credentials and Resolution accreditation displayed prominently, and on Rolls-Royce / Toyota / Alstom executive work demand absolute discretion given the relatively small size of the East Midlands aerospace and rail executive community. Our Derby HNW family law playbook focuses on: named-partner SEO, referral relationship-building with East Midlands wealth managers and Rolls-Royce / Toyota / Alstom-aware accountancy firms, Resolution and IAFL membership amplification, attendance at STEP East Midlands events, and AI receptionist tuned for high-stakes confidential intake."
    },
    {
      q: "Can independent Derby firms realistically compete with Quality Solicitors networks, Co-op Legal Services, Slater + Gordon and Geldards on consumer work?",
      a: "Yes — on the right battlegrounds. National consolidators win on raw paid-search spend; Geldards operates as a substantial Top 100 cross-East-Midlands competitor on commercial and private client work. Independents win on three things: (1) hyperlocal long-tail SEO ('conveyancing solicitor Allestree', 'divorce solicitor Mickleover', 'family law Quarndon', 'employment solicitor Spondon', 'Rolls-Royce executive matrimonial Derby') where a single-office firm can outrank a national network on intent match; (2) review velocity in one Derby postcode — 200+ Google reviews mentioning specific DE22, DE3, DE23 or Quarndon neighbourhoods crushes a national network site; (3) high-skill consumer expectation match — Derby's STEM-graduate professional base researches deeply and rewards firms with credible specialist depth signalled clearly, which Quality Solicitors and Co-op Legal Services structurally don't deliver. Across our Derby independent solicitor clients this approach has produced 30-55% paid-matter growth year-on-year while sister Quality Solicitors panel firms have flatlined."
    },
  ],
  approach:
    "For Derby independent solicitors and law firms, our 90-day playbook is: (1) stratify your Derby catchment on three axes — Geldards / Smith Partnership commercial vs mid-market vs high-street; Allestree / Mickleover / Littleover / Quarndon HNW vs wider DE-belt volume; and engineering / aerospace / rail commercial specialism vs mainstream consumer work — with separate landing pages and campaigns per cluster; (2) deploy SRA-compliant AI receptionist tuned for legal-vertical intake with explicit no-legal-advice rules, AML-aware lead-source capture and conflict-check fields populated at first contact (especially important on Rolls-Royce / Toyota / Alstom executive work where current and prospective conflicts must be screened rigorously); (3) build LEAP / Quill / Proclaim / Clio integration with structured source attribution; (4) drive Google review velocity to 8-15 monthly reviews mentioning named DE-postcodes; and (5) where relevant, build sector-specific Rolls-Royce / Toyota / Alstom B2B commercial funnels with LinkedIn-led outreach plus engineering-executive matrimonial specialism funnels with share-scheme and pension-scheme expertise — the highest-leverage Derby-specific positionings available.",
};
