import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "tree surgeon marketing Edinburgh",
    "Edinburgh arborist lead generation",
    "tree surgeon SEO Edinburgh",
    "Lothians tree surgery Google Ads",
    "ARB Approved Contractor marketing Edinburgh",
  ],
  secondaryKeywords: [
    "Holyrood Park Royal Botanic Garden tree contractor",
    "New Town World Heritage Conservation Area tree surgeon",
    "Scottish Forestry Felling Licence Edinburgh",
    "Capital Tree Care Edinburgh Tree Surgeons competitor",
    "ash dieback removal Lothians",
    "Murrayfield Cramond Barnton Colinton heritage tree work",
    "City of Edinburgh Council framework tree surgeon",
    "storm callout tree surgeon Edinburgh",
  ],
  heroSubhead:
    "Edinburgh is the most heritage-regulated arboricultural market in Scotland. The Old Town and New Town UNESCO World Heritage Site covers the largest contiguous urban Conservation Area in the UK, the City of Edinburgh Council manages Holyrood Park (under Historic Environment Scotland direct ownership), the Royal Botanic Garden of Edinburgh holds 70 acres of mature specimen stock under separate management, and the New Town's mature gardens and communal Conservation Area trees attract Section 60 notice on most works. The premium suburban belt — Murrayfield, Cramond, Barnton, Colinton, Grange, Morningside — supports £900–£3,500 mature-tree removal pricing on listed-building-adjacent properties, while Capital Tree Care, Edinburgh Tree Surgeons and Bartlett (UK national) compete at the heritage end. Council framework subcontracts run via Glendale, idverde and Tivoli at 25–35% margin compression. Kerblabs gives independent ARB Approved Contractors the AI storm-mode receptionist, ash-dieback funnel, World-Heritage-Site-aware Conservation Area qualifying flow and direct council-tender pipeline tuned for Scottish regulatory specifics.",
  marketContext: [
    "Edinburgh's regulatory context is the most heritage-dense in Scotland and arguably the UK. The Old Town and New Town UNESCO World Heritage Site (inscribed 1995) covers approximately 4.5 km² of Conservation Area at the heart of the city — the largest contiguous urban Conservation Area in the UK. Section 60 notice (the Scottish equivalent of the English Section 211) under the Town and Country Planning (Scotland) Act 1997 applies to any works on a tree over 8cm diameter at 1.3m height within the Conservation Area, with statutory 6-week notice to the City of Edinburgh Council Planning Service. Listed Building Consent applies to curtilage trees on the city's substantial Grade A and Grade B listed-building inventory. Holyrood Park (650 acres) is owned and managed by Historic Environment Scotland directly — not the council — with separate procurement processes. The Royal Botanic Garden of Edinburgh's 70 acres at Inverleith holds mature specimen stock managed by RBGE arboricultural staff with periodic specialist contract requirements.",
    "City of Edinburgh Council manages over 230,000 trees across the city's parks, streets and managed estates — Princes Street Gardens, the Meadows, Bruntsfield Links, Inverleith Park, Saughton Park, Lauriston Castle estate, Cramond foreshore. Tendered tree work runs through framework subcontract via Glendale, idverde, Tivoli and a small number of locally-procured frameworks. The Edinburgh Trams expansion, the St James Quarter regeneration, the Edinburgh BioQuarter expansion and the Granton Waterfront regeneration have driven phased TPO consent and replacement-planting work through tier-one contractors. On the domestic premium side, Murrayfield, Cramond, Barnton, Colinton, Grange, Morningside, Merchiston and Bruntsfield together support £900–£3,500 mature-tree removal on Conservation Area and listed-building-adjacent properties — Edinburgh fees run roughly 25–40% above Glasgow benchmarks because of the World Heritage and listed-building density.",
    "Ash dieback affects the wider Lothians and Borders mature roadside ash inventory — the City of Edinburgh Council, Midlothian Council, East Lothian Council and West Lothian Council together manage thousands of mature ash. Framework subcontracts pay £150–£600 per stem at 25–35% margin compression. Scottish Forestry South Region holds periodic dieback management forums. Google Ads CPCs run £4–£8 on 'tree surgeon Edinburgh', £2–£5 on suburban-belt terms, £6–£11 on 'emergency tree Edinburgh' (peaking £13+ during named-storm windows). Festival-season demand (August Fringe, Royal Edinburgh Military Tattoo, Hogmanay) creates atypical micro-spikes in tourism-zone tree work. Kerblabs Edinburgh tree surgery clients running borough-stratified GBP, dedicated dieback and World-Heritage-aware landing pages plus structured B2B outreach to City of Edinburgh Council, Historic Environment Scotland, RBGE and the Lothians chartered surveyors typically achieve £140–£270 cost-per-job.",
  ],
  stats: [
    { value: "4.5 km²", label: "Edinburgh Old Town + New Town UNESCO World Heritage Site Conservation Area — UK's largest contiguous urban Conservation Area" },
    { value: "650 acres", label: "Holyrood Park managed by Historic Environment Scotland (separate procurement from City of Edinburgh Council)" },
    { value: "230,000+", label: "trees managed by City of Edinburgh Council across parks, streets and managed estates" },
    { value: "£4–£13", label: "Google Ads CPC range for Edinburgh tree-surgeon and emergency-tree keywords 2024–2025", source: "Kerblabs client accounts" },
    { value: "£900–£3,500", label: "typical Murrayfield/Cramond/Barnton/Colinton/Morningside mature-tree removal price range" },
    { value: "70 acres", label: "Royal Botanic Garden of Edinburgh mature specimen stock under RBGE direct arboricultural management" },
  ],
  painPoints: [
    {
      title: "World Heritage Site Conservation Area Section 60 notice eating surveyor time on dead enquiries",
      body: "The Old Town + New Town WHS Conservation Area means almost every domestic enquiry in EH1, EH2, EH3, EH8 and parts of EH9 requires Section 60 notice with statutory 6-week wait. Without front-end qualifying, your surveyor wastes afternoons on Hampstead-Garden-Suburb-equivalent jobs that legally can't progress. AI receptionist with World-Heritage-Site-aware Conservation Area qualifying, City of Edinburgh Council planning portal templated hand-off SMS, and listed-building curtilage flag recovers the time.",
    },
    {
      title: "Holyrood Park, Princes Street Gardens, RBGE work going to direct-procured frameworks",
      body: "Holyrood Park is managed by Historic Environment Scotland (not the council); Princes Street Gardens, the Meadows and Inverleith Park run through City of Edinburgh Council Parks framework; Royal Botanic Garden Edinburgh handles its own arboricultural procurement. Most independents target the wrong procurement channel. We build separate B2B outreach packs for HES, City of Edinburgh Council Parks, RBGE and the Lothians council areas.",
    },
    {
      title: "Murrayfield/Cramond/Morningside premium work going to Capital Tree Care and Bartlett without independent counter-positioning",
      body: "EH4, EH10, EH9, EH13 and EH16 support £900–£3,500 mature-tree removal on Conservation Area and listed-building-adjacent properties. Capital Tree Care, Edinburgh Tree Surgeons and Bartlett command the heritage end. We rebuild around named EH-postcode case studies, surface ApCo, BS3998:2010, LOLER/PUWER 1998 in landing pages and quote PDFs, and run B2B outreach to Rettie & Co, Savills Edinburgh, Knight Frank Edinburgh, Coulters and Warners (ESPC member firms) where heritage tree work flows through repeat relationships.",
    },
    {
      title: "Festival-season tourism-zone storm callouts missed for lack of multilingual / out-of-hours capture",
      body: "August Fringe and the Royal Edinburgh Military Tattoo push tourism volumes 3–5x baseline through the Old Town and the Royal Mile. Storm or wind-event tree failures during Festival weeks generate disproportionate emergency callouts — often from short-let property managers, hotel groups and the major Festival venue operators (Underbelly, Pleasance, Gilded Balloon, Assembly). Without 24/7 AI receptionist with multilingual capability and venue-operator-aware booking flow, this work goes elsewhere.",
    },
  ],
  faqs: [
    {
      q: "How does the Old Town + New Town World Heritage Site change Conservation Area tree-work qualifying in Edinburgh?",
      a: "The UNESCO World Heritage Site (inscribed 1995, covering Old Town and New Town across approximately 4.5 km²) is the largest contiguous urban Conservation Area in the UK. Section 60 notice under the TCP(S)A 1997 applies to any works on a tree over 8cm diameter at 1.3m height with statutory 6-week wait to the City of Edinburgh Council Planning Service. The substantial Grade A and Grade B listed-building inventory means Listed Building Consent applies to curtilage trees on most New Town gardens. We build all of this into the customer journey: AI receptionist asks WHS Conservation Area status as the second qualifying question after job type and surfaces the City of Edinburgh planning portal automatically; quote enquiry forms include WHS, Conservation Area, Listed Building and Section 60 notice progress fields; the website carries a New-Town-by-New-Town Conservation Area content hub (separate pages for Old Town, New Town, Stockbridge Conservation Area, Bruntsfield, Marchmont, Grange, Morningside, Merchiston, Murrayfield) with named local detail. The AI never gives planning advice — only the council can determine status. This positioning earns citations from City of Edinburgh Council Planning Service, Historic Environment Scotland and the Edinburgh World Heritage Trust.",
    },
    {
      q: "How do we win Holyrood Park, Princes Street Gardens and RBGE work direct rather than via Glendale subcontract?",
      a: "Edinburgh's mature parkland inventory runs through three separate procurement channels and most independents target the wrong one. Holyrood Park (650 acres) is owned and managed by Historic Environment Scotland (HES) — not the council — with separate procurement. Princes Street Gardens, the Meadows, Bruntsfield Links, Inverleith Park, Saughton Park and Lauriston Castle estate run through City of Edinburgh Council Parks framework. Royal Botanic Garden of Edinburgh handles its own arboricultural procurement directly through RBGE staff. We build separate B2B outreach packs for each: HES (with heritage and World Heritage Site management case studies, BS3998:2010 currency, ApCo); City of Edinburgh Council Parks (with FCBI047 dieback compliance and £10M PL minimum); RBGE (with specimen-tree management case studies and named-species expertise). Plus Scottish Forestry South Region for any Felling Licence-required work, Royal Forestry Society Scotland for the broader network, and Forestry and Land Scotland for adjacent woodland holdings. Edinburgh arb crews running this typically win 1–3 direct framework places per year that displace subcontract income.",
    },
    {
      q: "Can you help us compete with Capital Tree Care, Edinburgh Tree Surgeons and Bartlett on Murrayfield, Cramond, Morningside and New Town premium domestic work?",
      a: "EH4, EH10, EH9, EH13 and EH16 — Murrayfield, Cramond, Barnton, Colinton, Grange, Morningside, Merchiston, Bruntsfield — support £900–£3,500 mature-tree removal on Conservation Area, World Heritage Site and listed-building-adjacent properties. Edinburgh fees run roughly 25–40% above Glasgow because of the WHS and listed-building density. Capital Tree Care, Edinburgh Tree Surgeons and Bartlett command the heritage end. We rebuild around three things: (1) a Conservation Area and WHS case study library with named EH-postcode properties, named City of Edinburgh Council Conservation Officer sign-offs (with permission), and properly photographed before/during/after MEWP and climbing dismantles; (2) ARB Approved Contractor schema, BS3998:2010 and LOLER/PUWER 1998 currency surfaced across landing pages and quote PDFs; (3) B2B outreach to Rettie & Co, Savills Edinburgh, Knight Frank Edinburgh, Coulters, Warners, Lindsays, Murray Beith Murray and the major ESPC member firms where heritage tree work flows through repeat relationships, plus the historic estate management offices (Lauriston Castle, Hopetoun House, Newhailes, Dalmeny estate).",
    },
    {
      q: "How does the AI receptionist handle Festival-season storm callouts and short-let property manager enquiries?",
      a: "Edinburgh's Festival season (August Fringe, Royal Edinburgh Military Tattoo) pushes tourism volumes 3–5x baseline and creates atypical demand patterns. Storm or wind-event tree failures during Festival weeks generate disproportionate emergency callouts from short-let property managers (Edinburgh has the UK's highest density of Airbnb-equivalent short-let properties post-Festival licensing reform), hotel groups (Edinburgh Marriott, Sheraton Grand, Balmoral, Waldorf Astoria Caledonian), and the major Festival venue operators (Underbelly, Pleasance, Gilded Balloon, Assembly, Summerhall). The AI receptionist runs Festival-mode protocols from late July through early September: multilingual greeting capability (German, French, Italian, US English), venue-operator-aware booking flow with venue contact reference capture, short-let-property-manager-aware quoting with formal scope-of-works templates, Hogmanay and Tattoo-week capacity-aware scheduling. Storm-mode runs in parallel year-round with what3words location capture, photograph SMS-link and instant climber-text alerts. Power-line incidents are routed to 105 — never booked on SP Energy Networks conductors. Insurance-claim landing pages capture loss-adjuster references.",
    },
  ],
  approach:
    "For Edinburgh and Lothians tree surgeons and arborists, our 90-day playbook is: (1) build borough-stratified Google Business Profile and Local Service Ads across City of Edinburgh, Midlothian, East Lothian and West Lothian with EH-postcode targeting and Murrayfield/Cramond/Morningside premium positioning; (2) deploy AI 24/7 storm-mode receptionist with World-Heritage-Site-aware Conservation Area qualifying flow, Festival-mode multilingual capability July–September, what3words location capture and instant climber-text alerts; (3) build dedicated specialism landing pages for Lothians ash dieback, Holyrood Park / Princes Street Gardens / RBGE specialist tree work, Conservation Area heritage tree work (Old Town, New Town, Stockbridge, Bruntsfield, Grange, Morningside), Murrayfield/Cramond/Barnton prime estate work, and Festival-season emergency response; (4) launch structured B2B outreach to City of Edinburgh Council Planning and Parks, Historic Environment Scotland, Royal Botanic Garden Edinburgh, Edinburgh World Heritage Trust, Lothians council tree officers, Scottish Forestry South, Forestry and Land Scotland, NTS East portfolio (Newhailes, Hopetoun House partnership), the Edinburgh chartered surveyors (Rettie, Savills, Knight Frank, Coulters, Warners, Lindsays); and (5) drive Google review velocity with named-EH-postcode and specialism keywords for local-pack dominance against Capital Tree Care, Edinburgh Tree Surgeons, Bartlett and the aggregators.",
};
