import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "vet marketing Swansea",
    "Swansea veterinary practice SEO",
    "veterinary marketing agency Swansea",
    "Mumbles vet marketing",
    "Swansea bilingual Welsh-language veterinary marketing",
  ],
  secondaryKeywords: [
    "Mumbles Sketty premium vet SEO",
    "Gower Peninsula coastal vet marketing",
    "Swansea Welsh-language vet near me",
    "SA1 SA2 SA3 Swansea vet marketing",
    "Llanelli Carmarthen fringe rural vet",
    "Swansea coastal pet ownership marketing",
    "Swansea University Trinity Saint David student pet",
    "Swansea Bay City Deal workforce pet care",
  ],
  heroSubhead:
    "Swansea's veterinary market is structurally distinct from Cardiff 45 miles east — consult fees run £40-£52 (versus Cardiff's £48-£62), Welsh-language patient communication is materially relevant in pockets (around 11-13% of Swansea residents speak Welsh, with higher concentrations in specific catchments), and the Mumbles, Sketty and Gower Peninsula coastal pattern produces distinctive premium pet-ownership demographics. NHS Wales operates a different healthcare framework affecting GP-to-vet referral patterns, NRW (Natural Resources Wales) governs environmental compliance, and Swansea Bay City Deal (£1.3bn investment) is reshaping the regional workforce. Kerblabs builds Swansea-specific vet funnels capturing the Mumbles/Sketty/Gower premium tier, Welsh-language and bilingual patient communication where appropriate, and coastal pet-ownership patterns.",
  marketContext: [
    "Swansea's veterinary economics sit clearly below Cardiff's premium tier but with distinctive structural advantages. Consult fees across the bulk of Swansea (SA1, SA2, SA5, SA6) sit at £40-£52 — meaningfully below Cardiff's £48-£62 and broadly comparable to Newport — reflecting both lower household disposable income relative to Cardiff and a coastal-and-post-industrial economic mix. The Mumbles (SA3), Sketty, Newton, Caswell, Langland and the Gower Peninsula (SA3 broader) anchor a clearer premium catchment supporting consult fees of £45-£58, with strong second-home and retiree pet-ownership patterns, professional-class spend, and coastal pet-ownership characteristics (high incidence of larger active dogs reflecting Gower Coast Path and Three Cliffs Bay walking culture). The wider Swansea valley catchments (SA4, SA8, SA9 toward Llanelli, Pontardawe and the Swansea Valley) operate at lower fee tiers (£36-£46) reflecting more rural and post-industrial demographics. Swansea Bay City Deal — a £1.3bn investment programme covering Swansea Bay, Pembrokeshire, Carmarthenshire and Neath Port Talbot — is gradually reshaping the regional workforce, with material implications for the longer-term premium-fee tier.",
    "The competitive set is moderately consolidated. CVS Group operates several Swansea-area sites, IVC Evidensia has multiple South Wales locations including Swansea practices, Vets4Pets (Mars Petcare) holds Pets at Home in-store presence in Swansea and Llanelli, and the independent tier — including Mumbles-area family practices, Sketty practices serving the premium catchment, plus the more volume-led Morriston, Townhill and Llansamlet practices — splits between coastal-premium work and high-volume civilian practice. Swansea University at Singleton Park and University of Wales Trinity Saint David at Mount Pleasant together produce around 22,000 students concentrated in SA2 and SA1 catchments, adding a smaller secondary student-pet cohort. South Wales's strong rural fringe — toward Llanelli, Carmarthen, Brecon Beacons and the Black Mountains — supports mixed-caseload practices with credible equine, smallholder and farm work, with referral pathways toward Bristol Vet School (Langford) and the RVC for specialist work. NHS Wales operates a different healthcare framework than NHS England (with implications for related medical practitioner referral patterns), and Welsh-language patient communication is materially relevant — around 11-13% of Swansea residents speak Welsh, with substantially higher concentrations in specific catchments toward the Welsh-speaking heartlands of West Wales.",
    "The non-obvious lever in Swansea veterinary marketing is bilingual Welsh-language patient communication combined with coastal-pet-ownership positioning. Approximately 11-13% of Swansea residents identify as Welsh speakers per the most recent census, with materially higher concentrations in catchments toward the Gower Peninsula's English-speaking communities, the Welsh-speaking pockets around Pontardawe and the Swansea Valley, and the Welsh-language schools (Ysgol Gymraeg Bryn-y-Mor, Ysgol Lon Las) serving Welsh-medium education families. Practices that surface bilingual patient communication — landing pages with Welsh-language sections, reception staff capable of basic Welsh greetings, and patient-communication materials available in Welsh on request — capture disproportionate market share in the Welsh-speaking cohort and earn local-business goodwill that translates into review velocity and word-of-mouth referral. Combined with explicit coastal-pet-ownership positioning (Gower Coast Path, Three Cliffs Bay, Rhossili, Caswell Bay walking culture, paddleboarding-and-active-dog content for the Mumbles cohort), this differentiation works disproportionately well against corporate group sites that typically default to English-only generic positioning. NRW (Natural Resources Wales) governs environmental compliance for clinical-waste handling under different procedures than England's Environment Agency framework. Kerblabs aggregated client data across South Wales coastal catchments shows 52% of veterinary new-client enquiries arrive outside 9-5.",
  ],
  stats: [
    { value: "£40-£52", label: "typical consult fee across wider Swansea (SA1, SA2, SA5, SA6)" },
    { value: "£45-£58", label: "typical consult fee in Mumbles / Sketty / Gower Peninsula premium catchment" },
    { value: "11-13%", label: "Swansea residents identifying as Welsh speakers", source: "ONS 2021 Census" },
    { value: "£1.3bn", label: "Swansea Bay City Deal investment reshaping regional workforce", source: "Welsh Government" },
    { value: "22,000+", label: "Swansea University and UWTSD students adding secondary cohort", source: "HESA 2023" },
    { value: "52%", label: "of Swansea vet enquiries arrive outside 9-5", source: "Kerblabs aggregated client data" },
  ],
  painPoints: [
    {
      title: "Cardiff-imported playbooks misreading Swansea's distinct fee tier",
      body: "Marketing approaches imported from Cardiff assume £48-£62 consult fees and stronger pet insurance penetration. Swansea's actual fee tier (£40-£52 across SA1, SA2, SA5, SA6) and lower insurance baseline mean Cardiff messaging actively underperforms. We rebuild around Swansea-specific willingness-to-pay benchmarks, with separate premium-pocket positioning for Mumbles/Sketty/Gower rather than transplanted Cardiff premium messaging.",
    },
    {
      title: "Welsh-language patient communication completely ignored",
      body: "Approximately 11-13% of Swansea residents speak Welsh, with higher concentrations in specific catchments and the Welsh-medium education families. Most Swansea practices have entirely English-only patient communication, surrendering meaningful market share and local-business goodwill. We build bilingual landing-page sections, Welsh-language patient communication materials on request, and Welsh-greeting reception protocols that earn disproportionate review velocity and word-of-mouth referral.",
    },
    {
      title: "Mumbles / Sketty / Gower premium pocket under-marketed",
      body: "The SA3-anchored premium catchment supports £45-£58 consult fees, second-home retiree pet-ownership and active coastal-pet demographics, but most Swansea practices market a single flat campaign that under-prices the premium pocket. Postcode-stratified messaging with Mumbles, Sketty and Gower-specific landing pages preserves both segments without compromising either, and explicit coastal-pet-ownership content (Gower Coast Path, Three Cliffs Bay, Caswell Bay) earns disproportionate local-pack ranking against corporate group sites.",
    },
    {
      title: "Carmarthenshire and Pembrokeshire rural fringe equine adjacency under-marketed",
      body: "Swansea-fringe practices toward Llanelli, Carmarthen, Brecon Beacons and into Pembrokeshire support genuinely mixed small-animal, equine and smallholder farm caseloads. Without explicit positioning naming Welsh equine venues (Builth Wells, Royal Welsh Show, Pembrokeshire Hunt area, Carmarthenshire eventing venues), you lose premium acquisition to specialist West Wales equine practices that market more aggressively to the affluent rural fringe.",
    },
  ],
  faqs: [
    {
      q: "Is bilingual Welsh-language veterinary marketing actually worth building specific infrastructure for in Swansea?",
      a: "Yes — and the differentiation is meaningfully larger than the headline 11-13% Welsh-speaker statistic implies. Three structural factors matter. First, the Welsh-medium education family cohort (Ysgol Gymraeg Bryn-y-Mor, Ysgol Lon Las and the broader Welsh-medium school network) is concentrated in specific Swansea catchments and represents a clearly identifiable household segment that strongly prefers bilingual service providers across all sectors including veterinary. Second, the Welsh-speaking heartlands toward Carmarthenshire and the Swansea Valley produce disproportionate referral traffic when families recommend bilingual-capable practices to extended family. Third, NHS Wales and Welsh Government tendering frameworks formally encourage Welsh-language service provision, and businesses with Welsh-language-aware marketing earn local authority and Welsh-Government-aligned business goodwill that translates into review velocity, local press mentions and word-of-mouth referral. The marketing infrastructure required is modest: bilingual landing-page sections, Welsh-language patient communication materials on request (downloadable consent forms, vaccination reminders), Welsh-greeting reception protocols, and explicit Welsh-language capability surfaced on Google Business Profile. Swansea practices implementing this typically capture 15-25% higher review-density growth in named Welsh-medium catchments and meaningful local-pack ranking improvements.",
    },
    {
      q: "How do you actually market the Mumbles, Sketty and Gower Peninsula premium catchment against corporate group sites?",
      a: "Three differentiation levers consistently produce results. First, named-clinician E-E-A-T with RCVS numbers, Advanced Practitioner credentials, named referral relationships with Bristol Vet School (Langford) and the RVC, and case studies demonstrating capability beyond first-opinion work — Mumbles and Sketty professional households respond strongly to clinical-credentials transparency. Second, hyperlocal review velocity in named SA3 streets, beaches and landmarks (Mumbles Pier, Caswell Bay, Three Cliffs Bay, Rhossili, Langland Bay, Newton, Sketty Lane) — reviews mentioning specific local landmarks materially outrank corporate sites relying on 'Swansea' generic positioning. Third, coastal-pet-ownership content tuned to the actual demographic — Gower Coast Path walking content, paddleboarding-and-active-dog content, salt-water-pet-care content, beach-paw-injury content, sand-fly and grass-seed seasonal content. This positioning respects the actual lifestyle of the catchment and earns disproportionate organic ranking against corporate sites that default to generic 'pet care' content. Across our South Wales independent vet clients this combination has produced 30-50% new-client growth in SA3 year-on-year while corporate sister sites in the same catchment have stagnated.",
    },
    {
      q: "How does NHS Wales and the Welsh regulatory framework actually affect veterinary marketing in Swansea?",
      a: "Two distinct considerations matter. First, environmental compliance — NRW (Natural Resources Wales) governs clinical-waste licensing, controlled-waste handling and veterinary-related environmental regulations under different procedures than England's Environment Agency framework. Practices need to surface NRW-compliant waste-handling credentials accurately rather than English-Environment-Agency phrasing. Second, the NHS Wales framework affects the broader healthcare context — Welsh GPs and human-medical practitioners operate under NHS Wales rather than NHS England, with implications for occupational-health-led pet referral patterns (pet bereavement, allergy testing referrals, zoonotic-disease-related discussions). Welsh Government Animal Welfare Strategy and the Wales Animal Health and Welfare Framework Group also operate distinct policies (Welsh-specific dog-breeding regulations, the Wales-specific lucy's-law-equivalent provisions, and Welsh-Government-led wildlife-welfare initiatives) that the marketing should reflect rather than transplanting English regulatory phrasing. Swansea practices that get this right earn local-press citations and Welsh-Government-aligned business goodwill, while practices that import English regulatory phrasing wholesale routinely earn negative review feedback for tone-deaf positioning.",
    },
    {
      q: "What's the realistic catchment radius for a Swansea veterinary practice?",
      a: "Heavily dependent on positioning. Central Swansea practices (SA1, SA2) typically serve 2-3 mile catchments. SA3 Mumbles/Sketty/Gower premium-pocket practices serve 4-7 miles because clients reliably travel for named-clinician and coastal-specialist care. Wider Swansea practices (SA5, SA6, SA7) serve 3-5 miles. Swansea-fringe practices toward Llanelli, Carmarthen, Pontardawe and into the Swansea Valley serve 8-15 miles because the mixed-practice and equine-adjacency differentiation is the draw. We map your existing client postcodes into realistic catchment shapes and build paid-spend rules accordingly: heavy bidding inside the primary catchment, moderate in secondary, and only specialist-differentiation bidding wider. This typically reduces wasted paid spend 30-45% versus a flat 'Swansea'-targeted campaign.",
    },
  ],
  approach:
    "For Swansea independent vets, our 90-day playbook is: (1) classify your practice into one of the four Swansea catchment types (central SA1/SA2, SA3 Mumbles/Sketty/Gower premium, wider Swansea SA5/SA6/SA7 volume, or rural-fringe Carmarthenshire/Brecon Beacons) and tune all campaigns accordingly; (2) deploy AI receptionist plus missed-call text-back capturing the 52% of enquiries arriving outside 9-5; (3) build bilingual Welsh-language patient communication infrastructure with landing-page Welsh sections, downloadable Welsh-language patient materials and Welsh-greeting reception protocols; (4) build SA3-specific premium positioning with named-clinician E-E-A-T, Bristol Vet School (Langford) referral relationships and coastal-pet-ownership content; and (5) for fringe practices, build authentic mixed-caseload positioning naming Carmarthenshire, Pembrokeshire and Brecon Beacons livery yards plus Royal Welsh Show relevance.",
};
