import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "wedding photographer marketing Edinburgh",
    "Edinburgh wedding photography SEO",
    "Scottish Highland wedding photographer Edinburgh",
    "luxury wedding photographer Edinburgh marketing",
    "Edinburgh castle wedding photographer SEO",
  ],
  secondaryKeywords: [
    "Inveraray Castle wedding photographer Edinburgh",
    "Crathes Castle wedding photographer marketing",
    "Eilean Donan Castle wedding photographer day trip",
    "Royal Botanic Garden Edinburgh wedding photographer",
    "Signet Library wedding photographer Edinburgh",
    "Edinburgh festival period wedding photographer SEO",
    "Mansfield Traquair wedding photographer Edinburgh",
    "fine art Highland wedding photographer Edinburgh",
  ],
  heroSubhead:
    "Edinburgh anchors the UK's most distinct premium wedding-photography market — Scottish Highland day-trip work to Eilean Donan, Inveraray, Crathes and Glenfinnan, city-castle weddings at Edinburgh Castle, Mansfield Traquair and the Signet Library, festival-period August pricing premiums, and a fine-art tradition led by Lisa Devlin, John Johnston and Mirrorbox Photography that commands £3,000-£6,000 packages. Hitched and Bridebook dominate the SERP, 'wedding photographer Edinburgh' CPC sits at £5-£8, and Highland venue long-tail (Eilean Donan, Glencoe, Skye) is where independents win. Kerblabs builds Highland-aware, festival-period-tuned, venue-specific funnels for Edinburgh independent wedding photographers.",
  marketContext: [
    "Edinburgh's wedding photography market is shaped by three forces no other UK city replicates. First, Highland day-trip work: a meaningful share of Edinburgh-based photographers' bookings are weddings at Eilean Donan Castle (the Skye-bridge fortress), Inveraray Castle (Argyll), Crathes Castle (Aberdeenshire), Glenfinnan (Lochaber), Glencoe House and the Isle of Skye — each requiring 4-7 hours of driving, overnight stays, and gear-and-second-shooter logistics that triple a city-wedding's operational footprint. Couples paying £3,500-£6,000 for Highland coverage expect a photographer who has shot the venue before, knows the light at Eilean Donan in late August and at Glenfinnan in October, has working relationships with the venue coordinators, and doesn't get caught out by the road from Fort William to Mallaig. Second, the city-castle and historic-venue cluster: Edinburgh Castle (limited weddings, Royal Scots Dragoon Guards events), Mansfield Traquair (the Beleforte triptych frescoed venue), the Signet Library (Scotland's most photographed library wedding venue), Prestonfield House, Dundas Castle and the Royal Botanic Garden Edinburgh anchor £2,500-£5,000 city weddings. Third, festival-period pricing: August (Fringe, International Festival, Tattoo) drives accommodation-cost-driven premium pricing across hotels, venues and suppliers, and photographers who don't price the August premium correctly absorb a margin hit on every Festival-month wedding.",
    "The Edinburgh fine-art tradition is real and recognised. Lisa Devlin (originally Brighton-trained, now a Scotland-based industry voice running The Photography Farm education programme) has shaped a generation of Highland wedding photographers. John Johnston runs an editorial-fine-art studio that wins international awards. Mirrorbox Photography has carved a documentary-meets-fine-art positioning. Across Edinburgh and the Lothians another 80-120 working wedding photographers compete for roughly 6,000-8,000 weddings a year within 90 minutes' drive of the city, plus the Highland day-trip volume. Average Edinburgh city-wedding photography spend runs £2,000-£4,000 mid-market, £4,000-£6,000 premium with named-photographer brand recognition, and Highland day-trip work commands £4,000-£8,000 with logistics premium. The luxury tier — Cromlix, Glenapp Castle, Kinloch House, multi-day Highland castle weddings — clears £8,000-£15,000 with international destination clients booking 18-24 months ahead. Hitched.co.uk and Bridebook own the top of 'wedding photographer Edinburgh' organic search; the opening for independents is the Highland venue long-tail and the festival-period and elopement segments aggregators under-serve.",
    "Edinburgh Google Ads CPCs run £5-£8 on 'wedding photographer Edinburgh', £8-£14 on 'luxury wedding photographer Edinburgh', and £3-£6 on Highland venue long-tail. The festival-period August pricing question — and the related Hogmanay and Burns Night winter-wedding work — creates a seasonal pricing complexity that flat photographer pricing pages handle badly. Couples comparing photographers in February for an August Festival wedding are price-sensitive and shopping aggressively; couples enquiring in October for a December micro-elopement at Glenfinnan are time-pressured and value photographer specialism over price. Saturday shoot days mean every Sunday-morning enquiry from a couple who saw a friend's Saturday Edinburgh wedding goes to voicemail unless an AI receptionist is in place. Kerblabs builds 25-50 venue-and-Highland hyperlocal pages per Edinburgh wedding-photographer client, runs festival-period-aware pricing automation, integrates Pixieset or Pic-Time gallery delivery against Studio Ninja or Light Blue (Light Blue has unusually strong Scottish independent market share), and orchestrates the 12-18 month booking horizon against a deposit-and-staged-payment cash flow structure.",
  ],
  stats: [
    { value: "6,000-8,000/yr", label: "weddings within 90 minutes of Edinburgh plus Highland day-trip volume" },
    { value: "£5-£8", label: "Google Ads CPC for 'wedding photographer Edinburgh' 2024-2025" },
    { value: "£4,000-£8,000", label: "Highland day-trip wedding photography package range with logistics premium" },
    { value: "£8,000-£15,000", label: "luxury Highland castle (Cromlix, Glenapp, Kinloch) photography range" },
    { value: "August", label: "Fringe / International Festival / Tattoo period drives 30-50% supplier premium" },
    { value: "4-7 hrs", label: "typical Highland venue drive time requiring overnight + second shooter logistics" },
  ],
  painPoints: [
    {
      title: "Highland venue logistics break sole-trader photographer schedules without proper second-shooter and overnight planning",
      body: "An Edinburgh-based photographer accepting an Eilean Donan wedding doesn't shoot it as a Saturday day-trip — it requires a Friday drive to Mallaig or Plockton, an overnight stay, a Saturday wedding shoot from morning prep to evening reception, and a Sunday return drive. Pricing this as a city wedding plus mileage absorbs £400-£800 of true operational cost. We build Highland-tier pricing pages with transparent travel and accommodation supplements, second-shooter availability automation, and venue-specific logistics walkthroughs that justify the premium and convert serious enquiries.",
    },
    {
      title: "August Festival period pricing absorbs margin if not structured against accommodation and supplier surge",
      body: "Edinburgh accommodation costs run 2-4x normal during Fringe, International Festival and Military Tattoo. Photographers shooting August weddings need to either price the premium explicitly (transparent 'August Festival rate') or absorb the cost. Couples comparing photographers in February for an August wedding need to see the pricing logic upfront or they'll churn to a competitor with hidden discounts. We build seasonal-pricing-aware quote and contract automation that surfaces Festival pricing without breaking the conversion flow.",
    },
    {
      title: "Hitched, Bridebook and Confetti dominate 'wedding photographer Edinburgh' generic search",
      body: "Aggregator pages own positions 1-5 for the head term across Edinburgh, Lothians and Borders. Independent photographers ranking on page two get a fraction of the volume. The opening is venue-and-Highland long-tail — 'wedding photographer Eilean Donan', 'fine art wedding photographer Mansfield Traquair', 'elopement photographer Glenfinnan' — where conversion runs 5-10x and aggregator pages cannot match portfolio specificity. We build 25-50 of these per Edinburgh photographer client.",
    },
    {
      title: "Saturday shoot days plus Sunday Highland-return travel mean enquiry calls leak for 36-48 hours",
      body: "An Edinburgh photographer shooting a Saturday Highland wedding is unreachable from Friday evening to Sunday afternoon. A couple enquiring on Saturday morning after seeing a friend's wedding the previous weekend gets voicemail, and by Monday they've enquired with three other photographers and chosen one. AI receptionist with portfolio-aware qualifying captures the enquiry, books a Tuesday consultation slot and prevents the 36-48-hour Highland-trip leakage that kills sole-trader booking rates.",
    },
  ],
  faqs: [
    {
      q: "How do you handle Highland venue work (Eilean Donan, Inveraray, Glenfinnan, Skye) versus Edinburgh city venues for a single photographer's marketing?",
      a: "We build two parallel funnels rather than one blended campaign. The Highland funnel emphasises specific venue experience (Eilean Donan, Inveraray, Crathes, Glenfinnan, Cromlix, Glenapp), demonstrable knowledge of Highland light and weather, transparent travel-and-accommodation supplement structure, second-shooter availability for multi-day castle weddings, and case studies showing real Highland weddings at scale. The city funnel emphasises Edinburgh and Lothians venue experience (Mansfield Traquair, Signet Library, Royal Botanic Garden, Prestonfield House, Dundas Castle), faster delivery turnaround, engagement-shoot offer in named Edinburgh locations (Calton Hill, Dean Village, Stockbridge), and Festival-period August pricing transparency. Many Edinburgh photographers want both segments, and the wrong move is to bury the Highland positioning in a single 'Scottish weddings' page. The right move is two distinct landing-page clusters with cross-linked navigation so the Mayfair couple booking Cromlix and the Hackney couple booking Mansfield Traquair both feel served.",
    },
    {
      q: "How do you handle August Festival pricing without losing couples to competitors who discount?",
      a: "Three things. First, we build a transparent seasonal-pricing page that explicitly states Festival-period (1-31 August) supplements applied to both photography and any second-shooter arrangement, with a brief explanation of accommodation and supplier surge — couples respect honest pricing logic and lose patience with hidden surcharges that emerge late in the process. Second, we offshore the comparison battle by emphasising what Festival-period photographers offer that discounters can't: actual Festival-period venue experience (the light at Mansfield Traquair on 12 August is not the light on 12 February), proven second-shooter availability against the supplier-shortage backdrop, and gallery delivery turnaround that doesn't slip when the photographer's diary is full. Third, we build a non-Festival shoulder-season offer (April-May, late September-October) that captures price-sensitive couples without dragging Festival-period pricing down, often paired with engagement-shoot bundles and weekday-wedding incentives.",
    },
    {
      q: "Can independent Edinburgh wedding photographers realistically beat Lisa Devlin, John Johnston and Mirrorbox for premium fine-art bookings?",
      a: "Not on direct brand-recognition battlegrounds — Lisa Devlin's industry profile from The Photography Farm and a fifteen-year body of award-winning Highland work is structurally hard to displace, and John Johnston and Mirrorbox sit in similar positions. But premium fine-art bookings in Edinburgh are not a winner-takes-all market. The opening for emerging or mid-career independents is in three places. First, distinct stylistic positioning that's not directly competing with the established names — dark-and-moody (Adrian Wood-influenced UK lineage), traditional-meets-editorial, or pure documentary in a market where fine-art currently dominates. Second, deeper Highland-venue specialism — shooting the same five venues thirty times each, building venue-specific portfolio pages, and being the named expert for Eilean Donan or Glenfinnan rather than a generalist. Third, intercultural and elopement specialism — Edinburgh-based same-sex weddings, intercultural ceremonies, and small-group elopements at hard-to-reach Highland locations are growing segments where the established names don't compete as hard. We build positioning, portfolio architecture and SEO around whichever angle matches the photographer's actual style.",
    },
    {
      q: "How do bridal shows like The Scottish Wedding Show at SECC Glasgow and The Royal Highland Centre Edinburgh shows convert for Edinburgh photographers?",
      a: "The Scottish Wedding Show at SEC Glasgow (formerly SECC) is the largest Scottish bridal-show event and pulls couples from across the central belt, Highlands and Borders — an Edinburgh photographer can absolutely justify the stand cost if the funnel is built right. We deploy a UTM-tagged QR code on the stand linking to a Scotland-specific landing page, a post-show SMS sequence within 48 hours referencing the show and offering a £250-£500 engagement shoot in Edinburgh or a Highland location, and a CRM-tagged stage progression in Studio Ninja or Light Blue that tracks show-attributable bookings six to twelve months out. Smaller Edinburgh-region shows at The Royal Highland Centre, Dundas Castle open days and venue-specific Mansfield Traquair and Signet Library showcases tend to convert at higher rates per attendee but lower volume — couples at venue-specific shows have already chosen the venue and are actively shortlisting suppliers. Tracked end-to-end this typically lifts bridal-show conversion from 8-15% to 25-40% and identifies within two seasons which Scottish shows pay back for your specific style.",
    },
  ],
  approach:
    "For Edinburgh independent wedding photographers, our 90-day playbook is: (1) split your funnel into Highland day-trip, Edinburgh city-venue, Festival-period August and elopement clusters with distinct landing pages, pricing transparency and engagement-shoot offers per cluster; (2) deploy AI receptionist with Saturday-and-Highland-trip enquiry capture so the 36-48-hour weekend window doesn't leak bookings; (3) build out 25-50 venue-and-Highland hyperlocal pages (Eilean Donan, Inveraray, Glenfinnan, Crathes, Mansfield Traquair, Signet Library, Royal Botanic Garden) with full logistics walkthroughs and real-wedding case studies; (4) integrate Studio Ninja or Light Blue with Pixieset or Pic-Time gallery delivery and automate the engagement-shoot-to-wedding conversion sequence; and (5) structure transparent Festival-period and seasonal pricing automation that protects margin without torching conversion.",
};
