import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "wedding photographer marketing Stoke-on-Trent",
    "Stoke-on-Trent wedding photography SEO",
    "Trentham Estate wedding photographer Stoke",
    "budget wedding photographer Staffordshire Stoke marketing",
    "six towns wedding photographer Stoke SEO",
  ],
  secondaryKeywords: [
    "Trentham Estate wedding photographer Stoke",
    "Doxey Park wedding photographer Stafford",
    "Heath House wedding photographer Tean",
    "Sandon Hall wedding photographer Stafford",
    "Hanley Burslem Tunstall wedding photographer Stoke",
    "Newcastle-under-Lyme wedding photographer Stoke",
    "Bet365 employee wedding photographer Stoke",
    "Staffordshire affordable wedding photographer Stoke",
  ],
  heroSubhead:
    "Stoke-on-Trent anchors a £1,200-£2,500 budget-tier Staffordshire wedding photography market shaped by the city's six federated towns (Tunstall, Burslem, Hanley, Stoke, Fenton, Longton) — the scattered six-towns geography means smaller photographer service-areas, hyper-local Burslem-versus-Longton catchment fragmentation, and disciplined cost-per-lead marketing that fits ST1-ST11 economics. Trentham Estate, Doxey Park, Heath House and Sandon Hall anchor venues; Newcastle-under-Lyme adds a £2,000-£3,500 mid-premium tier. Hitched, Bridebook and Guides for Brides aggregator pages dominate generic Stoke SERPs at £2-£4 CPC (among the lowest in England). Kerblabs builds six-towns-aware budget-tier funnels for Stoke independent wedding photographers.",
  marketContext: [
    "Stoke-on-Trent's wedding photography market is structured uniquely by the city's six federated towns geography — Tunstall, Burslem, Hanley, Stoke, Fenton and Longton were merged in 1910 and have stubbornly retained their own identities ever since, with each town's high-street independent customer base behaving as a distinct wedding-photography catchment rather than rolling up into a single 'Stoke' market. The practical consequence for Stoke wedding photographers is that the city's effective service-area pattern fragments meaningfully: a Burslem-resident photographer's couples rarely book through a Longton-resident competitor and vice versa, and the genuine cross-town wedding-photography brand recognition runs at city-rather-than-town level only for the larger established Stoke photography studios. The economic context reinforces the fragmentation: Stoke's average house prices around £155k make it among the most affordable English cities, average earnings sit a notch below the UK mean, and the typical wedding photography package sits at £1,200-£2,500 — meaningfully below the Manchester or Birmingham equivalent and well below the Cheshire premium-tier that sits just north across the M6.",
    "Stoke venues span three tiers across a wider Staffordshire catchment. The Trentham Estate (the regenerated Capability-Brown-landscaped Italian-Gardens estate at Trent Vale just south of the city, with the Trentham Gardens, Trentham Monkey Forest, the Trentham Estate Italian Garden ceremony space and the marquee-and-orangery reception options) anchors £2,000-£3,500 mid-premium photography work and is the single most-booked Stoke-area venue. Doxey Park (the Stafford-area renovated industrial-conversion venue), Heath House (the Tean Georgian country-house with strong owner-led-events positioning), Sandon Hall (the Earl of Harrowby's family estate near Stafford), Hoar Cross Hall (the Staffordshire spa-and-country-house resort), and Weston Hall (the Weston-on-Trent restored country-house) anchor £2,500-£4,500 premium-tier work with strong Newcastle-under-Lyme and Cheshire-edge crossover demand. The mainstream Stoke wedding market sits at £1,200-£2,500 across the Hanley, Burslem, Tunstall and Longton venue cluster including the Best Western Moat House, the Quality Hotel and the established town-hall and community-venue circuit. Roughly 5,000-7,000 weddings happen within 45 minutes' drive of Stoke each year including the Newcastle-under-Lyme, Stafford, Stone, Crewe and northern-Staffordshire-moorlands catchments.",
    "Stoke Google Ads CPCs run £2-£4 for 'wedding photographer Stoke' (among the lowest in England), £3-£5 for 'wedding photographer Trentham Estate' or 'luxury wedding photographer Staffordshire', and £2-£3 for venue-specific long-tail. Hitched.co.uk, Bridebook and Guides for Brides own SERP positions 1-5 on the head term, with the Trentham Estate preferred-supplier-listings page and the Sentinel Stoke Wedding Awards listings competing on paid. The opening for independents is the six-towns-and-venue long-tail: 'wedding photographer Burslem', 'wedding photographer Hanley', 'wedding photographer Trentham Estate', 'wedding photographer Newcastle-under-Lyme', 'wedding photographer Doxey Park', 'wedding photographer Heath House Tean', 'wedding photographer Sandon Hall'. The Bet365 Etruria HQ workforce (5,000+ staff) generates a small but distinctive £2,500-£4,000 mid-premium photography segment as Bet365 senior-staff and engineering-professional couples increasingly invest in named-photographer brand recognition. Saturday shoot days plus the budget-tier cost-per-lead pressure mean disciplined campaign design matters more in Stoke than in higher-priced markets — every pound of wasted spend disproportionately damages the photographer's margin. Kerblabs builds 20-35 venue-and-six-towns hyperlocal pages per Stoke photographer client, runs AI receptionist enquiry capture, integrates Studio Ninja or Tave with Pic-Time gallery delivery, and orchestrates the budget-tier pay-day-cycle and Bet365-shift-aware enquiry-capture pattern.",
  ],
  stats: [
    { value: "5,000-7,000/yr", label: "weddings within 45 minutes of Stoke including Newcastle-under-Lyme, Stafford, Stone, Crewe" },
    { value: "£2-£4", label: "Google Ads CPC for 'wedding photographer Stoke' 2024-2025 — among lowest in England" },
    { value: "£1,200-£2,500", label: "typical Stoke budget-tier wedding photography fee range" },
    { value: "£2,500-£4,500", label: "Trentham Estate, Heath House and Sandon Hall premium-tier package range" },
    { value: "Six federated towns", label: "Tunstall, Burslem, Hanley, Stoke, Fenton, Longton — fragmented service-area pattern" },
    { value: "5,000+", label: "Bet365 Etruria HQ staff driving small £2,500-£4,000 mid-premium photography segment" },
  ],
  painPoints: [
    {
      title: "Six-towns scattered geography means service-areas fragment and cross-town brand recognition is hard to build",
      body: "Hanley, Burslem, Tunstall, Stoke, Fenton and Longton each have their own high streets and customer bases, and a Burslem-resident photographer's couples rarely book through a Longton-resident competitor and vice versa. Generic 'Stoke-on-Trent wedding photographer' campaigns waste a meaningful share of every pound because they don't recognise the town-level catchment fragmentation. We set up separate landing pages, ad groups and Google Business Profile signals per town a client serves, which routinely cuts cost-per-lead by 25-40% versus a single 'Stoke' campaign.",
    },
    {
      title: "Budget-tier £1,200-£2,500 average package size means every wasted ad pound disproportionately damages margins",
      body: "Stoke wedding photography sits at £1,200-£2,500 typical packages — meaningfully below Manchester or Birmingham — so the cost-per-lead efficiency demands are tighter than higher-priced markets. A £200 cost-per-booked-enquiry that's tolerable in Cheshire is genuinely problematic in Stoke. We build hyper-disciplined Google Ads campaigns at the ST-postcode level, exact-and-phrase-match only on commercial intent, six-towns-specific creative variants, and Meta lead forms tuned to the Stoke audience pay-day cycle that converts at 30-45% lower CPL than flat city campaigns.",
    },
    {
      title: "Hitched, Bridebook and Guides for Brides own positions 1-5 for 'wedding photographer Stoke'",
      body: "Aggregator pages own the head term across Stoke, Newcastle-under-Lyme and Staffordshire. Independent photographers ranking on page two get a fraction of the volume. The opening is the six-towns-and-venue long-tail — 'wedding photographer Burslem', 'wedding photographer Hanley', 'wedding photographer Trentham Estate', 'wedding photographer Heath House Tean', 'wedding photographer Sandon Hall' — where conversion runs 4-6x and aggregator pages cannot match a portfolio-rich town-and-venue page for E-E-A-T or relevance.",
    },
    {
      title: "Trentham Estate preferred-supplier listing gatekeeps the £2,500-£4,500 mid-premium tier",
      body: "Trentham Estate operates a preferred-supplier-listings programme that gatekeeps the bulk of its £2,500-£4,500 wedding photography work. Photographers without Trentham Estate preferred-supplier status structurally cannot win the segment at scale. Where appropriate we build the trust scaffolding — Trentham-specific portfolio depth, named planner collaboration content, multiple completed-wedding case studies and review velocity — that earns preferred-supplier consideration over 12-24 months.",
    },
  ],
  faqs: [
    {
      q: "Why do the six towns matter for wedding photography marketing? Can't I just target 'Stoke'?",
      a: "You can, but you'll waste a meaningful share of every pound — and in a £1,200-£2,500 typical-package market that wasted spend disproportionately damages your margin. Hanley, Burslem, Tunstall, Stoke, Fenton and Longton each have their own high streets, their own demographic skews and — critically for wedding photography — their own perceived competitive set. A Burslem-resident couple rarely browses Longton-photographer Instagram feeds, an Endon couple's catchment looks completely different from a Tunstall couple's, and Newcastle-under-Lyme couples often consider themselves a separate Cheshire-edge market entirely. We set up separate landing pages, ad groups and Google Business Profile service-area signals per town a Stoke wedding photographer client serves, which routinely cuts cost-per-lead by 25-40% versus a single 'Stoke-on-Trent wedding photographer' campaign. The six-towns geography is unusual but it absolutely shapes wedding-photography enquiry behaviour, and the photographers who recognise it materially out-perform those who flatten the city into one campaign.",
    },
    {
      q: "How do you handle the £1,200-£2,500 budget-tier pricing pressure without damaging the photographer's margin?",
      a: "Three things. First, we run hyper-disciplined Google Ads campaigns at the ST-postcode level (ST1, ST3, ST4, ST5, ST6, ST7 separately rather than a flat 'Stoke' campaign), exact-and-phrase-match only on commercial intent, negative-keyword lists tuned to filter low-intent students and out-of-area researchers, and bid adjustments by drive-time rather than radius — typically cutting cost-per-booked-enquiry by 30-45% versus broad-match flat campaigns. Second, we build the £2,500-£4,500 Trentham Estate, Heath House, Sandon Hall and Hoar Cross Hall premium-tier funnel as a separate parallel campaign because the buyer behaviour is meaningfully different and the budget-tier pricing should not contaminate the premium-tier conversion path. Third, we run a small but distinct Bet365-Etruria £2,500-£4,000 mid-premium segment campaign targeting the Etruria-postcode catchment with engineering-and-tech-employer creative recognising the higher-disposable-income Bet365 senior-staff segment. This three-funnel stratification protects the photographer's margin in the budget tier while capturing the premium-tier and Bet365-segment opportunity that flat Stoke campaigns miss entirely.",
    },
    {
      q: "How do you earn Trentham Estate preferred-supplier status?",
      a: "Slowly and through demonstrable consistency. Trentham Estate operates a formal preferred-supplier-listings programme with selective entry criteria, and we build the 12-24 month trust scaffolding rather than treating it as a one-off pitch. Layer one is venue-specific portfolio depth — shooting Trentham Estate five-to-ten times in non-preferred capacity (couples who book the venue and bring their own photographer) and building venue-specific portfolio pages with the depth aggregator-listing supplier pages cannot match. Layer two is named-planner collaboration content — the Trentham Estate wedding-coordinator team and the Trentham Gardens events-management team need to have worked with the photographer before preferred-supplier consideration is meaningful. Layer three is review velocity above 4.8 stars from completed Trentham-specific weddings with explicit venue references in the review text. Layer four is supplier-network credentials with named Staffordshire florists, planners and venue-coordinator endorsements. We build the architecture, the photographer builds the body of work over 12-24 months, and the preferred-supplier listing follows. The same approach applies to Heath House, Sandon Hall and Hoar Cross Hall.",
    },
    {
      q: "How do you handle the Newcastle-under-Lyme £2,000-£3,500 mid-premium tier and the Cheshire-edge crossover?",
      a: "Newcastle-under-Lyme is technically a separate borough but operationally part of the Stoke conurbation with a distinct mid-premium wedding-photography customer base — older, higher-spending demographic, Keele University-resident academic households, and significant Cheshire-edge crossover demand from couples who could plausibly book Cheshire venues but choose Newcastle-area Heath House, Sandon Hall or Trentham. We build a dedicated Newcastle-under-Lyme wedding photographer landing page with mid-premium positioning (rather than budget-tier flagging), Cheshire-edge venue crossover content (Heath House, Sandon Hall, Hoar Cross Hall, Weston Hall), Keele University and named-Newcastle-supplier-network references, and engagement-shoot offers in named Newcastle locations (Brampton Park, Lyme Valley, Whitmore Hall). Google Ads tightly geo-fenced to ST5 with exact-match campaigns on Newcastle-specific terms. This typically lifts the £2,000-£3,500 Newcastle-segment booking velocity meaningfully versus rolling Newcastle into a flat Stoke campaign.",
    },
  ],
  approach:
    "For Stoke-on-Trent independent wedding photographers, our 90-day playbook is: (1) split your funnel into £1,200-£2,500 budget-tier six-towns mainstream cluster (with separate landing pages and ad groups for Hanley, Burslem, Tunstall, Stoke, Fenton, Longton catchments), £2,500-£4,500 Trentham Estate, Heath House, Sandon Hall and Hoar Cross Hall premium-tier cluster, £2,000-£3,500 Newcastle-under-Lyme mid-premium and Cheshire-edge crossover cluster, and £2,500-£4,000 Bet365-Etruria engineering-professional segment with distinct landing pages per cluster; (2) deploy AI receptionist plus weekend enquiry capture with budget-tier-aware qualifying so the £1,200-£2,500 mainstream segment converts efficiently; (3) build out 20-35 venue-and-six-towns hyperlocal pages with named-planner collaboration content, supplier-network credentials and 4.8-star review velocity targeting Trentham Estate, Heath House and Sandon Hall preferred-supplier-listings consideration over 12-24 months; (4) integrate Studio Ninja or Tave with Pic-Time gallery delivery and structure transparent budget-tier deposit-and-staged-payment terms calibrated to the Stoke pay-day cycle; and (5) run hyper-disciplined Google Ads tightly geo-fenced to ST1, ST3, ST4, ST5, ST6 and ST7 postcodes separately with exact-and-phrase-match only on commercial intent, cutting cost-per-lead by 30-45% versus broad-match flat Stoke campaigns.",
};
