import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "wedding photographer marketing Southampton",
    "Southampton wedding photography SEO",
    "New Forest wedding photographer Southampton crossover",
    "Highcliffe Castle wedding photographer Southampton",
    "Solent cruise wedding photographer Southampton SEO",
  ],
  secondaryKeywords: [
    "Highcliffe Castle wedding photographer",
    "New Forest wedding photographer Southampton",
    "Rhinefield House wedding photographer New Forest",
    "Beaulieu Palace House wedding photographer Southampton",
    "Ocean Village wedding photographer Southampton",
    "Carnival UK Cunard cruise wedding photographer Southampton",
    "Isle of Wight wedding photographer Southampton crossover",
    "destination cruise wedding photographer Southampton port",
  ],
  heroSubhead:
    "Southampton anchors a £1,800-£3,500 typical-package south-coast wedding photography market with two distinctive crossover segments: New Forest destination weddings (Rhinefield House, Beaulieu Palace House, Lime Wood Hotel, Careys Manor) commanding £2,500-£5,000, and the Highcliffe Castle premium-tier coastal wedding cluster on the Christchurch-Bournemouth fringe at £3,000-£5,500. The cruise-industry destination-wedding niche — Carnival UK and Cunard couples sailing from Southampton port — adds a small but distinctive premium segment. Hitched, Bridebook and Guides for Brides aggregator dominance is universal but the New Forest and Solent venue-specific long-tail at £3-£5 CPC converts 4-6x. Kerblabs builds New-Forest-aware funnels for Southampton independent wedding photographers.",
  marketContext: [
    "Southampton's wedding photography market is shaped uniquely by two crossover segments that sit outside the standard city wedding-economy pattern. The first is New Forest destination weddings: a meaningful share of Southampton-based photographers' bookings are weddings at Rhinefield House Hotel (the New Forest Tudor-style country-house at Brockenhurst), Beaulieu Palace House (the Montagu-family ancestral home with the National Motor Museum on site), Lime Wood Hotel (the Lyndhurst luxury country-house resort with Hartnett Holder & Co fine-dining), Careys Manor (the Brockenhurst spa-hotel), Chewton Glen (the New Milton five-star hotel just inside the New Forest national park boundary), Vinegar Hill Pottery (the Milford-on-Sea creative-quarter venue) and Burley Manor (the New Forest contemporary country-hotel). New Forest destination weddings command £2,500-£5,000 photography work with the Lime Wood and Chewton Glen tier supporting £4,000-£7,000 packages. The second is the Highcliffe Castle premium-coastal cluster on the Christchurch-Bournemouth fringe — Highcliffe Castle is the Robert Smirke neo-Gothic mansion overlooking Christchurch Bay and operates one of the south coast's most-photographed wedding venues, anchoring £3,000-£5,500 photography work with a strong destination-wedding draw from London couples seeking south-coast venues with Solent-adjacent positioning.",
    "The third distinctive Southampton segment is the cruise-industry destination wedding niche. Southampton is the UK's busiest cruise port with more than 2 million passengers passing through Mayflower and City Cruise Terminals in 2023, Carnival UK has its UK headquarters at Carnival House on Southampton's Centenary Quay, Cunard operates from Southampton, and the cruise-and-shipping professional workforce (Carnival senior staff, ship captains and officers, port-services management) generates a small but distinctive £3,000-£6,000 destination-cruise-wedding-photographer niche where couples sail from Southampton and want shore-side ceremony coverage at Ocean Village or the Mayflower terminal area before boarding, plus a smaller cruise-themed wedding-package segment with cruise-line preferred-supplier relationships. Roughly 8,000-10,000 weddings happen within 45 minutes' drive of Southampton each year including the New Forest, Hampshire Downs, Eastleigh, Romsey, Fareham and Isle of Wight catchments. The mainstream Southampton wedding market sits at £1,800-£3,500 across the Ocean Village, Bitterne, Hedge End and city-centre venue cluster.",
    "Southampton Google Ads CPCs run £4-£7 for 'wedding photographer Southampton', £6-£10 for 'New Forest wedding photographer' or 'luxury wedding photographer Hampshire', and £3-£5 for venue-specific long-tail. Hitched.co.uk, Bridebook and Guides for Brides own SERP positions 1-5 on the head term, with the Lime Wood Hotel and Chewton Glen preferred-supplier pages and the New Forest wedding-magazine listings competing on paid. The opening for independents is the New-Forest-and-coastal long-tail: 'Rhinefield House wedding photographer', 'Beaulieu Palace House wedding photographer', 'Lime Wood wedding photographer New Forest', 'Highcliffe Castle wedding photographer', 'Chewton Glen wedding photographer', 'Ocean Village wedding photographer Southampton', 'Cunard cruise wedding photographer Southampton'. Saturday shoot days plus the New Forest day-trip distance pattern and the Isle of Wight crossing-time considerations mean weekend enquiry capture and Sunday-return scheduling matter. Kerblabs builds 25-45 venue-plus-New-Forest hyperlocal pages per Southampton photographer client, runs AI receptionist enquiry capture across the Saturday-Sunday weekend window, integrates Studio Ninja or Tave with Pic-Time gallery delivery, and orchestrates the cruise-industry preferred-supplier outreach where commercially relevant.",
  ],
  stats: [
    { value: "8,000-10,000/yr", label: "weddings within 45 minutes of Southampton including New Forest, Eastleigh, Isle of Wight" },
    { value: "£4-£7", label: "Google Ads CPC for 'wedding photographer Southampton' 2024-2025" },
    { value: "£1,800-£3,500", label: "typical Southampton mainstream wedding photography fee range" },
    { value: "£2,500-£5,000", label: "New Forest destination wedding photography package range" },
    { value: "£4,000-£7,000", label: "Lime Wood and Chewton Glen tier premium package range" },
    { value: "2.0m+", label: "annual cruise passengers through Southampton driving cruise-wedding niche (ABP Southampton)" },
  ],
  painPoints: [
    {
      title: "New Forest destination-wedding logistics break sole-trader photographer schedules without proper planning",
      body: "A Southampton-based photographer accepting a Rhinefield House, Lime Wood or Chewton Glen wedding doesn't shoot it as a city-Saturday day-trip — the New Forest national-park venues require careful prep-arrival timing accounting for the New Forest road network's seasonal pony-and-livestock crossings, gear-and-second-shooter logistics for multi-location ceremony-and-reception coverage, and frequent overnight-stay considerations for couples staying at the venue pre-ceremony. We build New-Forest-tier pricing pages with transparent travel-and-overnight supplements and venue-specific logistics walkthroughs.",
    },
    {
      title: "Highcliffe Castle and the Christchurch-Bournemouth fringe sit outside Southampton catchment perceptions",
      body: "Highcliffe Castle is the south-coast premium-coastal venue most frequently photographed at scale, but it sits 25 miles south-west of Southampton on the Christchurch-Bournemouth fringe and many Southampton-based photographers under-build for it because it falls outside the standard Southampton catchment perception. The reality is that Highcliffe Castle anchors £3,000-£5,500 destination-coastal-wedding photography with a strong London-couple draw, and Southampton-based photographers willing to operate the Highcliffe segment win meaningful £4,000-£5,500 bookings.",
    },
    {
      title: "Hitched, Bridebook and Guides for Brides own positions 1-5 for 'wedding photographer Southampton'",
      body: "Aggregator pages own the head term across Southampton, Hampshire and the Isle of Wight. Independent photographers ranking on page two get a fraction of the volume. The opening is the New-Forest-and-coastal long-tail — 'Rhinefield House wedding photographer', 'Beaulieu Palace House wedding photographer', 'Lime Wood wedding photographer', 'Highcliffe Castle wedding photographer', 'Chewton Glen wedding photographer' — where conversion runs 4-6x and aggregator pages cannot match a portfolio-rich venue page for E-E-A-T or relevance.",
    },
    {
      title: "Cruise-industry destination-wedding niche requires Carnival UK and Cunard preferred-supplier credentials",
      body: "Carnival UK and Cunard run preferred-supplier programmes for cruise-departure wedding-photography work and the £3,000-£6,000 destination-cruise-wedding niche structurally requires those preferred-supplier credentials to win at scale. Photographers without Carnival or Cunard preferred-supplier status under-compete in the segment. Where appropriate we build the trust scaffolding — Ocean Village and Mayflower-terminal portfolio depth, named cruise-coordinator references, completed cruise-departure wedding case studies — that earns preferred-supplier consideration.",
    },
  ],
  faqs: [
    {
      q: "How do you handle the New Forest destination-wedding segment versus the Southampton city-venue segment?",
      a: "We build two parallel funnels rather than one blended Southampton-and-Hampshire campaign. The New Forest funnel emphasises specific venue experience (Rhinefield House, Beaulieu Palace House, Lime Wood, Careys Manor, Chewton Glen, Burley Manor, Vinegar Hill Pottery), demonstrable knowledge of New Forest national-park road network and pony-crossing timing considerations, transparent travel-and-overnight supplement structure, second-shooter availability for multi-location ceremony-and-reception coverage, and case studies showing real New Forest weddings at scale. The Southampton city funnel emphasises Ocean Village, Highfield, Bitterne and Hedge End venue experience, faster delivery turnaround, engagement-shoot offer in named Southampton locations (Ocean Village marina, Mayflower Park, Royal Pier, the New Forest fringe at Beaulieu) and transparent £1,800-£3,500 mainstream pricing. Many Southampton photographers want both segments, and the wrong move is to bury the New Forest positioning in a single 'Hampshire weddings' page. The right move is two distinct landing-page clusters with cross-linked navigation. The Highcliffe Castle premium-coastal funnel runs separately as a third cluster with destination-coastal positioning targeting London-couple acquisition.",
    },
    {
      q: "How do you compete with the established Lime Wood, Chewton Glen and Rhinefield House preferred-supplier photographers?",
      a: "Slowly and through demonstrable consistency. Lime Wood, Chewton Glen, Rhinefield House and Beaulieu Palace House each operate formal preferred-supplier-listings programmes with selective entry criteria, and we build the 12-24 month trust scaffolding rather than treating it as a one-off pitch. Layer one is venue-specific portfolio depth — shooting Lime Wood, Chewton Glen or Rhinefield House five-to-ten times in non-preferred capacity (couples who book the venue and bring their own photographer) and building venue-specific portfolio pages with the depth aggregator-listing supplier pages cannot match. Layer two is named-planner collaboration content — the named Lime Wood wedding-experience team, the Chewton Glen events-management team and the Rhinefield House wedding-coordinator team all need to have worked with the photographer before preferred-supplier consideration is meaningful. Layer three is review velocity above 4.8 stars from completed venue-specific weddings with explicit venue references in the review text. Layer four is supplier-network credentials with named New Forest florists, planners and venue-coordinator endorsements. We build the architecture, the photographer builds the body of work over 12-24 months, and the preferred-supplier listings follow.",
    },
    {
      q: "How do you serve the Carnival UK and Cunard cruise-industry destination-wedding niche?",
      a: "We build a dedicated 'Southampton cruise wedding photographer' landing page with three layers of content rather than treating it as an afterthought. Layer one is Ocean Village and Mayflower-terminal portfolio depth — pre-boarding ceremony coverage at the Mayflower Cruise Terminal staterooms, Ocean Village marina ceremony locations, City Cruise Terminal port-side imagery and the Carnival House Centenary Quay backdrop options. Layer two is cruise-line preferred-supplier positioning — explicit acknowledgement of Carnival UK and Cunard preferred-supplier work where genuinely earned, named cruise-coordinator references, and case studies of completed cruise-departure weddings showing the pre-boarding-to-sailing-day photo flow. Layer three is the destination-cruise-wedding-package segment — recognition that some cruise couples want shore-side Southampton ceremony coverage plus shipboard captain-officiated ceremony documentation where the cruise line's onboard photography service does not extend, with specific positioning around Cunard's Queen Mary 2, Queen Victoria and Queen Elizabeth ship-departure work. The niche is small but the £3,000-£6,000 average ticket size and the durable Carnival-Cunard preferred-supplier referral pipeline make it worth building once.",
    },
    {
      q: "How do you handle the academic-calendar and cruise-seasonality dynamics that affect Southampton enquiry patterns?",
      a: "We treat them as two overlaid seasonal calendars that drive distinct enquiry-volume patterns. The University of Southampton and Solent University academic calendar concentrates 35,000+ students into Highfield, Portswood, Swaythling and the city centre with September arrival waves and January return spikes — but for wedding photography this is meaningfully less important than the cruise-and-tourism seasonal calendar. The cruise season runs concentrated April-October with more than 500 cruise calls a year through Mayflower Terminal, peak summer activity drives Ocean Village and city-centre footfall and visibility, and November-February is meaningfully quieter across the cruise-and-tourism segment. We schedule paid campaign budgets around the April-October cruise-season peak (where Ocean Village, Mayflower Park and Royal Pier engagement-shoot offers convert best), the May-September New Forest wedding peak (where Rhinefield, Lime Wood, Chewton Glen and Beaulieu engagement shoots align with venue-coordinator preferred-supplier showcases), and the November-February shoulder-season lull (where Highcliffe Castle winter-coastal positioning and indoor-venue editorial-documentary content carry the off-season). Tracked end-to-end this typically lifts Southampton-wide booking conversion by 25-40% versus a flat year-round campaign.",
    },
  ],
  approach:
    "For Southampton independent wedding photographers, our 90-day playbook is: (1) split your funnel into £2,500-£5,000 New Forest destination-wedding cluster (Rhinefield, Beaulieu, Lime Wood, Chewton Glen, Careys Manor, Burley Manor), £3,000-£5,500 Highcliffe Castle premium-coastal cluster, £3,000-£6,000 Carnival UK and Cunard cruise-industry destination-wedding niche, and £1,800-£3,500 Ocean Village and Bitterne mainstream Southampton city-venue cluster with distinct landing pages per cluster; (2) deploy AI receptionist plus weekend enquiry capture so the New Forest day-trip and Saturday-Sunday operational window doesn't leak bookings; (3) build out 25-45 venue-plus-New-Forest hyperlocal pages with named-planner collaboration content, supplier-network credentials and 4.8-star review velocity targeting Lime Wood, Chewton Glen, Rhinefield House, Highcliffe Castle and Beaulieu Palace House preferred-supplier-listings consideration over 12-24 months; (4) integrate Studio Ninja or Tave with Pic-Time gallery delivery and structure transparent New-Forest-tier and cruise-departure pricing automation; and (5) run Google Ads tightly geo-fenced to SO14, SO15, SO17, SO18, SO30 and the New Forest national park postcodes (SO40, SO41, SO42, SO43) with separate exact-match campaigns per venue and segment.",
};
