import type { RichComboContent } from "../types";

export const content: RichComboContent = {
  primaryKeywords: [
    "wedding photographer marketing Derby",
    "Derby wedding photography SEO",
    "Donington Park wedding photographer Derby",
    "Kedleston Hall wedding photographer marketing",
    "Derby engineering professional wedding photographer SEO",
  ],
  secondaryKeywords: [
    "Kedleston Hall wedding photographer Derby",
    "Donington Park wedding photographer Castle Donington",
    "Morley Hayes wedding photographer Derby",
    "Shottle Hall wedding photographer Derbyshire",
    "Derby Rolls-Royce wedding photographer Toyota employee",
    "Allestree Mickleover wedding photographer Derby",
    "Derbyshire county cricket wedding photographer",
    "Pride Park stadium wedding photographer Derby",
  ],
  heroSubhead:
    "Derby anchors a £1,500-£3,000 typical-package East Midlands wedding photography market shaped by an engineering-professional consumer base — Rolls-Royce Civil Aerospace's 14,000+ Sinfin and Raynesway staff, Toyota Burnaston employees, and Alstom Litchurch Lane train-manufacturing professionals book photography differently from Nottingham or Leicester couples. Donington Park, Kedleston Hall, Morley Hayes, Shottle Hall and the Derbyshire-Dales country-house cluster anchor venues; engagement-photo-research-heavy buyers expect detailed treatment-page content and named-photographer GDPR-aware enquiry flows. Hitched, Bridebook and Guides for Brides aggregator pages dominate generic Derby SERPs but the venue-specific long-tail at £4-£6 CPC converts 4-7x. Kerblabs builds engineering-professional-aware funnels for Derby independent wedding photographers.",
  marketContext: [
    "Derby's wedding photography market is shaped uniquely by the city's high-skill engineering-professional economy. Rolls-Royce Civil Aerospace headquarters more than 14,000 staff at Sinfin and Raynesway, Toyota Burnaston employs over 3,000 across the assembly plant and engine plant, Alstom Litchurch Lane runs the UK's only volume train-manufacturing facility with around 3,000 staff, and Pattonair, JCB Power Systems and the wider aerospace and rail tier-one supplier ecosystem add several thousand more high-earning STEM-graduate households. The practical consequence for Derby wedding photographers is a customer base that researches before it buys with unusual depth: couples will visit a photographer's portfolio site three or four times across two months before enquiring, will read every Google review, will scrutinise GDC-equivalent professional-credential references, and will line-item-compare quotes from three or four shortlisted photographers. Glossy hero shots and discount headlines under-perform here. What works is detailed venue-experience walkthroughs, named-photographer biographies emphasising technical credentials and equipment, before-and-after engagement-shoot galleries with venue context, and continuous review velocity — exactly the content patterns that aggregator pages structurally cannot deliver.",
    "Derby venues split across three tiers. The Derbyshire premium country-house cluster — Kedleston Hall (the Robert Adam Palladian masterpiece operated by the National Trust for ceremony work plus marquee receptions in the grounds), Shottle Hall (Ecclesbourne Valley Georgian country house), Morley Hayes (Allestree-edge golf-course-and-hotel resort), Catton Hall and Locko Park — anchor £2,500-£4,500 mid-premium photography work with the Kedleston ceremony-plus-marquee tier supporting £4,000-£6,000 packages. The Donington Park motorsport-circuit-and-conference-venue at Castle Donington just south of Derby is a distinctive £2,500-£4,500 segment with strong demand from motorsport-enthusiast couples and Toyota Burnaston engineering employees. The Pride Park Derby County stadium and Derbyshire County Cricket Club at the County Ground at Nottingham Road run a smaller corporate-led segment at £2,000-£3,500. Roughly 7,000-9,000 weddings happen within 60 minutes' drive of Derby each year including the Burton-on-Trent, Belper, Ashbourne and southern-Peak-District catchments.",
    "Derby Google Ads CPCs run £4-£6 for 'wedding photographer Derby', £6-£9 for 'luxury wedding photographer Derbyshire', and £3-£5 for venue-specific long-tail. Hitched.co.uk, Bridebook and Guides for Brides own SERP positions 1-5 on the head term, with the local Derby Telegraph wedding-listings page and the larger national photography brands competing on paid. The opening for independents is the venue-plus-engineering-professional long-tail: 'Kedleston Hall wedding photographer', 'Donington Park wedding photographer', 'Morley Hayes wedding photographer Allestree', 'Shottle Hall wedding photographer Derbyshire', 'Rolls-Royce employee wedding photographer Derby'. The Derby buyer's research-heavy decision pattern means landing pages need 1,500+ words of genuine venue and process content with embedded testimonials, before-and-after engagement-shoot galleries, line-item pricing transparency where commercially appropriate, and detailed FAQs answering the engineering-professional buyer's actual research questions. Saturday shoot days mean weekend enquiry capture matters — couples discovering you on a Saturday won't wait until Monday for a phoned-back response. Kerblabs builds 25-40 venue-and-cluster hyperlocal pages per Derby photographer client, integrates Studio Ninja or Tave with Pic-Time gallery delivery against the Derby engineering-professional research-cycle pattern, and runs AI receptionist enquiry capture across the Saturday-Sunday weekend window.",
  ],
  stats: [
    { value: "7,000-9,000/yr", label: "weddings within 60 minutes' drive of Derby including Burton, Belper, Ashbourne" },
    { value: "£4-£6", label: "Google Ads CPC for 'wedding photographer Derby' 2024-2025" },
    { value: "£1,500-£3,000", label: "typical Derby mainstream wedding photography fee range" },
    { value: "£4,000-£6,000", label: "Kedleston Hall and premium country-house tier package range" },
    { value: "14,000+", label: "Rolls-Royce Civil Aerospace Derby staff — research-heavy engineering-professional buyer base" },
    { value: "Donington Park / Kedleston Hall", label: "anchor Derby's premium and motorsport-led wedding venue clusters" },
  ],
  painPoints: [
    {
      title: "Engineering-professional buyer expectations break generic photography landing pages",
      body: "A Rolls-Royce, Toyota or Alstom engineer comparing wedding photographers will visit your site three or four times, scrutinise named-photographer credentials, read every Google review, and line-item-compare quotes. Generic 'about us' pages and discount-headline campaigns under-perform here by 30-50% versus content engineered for the research-heavy buyer. We build detailed venue-experience walkthroughs, named-photographer biographies with technical-credential emphasis, before-and-after engagement-shoot galleries and line-item pricing transparency that the Derby engineering-professional audience actually reads.",
    },
    {
      title: "Hitched, Bridebook and Guides for Brides own positions 1-5 for 'wedding photographer Derby'",
      body: "Aggregator pages own the head term across Derby and Derbyshire and independent photographers ranking on page two get a fraction of the volume. The opening is venue-plus-style long-tail — 'Kedleston Hall wedding photographer', 'Donington Park wedding photographer Castle Donington', 'Morley Hayes wedding photographer', 'Shottle Hall wedding photographer Derbyshire' — where conversion runs 4-7x and aggregator pages cannot match a portfolio-rich venue page for E-E-A-T or relevance. We build 25-40 of these per Derby photographer client.",
    },
    {
      title: "Saturday-Sunday weekend enquiry-capture window leaks bookings to whoever has reception cover",
      body: "Couples planning a £3,000-£5,000 Derby premium wedding don't leave voicemails — they ring the next photographer on the list. Sole-trader Derby photographers shooting Saturdays lose 30-45% of high-value enquiries to whoever has weekend cover. AI receptionist with portfolio-style qualifying handles Saturday and Sunday enquiries warmly, books Tuesday consultations and prevents £4,000+ Kedleston Hall and Morley Hayes bookings leaking to less-talented but more-available competitors.",
    },
    {
      title: "Donington Park motorsport-couple segment is under-served by Derby photographers without circuit experience",
      body: "Donington Park weddings attract motorsport-enthusiast couples and Toyota Burnaston engineering employees who want photographer expertise with the circuit, the National Motorsport Centre, the Donington Hall historic-house ceremony space and the paddock-and-pit-lane portrait possibilities. Generic country-house photographers without Donington-specific portfolio struggle to convert this segment. We build a dedicated 'Donington Park wedding photographer' landing page with circuit-specific portfolio depth, motorsport-couple positioning and named Donington wedding-coordinator references.",
    },
  ],
  faqs: [
    {
      q: "How does the Rolls-Royce, Toyota and Alstom engineering-professional buyer change my photography marketing?",
      a: "Significantly, and most Derby photographers under-build for it. Engineering, R&D and aerospace professionals at Rolls-Royce Sinfin, Toyota Burnaston and Alstom Litchurch Lane are among the most research-driven consumer audiences any UK photographer will sell to — they will visit your site three or four times before enquiring, read every Google review, scrutinise GDC-equivalent professional-photography credentials and Companies House records, and line-item-compare quotes carefully. Glossy hero shots and discount headlines under-perform here by 30-50% versus content built for the research-heavy buyer. What works is detailed treatment and process explanations (full venue logistics walkthroughs for Kedleston, Donington, Morley Hayes), named-photographer biographies with technical credentials and equipment specifications, before-and-after engagement-shoot galleries with venue context, line-item pricing transparency where commercially appropriate, detailed FAQ pages answering the engineering-professional buyer's actual research questions, and continuous review velocity tied to delivered weddings. We build the longer-form, more technical landing-page content that this audience actually reads, then run Google Ads tightly geo-fenced to DE1, DE3, DE21, DE22 and DE23 postcodes into it.",
    },
    {
      q: "Can independent Derby wedding photographers realistically beat the established regional names for Kedleston Hall and Donington Park premium bookings?",
      a: "Yes, on three specific battlegrounds. The Kedleston Hall and premium-country-house segment in Derbyshire is not a winner-takes-all market and the established regional names rarely shoot more than 15-25 Kedleston weddings a year between them. The opening for emerging or mid-career independents is in three places. First, distinct stylistic positioning that's not directly competing with the established documentary or fine-art incumbents — dark-and-moody, traditional-meets-editorial, or pure documentary in a market where fine-art currently dominates. Second, deeper venue specialism — shooting Kedleston, Shottle Hall, Morley Hayes and Catton Hall thirty times each rather than scattering across thirty venues, building venue-specific portfolio pages that rank and convert. Third, the engineering-professional couple segment specifically — building positioning around technical credentials, equipment-and-process transparency and the research-heavy content the Rolls-Royce, Toyota and Alstom audience actually reads, rather than generic 'romantic country-house' marketing. We build positioning, portfolio architecture and SEO around whichever angle matches the photographer's actual style.",
    },
    {
      q: "How do you handle the Donington Park motorsport-couple segment and the Toyota Burnaston engineering-employee niche?",
      a: "We build a dedicated Donington Park wedding-photographer landing page with three layers of content. Layer one is circuit-specific portfolio depth — the Donington Hall ceremony space, the National Motorsport Centre, the paddock-and-pit-lane portrait possibilities, the McLaren Suite reception, the historic Donington Collection backdrop options. Layer two is motorsport-couple positioning — explicit recognition that Donington weddings often attract motorsport-enthusiast couples who want the circuit-and-history references in their imagery rather than generic country-house romance, with named Donington wedding-coordinator references and supplier-collaboration content. Layer three is the Toyota Burnaston engineering-employee bridge segment — Burnaston is six miles from Castle Donington and Toyota engineers booking weddings frequently choose Donington for the motorsport-and-circuit affinity, so we run paid campaigns into the Toyota Burnaston staff catchment with creative that recognises the engineering-and-circuit overlap. Tracked end-to-end this typically captures the entire Donington-segment opportunity that Derby photographers without circuit-specific portfolio struggle to win.",
    },
    {
      q: "How do bridal shows at Pride Park, Derbyshire County Cricket Club and the regional venue open days convert for Derby photographers?",
      a: "Derby bridal shows split into three tiers we treat differently. Volume shows (Derbyshire Wedding Show at Pride Park Stadium, the Derbyshire County Cricket Club open days at the County Ground) attract mid-market couples and reward fast follow-up — UTM-tagged QR code on the stand linking to a Derby-specific landing page, post-show SMS within 48 hours offering a £200-£400 engagement shoot at a Derbyshire location (Carsington Water, Kedleston grounds, Shipley Country Park), automated nurture sequence into Studio Ninja or Tave with stage-tracked progression. Premium shows and venue-specific open days at Kedleston Hall, Shottle Hall, Morley Hayes and Catton Hall attract higher-spend couples who need a different conversion approach — slower, portfolio-led, planner-collaboration-emphasised, with consultation booked at the venue itself rather than chased afterwards. Donington Park motorsport-themed wedding showcases attract the engineering-professional and motorsport-enthusiast couple segment with much higher per-attendee conversion rates. Tracked end-to-end this typically lifts Derby bridal-show conversion from 8-15% to 25-40% and identifies within two seasons which two or three regional shows actually pay back for your specific style and venue tier.",
    },
  ],
  approach:
    "For Derby independent wedding photographers, our 90-day playbook is: (1) stratify your catchment into Kedleston-Shottle-Catton premium country-house cluster, Morley Hayes Allestree-edge mid-premium cluster, Donington Park motorsport-couple cluster, and £1,500-£2,500 Pride Park and mainstream Derby city-venue cluster with separate landing pages per cluster; (2) deploy AI receptionist plus weekend enquiry capture across the Saturday-Sunday window so engineering-professional couples don't churn to a competitor with weekend cover; (3) build out 25-40 venue-plus-engineering-professional hyperlocal pages with detailed logistics walkthroughs, named-photographer technical credentials, before-and-after engagement-shoot galleries and line-item pricing transparency that the Rolls-Royce, Toyota and Alstom research-heavy buyer actually reads; (4) integrate Studio Ninja or Tave with Pic-Time gallery delivery and automate the engagement-shoot-to-wedding conversion sequence calibrated to the Derby buyer's two-month research cycle; and (5) run Google Ads tightly geo-fenced to DE1, DE3, DE21, DE22 and DE23 postcodes with separate campaigns per venue tier and engineering-employer catchment.",
};
