import type { Industry } from "@/lib/seo-data";

export const industry: Industry = {
  slug: "tree-surgeons",
  name: "Tree Surgeons & Arborists",
  industrySingular: "tree surgeon / arborist",
  industryPlural: "tree surgeons and arborists",
  emoji: "🌳",
  pageTitle: "AI Marketing for UK Tree Surgeons & Arborists | Kerblabs",
  metaDescription:
    "Independent UK tree surgeons and arborists use Kerblabs to capture 24/7 storm callouts, win ash dieback removal work, qualify TPO and Conservation Area enquiries, build ARB Approved authority, and beat Bartlett, Beechwood and the lead-aggregators. From £347/mo.",
  h1: "AI Growth Systems for",
  h1Highlight: "UK Tree Surgeons & Arborists.",
  subhead:
    "Independent UK tree surgeons and arborists are working through the busiest decade in living memory — ash dieback is forcing the removal of an estimated 80%+ of UK ash trees through 2030, named winter storms (Eunice, Babet, Isha, Jocelyn, Henk, Kathleen) are stacking emergency-callout backlogs into spring, and council framework agreements are increasingly running through Veolia, Glendale and FCC Environment subcontractor panels rather than direct procurement. Meanwhile, your phones go to voicemail every time a climber is in canopy or a chipper is running, every TPO and Conservation Area enquiry needs hand-qualified guidance you can't legally give over the phone, and Bartlett Tree Experts, Beechwood Trees & Landscapes, Western Tree Services and the Pryor & Rickett Silviculture utility-line specialists are eating the high-value heritage and forestry work above you. Kerblabs gives independent ARB Approved Contractors and growing crews the AI receptionist, review engine, ARB-aware local SEO, ash dieback survey funnel and council-framework B2B systems to capture the demand and stop losing storm work to whoever answers first.",
  stats: [
    { value: "~700", label: "ARB Approved Contractors (Arboricultural Association flagship scheme)" },
    { value: "80%+", label: "of UK ash trees expected to die from ash dieback (Hymenoscyphus fraxineus) by 2030" },
    { value: "£4–£18", label: "Google Ads CPC range for 'tree surgeon near me' / 'emergency tree' 2024–2025" },
  ],
  problems: [
    {
      title: "Storm callouts go to whoever answers first — and you're 30ft up a willow",
      body: "Named winter storms have hit the UK in unprecedented density since Eunice in February 2022. When a homeowner has a sycamore on their conservatory at 7am the morning after Henk, they ring four numbers in fifteen minutes and book whoever picks up. With climbers in canopy, chippers running and groundsmen on stop saws, missed calls during peak storm windows are the single biggest revenue leak in the sector — and the firm that captures them owns the £80–£200 callout fee plus £60–£120 hourly follow-on plus the 12-month relationship for the rest of that garden's mature stock.",
    },
    {
      title: "Ash dieback removal is a once-in-a-generation opportunity you're under-marketed for",
      body: "Hymenoscyphus fraxineus has been spreading since 2012 and the Forestry Commission, AA and ICF now project 80%+ of UK ash trees will die. Council highways, parish councils, large estates, schools and private landowners are commissioning surveys and removals at unprecedented volume — but the work is going to firms with visible ARB Approved Contractor status, MEWP capability, properly photographed ash dieback case studies and clear council-framework eligibility. Most independents have generic websites that say 'tree felling' and miss the entire dieback search wave.",
    },
    {
      title: "TPO and Conservation Area enquiries waste a day per week without proper qualifying",
      body: "Roughly a third of incoming domestic enquiries involve trees protected by a Tree Preservation Order, in a Conservation Area (which triggers the 6-week notice rule for any tree over 7.5cm), or covered by a Felling Licence requirement. Without front-end qualifying, your surveyor drives to a quote that can't progress for 8 weeks, the customer vanishes during the council wait, and you've burnt half a tank of diesel and three hours of climbing time. You also can't legally give the homeowner planning advice — only signpost to the council — and untrained call handlers routinely cross that line.",
    },
    {
      title: "ARB Approved Contractor membership is invisible everywhere it matters",
      body: "ARB ApCo membership costs around £1,000+ a year and gates eligibility for council framework agreements, large-estate work and most insurance-claim instructions worth having. But the badge is buried on most members' About pages. The conservation officers, tree officers, chartered surveyors and adjusters who recommend specialists rarely see it on Google. Schema, GBP descriptions, landing-page H1s and review prompts all need to surface ApCo, BS3998:2010 compliance and LOLER/PUWER 1998 inspection currency to convert the work that actually pays.",
    },
    {
      title: "Checkatrade, Bark, MyBuilder and council-framework subcontracting eat 40%+ of margin",
      body: "Independents are paying £15–£40 per shared tree-surgeon lead via Checkatrade and MyBuilder (often sold to four firms simultaneously) or running 25–35% subcontract margins under Veolia, Glendale, FCC Environment and idverde framework wins. That's £2,000–£6,000 per van of monthly leakage with no client ownership. Without parallel direct acquisition (GBP category-stacking, Google LSA, ARB-aware borough SEO, B2B outreach to tree officers and chartered surveyors), the aggregator and prime-contractor squeeze never relents.",
    },
  ],
  recommendedPlan: "Autopilot",
  recommendedPrice: 347,
  roiNote:
    "A single mature-tree removal on a Conservation Area site or a 12-tree ash dieback survey routinely runs £3,000–£12,000. Recovering one missed storm callout per month at £400–£1,200 covers Kerblabs fees several times over, and most ARB Approved Contractor clients see 4–8 recovered jobs per month within 90 days plus a measurable lift in council-framework, estate and chartered-surveyor referrals as ApCo, MEWP and ash dieback credentials surface across the customer journey.",
  faqs: [
    {
      q: "How does the AI receptionist handle a 7am storm-emergency call when the climber is already on a job?",
      a: "Storm response is the headline use-case. The AI receptionist (across phone, WhatsApp Business and SMS) picks up inside three rings 24/7, captures property address and what3words location, asks the four questions that actually triage tree emergencies — is anyone hurt or trapped, is the tree on a building/vehicle/highway/power line, is it a confirmed full-tree failure or a major limb, and is access blocked — then routes the call. Highway-blocking or property-impact calls trigger an immediate text alert to the on-call climber and groundsman with location and photographs uploaded via SMS link, while non-urgent storm damage books a same-day or next-day survey slot against your published callout rates (£80–£200 plus £60–£120 hourly typical). Power-line incidents are explicitly routed away — the AI tells the caller to ring 105 (national power network emergency number) first and never books work on live conductors. Every call is recorded, transcribed and dropped into your job-management software (Powered Now, Tree Plotter, ServiceM8, Workever) so the climbing team has full context before arriving. Independent crews running this typically capture 30–60+ extra storm-week callouts during named-storm activations they would otherwise have lost to whoever answered.",
    },
    {
      q: "Does Kerblabs integrate with Powered Now, Tree Plotter, ServiceM8 and Workever?",
      a: "Yes — these are the four most common platforms across UK arboricultural crews and we integrate with all of them. Tree Plotter handles the survey, TPO/Conservation Area mapping and tree-by-tree quote workflow that ARB Approved Contractors and council-framework operators rely on; ServiceM8 and Workever cover job-tracking, timesheets, photo evidence and invoicing for sole traders and growing crews; Powered Now is widely used for quote-to-invoice with finance attached. Kerblabs sits alongside the platform you already use: AI-receptionist appointments sync to your calendar, new client records auto-create with TPO/Conservation Area flag captured, ash dieback survey enquiries trigger a different appointment type and quote template than retail garden work, council-framework leads route to a separate B2B pipeline, and review-request flows trigger automatically once a job is marked complete in the platform. We also integrate with Stripe and GoCardless for survey deposits and with the major review platforms (Google Business Profile, Trustpilot, Checkatrade — yes, you can keep collecting Checkatrade reviews while reducing Checkatrade lead-buying).",
    },
    {
      q: "Is ARB Approved Contractor Scheme membership worth the £1,000+ annual fee, and how do you market it?",
      a: "For any crew chasing council framework, large-estate, chartered-surveyor-led or insurance-claim work, ARB ApCo is essentially mandatory — it's the AA flagship scheme (~700 member firms nationally) and it gates eligibility for the procurement panels that pay best. The standard mistake is paying the fee and burying the badge on the About page. We rebuild the customer journey around it: ApCo logo and audit-currency date in the GBP description and posts; ARB Approved Contractor schema and BS3998:2010 references in landing-page structured data; LOLER and PUWER 1998 inspection currency surfaced on quote PDFs; review-request flows that prompt customers to mention ApCo and BS3998 by name (which materially boosts ranking for queries like 'ARB Approved tree surgeon Manchester' that conservation officers and chartered surveyors actually search); and a dedicated B2B landing page targeting tree officers, parish clerks, RICS-registered estate managers and Lantra-trained land agents. Member firms running this typically book 2–6 council-framework or estate-led jobs per quarter that would otherwise have gone to a competitor with the same ApCo status but better marketing.",
    },
    {
      q: "How do you turn the ash dieback crisis into an actual lead pipeline rather than a slogan?",
      a: "Ash dieback (Hymenoscyphus fraxineus / Chalara) is the single largest UK arboricultural workload of the decade and most of the work is going to a small number of firms with visible specialism. We build a four-channel funnel. (1) A dedicated ash dieback survey and removal landing page with named photographic evidence of completed dieback fells, MEWP capability, sectional dismantling case studies, and the specific health-and-safety protocols (HSE FCBI047 Managing Ash Dieback in England, FISA 308) that council and estate buyers vet against. (2) GBP photo-post automation publishing one ash dieback before/after per week with proper geotagging and BS3998:2010 mention. (3) A council and estate B2B outreach programme — local authority tree officers, parish clerks, RICS-registered estate managers, National Trust and Forestry England regional contacts, large school groups (academy trusts manage thousands of mature ash on grounds) — with a structured panel-application pack including ApCo, insurance levels, MEWP capability and dieback-specific case studies. (4) An insurance-adjuster funnel for storm-damaged dieback-compromised trees, where the dieback-weakened ash failure pattern is now well-recognised by AXA, Aviva, Direct Line and the major loss adjusters. Crews running this routinely book 8–20 dieback survey jobs per quarter at £600–£12,000 each.",
    },
    {
      q: "How does the AI receptionist handle TPO and Conservation Area enquiries without giving illegal planning advice?",
      a: "This is the single biggest compliance trap in domestic tree work and we've engineered around it explicitly. The AI receptionist is trained never to confirm or deny TPO status, Conservation Area boundaries, listed-building tree implications or Felling Licence requirements — those are determinations only the local planning authority can make. Instead, the script asks the qualifying questions ('do you know if your tree has a TPO on it? is your property in a Conservation Area? have you spoken to your council's tree officer or planning portal?'), and then routes the call into one of three flows: confirmed TPO/Conservation Area where the customer has already made the council application — books a survey and quote against the consented works; suspected protection where the customer hasn't checked — sends a templated SMS/email pointing them to their specific council's planning portal and the gov.uk tree-protection guidance, and books a provisional follow-up call for after they've checked; clearly unprotected garden trees on non-listed properties with no Conservation Area overlay — books straight to survey or quote. The AI never tells the caller their tree is or isn't protected, never recommends works without consent, never quotes a job that requires a Felling Licence (>5m³ in a quarter) without flagging it. This keeps the firm clean of the AA's published guidance on member conduct and the wider issue of unauthorised works penalties (which can reach £20,000 per tree on a TPO breach). Fully compliant, considerably less surveyor time wasted, and council tree officers notice — which feeds back into framework eligibility.",
    },
    {
      q: "We're a MEWP-based crew competing against climber-led local outfits — how do we position that without sounding corporate?",
      a: "MEWP-based crews (40t spider lifts, tracked 25m booms, the £40,000–£100,000 kit) and climber-based crews are genuinely different propositions and the marketing should respect that. MEWP positioning wins on three search categories that climbers can't compete in profitably: large dead/dieback ash where canopy entry is unsafe under FISA 308 guidance; council highway and street tree work where lane closures, traffic management and CSCS-carded operatives are required; and time-pressured commercial work (school grounds in summer holidays, retail parks, NHS estates) where finishing in two days versus seven is the contract winner. Climber positioning wins on tight-access urban gardens, sectional dismantling on listed-building backdrops, fine reduction and crown lifting where MEWP boom intrusion damages the canopy structure being preserved, and traditional estate work where the relationship and craft signal matters. We rebuild the website, GBP and ad creative around your actual capability — MEWP-specialist firms get separate landing pages for ash dieback, highway, school and commercial work with the spider-lift kit photographed and named (Hinowa, Palazzani, CMC, Platform Basket — buyers know the brands), while climber-led firms get heritage, Conservation Area and Grade-II-adjacent work front and centre with named-borough conservation case studies. Neither needs to fake what they're not.",
    },
  ],
  comboIntroTemplate:
    "Tree surgeons and arborists working in {city} are operating in the busiest UK arboricultural decade in living memory, and the local market dynamics in {city} sharpen every pressure that's hitting the sector nationally. {city} is {character}, which means independent ARB Approved Contractors and growing crews here are fighting on five fronts at once: 24/7 named-storm callouts where homeowners ring four firms in fifteen minutes and book whoever answers; ash dieback removal and survey work running through council framework agreements (often subcontracted via Veolia, Glendale, FCC Environment or idverde at 25–35% margin compression); domestic Conservation Area and Tree Preservation Order work that needs careful pre-quote qualifying because the firm legally cannot give planning advice; large-estate, chartered-surveyor-led and insurance-adjuster instructions where ARB ApCo, BS3998:2010, LOLER and PUWER currency are vetted before a quote is even read; and aggregator pressure from Checkatrade, MyBuilder, Bark and Rated People charging £15–£40 per shared lead with no client ownership. Layer on competition from Bartlett Tree Experts (US-owned global, ~30 UK sites), Beechwood Trees & Landscapes, Western Tree Services and Pryor & Rickett Silviculture on the heritage and utility-line work, and the result is a {city} market where most crews are paying £140–£320 cost-per-acquired-job for work they could win directly with the right systems. Kerblabs gives {city} tree surgeons and arborists the AI receptionist, ARB-aware local SEO, ash dieback survey funnel, TPO/Conservation Area qualifying flow, council-framework B2B outreach and review velocity to capture every storm callout, win on credentials not price, and break aggregator dependency.",
};
